Repository GetJobber/atlantis, pull requests merged in 2019-11, with the labels that each got.

#167 docs: Update import for feature switch
  packages/components/src/FeatureSwitch/FeatureSwitch.mdx
Labels: docs

#169 fix(components): Colors were not consistent with the design page for Card accents
  packages/components/src/Card/colors.css
  packages/components/src/Card/colors.css.d.ts
Labels: review requested

#156 feat(components): ☑️Create a checkbox
  packages/components/package-lock.json
  packages/components/src/Checkbox/Checkbox.css
  packages/components/src/Checkbox/Checkbox.css.d.ts
  packages/components/src/Checkbox/Checkbox.mdx
  packages/components/src/Checkbox/Checkbox.test.tsx
  packages/components/src/Checkbox/Checkbox.tsx
  packages/components/src/Checkbox/__snapshots__/Checkbox.test.tsx.snap
  packages/components/src/Checkbox/index.ts
Labels: review requested

#173 fix: Stop font from being loaded twice
  packages/components/src/Typography/css/Typography.css
Labels: bug, review requested
