Repository GetJobber/atlantis, pull requests merged in 2020-04, with the labels that each got.

#119 feat: First pass at Input Group
  packages/components/src/FormField/FormField.css
  packages/components/src/InputGroup/InputGroup.css
  packages/components/src/InputGroup/InputGroup.css.d.ts
  packages/components/src/InputGroup/InputGroup.mdx
  packages/components/src/InputGroup/InputGroup.test.tsx
  packages/components/src/InputGroup/InputGroup.tsx
  packages/components/src/InputGroup/index.ts
Labels: review requested

#88 docs: InputColor proposal
  docs/proposals/InputColor/README.md
Labels: component proposal

#206 feat(components): Create ProgressBar
  packages/components/src/ProgressBar/ProgressBar.css
  packages/components/src/ProgressBar/ProgressBar.css.d.ts
  packages/components/src/ProgressBar/ProgressBar.mdx
  packages/components/src/ProgressBar/ProgressBar.test.tsx
  packages/components/src/ProgressBar/ProgressBar.tsx
  packages/components/src/ProgressBar/__snapshots__/ProgressBar.test.tsx.snap
  packages/components/src/ProgressBar/index.ts
  packages/eslint-config/package-lock.json
Labels: approved, external

#223 docs(generators): Add design decisions to template Readme
  package.json
  packages/generators/templates/component/{{name}}.tsx
  packages/generators/templates/component/{{name}}.{{mdx}}
Labels: review requested

#227 chore: Make our Ch-ch-ch-ch-changes more visible.
  .eslintrc.js
  doczrc.js
  package-lock.json
  package.json
  packages/components/CHANGELOG.md
  packages/components/src/Autocomplete/Autocomplete.tsx
  packages/components/src/InputTime/InputTimeSafari.tsx
  packages/design/CHANGELOG.md
  packages/generators/CHANGELOG.md
  packages/stylelint-config/CHANGELOG.md
  src/ensureChangelogHeaders.js
Labels: approved

#229 feat(components): Adds FormatEmail component
  package-lock.json
  packages/components/src/FormatEmail/FormatEmail.css
  packages/components/src/FormatEmail/FormatEmail.css.d.ts
  packages/components/src/FormatEmail/FormatEmail.mdx
  packages/components/src/FormatEmail/FormatEmail.test.tsx
  packages/components/src/FormatEmail/FormatEmail.tsx
  packages/components/src/FormatEmail/__snapshots__/FormatEmail.test.tsx.snap
  packages/components/src/FormatEmail/index.ts
Labels: approved

#232 chore(deps): Update typescript to 3.8.3
  package-lock.json
  package.json
  packages/eslint-config/package-lock.json
  packages/eslint-config/package.json
Labels: review requested

#234 chore: Add `.eslintrc.js` snippet to readme.
  packages/eslint-config/README.md
Labels: approved

#231 docs(components): Avatar component proposal
  docs/proposals/Avatar/README.md
Labels: review requested

#236 docs: propose new banner mods
  docs/proposals/BANNER_MODS.md
Labels: review requested

#241 chore(deps): Update typescript in components
  packages/components/package-lock.json
  packages/components/package.json
  packages/components/src/FeatureSwitch/FeatureSwitch.tsx
  packages/components/src/FormField/FormField.tsx
  packages/components/src/InputText/InputText.tsx
  packages/components/src/InputTime/time-input-polyfill.d.ts
  packages/components/src/Tooltip/Tooltip.tsx
Labels: approved

#233 chore: Add ListPage Proposal
  docs/proposals/ListPage.md
Labels: review requested

#235 feat(components): Avatar component
  packages/components/package-lock.json
  packages/components/package.json
  packages/components/src/Avatar/Avatar.css
  packages/components/src/Avatar/Avatar.css.d.ts
  packages/components/src/Avatar/Avatar.mdx
  packages/components/src/Avatar/Avatar.test.tsx
  packages/components/src/Avatar/Avatar.tsx
  packages/components/src/Avatar/__snapshots__/Avatar.test.tsx.snap
  packages/components/src/Avatar/index.ts
  packages/components/src/Avatar/utilities.ts
Labels: review requested

#243 feat: Radio Group component v1
  packages/components/src/RadioGroup/RadioGroup.css
  packages/components/src/RadioGroup/RadioGroup.css.d.ts
  packages/components/src/RadioGroup/RadioGroup.mdx
  packages/components/src/RadioGroup/RadioGroup.test.tsx
  packages/components/src/RadioGroup/RadioGroup.tsx
  packages/components/src/RadioGroup/__snapshots__/RadioGroup.test.tsx.snap
  packages/components/src/RadioGroup/index.ts
Labels: external, review requested

#239 docs(components): grammar fixup on checkbox
  packages/components/src/Checkbox/Checkbox.mdx
Labels: review requested
