Repository GetJobber/atlantis, pull requests merged in 2020-09, with the labels that each got.

#349 docs(components): Update Banner.mdx
  packages/components/src/Banner/Banner.mdx
Labels: approved, external

#348 docs(components): Update Autocomplete.mdx
  packages/components/src/Autocomplete/Autocomplete.mdx
Labels: approved, external

#350 fix(components): autocomplete: use subdued text for description on menu items
  packages/components/src/Autocomplete/Menu.tsx
Labels: WWR, approved

#356 fix(components): fix a border issue on card accent
  packages/components/src/Card/Card.css
Labels: external, review requested

#355 feat(components): modify autocomplete to scroll list up and down
  packages/components/src/Autocomplete/Autocomplete.css
  packages/components/src/Autocomplete/Menu.tsx
Labels: WWR, approved, external

#357 feat(components): Form component
  .eslintrc.js
  gatsby-node.js
  packages/components/src/Autocomplete/__snapshots__/Autocomplete.test.tsx.snap
  packages/components/src/Button/Button.mdx
  packages/components/src/Button/Button.test.tsx
  packages/components/src/Button/Button.tsx
  packages/components/src/Form/Form.mdx
  packages/components/src/Form/Form.test.tsx
  packages/components/src/Form/Form.tsx
  packages/components/src/Form/index.ts
  packages/components/src/FormField/FormField.test.tsx
  packages/components/src/FormField/FormField.tsx
  packages/components/src/InputNumber/InputNumber.test.tsx
  packages/components/src/InputPassword/InputPassword.test.tsx
  packages/components/src/InputText/InputText.test.tsx
  packages/components/src/InputTime/InputTime.test.tsx
  packages/components/src/Select/__snapshots__/Select.test.tsx.snap
  packages/hooks/src/index.ts
  packages/hooks/src/useFormState/index.ts
  packages/hooks/src/useFormState/useFormState.mdx
  packages/hooks/src/useFormState/useFormState.ts
Labels: approved

#358 docs(components): Add animation page to docs
  packages/design/src/animation.mdx
Labels: approved, external

#360 fix(components): Fixes types on useFormState
  packages/components/src/Form/Form.test.tsx
  packages/hooks/src/useFormState/useFormState.ts
Labels: approved

#352 feat(components): BREAKING CHANGE: FormField Validation
  .eslintrc.js
  gatsby-node.js
  packages/components/package-lock.json
  packages/components/package.json
  packages/components/src/Autocomplete/__snapshots__/Autocomplete.test.tsx.snap
  packages/components/src/Button/Button.mdx
  packages/components/src/Button/Button.test.tsx
  packages/components/src/Button/Button.tsx
  packages/components/src/Form/Form.mdx
  packages/components/src/Form/Form.test.tsx
  packages/components/src/Form/Form.tsx
  packages/components/src/Form/index.ts
  packages/components/src/FormField/FormField.test.tsx
  packages/components/src/FormField/FormField.tsx
  packages/components/src/InputNumber/InputNumber.mdx
  packages/components/src/InputNumber/InputNumber.test.tsx
  packages/components/src/InputNumber/InputNumber.tsx
  packages/components/src/InputPassword/InputPassword.mdx
  packages/components/src/InputPassword/InputPassword.test.tsx
  packages/components/src/InputPassword/InputPassword.tsx
  packages/components/src/InputText/InputText.mdx
  packages/components/src/InputText/InputText.test.tsx
  packages/components/src/InputText/InputText.tsx
  packages/components/src/InputTime/InputTime.test.tsx
  packages/components/src/InputTime/InputTimeSafari.tsx
  packages/components/src/InputValidation/InputValidation.css
  packages/components/src/InputValidation/InputValidation.css.d.ts
  packages/components/src/InputValidation/InputValidation.mdx
  packages/components/src/InputValidation/InputValidation.test.tsx
  packages/components/src/InputValidation/InputValidation.tsx
  packages/components/src/Select/__snapshots__/Select.test.tsx.snap
  packages/hooks/src/index.ts
  packages/hooks/src/useFormState/index.ts
  packages/hooks/src/useFormState/useFormState.mdx
  packages/hooks/src/useFormState/useFormState.ts
Labels: approved

#361 fix(components): Change Color of Checkbox Border to Green
  packages/components/src/Checkbox/Checkbox.css
Labels: WWR, approved

#363 fix(components): Fixes the inline input
  packages/components/src/Autocomplete/__snapshots__/Autocomplete.test.tsx.snap
  packages/components/src/Form/Form.mdx
  packages/components/src/FormField/FormField.test.tsx
  packages/components/src/FormField/FormField.tsx
  packages/components/src/InputNumber/InputNumber.test.tsx
  packages/components/src/InputPassword/InputPassword.test.tsx
  packages/components/src/InputText/InputText.test.tsx
  packages/components/src/InputTime/InputTime.test.tsx
  packages/components/src/Select/__snapshots__/Select.test.tsx.snap
Labels: approved

#364 fix(components): Allow the form to not be a form but be a div instead
  packages/components/src/Form/Form.test.tsx
  packages/components/src/Form/Form.tsx
Labels: approved
