Repository GetJobber/atlantis, pull requests merged in 2020-10, with the labels that each got.

#366 feat(components): InputAvatar & Expand variation options for InputFile
  packages/components/src/FormatFile/FormatFile.css
  packages/components/src/InputAvatar/InputAvatar.css
  packages/components/src/InputAvatar/InputAvatar.css.d.ts
  packages/components/src/InputAvatar/InputAvatar.mdx
  packages/components/src/InputAvatar/InputAvatar.test.tsx
  packages/components/src/InputAvatar/InputAvatar.tsx
  packages/components/src/InputAvatar/__snapshots__/InputAvatar.test.tsx.snap
  packages/components/src/InputAvatar/index.ts
  packages/components/src/InputFile/InputFile.css
  packages/components/src/InputFile/InputFile.css.d.ts
  packages/components/src/InputFile/InputFile.mdx
  packages/components/src/InputFile/InputFile.test.tsx
  packages/components/src/InputFile/InputFile.tsx
  packages/components/src/InputFile/__snapshots__/InputFile.test.tsx.snap
  packages/components/src/InputFile/index.ts
  packages/design/src/radii.css
Labels: approved

#373 fix(components): Remove input name if no validation is set
  packages/components/src/Autocomplete/__snapshots__/Autocomplete.test.tsx.snap
  packages/components/src/FormField/FormField.test.tsx
  packages/components/src/FormField/FormField.tsx
  packages/components/src/InputPassword/InputPassword.test.tsx
  packages/components/src/InputText/InputText.test.tsx
  packages/components/src/InputTime/InputTime.test.tsx
  packages/components/src/Select/__snapshots__/Select.test.tsx.snap
Labels: approved

#372 docs(components): add related components section to header doc
  packages/components/src/Heading/Heading.mdx
Labels: external, review requested

#368 docs(components): add related components section to checkbox docs
  packages/components/src/Checkbox/Checkbox.mdx
Labels: approved, external

#369 docs(components): add related components section to ConfirmationModal
  packages/components/src/ConfirmationModal/ConfirmationModal.mdx
Labels: approved, external

#365 feat(components): Add description to Checkbox
  packages/components/src/Checkbox/Checkbox.css
  packages/components/src/Checkbox/Checkbox.css.d.ts
  packages/components/src/Checkbox/Checkbox.mdx
  packages/components/src/Checkbox/Checkbox.test.tsx
  packages/components/src/Checkbox/Checkbox.tsx
  packages/components/src/Checkbox/__snapshots__/Checkbox.test.tsx.snap
Labels: approved

#362 feat(components): Adjust Autocomplete debounce rate
  packages/components/CHANGELOG.md
  packages/components/src/Autocomplete/Autocomplete.tsx
Labels: WWR, approved, external

#374 fix(design): embiggen the small Icons
  packages/design/src/icons/Sizes.css
Labels: approved

#375 fix(components): Autocomplete debounce for getOptions
  packages/components/src/Autocomplete/Autocomplete.mdx
  packages/components/src/Autocomplete/Autocomplete.test.tsx
  packages/components/src/Autocomplete/Autocomplete.tsx
  packages/components/src/Autocomplete/__snapshots__/Autocomplete.test.tsx.snap
Labels: approved, external

#393 feat(components): Add `validate` function to Form
  packages/components/src/Form/Form.mdx
  packages/components/src/Form/Form.test.tsx
  packages/components/src/Form/Form.tsx
  packages/components/src/Form/index.ts
Labels: approved, hacktoberfest, hacktoberfest-accepted

#390 feat(components): Autocomplete now filters out headers with no options
  packages/components/src/Autocomplete/Autocomplete.tsx
Labels: approved, hacktoberfest, hacktoberfest-accepted

#391 fix(components): Make modal focus when opened
  packages/components/src/ConfirmationModal/tests/__snapshots__/snapshot-ConfirmationModal.test.tsx.snap
  packages/components/src/Modal/Modal.test.tsx
  packages/components/src/Modal/Modal.tsx
  packages/components/src/Modal/__snapshots__/ModalSnapshots.test.tsx.snap
Labels: approved, external, hacktoberfest, hacktoberfest-accepted

#388 fix(components): update button padding on has icon and label button
  packages/components/src/Button/Button.css
Labels: approved, hacktoberfest, hacktoberfest-accepted

#398 chore: Forces node version on circle
  .circleci/config.yml
Labels: approved, hacktoberfest

#399 docs(components): update FormatDate design docs
  packages/components/src/FormatDate/FormatDate.mdx
Labels: approved, hacktoberfest

#404 docs(components): button docs hierarchy
  packages/components/src/Button/Button.mdx
Labels: approved, hacktoberfest-accepted

#403 docs(components): add design docs to InputPassword
  packages/components/src/InputPassword/InputPassword.mdx
Labels: approved, hacktoberfest-accepted

#370 docs(components): add related components section to DescriptionList
  packages/components/src/DescriptionList/DescriptionList.mdx
Labels: approved, external

#371 docs(components): add related components section to FormatFile
  packages/components/src/FormatFile/FormatFile.mdx
Labels: approved, external
