Repository GetJobber/atlantis, pull requests merged in 2020-07, with the labels that each got.

#280 feat: export foundation as a js file with the corresponding types
  package-lock.json
  packages/design/.gitignore
  packages/design/buildFoundation.js
  packages/design/jobberStyle.js
  packages/design/package.json
Labels: review requested

#295 build: Responsive CSS breakpoints
  doczrc.js
  gatsby-node.js
  package-lock.json
  package.json
  packages/components/src/Menu/Menu.css
  packages/design/package-lock.json
  packages/design/package.json
  packages/design/src/ResponsiveBreakpoints.mdx
Labels: review requested

#300 fix(components): Icon export everything
  packages/components/src/Icon/Icon.tsx
Labels: review requested

#302 fix(components): Add fragments to FormatRelativeDateTime
  packages/components/src/FormatRelativeDateTime/FormatRelativeDateTime.tsx
Labels: review requested

#301 refactor(components): new sendMessage Icon
  packages/components/src/Icon/Icon.mdx
  packages/design/src/icons/iconMap.ts
Labels: approved

#310 feat(components): expose focus method in InputText — (Minor) Feature Release
  packages/components/src/InputText/InputText.mdx
  packages/components/src/InputText/InputText.tsx
Labels: approved

#307 fix(components): removed seconds from time in FormatRelativeDateTime
  packages/components/src/FormatRelativeDateTime/FormatRelativeDateTime.mdx
  packages/components/src/FormatRelativeDateTime/FormatRelativeDateTime.test.tsx
  packages/components/src/FormatRelativeDateTime/FormatRelativeDateTime.tsx
Labels: approved, external

#308 feat(design): Change system colour for sendInvoice and paidInvoice icons
  packages/design/src/icons/Icon.css
Labels: approved, external

#312 fix: update icon type defs
  packages/design/src/icons/Icon.css.d.ts
Labels: approved

#311 docs(components): Update disabled state docs on checkbox
  packages/components/src/Checkbox/Checkbox.mdx
Labels: approved

#303 feat(components): InputText Automatic Resize
  .gitignore
  packages/components/src/FormField/FormField.css
  packages/components/src/InputText/InputText.mdx
  packages/components/src/InputText/InputText.test.tsx
  packages/components/src/InputText/InputText.tsx
  packages/components/src/InputText/index.ts
Labels: approved, external

#321 feat(components): Adds an onEnter handler for Form Fields
  packages/components/src/Autocomplete/__snapshots__/Autocomplete.test.tsx.snap
  packages/components/src/Checkbox/Checkbox.mdx
  packages/components/src/FormField/FormField.test.tsx
  packages/components/src/FormField/FormField.tsx
  packages/components/src/InputNumber/InputNumber.test.tsx
  packages/components/src/InputPassword/InputPassword.test.tsx
  packages/components/src/InputText/InputText.test.tsx
  packages/components/src/InputTime/InputTime.test.tsx
Labels: approved

#322 feat(components): Time and Date formatters now accept `Date` Objects and ISO Strings
  packages/components/src/FormatDate/FormatDate.test.tsx
  packages/components/src/FormatDate/FormatDate.tsx
  packages/components/src/FormatDate/__snapshots__/FormatDate.test.tsx.snap
  packages/components/src/FormatRelativeDateTime/FormatRelativeDateTime.test.tsx
  packages/components/src/FormatRelativeDateTime/FormatRelativeDateTime.tsx
  packages/components/src/FormatTime/FormatTime.test.tsx
  packages/components/src/FormatTime/FormatTime.tsx
  packages/components/src/FormatTime/__snapshots__/FormatTime.test.tsx.snap
Labels: approved

#323 fix(components): prevent jobber from overriding min-height on InputText when it is a text area
  packages/components/src/FormField/FormField.css
Labels: approved, external
