Repository GetJobber/atlantis, pull requests merged in 2020-11, with the labels that each got.

#411 feat(components): guard against external anchor element styling
  packages/components/src/Button/Button.css
Labels: approved, hacktoberfest, hacktoberfest-accepted, in review

#408 feat(components): Add DataDump Component
  packages/components/src/DataDump/DataDump.mdx
  packages/components/src/DataDump/DataDump.test.tsx
  packages/components/src/DataDump/DataDump.tsx
  packages/components/src/DataDump/__snapshots__/DataDump.test.tsx.snap
  packages/components/src/DataDump/index.ts
Labels: approved, hacktoberfest, hacktoberfest-accepted

#395 fix(components): Changing modal close button to use <Button> component
  packages/components/src/ButtonDismiss/.private
  packages/components/src/ButtonDismiss/ButtonDismiss.css
  packages/components/src/ButtonDismiss/ButtonDismiss.css.d.ts
  packages/components/src/ButtonDismiss/ButtonDismiss.mdx
  packages/components/src/ButtonDismiss/ButtonDismiss.test.tsx
  packages/components/src/ButtonDismiss/ButtonDismiss.tsx
  packages/components/src/ButtonDismiss/__snapshots__/ButtonDismiss.test.tsx.snap
  packages/components/src/ButtonDismiss/index.ts
  packages/components/src/Modal/Modal.tsx
  packages/components/src/Modal/__snapshots__/ModalSnapshots.test.tsx.snap
Labels: approved, hacktoberfest, hacktoberfest-accepted

#412 fix(components): Only focus the modal once when it opens
  packages/components/CHANGELOG.md
  packages/components/src/Modal/Modal.mdx
  packages/components/src/Modal/Modal.tsx
Labels: approved

#414 fix(components): Menu properly positions on right side of screen.
  packages/components/src/Menu/Menu.css
  packages/components/src/Menu/Menu.css.d.ts
  packages/components/src/Menu/Menu.tsx
Labels: approved

#402 feat(components): Make switch & description optional on FeatureSwitch
  packages/components/src/FeatureSwitch/FeatureSwitch.test.tsx
  packages/components/src/FeatureSwitch/FeatureSwitch.tsx
  packages/components/src/FeatureSwitch/__snapshots__/FeatureSwitch.test.tsx.snap
Labels: approved, hacktoberfest-accepted

#367 feat(components): Drawer component
  packages/components/src/Drawer/Drawer.css
  packages/components/src/Drawer/Drawer.css.d.ts
  packages/components/src/Drawer/Drawer.mdx
  packages/components/src/Drawer/Drawer.test.tsx
  packages/components/src/Drawer/Drawer.tsx
  packages/components/src/Drawer/DrawerGrid.module.css
  packages/components/src/Drawer/DrawerGrid.module.css.d.ts
  packages/components/src/Drawer/DrawerGrid.tsx
  packages/components/src/Drawer/index.ts
Labels: external, hacktoberfest-accepted, review requested

#415 fix(components): Sets AutoComplete to blank if no matches
  packages/components/src/Autocomplete/Autocomplete.test.tsx
  packages/components/src/Autocomplete/Autocomplete.tsx
  packages/components/src/Autocomplete/__snapshots__/Autocomplete.test.tsx.snap
Labels: approved

#416 feat(components): Add `onUploadComplete` to `InputAvatar`
  packages/components/src/InputAvatar/InputAvatar.test.tsx
  packages/components/src/InputAvatar/InputAvatar.tsx
Labels: approved

#417 feat(components): Add `invalid` to `Autocomplete`
  packages/components/src/Autocomplete/Autocomplete.test.tsx
  packages/components/src/Autocomplete/Autocomplete.tsx
  packages/components/src/Autocomplete/__snapshots__/Autocomplete.test.tsx.snap
Labels: approved, external

#376 docs(components): Update drawer proposal
  docs/proposals/Drawer/README.md
Labels: approved, component proposal, external, hacktoberfest-accepted

#419 feat(components): Add size prop to Text
  packages/components/src/Checkbox/Checkbox.css
  packages/components/src/Checkbox/Checkbox.tsx
  packages/components/src/Page/Page.tsx
  packages/components/src/Page/__snapshots__/Page.test.tsx.snap
  packages/components/src/Text/Text.mdx
  packages/components/src/Text/Text.test.tsx
  packages/components/src/Text/Text.tsx
Labels: approved

#420 feat(components): Add label and description to RadioOption
  packages/components/src/Checkbox/Checkbox.css
  packages/components/src/RadioGroup/RadioGroup.css
  packages/components/src/RadioGroup/RadioGroup.css.d.ts
  packages/components/src/RadioGroup/RadioGroup.mdx
  packages/components/src/RadioGroup/RadioGroup.test.tsx
  packages/components/src/RadioGroup/RadioGroup.tsx
  packages/components/src/RadioGroup/RadioOption.tsx
  packages/components/src/RadioGroup/__snapshots__/RadioGroup.test.tsx.snap
  packages/components/src/RadioGroup/index.ts
Labels: approved

#422 feat(components): Shrink `Page` breakpoints and allow page to breathe
  packages/components/src/Page/Page.css
  packages/components/src/Page/Page.css.d.ts
  packages/components/src/Page/Page.mdx
  packages/components/src/Page/Page.tsx
Labels: approved, external, in review

#424 feat(components): Add markdown to ConfirmationModal
  packages/components/src/ConfirmationModal/ConfirmationModal.mdx
  packages/components/src/ConfirmationModal/ConfirmationModal.tsx
  packages/components/src/ConfirmationModal/tests/__snapshots__/snapshot-ConfirmationModal.test.tsx.snap
  packages/components/src/ConfirmationModal/tests/interaction-ConfirmationModal.test.tsx
Labels: approved

#425 fix(components): Make sure drawer content is full width
  packages/components/src/Drawer/Drawer.css
Labels: approved, external
