Repository GetJobber/atlantis, pull requests merged in 2020-05, with the labels that each got.

#244 feat(components): Add primaryAction and placement to Banner
  packages/components/src/Banner/Banner.mdx
  packages/components/src/Banner/Banner.test.tsx
  packages/components/src/Banner/Banner.tsx
  packages/components/src/Banner/__snapshots__/Banner.test.tsx.snap
Labels: review requested

#242 feat: add hook package with resize oberserver hook
  .github/pull_request_template.md
  .github/semantic.yml
  packages/hooks/CHANGELOG.md
  packages/hooks/LICENSE
  packages/hooks/README.mdx
  packages/hooks/USE_RESIZE_OBSERVER.mdx
  packages/hooks/package-lock.json
  packages/hooks/package.json
  packages/hooks/src/index.ts
  packages/hooks/src/useResizeObserver.ts
  packages/hooks/tsconfig.json
Labels: review requested

#246 docs(components): Avatar typo fix on "calendar"
  packages/components/src/Avatar/Avatar.mdx
Labels: approved

#247 docs(components): update definition/add guidelines to content
  packages/components/src/Content/Content.mdx
Labels: approved

#245 docs(components): Update card docs with design usage guidelines
  packages/components/src/Card/Card.mdx
Labels: approved

#237 docs(components): Add design and usage guidelines to tooltip
  packages/components/src/Tooltip/Tooltip.mdx
Labels: approved

#238 docs(components): Update Switch design docs
  packages/components/src/Switch/Switch.mdx
Labels: approved

#249 feat(components): Confirmation modal
  jest.config.js
  packages/components/src/ConfirmationModal/ConfirmationModal.mdx
  packages/components/src/ConfirmationModal/ConfirmationModal.tsx
  packages/components/src/ConfirmationModal/index.ts
  packages/components/src/ConfirmationModal/tests/__snapshots__/snapshot-ConfirmationModal.test.tsx.snap
  packages/components/src/ConfirmationModal/tests/interaction-ConfirmationModal.test.tsx
  packages/components/src/ConfirmationModal/tests/snapshot-ConfirmationModal.test.tsx
Labels: approved

#251 feat(components): ProgressBar can have a size
  packages/components/src/ProgressBar/ProgressBar.css
  packages/components/src/ProgressBar/ProgressBar.test.tsx
  packages/components/src/ProgressBar/ProgressBar.tsx
  packages/components/src/ProgressBar/Sizes.css
  packages/components/src/ProgressBar/Sizes.css.d.ts
  packages/components/src/ProgressBar/__snapshots__/ProgressBar.test.tsx.snap
Labels: WWR, changes requested

#248 feat(components): add action buttons to Page component
  package-lock.json
  packages/components/src/Menu/Menu.tsx
  packages/components/src/Menu/index.ts
  packages/components/src/Page/Page.css
  packages/components/src/Page/Page.css.d.ts
  packages/components/src/Page/Page.mdx
  packages/components/src/Page/Page.test.tsx
  packages/components/src/Page/Page.tsx
  packages/components/src/Page/__snapshots__/Page.test.tsx.snap
  packages/formatters/package-lock.json
Labels: approved

#254 docs(components): update checkbox docs
  packages/components/src/Checkbox/Checkbox.mdx
Labels: review requested

#253 docs(components): update docs for progress bar
  packages/components/src/ProgressBar/ProgressBar.mdx
Labels: approved

#255 fix: Build css types on save
  doczrc.js
  package.json
  packages/formatters/package-lock.json
  packages/formatters/package.json
Labels: approved

#257 feat(components): update icons
  packages/components/src/Icon/Icon.mdx
  packages/components/src/Icon/iconMap.ts
Labels: approved

#259 feat(components): Add routing Link to Button
  package-lock.json
  package.json
  packages/components/package-lock.json
  packages/components/package.json
  packages/components/src/Button/Button.css
  packages/components/src/Button/Button.mdx
  packages/components/src/Button/Button.test.tsx
  packages/components/src/Button/Button.tsx
  packages/components/src/Button/__snapshots__/Button.test.tsx.snap
Labels: review requested

#258 fix(generators): correct proposal template URL
  CONTRIBUTING.md
Labels: review requested

#263 fix(components): Export Page Props from index
  packages/components/src/Page/index.ts
Labels: review requested

#266 feat(components): remove quoteCopy icon and add system colour to userUnassigned
  packages/components/src/Icon/Icon.css
  packages/components/src/Icon/Icon.css.d.ts
  packages/components/src/Icon/Icon.tsx
  packages/components/src/Icon/Icons.css
  packages/components/src/Icon/Icons.css.d.ts
Labels: review requested

#267 feat(components): Export AvatarProps from avatar
  packages/components/src/Avatar/Avatar.tsx
  packages/components/src/Avatar/index.ts
  packages/design/src/foundation.css.d.ts
Labels: review requested

#268 feat(components): Export ActionProps from menu
  packages/components/src/Menu/Menu.tsx
  packages/components/src/Menu/index.ts
Labels: approved

#269 feat(components): Button as Icon only
  packages/components/src/Button/Button.css
  packages/components/src/Button/Button.css.d.ts
  packages/components/src/Button/Button.mdx
  packages/components/src/Button/Button.test.tsx
  packages/components/src/Button/Button.tsx
  packages/components/src/Button/__snapshots__/Button.test.tsx.snap
  packages/components/src/Menu/__snapshots__/Menu.test.tsx.snap
  packages/components/src/Page/__snapshots__/Page.test.tsx.snap
Labels: review requested

#270 docs(components): Added a note on an accessibility problem on the Tooltip component
  packages/components/src/Tooltip/Tooltip.mdx
Labels: review requested
