Repository GetJobber/atlantis, pull requests merged in 2020-08, with the labels that each got.

#327 feat(components): new home and offline icons
  packages/components/src/Icon/Icon.mdx
  packages/design/src/icons/iconMap.ts
Labels: approved, external

#326 feat(components): Toast Component
  packages/components/src/Avatar/__snapshots__/Avatar.test.tsx.snap
  packages/components/src/Banner/__snapshots__/Banner.test.tsx.snap
  packages/components/src/Button/Button.tsx
  packages/components/src/Button/__snapshots__/Button.test.tsx.snap
  packages/components/src/Checkbox/__snapshots__/Checkbox.test.tsx.snap
  packages/components/src/Icon/Icon.tsx
  packages/components/src/Icon/__snapshots__/Icon.test.tsx.snap
  packages/components/src/List/__snapshots__/List.test.tsx.snap
  packages/components/src/Menu/__snapshots__/Menu.test.tsx.snap
  packages/components/src/Modal/__snapshots__/ModalSnapshots.test.tsx.snap
  packages/components/src/Page/__snapshots__/Page.test.tsx.snap
  packages/components/src/Select/__snapshots__/Select.test.tsx.snap
  packages/components/src/Toast/Toast.css
  packages/components/src/Toast/Toast.css.d.ts
  packages/components/src/Toast/Toast.mdx
  packages/components/src/Toast/Toast.test.tsx
  packages/components/src/Toast/Toast.tsx
  packages/components/src/Toast/index.ts
  packages/components/src/Toast/showToast.tsx
  packages/design/src/elevations.css
  tsconfig.base.json
Labels: approved

#328 fix(components): make autocomplete work in input groups
  packages/components/src/Autocomplete/Autocomplete.css
  packages/components/src/InputGroup/InputGroup.mdx
Labels: approved

#274 fix(components): update button padding on icon button
  packages/components/src/Button/Button.css
  packages/components/src/Button/Button.css.d.ts
  packages/components/src/Button/Button.tsx
  packages/components/src/Button/__snapshots__/Button.test.tsx.snap
Labels: approved

#334 fix(components): missing button css type
  packages/components/src/Button/Button.css.d.ts
Labels: approved

#324 feat(components): modify autocomplete to show section headings, descriptions and details
  packages/components/src/Autocomplete/Autocomplete.css
  packages/components/src/Autocomplete/Autocomplete.css.d.ts
  packages/components/src/Autocomplete/Autocomplete.mdx
  packages/components/src/Autocomplete/Autocomplete.test.tsx
  packages/components/src/Autocomplete/Autocomplete.tsx
  packages/components/src/Autocomplete/Menu.tsx
  packages/components/src/Autocomplete/Option.ts
  packages/components/src/Autocomplete/__snapshots__/Autocomplete.test.tsx.snap
  packages/components/src/FormField/FormField.tsx
Labels: WWR, approved

#331 fix(components): Make Toast variation optional
  packages/components/src/Toast/Toast.test.tsx
  packages/components/src/Toast/Toast.tsx
Labels: approved

#333 fix(components): Style fixes for Toast
  packages/components/src/Toast/Toast.css
  packages/components/src/Toast/Toast.css.d.ts
  packages/components/src/Toast/showToast.tsx
Labels: approved

#335 fix(components): autocomplete: update documentation and disable browser autofill
  packages/components/src/Autocomplete/Autocomplete.mdx
  packages/components/src/Autocomplete/Autocomplete.tsx
  packages/components/src/Autocomplete/__snapshots__/Autocomplete.test.tsx.snap
Labels: approved

#330 feat(components): InputFile
  .eslintrc.js
  packages/components/package-lock.json
  packages/components/package.json
  packages/components/src/FormatFile/FileUpload.tsx
  packages/components/src/FormatFile/FormatFile.tsx
  packages/components/src/InputFile/InputFile.css
  packages/components/src/InputFile/InputFile.css.d.ts
  packages/components/src/InputFile/InputFile.mdx
  packages/components/src/InputFile/InputFile.test.tsx
  packages/components/src/InputFile/InputFile.tsx
  packages/components/src/InputFile/__snapshots__/InputFile.test.tsx.snap
  packages/components/src/InputFile/index.ts
Labels: approved

#340 docs(components): Use FormatFile in the InputFile Docs.
  packages/components/src/InputFile/InputFile.mdx
Labels: approved

#341 fix(components): Toast show the right icon
  packages/components/src/Toast/Toast.mdx
  packages/components/src/Toast/Toast.test.tsx
  packages/components/src/Toast/Toast.tsx
Labels: approved

#343 fix(components): Adds unique ids to radio ids
  packages/components/src/RadioGroup/RadioGroup.test.tsx
  packages/components/src/RadioGroup/RadioGroup.tsx
  packages/components/src/RadioGroup/__snapshots__/RadioGroup.test.tsx.snap
Labels: approved

#344 feat(components): Disable RadioOption component
  packages/components/src/RadioGroup/RadioGroup.css
  packages/components/src/RadioGroup/RadioGroup.css.d.ts
  packages/components/src/RadioGroup/RadioGroup.mdx
  packages/components/src/RadioGroup/RadioGroup.test.tsx
  packages/components/src/RadioGroup/RadioGroup.tsx
Labels: changes requested

#345 feat(components): Divider component
  packages/components/src/Divider/Divider.css
  packages/components/src/Divider/Divider.css.d.ts
  packages/components/src/Divider/Divider.mdx
  packages/components/src/Divider/Divider.test.tsx
  packages/components/src/Divider/Divider.tsx
  packages/components/src/Divider/__snapshots__/Divider.test.tsx.snap
  packages/components/src/Divider/index.ts
Labels: approved

#347 docs(components): Update Text Proposal
  docs/proposals/Text/Text_Mods.md
Labels: approved
