Repository GetJobber/atlantis, pull requests merged in 2020-12, with the labels that each got.

#426 feat(components): Reduce width of drawer for medium breakpoint
  packages/components/src/Drawer/Drawer.css
  packages/components/src/Drawer/DrawerGrid.module.css
Labels: external, review requested

#433 feat: add required column to component proposal template
  docs/proposals/TEMPLATE.md
Labels: approved

#427 fix(components): Change `Table` borders from box-shadow to pseudo element
  packages/components/src/Table/Table.css
  packages/design/src/borders.css
Labels: approved

#429 feat(components): add keyboard to inputText
  packages/components/src/FormField/FormField.test.tsx
  packages/components/src/FormField/FormField.tsx
  packages/components/src/InputNumber/InputNumber.tsx
  packages/components/src/InputPassword/InputPassword.tsx
  packages/components/src/InputText/InputText.mdx
  packages/components/src/InputTime/InputTimeProps.tsx
  packages/components/src/Select/Select.tsx
Labels: approved, external, in review

#431 feat(components): Add dismissible prop to banner
  packages/components/src/Banner/Banner.mdx
  packages/components/src/Banner/Banner.test.tsx
  packages/components/src/Banner/Banner.tsx
Labels: approved, external, in review

#432 feat(hooks): Add useOnKeyDown hook
  packages/hooks/package-lock.json
  packages/hooks/package.json
  packages/hooks/src/index.ts
  packages/hooks/src/useOnKeyDown/index.ts
  packages/hooks/src/useOnKeyDown/useOnKeyDown.mdx
  packages/hooks/src/useOnKeyDown/useOnKeyDown.test.tsx
  packages/hooks/src/useOnKeyDown/useOnKeyDown.ts
Labels: approved

#428 feat(components): add inputNumberRef to inputNumber
  packages/components/src/InputNumber/InputNumber.mdx
  packages/components/src/InputNumber/InputNumber.test.tsx
  packages/components/src/InputNumber/InputNumber.tsx
  packages/components/src/InputNumber/index.ts
Labels: approved

#436 fix(components): Fix the positioning of the Table
  packages/components/src/Table/Table.css
Labels: approved

#437 fix(components): match colors on radio and checkbox labels and inputs
  packages/components/src/Checkbox/Checkbox.css
  packages/components/src/Checkbox/Checkbox.mdx
  packages/components/src/Checkbox/Checkbox.tsx
  packages/components/src/Checkbox/__snapshots__/Checkbox.test.tsx.snap
  packages/components/src/RadioGroup/RadioGroup.css
Labels: approved

#438 feat(components): adjust line-height on largest font sizes and add h6
  packages/components/src/Heading/Heading.mdx
  packages/components/src/Heading/Heading.tsx
  packages/components/src/Typography/css/FontSizes.css
Labels: approved, external, in review

#441 fix(components): account for checked disabled state on RadioGroup
  packages/components/src/RadioGroup/RadioGroup.css
Labels: approved
