Repository GetJobber/atlantis, pull requests merged in 2021-03, with the labels that each got.

#474 fix(components): Refix the vertical alignment firefix on Firefox for FormFields
  packages/components/src/FormField/FormField.css
Labels: changes requested, external

#476 chore: update prettier in root and eslint package
  .prettierrc.js
  docs/proposals/Avatar/README.md
  docs/proposals/InputEmail/InputEmail.md
  null-markdown-loader.js
  package-lock.json
  package.json
  packages/components/scripts/convertIcoMoon.ts
  packages/components/src/Autocomplete/Autocomplete.mdx
  packages/components/src/Autocomplete/Autocomplete.tsx
  packages/components/src/Avatar/Avatar.mdx
  packages/components/src/Banner/Banner.mdx
  packages/components/src/ConfirmationModal/ConfirmationModal.mdx
  packages/components/src/DescriptionList/DescriptionList.mdx
  packages/components/src/DescriptionList/DescriptionList.test.tsx
  packages/components/src/Form/Form.mdx
  packages/components/src/FormField/FormField.tsx
  packages/components/src/FormatFile/FormatFile.mdx
  packages/components/src/InputGroup/InputGroup.mdx
  packages/components/src/InputPassword/InputPassword.mdx
  packages/components/src/InputText/InputText.mdx
  packages/components/src/InputValidation/InputValidation.mdx
  packages/components/src/LightBox/LightBox.mdx
  packages/components/src/List/List.mdx
  packages/components/src/Page/Page.mdx
  packages/components/src/RadioGroup/RadioGroup.mdx
  packages/components/src/Switch/Switch.mdx
  packages/components/src/Table/Table.mdx
  packages/components/src/Toast/Toast.mdx
  packages/design/README.mdx
  packages/design/jobberStyle.js
  packages/design/src/Spacing.mdx
  packages/design/src/animation.mdx
  packages/docx/README.mdx
  packages/docz-tools/src/gatsby-theme-docz/components/Playground/styles.ts
  packages/eslint-config/.eslintrc.js
  packages/eslint-config/README.md
  packages/eslint-config/package-lock.json
  packages/eslint-config/package.json
  packages/generators/index.js
  packages/hooks/src/useFormState/useFormState.mdx
  packages/hooks/src/useOnKeyDown/useOnKeyDown.mdx
  packages/hooks/src/useResizeObserver.mdx
  plopfile.js
Labels: approved

#481 feat(design): Add presentation icon
  packages/components/src/Icon/Icon.mdx
  packages/design/src/icons/iconMap.ts
Labels: approved, external

#480 fix(docz-tools): update styling for code to prevent breaking paragraphs [29104]
  packages/docz-tools/src/gatsby-theme-docz/theme/styles.ts
Labels: approved

#458 fix(components): allow button to remain its' own height when Banner content gets long
  packages/components/src/Banner/Banner.css
Labels: approved

#482 build: moves the convertIcoMoon file
  package.json
  packages/components/package.json
  scripts/convertIcoMoon.ts
Labels: approved

#479 docs: Add some documentation about validations
  packages/components/src/Form/Form.mdx
  packages/components/src/InputNumber/InputNumber.mdx
  packages/components/src/InputPassword/InputPassword.mdx
  packages/components/src/InputText/InputText.mdx
  packages/components/src/InputValidation/InputValidation.mdx
Labels: approved

#484 docs: Pull request name generator
  .github/pull_request_template.md
  docs/CONTRIBUTING.md
  docs/guides/pull-request-title-generator.mdx
  packages/docz-tools/index.js
  packages/docz-tools/package.json
  packages/docz-tools/src/gatsby-theme-docz/components/Navigation/index.tsx
  packages/docz-tools/src/gatsby-theme-docz/components/PullRequestGenerator/PullRequestGenerator.tsx
  packages/docz-tools/src/gatsby-theme-docz/components/PullRequestGenerator/index.ts
Labels: approved

#487 feat(docz-tools): added theme configuration options for hiding actions, logo and fixed sidebar
  packages/docz-tools/README.md
  packages/docz-tools/src/gatsby-theme-docz/components/Layout/index.tsx
  packages/docz-tools/src/gatsby-theme-docz/components/Logo/index.tsx
  packages/docz-tools/src/gatsby-theme-docz/components/Sidebar/index.tsx
  packages/docz-tools/src/gatsby-theme-docz/components/Sidebar/styles.ts
Labels: approved, proposal

#471 feat(docz-tools): DoczTOC component
  packages/docz-tools/components/DoczTOC/DoczTOC.tsx
  packages/docz-tools/components/DoczTOC/index.ts
  packages/docz-tools/components/DoczTOC/styles.ts
  packages/docz-tools/index.ts
  packages/docz-tools/package.json
Labels: approved

#488 fix(docz-tools): fixes the broken github link
  packages/components/src/Autocomplete/Autocomplete.mdx
  packages/components/src/Avatar/Avatar.mdx
  packages/components/src/Banner/Banner.mdx
  packages/components/src/Button/Button.mdx
  packages/components/src/ButtonDismiss/ButtonDismiss.mdx
  packages/components/src/Card/Card.mdx
  packages/components/src/Checkbox/Checkbox.mdx
  packages/components/src/ConfirmationModal/ConfirmationModal.mdx
  packages/components/src/Content/Content.mdx
  packages/components/src/DataDump/DataDump.mdx
  packages/components/src/DescriptionList/DescriptionList.mdx
  packages/components/src/Divider/Divider.mdx
  packages/components/src/Drawer/Drawer.mdx
  packages/components/src/FeatureSwitch/FeatureSwitch.mdx
  packages/components/src/Form/Form.mdx
  packages/components/src/FormField/FormField.mdx
  packages/components/src/FormatDate/FormatDate.mdx
  packages/components/src/FormatEmail/FormatEmail.mdx
  packages/components/src/FormatFile/FormatFile.mdx
  packages/components/src/FormatRelativeDateTime/FormatRelativeDateTime.mdx
  packages/components/src/FormatTime/FormatTime.mdx
  packages/components/src/Icon/Icon.mdx
  packages/components/src/InlineLabel/InlineLabel.mdx
  packages/components/src/InputAvatar/InputAvatar.mdx
  packages/components/src/InputFile/InputFile.mdx
  packages/components/src/InputGroup/InputGroup.mdx
  packages/components/src/InputNumber/InputNumber.mdx
  packages/components/src/InputPassword/InputPassword.mdx
  packages/components/src/InputText/InputText.mdx
  packages/components/src/InputTime/InputTime.mdx
  packages/components/src/InputValidation/InputValidation.mdx
  packages/components/src/LightBox/LightBox.mdx
  packages/components/src/List/List.mdx
  packages/components/src/Markdown/Markdown.mdx
  packages/components/src/Menu/Menu.mdx
  packages/components/src/Modal/Modal.mdx
  packages/components/src/Page/Page.mdx
  packages/components/src/ProgressBar/ProgressBar.mdx
  packages/components/src/RadioGroup/RadioGroup.mdx
  packages/components/src/Select/Select.mdx
  packages/components/src/Spinner/Spinner.mdx
  packages/components/src/Switch/Switch.mdx
  packages/components/src/Table/Table.mdx
  packages/components/src/Tabs/Tabs.mdx
  packages/components/src/Toast/Toast.mdx
  packages/components/src/Tooltip/Tooltip.mdx
  packages/docz-tools/README.md
  packages/docz-tools/src/gatsby-theme-docz/components/Actions/Actions.tsx
  packages/docz-tools/src/gatsby-theme-docz/components/Actions/styles.ts
  packages/generators/templates/component/{{name}}.{{mdx}}
Labels: approved
