Repository GetJobber/atlantis, pull requests merged in 2021-01, with the labels that each got.

#430 feat(components): convert `progressBar` to semantic HTML and count step 1
  packages/components/src/ProgressBar/ProgressBar.css
  packages/components/src/ProgressBar/ProgressBar.css.d.ts
  packages/components/src/ProgressBar/ProgressBar.mdx
  packages/components/src/ProgressBar/ProgressBar.tsx
  packages/components/src/ProgressBar/__snapshots__/ProgressBar.test.tsx.snap
Labels: approved, external

#445 docs(design): update color docs layouts
  packages/docx/src/ColorSwatches/ColorSwatch/ColorSwatch.css
  packages/docx/src/ColorSwatches/ColorSwatches.css
Labels: approved

#448 fix(components): reset vertical-align property on `ProgressBar`
  packages/components/src/ProgressBar/ProgressBar.css
Labels: approved

#447 fix(components): allow Toast to expand on small screens
  packages/components/src/Toast/Toast.css
Labels: approved

#443 feat(components)!: Visual and layout updates to banner
  packages/components/src/Banner/Banner.css
  packages/components/src/Banner/Banner.css.d.ts
  packages/components/src/Banner/Banner.mdx
  packages/components/src/Banner/Banner.tsx
  packages/components/src/Banner/__snapshots__/Banner.test.tsx.snap
  packages/components/src/Checkbox/Checkbox.css
  packages/components/src/RadioGroup/RadioGroup.css
  packages/design/src/shadows.css
Labels: approved

#450 docs: Product vocabulary list
  docs/guides/product-vocabulary.mdx
  public/assets/images/product-vocabulary/addvscreate.png
Labels: approved

#451 docs: fix image path on product vocabulary
  docs/guides/product-vocabulary.mdx
Labels: approved

#452 feat(components): add iOS autocomplete support for OTPs to form fields
  packages/components/src/FormField/FormField.test.tsx
  packages/components/src/FormField/FormField.tsx
Labels: approved

#453 fix(components): change line-height on large font size
  packages/components/src/Typography/css/FontSizes.css
Labels: approved, in review

#454 docs(components): propose an InputEmail component
  docs/proposals/InputEmail/InputEmail.md
  docs/proposals/InputEmail/inputemail_blank.png
  docs/proposals/InputEmail/inputemail_error.png
  docs/proposals/InputEmail/inputemail_valid.png
Labels: approved, proposal

#457 feat(components): Add subtitle to Page component
  packages/components/src/Page/Page.css
  packages/components/src/Page/Page.css.d.ts
  packages/components/src/Page/Page.mdx
  packages/components/src/Page/Page.tsx
  packages/components/src/Page/__snapshots__/Page.test.tsx.snap
Labels: approved

#459 fix(components): Make page subtitle and intro optional
  packages/components/CHANGELOG.md
  packages/components/package-lock.json
  packages/components/package.json
  packages/components/src/Page/Page.tsx
Labels: approved

#401 feat(components): Add numberOfLines prop to Text component
  packages/components/src/Button/Button.mdx
  packages/components/src/DescriptionList/DescriptionList.mdx
  packages/components/src/Emphasis/Emphasis.test.tsx
  packages/components/src/FormatDate/FormatDate.mdx
  packages/components/src/FormatFile/FormatFile.mdx
  packages/components/src/InputPassword/InputPassword.mdx
  packages/components/src/Text/Text.mdx
  packages/components/src/Text/Text.test.tsx
  packages/components/src/Text/Text.tsx
  packages/components/src/Typography/Typography.test.tsx
  packages/components/src/Typography/Typography.tsx
  packages/components/src/Typography/css/Truncate.css
  packages/components/src/Typography/css/Truncate.css.d.ts
Labels: approved, external, hacktoberfest-accepted

#460 feat(components): spinner loading state on input text
  packages/components/src/FormField/FormField.css
  packages/components/src/FormField/FormField.test.tsx
  packages/components/src/FormField/FormField.tsx
  packages/components/src/InputText/InputText.mdx
  packages/components/src/Select/__snapshots__/Select.test.tsx.snap
Labels: changes requested, external
