Repository GetJobber/atlantis, pull requests merged in 2021-11, with the labels that each got.

#766 docs(components): Put InputValidation below the Input where it belongs
  packages/components/src/InputValidation/InputValidation.mdx
Labels: approved

#761 feat(components): Menu component respects fullwidth on custom activator such as button
  packages/components/src/Menu/Menu.css
  packages/components/src/Menu/Menu.css.d.ts
  packages/components/src/Menu/Menu.tsx
Labels: approved, design approved

#763 feat(components): add Body component to Table components
  packages/components/src/Table/Body.tsx
  packages/components/src/Table/Table.mdx
  packages/components/src/Table/Table.test.tsx
  packages/components/src/Table/__snapshots__/Table.test.tsx.snap
  packages/components/src/Table/index.ts
Labels: approved, external, hacktoberfest, hacktoberfest-accepted, accessibility

#740 fix: adding aria-controls and aria-hidden markup
  packages/components/src/Drawer/Drawer.mdx
  packages/components/src/Drawer/Drawer.tsx
Labels: approved, external, hacktoberfest, hacktoberfest-accepted, accessibility, design approved

#770 docs(components): add warning to InputValidation
  packages/components/src/InputValidation/InputValidation.mdx
Labels: approved

#772 refactor: Fix linting and tests on Drawer
  packages/components/src/Drawer/Drawer.test.tsx
  packages/components/src/Drawer/Drawer.tsx
Labels: approved

#776 fix(components): use correct colors for disabled text
  packages/components/src/FormField/FormField.css
Labels: approved

#777 feat(components): Use focus shadow instead of focus border
  packages/components/src/FormField/FormField.css
Labels: approved, accessibility

#775 docs(design): Focus on focus
  packages/design/src/Colors.mdx
Labels: approved, design review requested

#774 feat(components): DatePicker component
  packages/components/package-lock.json
  packages/components/package.json
  packages/components/patches/@types+react-datepicker+4.1.7.patch
  packages/components/src/DatePicker/DatePicker.css
  packages/components/src/DatePicker/DatePicker.css.d.ts
  packages/components/src/DatePicker/DatePicker.mdx
  packages/components/src/DatePicker/DatePicker.test.tsx
  packages/components/src/DatePicker/DatePicker.tsx
  packages/components/src/DatePicker/DatePickerCustomHeader.tsx
  packages/components/src/DatePicker/index.ts
  packages/components/src/Typography/Typography.tsx
  packages/components/src/Typography/css/FontFamilies.css
  packages/components/src/Typography/css/FontFamilies.css.d.ts
Labels: approved, design approved

#780 docs(components): include layout considerations in Banner guidelines
  packages/components/src/Banner/Banner.mdx
Labels: approved, design approved

#779 docs(design): Write spacing guidelines
  packages/design/src/Spacing.mdx
Labels: approved, design review requested

#778 fix(components): Allowlist accepted image types [JOB-37183]
  packages/components/src/InputFile/InputFile.tsx
Labels: approved, external

#784 feat(components): Adjust formfield suffix actions to subtle
  packages/components/src/FormField/FormFieldAffix.tsx
  packages/components/src/InputText/InputText.mdx
Labels: approved

#787 feat(components): update toast visuals and timing [JOB-27572]
  packages/components/src/Toast/Toast.css
  packages/components/src/Toast/Toast.tsx
Labels: approved, Team McWeb
