Repository GetJobber/atlantis, pull requests merged in 2021-07, with the labels that each got.

#587 docs: add grammar guide and move product vocab to content section
  docs/content/product-vocabulary.mdx
  docs/content/voice-and-tone.mdx
Labels: approved

#561 feat(hooks): add useCollectionQuery and useIsMounted [JOB-32207]
  doczrc.js
  package-lock.json
  package.json
  packages/formatters/src/config.ts
  packages/hooks/package-lock.json
  packages/hooks/package.json
  packages/hooks/src/index.ts
  packages/hooks/src/useCollectionQuery/index.ts
  packages/hooks/src/useCollectionQuery/mdxUtils.ts
  packages/hooks/src/useCollectionQuery/test-utilities/index.ts
  packages/hooks/src/useCollectionQuery/test-utilities/mocks.tsx
  packages/hooks/src/useCollectionQuery/test-utilities/queries.ts
  packages/hooks/src/useCollectionQuery/test-utilities/utils.ts
  packages/hooks/src/useCollectionQuery/uniqueEdges.tsx
  packages/hooks/src/useCollectionQuery/uniqueNodes.tsx
  packages/hooks/src/useCollectionQuery/useCollectionQuery.mdx
  packages/hooks/src/useCollectionQuery/useCollectionQuery.test.tsx
  packages/hooks/src/useCollectionQuery/useCollectionQuery.ts
  packages/hooks/src/useIsMounted/index.ts
  packages/hooks/src/useIsMounted/useIsMounted.mdx
  packages/hooks/src/useIsMounted/useIsMounted.test.tsx
  packages/hooks/src/useIsMounted/useIsMounted.ts
  packages/hooks/tsconfig.json
Labels: Communiverse, approved, external

#586 docs: Initial Pass on frontend style
  docs/guides/frontent-style.mdx
Labels: 30%, approved

#589 feat(hooks): Update useCollectionQuery to handle search terms [32867]
  packages/hooks/src/useCollectionQuery/test-utilities/mocks.tsx
  packages/hooks/src/useCollectionQuery/test-utilities/queries.ts
  packages/hooks/src/useCollectionQuery/useCollectionQuery.test.tsx
  packages/hooks/src/useCollectionQuery/useCollectionQuery.ts
Labels: Communiverse, approved

#591 docs(components): update icon docs
  packages/components/src/Icon/Icon.mdx
Labels: approved

#590 feat(design): add active surface and dimmed overlay colors
  packages/components/src/List/ListItem.css
  packages/design/src/Colors.mdx
  packages/design/src/colors.css
  packages/docx/src/ColorSwatches/ColorSwatch/ColorSwatch.css
Labels: approved

#588 feat(design): introduce web shadow variations, document and add to Toast
  packages/components/src/Toast/Toast.css
  packages/components/src/Toast/Toast.mdx
  packages/design/src/Elevations.mdx
  packages/design/src/shadows.css
Labels: approved

#592 feat(design): add directions icon
  packages/components/src/Icon/Icon.mdx
  packages/design/src/icons/iconMap.ts
Labels: approved

#599 fix(design): clean up --rgb tokens
  packages/design/src/colors.css
Labels: approved
