Repository GetJobber/atlantis, pull requests merged in 2021-04, with the labels that each got.

#490 fix(components): use correct html for DescriptionList
  packages/components/src/DescriptionList/DescriptionList.tsx
  packages/components/src/DescriptionList/__snapshots__/DescriptionList.test.tsx.snap
Labels: approved

#491 fix(components): allow screen-readers to skip Divider
  packages/components/src/Divider/Divider.tsx
  packages/components/src/Divider/__snapshots__/Divider.test.tsx.snap
Labels: approved

#498 docs(components): enhance our elevation docs to reflect mobile work
  packages/design/src/Elevations.mdx
Labels: approved

#500 docs(design): Docs With Borders (write docs for Borders)
  packages/components/src/Card/Card.css
  packages/components/src/Drawer/Drawer.css
  packages/components/src/FormField/FormField.css
  packages/components/src/FormatFile/FormatFile.css
  packages/components/src/InputFile/InputFile.css
  packages/components/src/List/List.css
  packages/components/src/List/SectionHeader.css
  packages/components/src/Modal/Modal.css
  packages/components/src/Table/Table.css
  packages/components/src/Tabs/Tabs.css
  packages/design/src/Borders.mdx
  packages/design/src/borders.css
Labels: approved

#499 docs(generators): Update component documentation template
  packages/generators/templates/component/{{name}}.{{mdx}}
Labels: approved

#486 docs(components): Add accessibility notes to Spinner
  packages/components/src/Spinner/Spinner.mdx
Labels: approved

#351 docs(components): Disclosure Component Proposal
  docs/proposals/Disclosure/README.md
Labels: approved, external, proposal

#502 docs: update our contribution docs to reflect our new process and content
  docs/CONTRIBUTING.md
  docs/proposals/TEMPLATE.md
Labels: approved

#494 feat(components): Add new popover component
  packages/components/package-lock.json
  packages/components/package.json
  packages/components/src/Popover/Popover.css
  packages/components/src/Popover/Popover.css.d.ts
  packages/components/src/Popover/Popover.mdx
  packages/components/src/Popover/Popover.test.tsx
  packages/components/src/Popover/Popover.tsx
  packages/components/src/Popover/index.ts
Labels: changes requested

#501 docs(components): update Tooltip to reflect Popover
  packages/components/src/Tooltip/Tooltip.mdx
Labels: approved

#503 fix(docz-tools): change configuration option for hiding logo to resolve undefined page titles
  packages/docz-tools/README.md
  packages/docz-tools/src/gatsby-theme-docz/components/Sidebar/index.tsx
Labels: approved, external

#510 docs: remove ComponentStatus and clean up some "related components" and "usage" verbiage
  packages/docx/src/ComponentStatus/ComponentStatus.tsx
Labels: approved

#509 feat(design): Update timing variables and docs
  packages/components/src/Button/Button.css
  packages/design/src/animation.mdx
  packages/design/src/timings.css
Labels: approved

#505 docs(components): Tweak some verbiage and order of the Popover docs
  packages/components/src/Popover/Popover.css
  packages/components/src/Popover/Popover.mdx
  packages/components/src/Popover/Popover.tsx
Labels: approved

#512 docs: Add note on requesting review
  docs/CONTRIBUTING.md
Labels: approved

#506 fix(components): Allow input validation to be easily read by assistive tech
  packages/components/src/InputValidation/InputValidation.css
  packages/components/src/InputValidation/InputValidation.test.tsx
  packages/components/src/InputValidation/InputValidation.tsx
Labels: accessibility, approved

#508 feat(components): Add new Disclosure component
  packages/components/package-lock.json
  packages/components/package.json
  packages/components/src/Disclosure/Disclosure.css
  packages/components/src/Disclosure/Disclosure.css.d.ts
  packages/components/src/Disclosure/Disclosure.mdx
  packages/components/src/Disclosure/Disclosure.test.tsx
  packages/components/src/Disclosure/Disclosure.tsx
  packages/components/src/Disclosure/__snapshots__/Disclosure.test.tsx.snap
  packages/components/src/Disclosure/index.ts
Labels: approved, external

#514 fix(components): use CSS only to determine whether to open arrow
  packages/components/src/Disclosure/Disclosure.css
  packages/components/src/Disclosure/Disclosure.css.d.ts
  packages/components/src/Disclosure/Disclosure.tsx
Labels: approved

#511 docs: add installation notes to Atlantis home
  docs/README.md
Labels: approved

#444 feat(design): introduce semantic colors to Atlantis foundation [JOB-28065]
  packages/components/src/Autocomplete/Autocomplete.css
  packages/components/src/Button/Button.css
  packages/components/src/Card/Card.css
  packages/components/src/Card/colors.css
  packages/components/src/Card/colors.css.d.ts
  packages/components/src/FormField/FormField.css
  packages/components/src/FormatFile/FormatFile.css
  packages/components/src/InputFile/InputFile.css
  packages/components/src/Menu/Menu.css
  packages/components/src/Modal/Modal.css
  packages/components/src/Select/Select.css
  packages/design/src/Colors.mdx
  packages/design/src/borders.css
  packages/design/src/colors.css
  packages/design/src/shadows.css
  packages/docx/src/ColorSwatches/ColorSwatch/ColorSwatch.css
  packages/docx/src/ColorSwatches/ColorSwatch/ColorSwatch.tsx
Labels: approved

#515 fix(components): fixes the descenders on Select
  packages/components/src/FormField/FormField.css
  packages/components/src/FormField/FormField.css.d.ts
  packages/components/src/FormField/FormField.tsx
  packages/components/src/Select/Select.mdx
  packages/components/src/Select/__snapshots__/Select.test.tsx.snap
Labels: approved

#516 fix(components): Fix the css for Select with miniLabel
  packages/components/src/FormField/FormField.css
  packages/components/src/Select/Select.mdx
Labels: approved

#518 docs(hooks): Add Jest testing section to useResizeObserver docs
  packages/hooks/src/useResizeObserver.mdx
Labels: approved, external
