Repository GetJobber/atlantis, pull requests merged in 2021-08, with the labels that each got.

#579 fix(hooks): fix refreshing expected behaviour until apollo fix lands
  packages/hooks/src/useCollectionQuery/useCollectionQuery.ts
Labels: approved, Communiverse

#603 fix(components): Focus the first error on Form submission
  packages/components/src/Form/Form.test.tsx
  packages/components/src/Form/Form.tsx
Labels: review requested, approved

#604 feat(components): Add compose icon [JOB-33955]
  packages/components/src/Icon/Icon.mdx
  packages/design/src/icons/iconMap.ts
Labels: approved, Communiverse

#611 feat(components): Add more values to autocomplete attribute
  packages/components/src/FormField/FormField.test.tsx
  packages/components/src/FormField/FormField.tsx
  packages/components/src/FormField/FormFieldTypes.ts
Labels: approved

#610 feat(components): Adds the InputEmail component
  packages/components/src/FormField/FormFieldTypes.ts
  packages/components/src/InputEmail/InputEmail.mdx
  packages/components/src/InputEmail/InputEmail.test.tsx
  packages/components/src/InputEmail/InputEmail.tsx
  packages/components/src/InputEmail/index.ts
Labels: approved

#615 fix(design): temp fix the colors until a good fix is available
  packages/design/src/colors.css
Labels: approved

#616 fix(design): Fix parsing of colors.css to support rgb and rgba [JOB-34356]
  packages/design/jobberStyle.js
  packages/design/src/colors.css
Labels: approved, external

#617 docs: add XOR note
  docs/guides/frontent-style.mdx
Labels: review requested

#630 fix(hooks): update exports to include usePasswordStrength
  packages/hooks/src/index.ts
Labels: approved, external
