Repository GetJobber/atlantis, pull requests merged in 2021-12, with the labels that each got.

#783 feat(components): InputDate Component
  packages/components/src/DatePicker/DatePicker.css
  packages/components/src/DatePicker/DatePicker.css.d.ts
  packages/components/src/DatePicker/DatePicker.tsx
  packages/components/src/DatePicker/DatePickerActivator.test.tsx
  packages/components/src/DatePicker/DatePickerActivator.tsx
  packages/components/src/FormField/FormField.test.tsx
  packages/components/src/FormField/FormField.tsx
  packages/components/src/FormField/FormFieldTypes.ts
  packages/components/src/InputDate/InputDate.mdx
  packages/components/src/InputDate/InputDate.test.tsx
  packages/components/src/InputDate/InputDate.tsx
  packages/components/src/InputDate/index.ts
  packages/components/src/InputEmail/InputEmail.tsx
  packages/components/src/InputNumber/InputNumber.tsx
  packages/components/src/InputPassword/InputPassword.tsx
  packages/components/src/InputText/InputText.tsx
  packages/components/src/Select/Select.test.tsx
  packages/design/src/elevations.css
Labels: approved, Team McWeb

#791 fix(components): Fix Activator Test
  packages/components/src/DatePicker/DatePickerActivator.test.tsx
Labels: approved, Team McWeb

#788 docs(components): remove error toast from examples
  packages/components/src/Toast/Toast.mdx
Labels: approved, design review requested

#781 docs(components): update warning banner content for use case clarity
  packages/components/src/Banner/Banner.mdx
Labels: approved, design review requested

#786 docs(components): add more detail to datepicker usage
  packages/components/src/DatePicker/DatePicker.mdx
Labels: approved, design review requested

#798 fix(components): Make countdown label smarter [JOB-39652]
  packages/components/src/Countdown/Countdown.test.tsx
  packages/components/src/Countdown/Countdown.tsx
  packages/components/src/Countdown/computeTimeUnit.test.tsx
  packages/components/src/Countdown/computeTimeUnit.tsx
Labels: approved, Team McWeb

#796 chore(deps): Upgrade atlantis to node 14
  .circleci/config.yml
  .nvmrc
  docs/README.md
  packages/components/src/FormatDate/FormatDate.test.tsx
  packages/components/src/FormatDate/__snapshots__/FormatDate.test.tsx.snap
  packages/components/src/FormatRelativeDateTime/FormatRelativeDateTime.test.tsx
  packages/docz-tools/package-lock.json
Labels: approved, Team McWeb

#805 build: Decrease max old space size back to Node 10 value of 1400MB
  .circleci/config.yml
Labels: approved

#797 chore(deps): Bump UUID to latest
  packages/components/__mocks__/uuid.ts
  packages/components/package-lock.json
  packages/components/package.json
  packages/components/src/Chips/InternalChipSingleSelect.tsx
  packages/components/src/FormField/FormField.tsx
  packages/components/src/InputFile/InputFile.mdx
  packages/components/src/InputFile/InputFile.tsx
  packages/components/src/Menu/Menu.tsx
  packages/components/src/RadioGroup/RadioGroup.tsx
  packages/components/src/RadioGroup/RadioOption.tsx
  packages/hooks/package-lock.json
  packages/hooks/package.json
  packages/hooks/src/useCollectionQuery/test-utilities/mocks.tsx
Labels: approved, Team McWeb

#807 fix(components): Prevent date picker from flickering / closing when click the activator again
  packages/components/src/DatePicker/DatePicker.test.tsx
  packages/components/src/DatePicker/DatePicker.tsx
Labels: approved, Team McWeb

#758 fix: Stop search results from lagging by one keystroke.
  packages/docz-tools/src/gatsby-theme-docz/components/Navigation/Navigation.tsx
Labels: approved, hacktoberfest, hacktoberfest-accepted

#757 fix: resolve build warning
  packages/design/src/foundation.css.d.ts
Labels: approved, hacktoberfest, hacktoberfest-accepted

#808 chore(components): Add test for datepicker to make sure custom css doesnt fail
  packages/components/src/DatePicker/DatePicker.test.tsx
Labels: approved, Team McWeb

#762 fix(components): Fix form field inconsistent spacing when used under Form and InputGroup JOB-37646
  packages/components/src/Autocomplete/__snapshots__/Autocomplete.test.tsx.snap
  packages/components/src/FormField/FormField.css
  packages/components/src/FormField/FormField.css.d.ts
  packages/components/src/FormField/FormFieldDescription.tsx
  packages/components/src/FormField/FormFieldWrapper.tsx
  packages/components/src/FormField/__snapshots__/FormField.test.tsx.snap
  packages/components/src/InputGroup/InputGroup.css
  packages/components/src/InputNumber/InputNumber.test.tsx
  packages/components/src/InputPassword/__snapshots__/InputPassword.test.tsx.snap
  packages/components/src/InputText/InputText.test.tsx
  packages/components/src/InputTime/InputTime.test.tsx
  packages/components/src/InputValidation/InputValidation.css
  packages/components/src/InputValidation/InputValidation.css.d.ts
  packages/components/src/Select/__snapshots__/Select.test.tsx.snap
Labels: approved, Team McWeb

#806 feat(components): Update checkbox to use react components as a label
  packages/components/src/Checkbox/Checkbox.mdx
  packages/components/src/Checkbox/Checkbox.test.tsx
  packages/components/src/Checkbox/Checkbox.tsx
  packages/components/src/Checkbox/__snapshots__/Checkbox.test.tsx.snap
Labels: changes requested, design approved, Team McFriends

#810 chore(components): Make datepicker import css module instead of general css [JOB-38626]
  packages/components/src/DatePicker/DatePicker.css
  packages/components/src/DatePicker/DatePicker.css.d.ts
  packages/components/src/DatePicker/DatePicker.tsx
Labels: approved, Team McWeb

#811 fix(components): Move import of ReactDatePicker CSS back to DatePicker.tsx
  packages/components/src/DatePicker/DatePicker.css
  packages/components/src/DatePicker/DatePicker.css.d.ts
  packages/components/src/DatePicker/DatePicker.tsx
Labels: approved, Team McWeb

#799 feat(components): More dividers to align with mobile conventions
  packages/components/src/Divider/Divider.css
  packages/components/src/Divider/Divider.css.d.ts
  packages/components/src/Divider/Divider.mdx
  packages/components/src/Divider/Divider.test.tsx
  packages/components/src/Divider/Divider.tsx
  packages/components/src/Divider/__snapshots__/Divider.test.tsx.snap
  packages/design/src/Borders.mdx
  packages/design/src/borders.css
Labels: approved, design approved

#793 feat(components): RecurringSelect Component
  packages/components/src/RecurringSelect/CurrentRecurrenceComponent.tsx
  packages/components/src/RecurringSelect/DateCellCheckbox.css
  packages/components/src/RecurringSelect/DateCellCheckbox.css.d.ts
  packages/components/src/RecurringSelect/RecurringSelect.css
  packages/components/src/RecurringSelect/RecurringSelect.css.d.ts
  packages/components/src/RecurringSelect/RecurringSelect.mdx
  packages/components/src/RecurringSelect/RecurringSelect.test.tsx
  packages/components/src/RecurringSelect/RecurringSelect.tsx
  packages/components/src/RecurringSelect/components/DayOfMonthSelect/DayOfMonthSelect.css
  packages/components/src/RecurringSelect/components/DayOfMonthSelect/DayOfMonthSelect.css.d.ts
  packages/components/src/RecurringSelect/components/DayOfMonthSelect/DayOfMonthSelect.test.tsx
  packages/components/src/RecurringSelect/components/DayOfMonthSelect/DayOfMonthSelect.tsx
  packages/components/src/RecurringSelect/components/MonthlyDayOfWeekSelect/MonthlyDayOfWeekSelect.css
  packages/components/src/RecurringSelect/components/MonthlyDayOfWeekSelect/MonthlyDayOfWeekSelect.css.d.ts
  packages/components/src/RecurringSelect/components/MonthlyDayOfWeekSelect/MonthlyDayOfWeekSelect.test.tsx
  packages/components/src/RecurringSelect/components/MonthlyDayOfWeekSelect/MonthlyDayOfWeekSelect.tsx
  packages/components/src/RecurringSelect/components/MonthlySelect/MonthlySelect.css
  packages/components/src/RecurringSelect/components/MonthlySelect/MonthlySelect.css.d.ts
  packages/components/src/RecurringSelect/components/MonthlySelect/MonthlySelect.tsx
  packages/components/src/RecurringSelect/components/WeeklySelect/WeeklySelect.css
  packages/components/src/RecurringSelect/components/WeeklySelect/WeeklySelect.css.d.ts
  packages/components/src/RecurringSelect/components/WeeklySelect/WeeklySelect.tsx
  packages/components/src/RecurringSelect/components/index.tsx
  packages/components/src/RecurringSelect/index.tsx
  packages/components/src/RecurringSelect/types.ts
Labels: approved, design approved, Team McWeb

#812 fix: DatePicker smart focus [JOB-39118, JOB-38255]
  packages/components/src/DatePicker/DatePicker.test.tsx
  packages/components/src/DatePicker/DatePicker.tsx
  packages/components/src/InputDate/InputDate.tsx
Labels: approved, Team McWeb

#794 chore(deps): Remove datepicker header type patch
  packages/components/package-lock.json
  packages/components/package.json
  packages/components/patches/@types+react-datepicker+4.1.7.patch
Labels: approved, Team McWeb

#817 fix(components): Move focus to hook
  packages/components/src/DatePicker/DatePicker.test.tsx
  packages/components/src/DatePicker/DatePicker.tsx
  packages/components/src/DatePicker/useFocusOnSelectedDate.test.tsx
  packages/components/src/DatePicker/useFocusOnSelectedDate.ts
Labels: approved, Team McWeb

#815 fix(components): Revert fix form field inconsistent spacing when used under Form and InputGroup JOB-37646
  packages/components/src/Autocomplete/__snapshots__/Autocomplete.test.tsx.snap
  packages/components/src/FormField/FormField.css
  packages/components/src/FormField/FormField.css.d.ts
  packages/components/src/FormField/FormFieldDescription.tsx
  packages/components/src/FormField/FormFieldWrapper.tsx
  packages/components/src/FormField/__snapshots__/FormField.test.tsx.snap
  packages/components/src/InputGroup/InputGroup.css
  packages/components/src/InputNumber/InputNumber.test.tsx
  packages/components/src/InputPassword/__snapshots__/InputPassword.test.tsx.snap
  packages/components/src/InputText/InputText.test.tsx
  packages/components/src/InputTime/InputTime.test.tsx
  packages/components/src/InputValidation/InputValidation.css
  packages/components/src/InputValidation/InputValidation.css.d.ts
  packages/components/src/Select/__snapshots__/Select.test.tsx.snap
Labels: approved, Team McWeb

#818 chore(components): Update package json to accommodate the DatePicker import
  package.json
  packages/components/package.json
  packages/components/src/DatePicker/DatePicker.css
  packages/components/src/DatePicker/DatePicker.css.d.ts
  packages/components/src/DatePicker/DatePicker.tsx
  packages/generators/templates/component/{{name}}.css.d.ts
Labels: approved, Team McWeb
