Repository GetJobber/atlantis, pull requests merged in 2021-06, with the labels that each got.

#558 docs: remove the "gold" in sidenav and increase contrast of pageLabel
  packages/docz-tools/src/gatsby-theme-docz/components/Logo/styles.ts
  packages/docz-tools/src/gatsby-theme-docz/components/Navigation/Navigation.module.css
Labels: approved

#557 docs(design): create radius docs
  packages/design/src/Radii.mdx
Labels: approved

#559 docs: keep newlines of pageLabel aligned
  packages/docz-tools/src/gatsby-theme-docz/components/Navigation/Navigation.module.css
Labels: approved

#548 feat(components): use aside and ButtonDismiss
  packages/components/src/Drawer/Drawer.css
  packages/components/src/Drawer/Drawer.css.d.ts
  packages/components/src/Drawer/Drawer.mdx
  packages/components/src/Drawer/Drawer.tsx
Labels: accessibility, approved

#563 fix: Text / Typography don't always respect maxLines [JOB-32400]
  packages/components/src/Typography/Typography.test.tsx
  packages/components/src/Typography/Typography.tsx
Labels: approved, external

#504 fix: resolve render issues when using controlled component inside form component
  packages/components/src/Autocomplete/__snapshots__/Autocomplete.test.tsx.snap
  packages/components/src/FormField/FormField.test.tsx
  packages/components/src/FormField/FormField.tsx
  packages/components/src/InputPassword/InputPassword.test.tsx
  packages/components/src/InputTime/InputTime.test.tsx
Labels: approved, external

#564 feat(components): Include responsive breakpoints in Rollup
  packages/components/rollup.config.js
Labels: approved

#562 feat(hooks): add useCollectionQuery and useIsMounted [JOB-32207]
  package-lock.json
  package.json
  packages/hooks/package-lock.json
  packages/hooks/package.json
  packages/hooks/src/configure.test.ts
  packages/hooks/src/configure.ts
  packages/hooks/src/index.ts
  packages/hooks/src/useCollectionQuery/__mocks__/index.ts
  packages/hooks/src/useCollectionQuery/__mocks__/mocks.tsx
  packages/hooks/src/useCollectionQuery/__mocks__/queries.ts
  packages/hooks/src/useCollectionQuery/__mocks__/utils.ts
  packages/hooks/src/useCollectionQuery/index.ts
  packages/hooks/src/useCollectionQuery/uniqueEdges.tsx
  packages/hooks/src/useCollectionQuery/uniqueNodes.tsx
  packages/hooks/src/useCollectionQuery/useCollectionQuery.mdx
  packages/hooks/src/useCollectionQuery/useCollectionQuery.test.tsx
  packages/hooks/src/useCollectionQuery/useCollectionQuery.ts
  packages/hooks/src/useIsMounted/index.ts
  packages/hooks/src/useIsMounted/useIsMounted.mdx
  packages/hooks/src/useIsMounted/useIsMounted.test.tsx
  packages/hooks/src/useIsMounted/useIsMounted.ts
  packages/hooks/tsconfig.json
Labels: Communiverse

#570 fix: Update NPM requirement
  docs/README.md
Labels: approved

#575 docs(hooks): MDX File Documentation for UseCollectionQuery and useIsMounted Hooks [32207]
  packages/hooks/src/useCollectionQuery/mdxUtils.ts
  packages/hooks/src/useCollectionQuery/useCollectionQuery.mdx
  packages/hooks/src/useIsMounted/useIsMounted.mdx
Labels: Communiverse, approved

#565 fix(hooks): Update package file [JOB-32207]
  packages/hooks/package-lock.json
  packages/hooks/package.json
  packages/hooks/tsconfig.json
Labels: Communiverse, approved

#577 fix(components): add "radiogroup" role to RadioGroup
  packages/components/src/RadioGroup/RadioGroup.tsx
  packages/components/src/RadioGroup/__snapshots__/RadioGroup.test.tsx.snap
Labels: accessibility, approved

#581 docs: Add skipnav to `Layout`
  packages/docz-tools/src/gatsby-theme-docz/components/Layout/Layout.module.css
  packages/docz-tools/src/gatsby-theme-docz/components/Layout/Layout.module.css.d.ts
  packages/docz-tools/src/gatsby-theme-docz/components/Layout/Layout.tsx
Labels: accessibility, approved

#578 feat(components): Refactor FormField to fix some bugs
  packages/components/src/Autocomplete/Autocomplete.tsx
  packages/components/src/Autocomplete/__snapshots__/Autocomplete.test.tsx.snap
  packages/components/src/Form/Form.mdx
  packages/components/src/FormField/FieldWrapper.tsx
  packages/components/src/FormField/FormField.test.tsx
  packages/components/src/FormField/FormField.tsx
  packages/components/src/FormField/FormFieldTypes.ts
  packages/components/src/FormField/FormLabel.tsx
  packages/components/src/FormField/FormSpinner.tsx
  packages/components/src/FormField/index.ts
  packages/components/src/InputNumber/InputNumber.test.tsx
  packages/components/src/InputNumber/InputNumber.tsx
  packages/components/src/InputPassword/InputPassword.test.tsx
  packages/components/src/InputPassword/InputPassword.tsx
  packages/components/src/InputText/InputText.test.tsx
  packages/components/src/InputText/InputText.tsx
  packages/components/src/InputTime/InputTime.test.tsx
  packages/components/src/InputTime/InputTimeProps.tsx
  packages/components/src/Select/Select.tsx
  packages/components/src/Select/__snapshots__/Select.test.tsx.snap
  packages/eslint-config/.eslintrc.js
  packages/eslint-config/package-lock.json
  packages/eslint-config/package.json
Labels: approved

#585 docs: Outline some notes for working in a MonoRepo
  docs/README.md
Labels: approved
