Repository GetJobber/atlantis, pull requests merged in 2021-09, with the labels that each got.

#628 feat(design): Update surface reverse color
  packages/design/src/Colors.mdx
  packages/design/src/colors.css
  packages/docz-tools/index.ts
  packages/docz-tools/src/components/ColorSwatches/ColorSwatches.module.css
  packages/docz-tools/src/components/ColorSwatches/ColorSwatches.module.css.d.ts
  packages/docz-tools/src/components/ColorSwatches/ColorSwatches.tsx
  packages/docz-tools/src/components/ColorSwatches/index.ts
Labels: approved

#613 feat(components): Add prefix/suffix to FormField
  packages/components/src/Autocomplete/__snapshots__/Autocomplete.test.tsx.snap
  packages/components/src/FormField/FieldWrapper.tsx
  packages/components/src/FormField/FormField.css
  packages/components/src/FormField/FormField.css.d.ts
  packages/components/src/FormField/FormField.test.tsx
  packages/components/src/FormField/FormField.tsx
  packages/components/src/FormField/FormFieldAffix.tsx
  packages/components/src/FormField/FormFieldPostFix.tsx
  packages/components/src/FormField/FormFieldTypes.ts
  packages/components/src/FormField/FormFieldWrapper.tsx
  packages/components/src/FormField/FormLabel.tsx
  packages/components/src/FormField/FormSpinner.tsx
  packages/components/src/InputNumber/InputNumber.test.tsx
  packages/components/src/InputPassword/InputPassword.test.tsx
  packages/components/src/InputText/InputText.mdx
  packages/components/src/InputText/InputText.test.tsx
  packages/components/src/InputTime/InputTime.test.tsx
  packages/components/src/Select/__snapshots__/Select.test.tsx.snap
Labels: approved

#631 feat(components): Add `event` argument to onClick events
  docs/CONTRIBUTING.md
  packages/components/src/Button/Button.tsx
  packages/components/src/ButtonDismiss/ButtonDismiss.tsx
  packages/components/src/Card/Card.tsx
  packages/components/src/List/ListItem.tsx
  packages/components/src/Menu/Menu.tsx
  packages/components/src/Tabs/Tabs.tsx
  packages/generators/templates/component/{{name}}.tsx
Labels: approved, external

#624 feat(components): add subtle button [JOB-34785]
  packages/components/src/Button/Button.css
  packages/components/src/Button/Button.css.d.ts
  packages/components/src/Button/Button.mdx
  packages/components/src/Button/Button.tsx
  packages/design/src/Colors.mdx
  packages/design/src/colors.css
Labels: approved

#638 fix(components): Create a hook to focus back on modal and popover activator
  packages/components/src/Modal/Modal.tsx
  packages/components/src/Popover/Popover.tsx
  packages/hooks/src/index.ts
  packages/hooks/src/useRefocusOnActivator/index.ts
  packages/hooks/src/useRefocusOnActivator/useRefocusOnActivator.mdx
  packages/hooks/src/useRefocusOnActivator/useRefocusOnActivator.test.tsx
  packages/hooks/src/useRefocusOnActivator/useRefocusOnActivator.ts
Labels: approved, accessibility, design approved

#643 fix(components): properly style disabled primary buttons
  packages/components/src/Button/Button.css
  packages/components/src/Button/Button.css.d.ts
Labels: approved

#639 build: Prevent manual releases
  .circleci/config.yml
  package-lock.json
  package.json
  scripts/preventManualRelease.js
Labels: approved

#644 fix(hooks): Temporarily delete flakey hook test
  packages/hooks/src/useRefocusOnActivator/useRefocusOnActivator.test.tsx
Labels: approved, external

#634 fix(components): Trap focus on the open modal [JOB-26477]
  packages/components/src/Modal/Modal.tsx
  packages/components/src/Modal/useFocusTrap.test.tsx
  packages/components/src/Modal/useFocusTrap.ts
Labels: approved, accessibility, design approved

#627 refactor(components): Refactor formfieldprops, remove exclude keyword useage
  packages/components/src/Autocomplete/Autocomplete.test.tsx
  packages/components/src/Autocomplete/Autocomplete.tsx
  packages/components/src/FormField/FormFieldTypes.ts
  packages/components/src/FormField/index.ts
  packages/components/src/InputEmail/InputEmail.tsx
  packages/components/src/InputNumber/InputNumber.tsx
  packages/components/src/InputPassword/InputPassword.tsx
  packages/components/src/InputText/InputText.tsx
  packages/components/src/InputTime/InputTimeProps.tsx
Labels: approved

#648 fix(components): remove aria-hidden prop on trap focus
  packages/components/src/Modal/useFocusTrap.test.tsx
  packages/components/src/Modal/useFocusTrap.ts
Labels: approved

#576 fix(components): improve Tabs accessibility
  packages/components/src/Tabs/Tabs.css
  packages/components/src/Tabs/Tabs.mdx
  packages/components/src/Tabs/Tabs.tsx
  packages/components/src/Tabs/__snapshots__/Tabs.test.tsx.snap
Labels: approved, accessibility

#653 fix: Revert Use the correct path for the iconMap.ts file…
  packages/design/package-lock.json
  packages/design/package.json
  packages/design/scripts/convertIcoMoon.ts
Labels: approved

#306 fix(eslint): Use @typescript-eslint extension rule for no-unused-expressions
  packages/components/src/Card/Card.test.tsx
  packages/components/src/Page/Page.test.tsx
  packages/components/src/Page/__snapshots__/Page.test.tsx.snap
  packages/eslint-config/.eslintrc.js
Labels: approved, external

#662 chore: sync up the package-lock
  packages/components/package-lock.json
Labels: approved

#667 feat(eslint): Update prettier to latest
  package-lock.json
  package.json
  packages/components/src/Banner/Banner.tsx
  packages/components/src/Form/Form.tsx
  packages/components/src/InputEmail/InputEmail.tsx
  packages/components/src/Page/Page.tsx
  packages/docz-tools/src/gatsby-theme-docz/components/Navigation/useJobberMenu.tsx
  packages/eslint-config/package-lock.json
  packages/eslint-config/package.json
  packages/hooks/src/useCollectionQuery/useCollectionQuery.ts
  packages/hooks/src/useOnKeyDown/useOnKeyDown.ts
  packages/hooks/src/usePasswordStrength/usePasswordStrength.ts
Labels: approved

#620 fix(components): Show tooltip on focus and let the screen readers announce the message [JOB-26479]
  packages/components/src/Tooltip/Tooltip.mdx
  packages/components/src/Tooltip/Tooltip.test.tsx
  packages/components/src/Tooltip/Tooltip.tsx
Labels: approved, accessibility, design approved

#665 docs(design): Adding subscription definitions to concepts and items in our product vocabulary
  docs/content/product-vocabulary.mdx
Labels: approved

#633 feat(components): Add destructive option for confirmation modal
  packages/components/src/Button/Button.tsx
  packages/components/src/ConfirmationModal/ConfirmationModal.mdx
  packages/components/src/ConfirmationModal/ConfirmationModal.tsx
  packages/components/src/ConfirmationModal/tests/interaction-ConfirmationModal.test.tsx
Labels: approved, design approved

#671 build: Fixes the markdown linter
  docs/content/product-vocabulary.mdx
  docs/guides/frontent-style.mdx
  docs/proposals/InputEmail/InputEmail.md
  package.json
  packages/components/src/Button/Button.mdx
  packages/components/src/Disclosure/Disclosure.mdx
  packages/components/src/Spinner/Spinner.mdx
  packages/hooks/src/useResizeObserver.mdx
Labels: approved

#673 fix(components): Add small size to avatar
  packages/components/src/Avatar/Avatar.css
  packages/components/src/Avatar/Avatar.css.d.ts
  packages/components/src/Avatar/Avatar.mdx
  packages/components/src/Avatar/Avatar.tsx
Labels: approved, external

#676 fix(components): clean up focus state on Avatar
  packages/components/src/Avatar/Avatar.css
Labels: approved

#669 feat(components): Added keyboard shortcut to confirmation modal
  docs/proposals/InputEmail/InputEmail.md
  packages/components/src/ConfirmationModal/ConfirmationModal.tsx
  packages/components/src/ConfirmationModal/tests/interaction-ConfirmationModal.test.tsx
  packages/hooks/src/useResizeObserver.mdx
Labels: approved, external, accessibility, design approved

#679 fix: Support semantic colors on icon
  packages/components/src/Icon/Icon.tsx
  packages/design/src/icons/Colors.css
  packages/design/src/icons/Colors.css.d.ts
  packages/design/src/icons/getIcon.ts
Labels: approved

#681 docs: use inverse examples for remove and delete
  docs/content/product-vocabulary.mdx
Labels: approved

#685 fix: adjust skipnav offset in hidden state
  packages/docz-tools/src/gatsby-theme-docz/components/Layout/Layout.module.css
Labels: approved

#683 feat: update sidenav to match Jobber appearance
  packages/docz-tools/src/gatsby-theme-docz/components/Navigation/Navigation.module.css
  packages/docz-tools/src/gatsby-theme-docz/components/Sidebar/styles.ts
Labels: approved

#688 feat(components): export banner type
  packages/components/src/Banner/Banner.mdx
  packages/components/src/Banner/Banner.tsx
  packages/components/src/Banner/index.ts
Labels: approved

#694 chore: fix README hyperlink to CONTRIBUTING.md
  docs/README.md
Labels: approved, hacktoberfest, hacktoberfest-accepted

#668 feat(design): add Typography letter spacing to @jobber/design [JOB-29564]
  docs/content/product-vocabulary.mdx
  package-lock.json
  packages/design/src/Typography.mdx
  packages/design/src/colors.css
  packages/design/src/foundation.css
  packages/design/src/typography.css
Labels: approved, external
