Repository GetJobber/atlantis, pull requests merged in 2021-10, with the labels that each got.

#678 feat(components): Add chips (single/multiple/standalone dismissible) component [JOB-35714]
  packages/components/src/Chips/Chip.tsx
  packages/components/src/Chips/ChipDismissible.tsx
  packages/components/src/Chips/ChipTypes.tsx
  packages/components/src/Chips/Chips.mdx
  packages/components/src/Chips/Chips.tsx
  packages/components/src/Chips/ChipsTypes.tsx
  packages/components/src/Chips/InternalChip.css
  packages/components/src/Chips/InternalChip.css.d.ts
  packages/components/src/Chips/InternalChip.tsx
  packages/components/src/Chips/InternalChipAffix.tsx
  packages/components/src/Chips/InternalChipButton.tsx
  packages/components/src/Chips/InternalChipMultiSelect.tsx
  packages/components/src/Chips/InternalChipSingleSelect.tsx
  packages/components/src/Chips/index.ts
  packages/components/src/Chips/tests/Chip.test.tsx
  packages/components/src/Chips/tests/ChipDismissible.test.tsx
  packages/components/src/Chips/tests/InternalChip.test.tsx
  packages/components/src/Chips/tests/InternalChipButton.test.tsx
  packages/components/src/Chips/tests/InternalChipMultiSelect.test.tsx
  packages/components/src/Chips/tests/InternalChipSingleSelect.test.tsx
  packages/components/src/Chips/useAssert.tsx
Labels: approved, design approved

#702 docs(design): Add 'refresh' to product vocabulary
  docs/content/product-vocabulary.mdx
Labels: approved, hacktoberfest, hacktoberfest-accepted

#706 feat(components): Autofocus on first Menu item
  packages/components/src/Content/Paddings.css.d.ts
  packages/components/src/Menu/Menu.test.tsx
  packages/components/src/Menu/Menu.tsx
  packages/components/src/Select/Select.css.d.ts
Labels: approved, hacktoberfest, hacktoberfest-accepted

#712 fix(components): Fix formatting of css declaration files to unbreak Lerna
  packages/components/src/Content/Paddings.css.d.ts
  packages/components/src/Select/Select.css.d.ts
Labels: approved

#711 fix: Rerender select and padding css.d.ts
  packages/components/src/Content/Paddings.css.d.ts
  packages/components/src/Select/Select.css.d.ts
Labels: approved

#703 fix(components): Add a more distinct aria-label to Banner
  packages/components/src/Banner/Banner.test.tsx
  packages/components/src/Banner/Banner.tsx
  packages/components/src/Banner/__snapshots__/Banner.test.tsx.snap
Labels: approved, hacktoberfest, hacktoberfest-accepted

#625 fix(components): Make onclick card operable by keyboard [JOB-30838]
  packages/components/src/Card/Card.tsx
  packages/components/src/Card/CardClickable.tsx
  packages/components/src/Card/tests/Card.test.tsx
  packages/components/src/Card/tests/CardClickable.test.tsx
Labels: blocked, approved, accessibility, design approved

#719 feat(components): add ability to specify external url on card
  packages/components/src/Card/Card.mdx
  packages/components/src/Card/Card.tsx
  packages/components/src/Card/tests/Card.test.tsx
Labels: approved, hacktoberfest, hacktoberfest-accepted

#718 fix(components): Card no longer overrides border color variable
  packages/components/src/Card/Card.css
Labels: approved, hacktoberfest, hacktoberfest-accepted

#722 docs: Add content guidelines to Banner component
  packages/components/src/Banner/Banner.mdx
Labels: approved, hacktoberfest, hacktoberfest-accepted, design review requested
