Repository GetJobber/atlantis, pull requests merged in 2022-03, with the labels that each got.

#861 feat(design): update overlay color to black
  packages/components/src/FormatFile/FormatFile.css
  packages/components/src/LightBox/LightBox.css
  packages/components/src/Menu/Menu.css
  packages/components/src/Modal/Modal.css
  packages/design/src/colors.css
Labels: approved

#814 build(deps): Uninstall @types/jest under hooks
  packages/hooks/package-lock.json
  packages/hooks/package.json
Labels: approved, Team McWeb

#863 fix(components): Update tooltip to use react-popper
  packages/components/src/Tooltip/Tooltip.tsx
  packages/components/src/Tooltip/useTooltipPositioning.ts
Labels: approved, Team McWeb

#864 chore(deps): sync package-lock
  packages/hooks/package-lock.json
Labels: approved, Team McWeb

#869 fix(components): Update popover elevation and width
  packages/components/src/Popover/Popover.css
Labels: approved, Team McWeb

#870 feat(components): create statuslabel component
  packages/components/src/StatusLabel/StatusLabel.css
  packages/components/src/StatusLabel/StatusLabel.css.d.ts
  packages/components/src/StatusLabel/StatusLabel.mdx
  packages/components/src/StatusLabel/StatusLabel.test.tsx
  packages/components/src/StatusLabel/StatusLabel.tsx
  packages/components/src/StatusLabel/__snapshots__/StatusLabel.test.tsx.snap
  packages/components/src/StatusLabel/index.ts
Labels: approved, design approved, Team McFriends
