Repository GetJobber/atlantis, pull requests merged in 2022-04, with the labels that each got.

#872 feat(components): Enable chip navigation with left and right arrow keys
  packages/components/src/Chips/ChipTypes.tsx
  packages/components/src/Chips/InternalChip.css
  packages/components/src/Chips/InternalChip.tsx
  packages/components/src/Chips/InternalChipDismissible/InternalChipDismissible.tsx
  packages/components/src/Chips/InternalChipDismissible/InternalChipDismissibleInput.tsx
  packages/components/src/Chips/InternalChipDismissible/InternalChipDismissibleTypes.ts
  packages/components/src/Chips/InternalChipDismissible/__tests__/InternalChipDismissible.test.tsx
  packages/components/src/Chips/InternalChipDismissible/__tests__/InternalChipDismissibleInput.test.tsx
  packages/components/src/Chips/InternalChipDismissible/hooks/__tests__/useInternalChipDismissible.test.tsx
  packages/components/src/Chips/InternalChipDismissible/hooks/__tests__/useInternalChipDismissibleInput.test.tsx
  packages/components/src/Chips/InternalChipDismissible/hooks/useInternalChipDismissible.ts
  packages/components/src/Chips/InternalChipDismissible/hooks/useInternalChipDismissibleInput.tsx
Labels: approved, Team McWeb

#874 fix(components): Disable enter press on chip menu debounce
  packages/components/src/Chips/InternalChipDismissible/hooks/useInternalChipDismissibleInput.tsx
Labels: approved, Team McWeb

#880 fix(design): Add back missing icon colors types
  packages/design/package-lock.json
  packages/design/package.json
  packages/design/rollup.config.js
  packages/design/src/icons/getIcon.ts
Labels: approved, Team McWeb

#881 feat(components): only wrap Banner children in Text if they are a simple string.
  packages/components/src/Banner/Banner.test.tsx
  packages/components/src/Banner/Banner.tsx
Labels: approved, Team McWeb, Team Brickheads

#836 feat(stylelint): Add alpha-value-notation rule to stylelint
  package-lock.json
  package.json
  packages/components/src/Button/Button.css
  packages/docz-tools/package-lock.json
  packages/stylelint-config/package.json
  packages/stylelint-config/stylelint.config.js
Labels: approved
