Repository GetJobber/atlantis, pull requests merged in 2022-12, with the labels that each got.

#945 feat(component) add size property to MultiSelect component
  packages/components/src/MultiSelect/MultiSelect.css
  packages/components/src/MultiSelect/MultiSelect.css.d.ts
  packages/components/src/MultiSelect/MultiSelect.mdx
  packages/components/src/MultiSelect/MultiSelect.tsx
Labels: approved, design approved, Team Atlantis

#948 fix(design) Add box-sizing css to MultiSelect component
  packages/components/src/MultiSelect/MultiSelect.css
Labels: approved, Team Atlantis

#949 JOB-58374 build: Add compile to circle ci
  .circleci/config.yml
  .gitignore
  package-lock.json
  package.json
  packages/components/package.json
  packages/components/rollup.config.js
  packages/components/tsconfig.ci.json
  packages/design/package.json
  packages/formatters/package.json
  packages/hooks/package.json
Labels: approved

#951 feat(components): Add configurable column width to DataTable
  packages/components/src/DataTable/Body.tsx
  packages/components/src/DataTable/DataTable.mdx
  packages/components/src/DataTable/DataTable.test.tsx
  packages/components/src/DataTable/Footer.tsx
  packages/components/src/DataTable/Header.tsx
  packages/components/src/DataTable/test-utilities/mocks.ts
Labels: approved, Team Atlantis, Team Finsights

#950 fix(component) only add tooltip arrow background colour after rotation
  packages/components/src/Tooltip/Tooltip.css
Labels: approved, Team Atlantis
