Repository GetJobber/atlantis, pull requests merged in 2022-11, with the labels that each got.

#929 docs: Fix broken link on /packages/hooks
  packages/hooks/README.mdx
Labels: approved, Team Atlantis

#922 docs(components): MultiSelect Component Proposal
  docs/proposals/MultiSelect/MultiSelect.md
  docs/proposals/MultiSelect/multi_select.png
Labels: approved

#932 feat(components): MultiSelect component
  packages/components/src/Checkbox/Checkbox.tsx
  packages/components/src/MultiSelect/DropDownMenu.css
  packages/components/src/MultiSelect/DropDownMenu.css.d.ts
  packages/components/src/MultiSelect/DropDownMenu.tsx
  packages/components/src/MultiSelect/MultiSelect.css
  packages/components/src/MultiSelect/MultiSelect.css.d.ts
  packages/components/src/MultiSelect/MultiSelect.mdx
  packages/components/src/MultiSelect/MultiSelect.test.tsx
  packages/components/src/MultiSelect/MultiSelect.tsx
  packages/components/src/MultiSelect/index.ts
  packages/components/src/MultiSelect/types.ts
  packages/components/src/MultiSelect/utils.ts
Labels: approved, design approved, Team Atlantis

#934 feat(components): Add footer row to Data Table component (JOB-57643)
  packages/components/src/DataTable/DataTable.css
  packages/components/src/DataTable/DataTable.mdx
  packages/components/src/DataTable/DataTable.test.tsx
  packages/components/src/DataTable/DataTable.tsx
  packages/components/src/DataTable/Footer.css
  packages/components/src/DataTable/Footer.css.d.ts
  packages/components/src/DataTable/Footer.tsx
  packages/components/src/DataTable/Pagination.css
  packages/components/src/DataTable/Pagination.css.d.ts
  packages/components/src/DataTable/Pagination.tsx
  packages/components/src/DataTable/test-utilities/mocks.ts
  packages/components/src/DataTable/types.ts
Labels: approved, design approved, Team Atlantis, Team Finsights

#937 fix(component) Adjust dropdown height in DataTable compoment
  packages/components/src/DataTable/DataTable.tsx
  packages/components/src/DataTable/Header.tsx
  packages/components/src/DataTable/Pagination.tsx
  packages/components/src/DataTable/createTableSettings.ts
  packages/components/src/DataTable/types.ts
Labels: approved, design in review, Team Atlantis
