Repository GetJobber/atlantis, pull requests merged in 2022-06, with the labels that each got.

#896 fix(deps): update markdown to v6.0.3
  package-lock.json
  packages/components/package-lock.json
  packages/components/package.json
  packages/components/src/Markdown/Markdown.tsx
  packages/components/src/Markdown/__snapshots__/Markdown.test.tsx.snap
Labels: approved, Team Atlantis

#895 feat(components): JOB-40406 Allow PUT requests in InputFile component
  packages/components/src/InputFile/InputFile.test.tsx
  packages/components/src/InputFile/InputFile.tsx
  packages/components/src/InputFile/__snapshots__/InputFile.test.tsx.snap
Labels: approved

#898 JOB-40406 Modify FormField Altantis Component For Thumbnail Functionality
  packages/components/src/FormatFile/FormatFile.css
  packages/components/src/FormatFile/FormatFile.css.d.ts
  packages/components/src/FormatFile/FormatFile.mdx
  packages/components/src/FormatFile/FormatFile.test.tsx
  packages/components/src/FormatFile/FormatFile.tsx
  packages/components/src/FormatFile/FormatFileDeleteButton.tsx
  packages/components/src/FormatFile/InternalThumbnail.css
  packages/components/src/FormatFile/InternalThumbnail.css.d.ts
  packages/components/src/FormatFile/InternalThumbnail.tsx
  packages/components/src/FormatFile/__snapshots__/FormatFile.test.tsx.snap
Labels: approved, design approved, Team Atlantis, Team Platooine

#891 feat(components): Atlantis Component For Gallery
  packages/components/src/Gallery/Gallery.css
  packages/components/src/Gallery/Gallery.css.d.ts
  packages/components/src/Gallery/Gallery.mdx
  packages/components/src/Gallery/Gallery.test.tsx
  packages/components/src/Gallery/Gallery.tsx
  packages/components/src/Gallery/GalleryTypes.ts
  packages/components/src/Gallery/index.ts
Labels: approved, design approved, Team Atlantis, Team Platooine

#901 docs(design): Formatting guidelines
  docs/content/formatting.mdx
Labels: approved
