Repository GetJobber/atlantis, pull requests merged in 2022-01, with the labels that each got.

#819 docs(components): flesh out RecurringSelect docs
  packages/components/src/RecurringSelect/RecurringSelect.mdx
Labels: approved

#822 docs(components): add signature to Icon examples
  packages/components/src/Icon/Icon.mdx
Labels: approved

#821 fix(components): reorganize RecurringSelect structure to avoid circular dependencies
  packages/components/src/RecurringSelect/components/DayOfMonthSelect.css
  packages/components/src/RecurringSelect/components/DayOfMonthSelect.css.d.ts
  packages/components/src/RecurringSelect/components/DayOfMonthSelect.test.tsx
  packages/components/src/RecurringSelect/components/DayOfMonthSelect.tsx
  packages/components/src/RecurringSelect/components/MonthlyDayOfWeekSelect.css
  packages/components/src/RecurringSelect/components/MonthlyDayOfWeekSelect.css.d.ts
  packages/components/src/RecurringSelect/components/MonthlyDayOfWeekSelect.test.tsx
  packages/components/src/RecurringSelect/components/MonthlyDayOfWeekSelect.tsx
  packages/components/src/RecurringSelect/components/MonthlySelect.css
  packages/components/src/RecurringSelect/components/MonthlySelect.css.d.ts
  packages/components/src/RecurringSelect/components/MonthlySelect.tsx
  packages/components/src/RecurringSelect/components/WeeklySelect.css
  packages/components/src/RecurringSelect/components/WeeklySelect.css.d.ts
  packages/components/src/RecurringSelect/components/WeeklySelect.tsx
  packages/components/src/RecurringSelect/components/index.tsx
Labels: approved, Team McWeb

#759 feat: Section headers for screen readers.
  packages/components/src/Banner/Banner.mdx
  packages/components/src/DatePicker/DatePicker.mdx
  packages/components/src/InputValidation/InputValidation.mdx
  packages/components/src/Menu/Menu.css
  packages/components/src/Menu/Menu.css.d.ts
  packages/components/src/Menu/Menu.tsx
  packages/components/src/Toast/Toast.mdx
Labels: approved, hacktoberfest, hacktoberfest-accepted, accessibility, design approved

#827 fix: Allow space bar key deselect on single select chip
  packages/components/src/Chips/InternalChipSingleSelect.tsx
  packages/components/src/Chips/tests/InternalChipSingleSelect.test.tsx
Labels: approved, design approved, Team McWeb

#837 build: Speed Up CI Config Steps
  .circleci/config.yml
Labels: approved, Team McWeb

#840 build: Remove extra persist, use ssh variables
  .circleci/config.yml
Labels: approved, Team McWeb

#843 build: Revert back ssh key to make release pass
  .circleci/config.yml
Labels: approved, Team McWeb

#839 feat(hooks): Create the hooks index dynamically
  package.json
  packages/hooks/src/index.ts
  packages/hooks/src/useResizeObserver/index.ts
  packages/hooks/src/useResizeObserver/useResizeObserver.mdx
  packages/hooks/src/useResizeObserver/useResizeObserver.ts
  scripts/createIndexFile.js
Labels: approved, Team McWeb

#838 build: @jobber/hooks use the src dir instead of dist
  packages/docz-tools/gatsby-node.js
Labels: approved, Team McWeb

#846 feat(components): add explicit "Heading" color to Card header
  packages/components/src/Card/Card.tsx
  packages/components/src/Card/tests/Card.test.tsx
Labels: approved, Team McFriends

#841 feat(components): Left-align wrapping button labels when Icon is present
  packages/components/src/Button/Button.css
Labels: approved, design approved, Team McFriends

#847 feat(components): Support dismissible type on Chips
  packages/components/package-lock.json
  packages/components/package.json
  packages/components/src/Chips/Chips.mdx
  packages/components/src/Chips/Chips.tsx
  packages/components/src/Chips/ChipsTypes.tsx
  packages/components/src/Chips/InternalChip.css
  packages/components/src/Chips/InternalChipDismissible/InternalChipDismissible.css
  packages/components/src/Chips/InternalChipDismissible/InternalChipDismissible.css.d.ts
  packages/components/src/Chips/InternalChipDismissible/InternalChipDismissible.tsx
  packages/components/src/Chips/InternalChipDismissible/InternalChipDismissibleInput.tsx
  packages/components/src/Chips/InternalChipDismissible/InternalChipDismissibleTypes.ts
  packages/components/src/Chips/InternalChipDismissible/__tests__/InternalChipDismissible.test.tsx
  packages/components/src/Chips/InternalChipDismissible/__tests__/InternalChipDismissibleInput.test.tsx
  packages/components/src/Chips/InternalChipDismissible/hooks/__tests__/useInternalChipDismissible.test.tsx
  packages/components/src/Chips/InternalChipDismissible/hooks/__tests__/useInternalChipDismissibleInput.test.tsx
  packages/components/src/Chips/InternalChipDismissible/hooks/index.ts
  packages/components/src/Chips/InternalChipDismissible/hooks/useInView.ts
  packages/components/src/Chips/InternalChipDismissible/hooks/useInternalChipDismissible.ts
  packages/components/src/Chips/InternalChipDismissible/hooks/useInternalChipDismissibleInput.tsx
  packages/components/src/Chips/InternalChipDismissible/hooks/useRepositionMenu.ts
  packages/components/src/Chips/InternalChipDismissible/hooks/useScrollToActive.tsx
  packages/components/src/Chips/InternalChipDismissible/index.ts
  packages/components/src/Chips/utils/mdxUtils.ts
Labels: approved, Team McWeb

#848 feat: Announce chip deletion and addition JOB-41252
  packages/components/src/Chips/InternalChipDismissible/InternalChipDismissible.tsx
  packages/components/src/Chips/InternalChipDismissible/hooks/__tests__/useInternalChipDismissible.test.tsx
  packages/components/src/Chips/InternalChipDismissible/hooks/useInternalChipDismissible.ts
  packages/components/src/Chips/InternalChipDismissible/hooks/useInternalChipDismissibleInput.tsx
  packages/hooks/src/index.ts
  packages/hooks/src/useLiveAnnounce/index.ts
  packages/hooks/src/useLiveAnnounce/useLiveAnnounce.mdx
  packages/hooks/src/useLiveAnnounce/useLiveAnnounce.test.tsx
  packages/hooks/src/useLiveAnnounce/useLiveAnnounce.tsx
Labels: approved, accessibility, design approved, Team McWeb
