Repository GetJobber/atlantis, pull requests merged in 2023-07, with the labels that each got.

#1349 refactor(components-native): Make useScreenInformation use headerHeight from Atlantis Context
  packages/components-native/src/Form/context/AtlantisFormContext.tsx
  packages/components-native/src/Form/context/types.ts
  packages/components-native/src/Form/hooks/useScreenInformation.ts
Labels: approved, Team Atlantis

#1352 fix(components-native): Install react-native-keyboard-aware-scroll-view as dependency
  package-lock.json
  packages/components-native/package.json
Labels: approved, Team Atlantis

#1363 docs(components): Update Content documentation
  docs/components/Content/Content.stories.mdx
  docs/components/Content/Mobile.stories.mdx
  docs/components/Content/Mobile.stories.tsx
  docs/components/Content/Web.stories.mdx
  docs/components/Content/Web.stories.tsx
Labels: approved, Team Atlantis

#1368 docs(components): Update Drawer stories
  docs/components/Drawer/Drawer.stories.mdx
  docs/components/Drawer/Web.stories.tsx
  docs/guides/frontend-style.stories.mdx
  packages/components/src/Drawer/Drawer.stories.mdx
Labels: approved, Team Atlantis

#1365 chore: Delete unused file
  null-markdown-loader.js
Labels: approved, Team Atlantis

#1361 refactor(components-native): Remove react-native-localize dependency
  package-lock.json
  packages/components-native/package.json
  packages/components-native/src/AtlantisContext/AtlantisContext.tsx
  packages/components-native/src/InputCurrency/InputCurrency.test.tsx
  packages/components-native/src/__mocks__/__mocks.ts
Labels: approved, Team Atlantis

#1367 docs(components): Update Divider stories
  docs/components/Divider/Divider.stories.mdx
  docs/components/Divider/Mobile.stories.mdx
  docs/components/Divider/Mobile.stories.tsx
  docs/components/Divider/Web.stories.mdx
  docs/components/Divider/Web.stories.tsx
Labels: approved, Team Atlantis

#1366 docs: Implement code sandbox
  .storybook/components/Playground/Playground.css
  .storybook/components/Playground/Playground.test.tsx
  .storybook/components/Playground/Playground.tsx
  .storybook/components/Playground/index.ts
  .storybook/manager.js
  .storybook/preview.tsx
  docs/components/Avatar/Web.stories.tsx
  docs/components/Card/Web.stories.tsx
  docs/components/FormatFile/Web.stories.tsx
  docs/components/Gallery/Web.stories.tsx
  docs/components/Icon/Web.stories.tsx
  docs/components/LightBox/Web.stories.tsx
  jest.web.config.js
  package-lock.json
  package.json
Labels: approved, Team Atlantis

#1358 docs(components): Add ThumbnailList Story
  .storybook/components/SBProvider/SBProvider.tsx
  docs/components/ThumbnailList/Mobile.stories.tsx
  docs/components/ThumbnailList/ThumbnailList.stories.mdx
Labels: approved, Team Atlantis

#1374 docs(components): update page docs
  docs/components/Page/Page.stories.mdx
  docs/components/Page/Web.stories.tsx
  packages/components/src/Page/Page.stories.mdx
  packages/design/src/Spacing.stories.mdx
Labels: approved, Team Atlantis

#1369 docs: add extra warning on code sandbox when it errors out
  .storybook/components/Playground/Playground.css
  .storybook/components/Playground/Playground.test.tsx
  .storybook/components/Playground/Playground.tsx
  .storybook/components/Playground/PlaygroundWarning.tsx
Labels: approved, Team Atlantis

#1375 docs: update action label stories
  docs/components/ActionLabel/ActionLabel.stories.mdx
  docs/components/ActionLabel/Mobile.stories.mdx
  docs/components/ActionLabel/Mobile.stories.tsx
Labels: approved, Team Atlantis

#1362 docs(components-native): Add FormatFile mobile stories
  docs/components/FormatFile/FormatFile.stories.mdx
  docs/components/FormatFile/Mobile.stories.tsx
Labels: approved, Team Atlantis

#1373 docs(components): Update Grid documentation
  docs/components/Flex/Flex.stories.mdx
  docs/components/Flex/Mobile.stories.tsx
  docs/components/Grid/Grid.stories.mdx
  docs/components/Grid/Web.stories.tsx
  packages/components/src/Grid/Grid.stories.mdx
Labels: approved, Team Atlantis

#1364 docs(components): Update Disclosure stories
  .storybook/main.js
  docs/components/Disclosure/Disclosure.stories.mdx
  docs/components/Disclosure/Mobile.stories.tsx
  docs/components/Disclosure/Web.stories.tsx
  package-lock.json
  package.json
  packages/components-native/babel.config.js
  packages/components/src/Disclosure/Disclosure.stories.mdx
Labels: approved, Team Atlantis

#1384 docs(components): Update InputPhoneNumber docs
  docs/components/InputPhoneNumber/InputPhoneNumber.stories.mdx
  docs/components/InputPhoneNumber/Web.stories.tsx
  packages/components/src/InputPhoneNumber/InputPhoneNumber.stories.mdx
Labels: approved, Team Atlantis

#1380 docs: add button group docs and mobile example
  .storybook/components/StoryDetails/StoryDetails.css
  .storybook/components/StoryDetails/StoryDetails.css.d.ts
  .storybook/components/StoryDetails/StoryDetails.tsx
  .storybook/components/StoryDetails/index.ts
  .storybook/preview.tsx
  docs/CONTRIBUTING.md
  docs/components/ButtonGroup/ButtonGroup.stories.mdx
  docs/components/ButtonGroup/Mobile.PrimaryAction.stories.tsx
  docs/components/ButtonGroup/Mobile.SecondaryAction.stories.tsx
  docs/components/ButtonGroup/Mobile.stories.tsx
Labels: review requested, approved, Team Atlantis

#1381 docs: add IconButton docs
  docs/components/IconButton/IconButton.stories.mdx
  docs/components/IconButton/Mobile.stories.tsx
Labels: approved, Team Atlantis

#1385 docs: Allow to PlayGround component to use third party dependencies
  .storybook/components/Playground/Playground.css
  .storybook/components/Playground/Playground.test.tsx
  .storybook/components/Playground/Playground.tsx
  .storybook/components/Playground/PlaygroundWarning.tsx
  .storybook/components/Playground/constants.ts
  .storybook/components/Playground/index.ts
  .storybook/components/Playground/types.ts
  docs/components/Button/Web.stories.tsx
Labels: approved, Team Atlantis

#1387 fix(design): add export tokens from foundation index
  packages/design/src/index.ts
Labels: approved, Team Atlantis

#1383 docs(components): Update InputEmail docs
  docs/InputEmail/InputEmail.stories.mdx
  docs/InputEmail/Web.stories.tsx
  docs/components/Content/Web.stories.tsx
  docs/components/Divider/Web.stories.tsx
  docs/components/Drawer/Web.stories.tsx
  packages/components/src/InputEmail/InputEmail.stories.mdx
Labels: approved, Team Atlantis

#1389 docs(components): Add InputCurrency Docs
  docs/components/InputCurrency/InputCurrency.stories.mdx
  docs/components/InputCurrency/Mobile.stories.tsx
Labels: approved, Team Atlantis

#1388 docs: add Google Analytics tracking
  .storybook/manager.js
  package-lock.json
  package.json
Labels: approved, Team Atlantis

#1393 docs: allow code tab with no preview for mobile and other improvements
  .storybook/components/Playground/Playground.css
  .storybook/components/Playground/Playground.test.tsx
  .storybook/components/Playground/Playground.tsx
  .storybook/components/Playground/utils.ts
  docs/components/ActionLabel/Mobile.stories.tsx
  docs/components/Button/Mobile.stories.tsx
  docs/components/ButtonGroup/Mobile.PrimaryAction.stories.tsx
  docs/components/ButtonGroup/Mobile.SecondaryAction.stories.tsx
  docs/components/ButtonGroup/Mobile.stories.tsx
  docs/components/IconButton/Mobile.stories.tsx
  docs/components/Text/Mobile.stories.mdx
  docs/components/Text/Web.stories.mdx
  packages/components/src/Typography/Typography.stories.mdx
Labels: approved, Team Atlantis

#1386 docs(components): Update InputGroup docs
  docs/components/InputGroup/InputGroup.stories.mdx
  docs/components/InputGroup/Web.stories.tsx
  packages/components/src/InputGroup/InputGroup.stories.mdx
Labels: approved, Team Atlantis

#1390 docs(components): Update InputPassword docs
  docs/components/InputPassword/InputPassword.stories.mdx
  docs/components/InputPassword/Mobile.stories.tsx
  docs/components/InputPassword/Web.stories.tsx
  packages/components-native/src/InputPassword/InputPassword.tsx
  packages/components/src/InputPassword/InputPassword.stories.mdx
Labels: approved, Team Atlantis

#1395 build: ping designers on icon addition
  .github/CODEOWNERS
Labels: approved, Team Atlantis

#1399 docs: use babel-ts instead of babel as parser
  .storybook/components/Playground/utils.ts
Labels: approved, Team Atlantis

#1403 build: Fix pre-release script
  .github/workflows/trigger-qa-build.yml
Labels: approved, Team Atlantis

#1391 docs(components): Update InputText docs
  docs/components/InputText/InputText.stories.mdx
  docs/components/InputText/Mobile.stories.tsx
  docs/components/InputText/Web.stories.tsx
  package-lock.json
  package.json
  packages/components/src/InputText/InputText.tsx
Labels: approved, Team Atlantis

#1397 chore(components): Deprecate Toast Actions
  packages/components/src/Toast/Toast.tsx
Labels: approved, Team Atlantis

#1404 docs(components): Update InputValidation docs
  docs/components/InputText/InputText.stories.mdx
  docs/components/InputValidation/InputValidation.stories.mdx
  docs/components/InputValidation/Web.stories.tsx
  packages/components/src/Banner/Banner.stories.mdx
  packages/components/src/InputNumber/InputNumber.stories.mdx
  packages/components/src/InputValidation/InputValidation.stories.mdx
  packages/components/src/Toast/Toast.stories.mdx
Labels: approved, Team Atlantis

#1401 docs: track code tab in GA
  .storybook/components/Playground/Playground.test.tsx
  .storybook/components/Playground/Playground.tsx
  .storybook/manager.js
Labels: approved, Team Atlantis

#1405 docs(components): Add InputFile examples and revise docs
  .storybook/components/Playground/constants.ts
  docs/components/InputFile/InputFile.stories.mdx
  docs/components/InputFile/Web.stories.tsx
  packages/components/src/InputFile/InputFile.stories.mdx
Labels: approved, Team Atlantis

#1410 docs(components): Fix Disclosure mobile example
  docs/components/Disclosure/Mobile.stories.tsx
Labels: approved, Team Atlantis

#1408 refactor(design): Make all links within a banner component the default text color
  packages/components/src/Banner/Banner.css
  packages/components/src/Banner/Banner.css.d.ts
Labels: approved, Team Atlantis

#1409 docs(components): Update InputTime docs
  docs/components/InputDate/InputDate.stories.mdx
  docs/components/InputTime/InputTime.stories.mdx
  docs/components/InputTime/Mobile.stories.tsx
  docs/components/InputTime/Web.stories.tsx
  package-lock.json
  package.json
  packages/components-native/package.json
  packages/components/src/DatePicker/DatePicker.stories.mdx
  packages/components/src/InputTime/InputTime.stories.mdx
Labels: approved, Team Atlantis

#1406 docs(components): Update docs for Form
  .storybook/components/Playground/Playground.tsx
  docs/components/Form/Form.stories.mdx
  docs/components/Form/Mobile.stories.tsx
  docs/components/Form/Web.stories.tsx
  packages/components/src/Form/Form.stories.mdx
  packages/components/src/Form/Form.tsx
Labels: approved, Team Atlantis

#1412 docs(components): Update docs for InputNumber in the new layout
  docs/components/InputNumber/InputNumber.stories.mdx
  docs/components/InputNumber/Mobile.stories.tsx
  docs/components/InputNumber/Web.stories.tsx
  packages/components/src/InputNumber/InputNumber.tsx
Labels: approved, Team Atlantis

#1411 docs(components): Update Tooltip docs
  docs/components/Tooltip/Tooltip.stories.mdx
  docs/components/Tooltip/Web.stories.tsx
  packages/components/src/Tooltip/Tooltip.stories.mdx
Labels: approved, Team Atlantis

#1407 docs(components): Update docs for RadioGroup
  docs/components/RadioGroup/RadioGroup.stories.mdx
  docs/components/RadioGroup/Web.stories.tsx
  packages/components/src/RadioGroup/RadioGroup.stories.mdx
Labels: approved, Team Atlantis

#1415 docs(components): Update ContentOverlay docs
  docs/components/ContentOverlay/ContentOverlay.stories.mdx
  docs/components/ContentOverlay/Mobile.stories.tsx
Labels: approved, Team Atlantis

#1419 docs(components): Update Table docs
  docs/components/Table/Table.stories.mdx
  docs/components/Table/Web.stories.tsx
  packages/components/src/Table/Table.stories.mdx
Labels: approved, Team Atlantis

#1417 docs(components): Update DataTable docs
  .storybook/components/Playground/Playground.tsx
  docs/components/DataTable/DataTable.stories.mdx
  docs/components/DataTable/Web.stories.tsx
  packages/components/src/DataTable/DataTable.stories.mdx
Labels: approved, Team Atlantis

#1421 docs(components): Update ConfirmationModal docs
  docs/components/Button/Button.stories.mdx
  docs/components/ConfirmationModal/ConfirmationModal.stories.mdx
  docs/components/ConfirmationModal/Web.stories.tsx
  packages/components/src/Banner/Banner.stories.mdx
  packages/components/src/ConfirmationModal/ConfirmationModal.stories.mdx
  packages/components/src/ConfirmationModal/ConfirmationModal.tsx
Labels: approved, Team Atlantis

#1422 docs(components): Update List docs
  docs/components/List/List.stories.mdx
  docs/components/List/Web.stories.tsx
  packages/components/src/List/List.stories.mdx
  packages/components/src/List/List.stories.tsx
  packages/components/src/List/List.tsx
  packages/components/src/List/index.ts
Labels: approved, Team Atlantis

#1427 docs(components): Cleanup links for docs pages
  docs/InputEmail/InputEmail.stories.mdx
  docs/components/Autocomplete/Autocomplete.stories.mdx
  docs/components/Button/Button.stories.mdx
  docs/components/Disclosure/Disclosure.stories.mdx
  docs/components/InputAvatar/InputAvatar.stories.mdx
  docs/components/InputPassword/InputPassword.stories.mdx
  docs/components/InputValidation/InputValidation.stories.mdx
  docs/getting-started-with-react/getting-started-with-react.stories.mdx
  docs/guides/create-basic-component.stories.mdx
  docs/guides/frontend-style.stories.mdx
  packages/components/src/Checkbox/Checkbox.stories.mdx
  packages/components/src/Chips/Chips.stories.mdx
  packages/components/src/DatePicker/DatePicker.stories.mdx
  packages/components/src/DescriptionList/DescriptionList.stories.mdx
  packages/components/src/Popover/Popover.stories.mdx
  packages/components/src/RecurringSelect/RecurringSelect.stories.mdx
  packages/components/src/Tabs/Tabs.stories.mdx
  packages/design/src/Radii.stories.mdx
  packages/design/src/Spacing.stories.mdx
Labels: approved, Team Atlantis

#1418 docs(components): Update DescriptionList docs
  docs/components/DescriptionList/DescriptionList.stories.mdx
  docs/components/DescriptionList/Web.stories.tsx
  packages/components/src/DescriptionList/DescriptionList.stories.mdx
Labels: approved, Team Atlantis

#1414 feat(design): Add the loadingCheck icon
  docs/components/Icon/Icon.stories.mdx
  packages/design/assets/icons/loadingCheck.svg
Labels: approved, Team Atlantis, Team Comms Experience

#1429 fix: include index.tsx on component packing
  packages/components/rollup.config.js
  scripts/entryPoints.ts
Labels: approved, Team Atlantis

#1413 docs(components): Update Popover docs
  docs/components/Popover/Popover.stories.mdx
  docs/components/Popover/Web.stories.tsx
  packages/components/src/Popover/Popover.stories.mdx
Labels: approved, Team Atlantis

#1420 docs(components): Adjust Modal docs
  .storybook/components/Playground/Playground.tsx
  docs/components/Drawer/Drawer.stories.mdx
  docs/components/Modal/Modal.stories.mdx
  docs/components/Modal/Web.stories.tsx
  docs/guides/frontend-style.stories.mdx
  packages/components/src/Modal/Modal.stories.mdx
  packages/design/src/Colors.stories.mdx
  packages/design/src/Spacing.stories.mdx
Labels: approved, Team Atlantis

#1425 docs(components): Update FeatureSwitch docs
  docs/components/FeatureSwitch/FeatureSwitch.stories.mdx
  docs/components/FeatureSwitch/Web.stories.tsx
  packages/components/src/FeatureSwitch/FeatureSwitch.stories.mdx
Labels: approved, Team Atlantis

#1428 docs(components): Update Checkbox docs
  docs/components/Checkbox/Checkbox.stories.mdx
  docs/components/Checkbox/Mobile.stories.tsx
  docs/components/Checkbox/Web.stories.tsx
  packages/components/src/Checkbox/Checkbox.stories.mdx
  packages/components/src/Chips/Chips.stories.mdx
Labels: approved, Team Atlantis

#1423 docs(components): Update Tabs docs
  docs/components/Tabs/Tabs.stories.mdx
  docs/components/Tabs/Web.stories.tsx
  packages/components/src/Tabs/Tabs.stories.mdx
Labels: approved, Team Atlantis

#1426 docs(components): Update MultiSelect docs
  docs/components/MultiSelect/MultiSelect.stories.mdx
  docs/components/MultiSelect/Web.stories.tsx
  packages/components/src/MultiSelect/MultiSelect.stories.mdx
Labels: approved, Team Atlantis

#1431 docs(components): Update DatePicker Docs
  docs/components/Datepicker/Datepicker.stories.mdx
  docs/components/Datepicker/Web.stories.tsx
  docs/components/InputDate/InputDate.stories.mdx
  packages/components/src/DatePicker/DatePicker.tsx
  packages/components/src/RecurringSelect/RecurringSelect.stories.mdx
Labels: approved, Team Atlantis

#1434 docs(components): Update Select docs
  docs/components/Autocomplete/Autocomplete.stories.mdx
  docs/components/Select/Mobile.stories.tsx
  docs/components/Select/Select.stories.mdx
  docs/components/Select/Web.stories.tsx
  docs/components/Tabs/Tabs.stories.mdx
  packages/components/src/Select/Select.stories.mdx
Labels: approved, Team Atlantis

#1436 docs(components): Update spinner docs
  docs/components/Spinner/Spinner.stories.mdx
  docs/components/Spinner/Web.stories.tsx
  docs/guides/frontend-style.stories.mdx
  packages/components/src/Spinner/Spinner.stories.mdx
Labels: approved, Team Atlantis

#1439 docs(components): Updated StatusLabel docs
  docs/components/StatusLabel/Mobile.stories.tsx
  docs/components/StatusLabel/StatusLabel.stories.mdx
  docs/components/StatusLabel/Web.stories.tsx
Labels: approved, Team Atlantis

#1438 docs(components): Update ActivityIndicator docs
  docs/components/ActivityIndicator/ActivityIndicator.stories.mdx
  docs/components/ActivityIndicator/Mobile.stories.mdx
  docs/components/ActivityIndicator/Mobile.stories.tsx
Labels: approved, Team Atlantis

#1437 docs(components): Update Switch documentation
  .storybook/__mocks__/react-native-gesture-handler.tsx
  docs/components/Switch/Mobile.stories.tsx
  docs/components/Switch/Switch.stories.mdx
  docs/components/Switch/Web.stories.tsx
  packages/components-native/src/Switch/Switch.tsx
  packages/components-native/src/Switch/index.ts
  packages/components/src/Switch/Switch.stories.mdx
Labels: approved, Team Atlantis

#1443 docs(components): Update links for ActivityIndicator and Spinner
  docs/components/ActivityIndicator/ActivityIndicator.stories.mdx
  docs/components/Spinner/Spinner.stories.mdx
Labels: approved, Team Atlantis

#1440 docs(components): Update InlineLabel docs
  docs/components/DataTable/DataTable.stories.mdx
  docs/components/DescriptionList/DescriptionList.stories.mdx
  docs/components/Icon/Icon.stories.mdx
  docs/components/InlineLabel/InlineLabel.stories.mdx
  docs/components/InlineLabel/Web.stories.tsx
  docs/components/StatusLabel/StatusLabel.stories.mdx
  docs/components/Table/Table.stories.mdx
  packages/components/src/Chips/Chips.stories.mdx
Labels: approved, Team Atlantis

#1441 docs(components): Update docs for EmptyState
  docs/components/EmptyState/EmptyState.stories.mdx
  docs/components/EmptyState/Mobile.stories.tsx
Labels: approved, Team Atlantis

#1432 docs(components): Update docs for Chips
  docs/components/Chips/Chips.stories.mdx
  docs/components/Chips/Mobile.stories.tsx
  docs/components/Chips/Web.stories.tsx
  docs/components/Chips/utils/mdxUtils.ts
Labels: approved, Team Atlantis

#1433 docs(components-native): Update BottomSheet docs
  docs/components/BottomSheet/BottomSheet.stories.mdx
  docs/components/BottomSheet/Mobile.stories.tsx
  packages/components-native/src/BottomSheet/BottomSheet.tsx
Labels: approved, Team Atlantis

#1444 docs(components): Update Emphasis docs
  docs/components/Emphasis/Emphasis.stories.mdx
  docs/components/Emphasis/Web.stories.tsx
  packages/design/src/Typography.stories.mdx
Labels: approved, Team Atlantis

#1447 docs(components-native): Added AutoLink docs
  docs/components/AutoLink/AutoLink.stories.mdx
  docs/components/AutoLink/Mobile.stories.tsx
Labels: approved, Team Atlantis

#1449 docs(components): Update Glimmer Docs
  docs/components/Glimmer/Glimmer.stories.mdx
  docs/components/Glimmer/Web.stories.tsx
  packages/components/src/Glimmer/Glimmer.stories.mdx
Labels: approved, Team Atlantis

#1446 docs(components): Update ProgressBar docs
  docs/components/ProgressBar/Mobile.stories.mdx
  docs/components/ProgressBar/Mobile.stories.tsx
  docs/components/ProgressBar/ProgressBar.stories.mdx
  docs/components/ProgressBar/Web.stories.mdx
  docs/components/ProgressBar/Web.stories.tsx
Labels: approved, Team Atlantis

#1435 docs(components): fix InputFile code examples
  docs/components/InputFile/Web.stories.tsx
Labels: approved, Team Atlantis

#1451 docs: Update Typography docs
  docs/components/Typography/Mobile.stories.tsx
  docs/components/Typography/Typography.stories.mdx
  docs/components/Typography/Web.stories.tsx
  packages/components/src/Typography/Typography.stories.mdx
Labels: approved, Team Atlantis

#1460 docs(components): Update FormatEmail docs
  docs/components/FormatEmail/FormatEmail.stories.mdx
  docs/components/FormatEmail/Web.stories.tsx
  packages/components/src/FormatEmail/FormatEmail.stories.mdx
Labels: approved, Team Atlantis

#1455 docs(components): Update AnimatedSwitcher docs
  docs/components/AnimatedSwitcher/AnimatedSwitcher.stories.mdx
  docs/components/AnimatedSwitcher/Web.stories.tsx
  packages/components/src/AnimatedSwitcher/AnimatedSwitcher.stories.mdx
Labels: approved, Team Atlantis

#1448 docs: Unify Banner docs
  docs/components/Banner/Banner.stories.mdx
  docs/components/Banner/Mobile.stories.tsx
  docs/components/Banner/Web.stories.tsx
  docs/components/Popover/Popover.stories.mdx
  docs/components/TextList/TextList.stories.mdx
  docs/components/Toast/Toast.stories.mdx
Labels: approved, Team Atlantis
