Repository GetJobber/atlantis, pull requests merged in 2023-01, with the labels that each got.

#953 feat(design): add syncAlert and apps icons
  packages/components/src/Icon/Icon.mdx
  packages/design/src/icons/iconMap.ts
Labels: approved, Team Atlantis, Team Platform Experience

#960 fix: Update ssh-key fingerprint for release
  .circleci/config.yml
Labels: approved, Team Atlantis

#963 fix: Update ssh-key fingerprint for release take 2
  .circleci/config.yml
Labels: approved, Team Atlantis

#890 feat(components): new highlighter for Emphasis
  packages/components/src/Emphasis/EmphasisBrushstroke.svg
  packages/components/src/Typography/css/Emphasis.css
Labels: approved, Team Atlantis

#964 fix: Update ssh-key fingerprint for release take 3
  .circleci/config.yml
Labels: approved

#954 feat(components): Add DataTable test helpers
  packages/components/src/DataTable/DataTable.test.tsx
  packages/components/src/DataTable/index.ts
  packages/components/src/DataTable/test-utilities/helpers.ts
  packages/components/src/DataTable/test-utilities/index.ts
Labels: approved, Team Atlantis, Team Finsights

#968 fix(components): Fix radio button shrinking when label is too long
  packages/components/src/RadioGroup/RadioGroup.css
Labels: approved, Team Atlantis

#970 refactor(components): update autocomplete false value in FormField
  packages/components/src/Autocomplete/__snapshots__/Autocomplete.test.tsx.snap
  packages/components/src/FormField/FormField.test.tsx
  packages/components/src/FormField/FormField.tsx
Labels: approved, Team Atlantis

#959 build(design): Export Atlantis CSS vars to SCSS
  packages/design/jobberStyle.js
Labels: approved, Team Atlantis

#976 refactor(design): Adjust base typography scale
  packages/components/src/Typography/css/Typography.css
Labels: approved, Team Atlantis

#972 feat(components): Implement the new sorting behavior / alignment to DataTable component in Atlantis [JOB-58028]
  packages/components/src/DataTable/DataTable.mdx
  packages/components/src/DataTable/DataTable.tsx
  packages/components/src/DataTable/Header.tsx
  packages/components/src/DataTable/SortIcon.css
  packages/components/src/DataTable/SortIcon.css.d.ts
  packages/components/src/DataTable/SortIcon.tsx
Labels: approved, Team Atlantis, Team Finsights

#973 feat(components): Add empty state behavior to DataTable component in Atlantis [JOB-58935]
  packages/components/src/DataTable/Body.tsx
  packages/components/src/DataTable/DataTable.css
  packages/components/src/DataTable/DataTable.css.d.ts
  packages/components/src/DataTable/DataTable.mdx
  packages/components/src/DataTable/DataTable.test.tsx
  packages/components/src/DataTable/DataTable.tsx
  packages/components/src/DataTable/Pagination.tsx
Labels: approved, design approved, Team Atlantis, Team Finsights

#975 Bumping `engine.io` sub dependency version to 3.6.1
  package-lock.json
Labels: dependencies, approved, Team Atlantis

#974 Bumping `loader-utils` to v1.4.2
  package-lock.json
Labels: dependencies, approved, Team Atlantis

#979 refactor: Move all Typography token variables to design package
  packages/components/src/Typography/css/Typography.css
  packages/design/src/typography.css
Labels: approved, Team Atlantis

#971 Bumping json5 dependency to 1.0.2 and 2.2.3 throughout Atlantis
  package-lock.json
  packages/docz-tools/package-lock.json
  packages/eslint-config/package-lock.json
Labels: dependencies, approved, Team Atlantis

#978 docs(design): Update Typography documentation to reflect new base font-size
  packages/components/src/Typography/.private
  packages/components/src/Typography/Typography.mdx
  packages/design/src/Typography.mdx
Labels: approved, Team Atlantis

#983 feat(components): Add sparkles icon to component library
  packages/components/src/Icon/Icon.mdx
  packages/design/src/icons/iconMap.ts
Labels: approved, Team Atlantis

#985 Typography updates feature branch master update
  .circleci/config.yml
  package-lock.json
  packages/components/CHANGELOG.md
  packages/components/package-lock.json
  packages/components/package.json
  packages/components/src/Autocomplete/__snapshots__/Autocomplete.test.tsx.snap
  packages/components/src/DataTable/Body.tsx
  packages/components/src/DataTable/DataTable.css
  packages/components/src/DataTable/DataTable.css.d.ts
  packages/components/src/DataTable/DataTable.mdx
  packages/components/src/DataTable/DataTable.test.tsx
  packages/components/src/DataTable/DataTable.tsx
  packages/components/src/DataTable/Header.tsx
  packages/components/src/DataTable/Pagination.tsx
  packages/components/src/DataTable/SortIcon.css
  packages/components/src/DataTable/SortIcon.css.d.ts
  packages/components/src/DataTable/SortIcon.tsx
  packages/components/src/DataTable/index.ts
  packages/components/src/DataTable/test-utilities/helpers.ts
  packages/components/src/DataTable/test-utilities/index.ts
  packages/components/src/Emphasis/EmphasisBrushstroke.svg
  packages/components/src/FormField/FormField.test.tsx
  packages/components/src/FormField/FormField.tsx
  packages/components/src/Icon/Icon.mdx
  packages/components/src/RadioGroup/RadioGroup.css
  packages/components/src/Tooltip/Tooltip.css
  packages/components/src/Typography/css/Emphasis.css
  packages/components/src/Typography/css/Typography.css
  packages/design/CHANGELOG.md
  packages/design/jobberStyle.js
  packages/design/package-lock.json
  packages/design/package.json
  packages/design/src/icons/iconMap.ts
  packages/design/src/typography.css
  packages/docz-tools/CHANGELOG.md
  packages/docz-tools/package-lock.json
  packages/docz-tools/package.json
  packages/eslint-config/package-lock.json
Labels: approved

#986 refactor(components): Update typography for Popover and ColorSwatches
  packages/components/src/Popover/Popover.css
  packages/docx/src/ColorSwatches/ColorSwatches.css
Labels: approved, Team Atlantis

#952 feat(design): BREAKING CHANGE: Implement new typefaces in Atlantis [JOB-46209]
  .circleci/config.yml
  .gitignore
  .npmrc.pages
  docs/README.md
  package-lock.json
  package.json
  packages/components/package-lock.json
  packages/components/src/Heading/Heading.test.tsx
  packages/components/src/Heading/Heading.tsx
  packages/components/src/LightBox/LightBox.css
  packages/components/src/Markdown/__snapshots__/Markdown.test.tsx.snap
  packages/components/src/Page/__snapshots__/Page.test.tsx.snap
  packages/design/buildFoundation.js
  packages/design/buildIconStyles.js
  packages/design/foundation_config/postcss-filter-rules/index.js
  packages/design/foundation_config/postcss.config.js
  packages/design/package-lock.json
  packages/design/package.json
  packages/design/rollup.config.js
  packages/design/src/Typography.mdx
  packages/design/src/foundation.css
  packages/design/src/styles.css
  packages/design/src/typography.css
  packages/design/tsconfig.json
  packages/docz-tools/src/gatsby-theme-docz/components/Navigation/Navigation.module.css
  packages/docz-tools/src/gatsby-theme-docz/theme/typography.ts
  packages/eslint-config/package-lock.json
  scripts/bootstrap.sh
  scripts/pre-install.sh
  scripts/pre-prerelease.sh
Labels: approved, Team Atlantis

#988 refactor(components): Update datepicker days of week to use `small` fontSize
  packages/components/src/DatePicker/DatePicker.css
Labels: approved, Team Atlantis

#990 refactor(design): Re-add typography scale
  packages/design/src/typography.css
Labels: approved, Team Atlantis

#993 refactor(components): Update FormField component typography
  packages/components/src/FormField/FormField.css
Labels: approved, Team Atlantis

#989 refactor(components): Adjust banner alignment
  packages/components/src/Banner/Banner.css
  packages/components/src/Banner/Banner.css.d.ts
  packages/components/src/Banner/Banner.tsx
  packages/components/src/Banner/__snapshots__/Banner.test.tsx.snap
Labels: approved, Team Atlantis

#992 refactor(components): Update typography for Button
  packages/components/src/Banner/__snapshots__/Banner.test.tsx.snap
  packages/components/src/Button/Button.css
  packages/components/src/Button/Button.mdx
  packages/components/src/Button/Button.tsx
  packages/components/src/Button/__snapshots__/Button.test.tsx.snap
  packages/components/src/ButtonDismiss/__snapshots__/ButtonDismiss.test.tsx.snap
  packages/components/src/ConfirmationModal/tests/__snapshots__/snapshot-ConfirmationModal.test.tsx.snap
  packages/components/src/FeatureSwitch/__snapshots__/FeatureSwitch.test.tsx.snap
  packages/components/src/InputAvatar/__snapshots__/InputAvatar.test.tsx.snap
  packages/components/src/InputFile/__snapshots__/InputFile.test.tsx.snap
  packages/components/src/Menu/__snapshots__/Menu.test.tsx.snap
  packages/components/src/Modal/__snapshots__/ModalSnapshots.test.tsx.snap
  packages/components/src/Page/__snapshots__/Page.test.tsx.snap
Labels: approved, Team Atlantis

#995 refactor(components): Update FormatFile filename size
  packages/components/src/FormatFile/FormatFile.tsx
  packages/components/src/FormatFile/__snapshots__/FormatFile.test.tsx.snap
Labels: approved, Team Atlantis

#994 refactor(components): Use typography tokens for InternalThumbnail [JOB-60820]
  packages/components/src/FormatFile/InternalThumbnail.css
Labels: approved

#996 fix(docs): Round the decimals on line height
  packages/design/src/Typography.mdx
Labels: approved, Team Atlantis

#997 refactor(components): Increase sidenav component list from small to base
  packages/docz-tools/src/gatsby-theme-docz/components/Navigation/Navigation.module.css
Labels: approved, Team Atlantis

#991 feat(components): Update drawer, modal and card headings
  packages/components/src/Card/Card.tsx
  packages/components/src/Card/tests/Card.test.tsx
  packages/components/src/ConfirmationModal/tests/__snapshots__/snapshot-ConfirmationModal.test.tsx.snap
  packages/components/src/Drawer/Drawer.css
  packages/components/src/Drawer/Drawer.tsx
  packages/components/src/Heading/Heading.test.tsx
  packages/components/src/Heading/Heading.tsx
  packages/components/src/Markdown/__snapshots__/Markdown.test.tsx.snap
  packages/components/src/Modal/Modal.tsx
  packages/components/src/Modal/__snapshots__/ModalSnapshots.test.tsx.snap
Labels: approved, Team Atlantis

#999 refactor(components): Update statuslabel indicator offset
  packages/components/src/StatusLabel/StatusLabel.css
Labels: approved

#1000 fix(components): Adjust placement of emphasis highlight [JOB-41951]
  packages/components/src/Typography/css/Emphasis.css
Labels: approved

#998 refactor(components): Update InlineLabel
  packages/components/src/InlineLabel/InlineLabel.css
  packages/components/src/InlineLabel/InlineLabel.mdx
  packages/components/src/InlineLabel/InlineLabel.test.tsx
  packages/components/src/InlineLabel/InlineLabel.tsx
Labels: approved, Team Atlantis

#1002 Docs: update voice and tone marketing link
  docs/content/voice-and-tone.mdx
Labels: approved

#1001 build: Fix lerna package json
  docs/README.md
  package.json
  packages/components/CHANGELOG.md
  packages/components/package-lock.json
  packages/components/package.json
  packages/design/CHANGELOG.md
  packages/design/package-lock.json
  packages/design/package.json
  packages/docx/CHANGELOG.md
  packages/docx/package-lock.json
  packages/docx/package.json
  packages/docz-tools/CHANGELOG.md
  packages/docz-tools/package-lock.json
  packages/docz-tools/package.json
  scripts/pre-prerelease.sh
Labels: approved, Team Atlantis

#969 feat(components): add modal size and child render support to confirmation modal
  packages/components/src/ConfirmationModal/ConfirmationModal.tsx
  packages/components/src/ConfirmationModal/tests/interaction-ConfirmationModal.test.tsx
Labels: proposal, approved, Team Atlantis

#1005 refactor(components): Fix vertical spacing of label within Switch component
  packages/components/src/Switch/Switch.css
Labels: approved, Team Atlantis

#1007 refactor(components): Remove letterSpacing-loose letter spacing from Buttons
  packages/components/src/Button/Button.css
Labels: approved, Team Atlantis

#1006 TECH-22: Typography fix files included in bundle
  packages/components/CHANGELOG.md
  packages/components/package-lock.json
  packages/components/package.json
  packages/design/CHANGELOG.md
  packages/design/npm-shrinkwrap.json
  packages/design/package.json
  packages/design/tsconfig.json
  packages/docx/CHANGELOG.md
  packages/docx/package-lock.json
  packages/docx/package.json
  packages/docz-tools/CHANGELOG.md
  packages/docz-tools/package-lock.json
  packages/docz-tools/package.json
  scripts/pre-prerelease.sh
Labels: approved, Team Atlantis

#1009 Job 61137 fix(components) Emphasis Svg not included in build
  packages/components/package-lock.json
  packages/components/package.json
  packages/components/rollup.config.js
Labels: approved, design approved, Team Atlantis

#1010 Cleanup: Update validation link for banner
  packages/components/src/Banner/Banner.mdx
Labels: approved

#1008 refactor(components): Fix vertical spacing for Checkbox
  packages/components/src/Checkbox/Checkbox.css
Labels: approved, design approved, Team Comms Experience

#1011 build(design): Export spacing tokens to SCSS
  packages/design/jobberStyle.js
Labels: approved, Team Atlantis

#1013 build(design): Export timing and elevation tokens
  packages/design/jobberStyle.js
Labels: approved, Team Atlantis

#1012 build(design): Export border and radius tokens to SCSS
  packages/design/jobberStyle.js
Labels: approved, Team Atlantis

#1016 build(design): Export Typography tokens
  packages/design/jobberStyle.js
Labels: approved, Team Atlantis
