Repository GetJobber/atlantis, pull requests merged in 2023-09, with the labels that each got.

#1512 feat(components): implement ability to add a data list filters
  docs/components/DataList/Web.stories.tsx
  package-lock.json
  packages/components/src/DataList/DataList.css
  packages/components/src/DataList/DataList.css.d.ts
  packages/components/src/DataList/DataList.tsx
  packages/components/src/DataList/components/DataListFilters/DataListFilter.const.ts
  packages/components/src/DataList/components/DataListFilters/DataListFilters.css
  packages/components/src/DataList/components/DataListFilters/DataListFilters.css.d.ts
  packages/components/src/DataList/components/DataListFilters/DataListFilters.test.tsx
  packages/components/src/DataList/components/DataListFilters/DataListFilters.tsx
  packages/components/src/DataList/components/DataListFilters/index.ts
  packages/components/src/DataList/components/DataListLayoutInternal/DataListHeader.tsx
  packages/components/src/DataList/context/DataListContext/DataListContext.tsx
  packages/components/src/DataList/context/DataListContext/index.ts
  packages/hooks/package.json
  packages/hooks/src/useInView/index.ts
  packages/hooks/src/useInView/useInView.test.tsx
  packages/hooks/src/useInView/useInView.ts
Labels: approved, design review requested, Team Atlantis

#1510 feat(components): Combobox Folder Reorg & Validation
  packages/components/src/Combobox/Combobox.test.tsx
  packages/components/src/Combobox/Combobox.tsx
  packages/components/src/Combobox/Combobox.types.ts
  packages/components/src/Combobox/ComboboxProvider.tsx
  packages/components/src/Combobox/components/Action/Action.css
  packages/components/src/Combobox/components/Action/Action.css.d.ts
  packages/components/src/Combobox/components/Action/Action.tsx
  packages/components/src/Combobox/components/Action/index.ts
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.css
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.css.d.ts
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.tsx
  packages/components/src/Combobox/components/ComboboxContent/index.ts
  packages/components/src/Combobox/components/Trigger/TriggerButton.tsx
  packages/components/src/Combobox/components/Trigger/TriggerChip.css
  packages/components/src/Combobox/components/Trigger/TriggerChip.css.d.ts
  packages/components/src/Combobox/components/Trigger/TriggerChip.tsx
  packages/components/src/Combobox/components/Trigger/index.ts
  packages/components/src/Combobox/index.ts
Labels: approved, Team Atlantis

#1517 fix(components): add border on DataList header when scrolling without column headers
  packages/components/src/DataList/DataList.tsx
  packages/components/src/DataList/components/DataListStickyHeader/DataListStickyHeader.css
  packages/components/src/DataList/components/DataListStickyHeader/DataListStickyHeader.css.d.ts
  packages/components/src/DataList/components/DataListStickyHeader/DataListStickyHeader.test.tsx
  packages/components/src/DataList/components/DataListStickyHeader/DataListStickyHeader.tsx
  packages/components/src/DataList/components/DataListStickyHeader/index.ts
Labels: review requested, Team Atlantis

#1515 docs(hooks): create useInView documentation
  packages/hooks/src/useInView/useInView.stories.mdx
Labels: review requested, Team Atlantis

#1518 feat(components): ComboboxContent
  docs/components/Combobox/Web.stories.tsx
  packages/components/src/Combobox/Combobox.css
  packages/components/src/Combobox/Combobox.css.d.ts
  packages/components/src/Combobox/Combobox.test.tsx
  packages/components/src/Combobox/Combobox.types.ts
  packages/components/src/Combobox/ComboboxProvider.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.css
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.css.d.ts
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.tsx
Labels: approved, Team Atlantis

#1526 feat(components): Combobox Search
  packages/components/src/Combobox/Combobox.test.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.css
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.css.d.ts
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.tsx
Labels: approved, Team Atlantis

#1524 fix(components): adjust no result state of data list
  docs/components/DataList/Web.stories.tsx
  packages/components/src/DataList/DataList.const.ts
  packages/components/src/DataList/DataList.css
  packages/components/src/DataList/DataList.test.tsx
  packages/components/src/DataList/DataList.tsx
  packages/components/src/DataList/DataList.types.ts
  packages/components/src/DataList/DataList.utils.tsx
  packages/components/src/DataList/components/DataListEmptyState/DataListEmptyState.css
  packages/components/src/DataList/components/DataListEmptyState/DataListEmptyState.css.d.ts
  packages/components/src/DataList/components/DataListEmptyState/DataListEmptyState.test.tsx
  packages/components/src/DataList/components/DataListEmptyState/DataListEmptyState.tsx
  packages/components/src/DataList/components/DataListEmptyState/index.ts
  packages/components/src/DataList/components/DataListStickyHeader/index.ts
  packages/components/src/DataList/components/EmptyState/EmptyState.test.tsx
  packages/components/src/DataList/components/EmptyState/EmptyState.tsx
  packages/components/src/DataList/components/EmptyState/index.ts
Labels: approved, Team Atlantis

#1527 feat(components): add 'back to top' on DataList
  packages/components/src/DataList/DataList.css
  packages/components/src/DataList/DataList.css.d.ts
  packages/components/src/DataList/DataList.test.tsx
  packages/components/src/DataList/DataList.tsx
  packages/components/src/DataList/components/DataListLoadMore/DataListLoadMore.css
  packages/components/src/DataList/components/DataListLoadMore/DataListLoadMore.css.d.ts
  packages/components/src/DataList/components/DataListLoadMore/DataListLoadMore.test.tsx
  packages/components/src/DataList/components/DataListLoadMore/DataListLoadMore.tsx
  packages/components/src/DataList/components/DataListLoadMore/DataListLoadMoreTrigger.tsx
Labels: approved, Team Atlantis

#1529 feat(components): JOB-78452 Select DataList row
  docs/components/DataList/Web.stories.tsx
  packages/components/src/DataList/DataList.css
  packages/components/src/DataList/DataList.css.d.ts
  packages/components/src/DataList/DataList.test.tsx
  packages/components/src/DataList/DataList.tsx
  packages/components/src/DataList/DataList.types.ts
  packages/components/src/DataList/components/DataListLayoutInternal/DataListItemInternal.tsx
  packages/components/src/DataList/components/DataListLayoutInternal/DataListItems.test.tsx
  packages/components/src/DataList/components/DataListLayoutInternal/DataListItems.tsx
  packages/components/src/DataList/context/DataListContext/DataListContext.tsx
  packages/hooks/src/index.ts
Labels: approved, Team Atlantis

#1521 feat(components): Ability to set selected option for combobox
  docs/components/Combobox/Web.stories.tsx
  packages/components/src/Combobox/Combobox.test.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.tsx
Labels: approved, Team Atlantis

#1528 feat(components): Combobox zero index state
  docs/components/Combobox/Web.stories.tsx
  packages/components/src/Combobox/Combobox.test.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.css
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.tsx
Labels: approved, Team Atlantis

#1538 feat(components): Allow actions to be added on a single DataList item
  docs/components/DataList/Web.stories.tsx
  packages/components/src/DataList/DataList.const.ts
  packages/components/src/DataList/DataList.css
  packages/components/src/DataList/DataList.tsx
  packages/components/src/DataList/DataList.types.ts
  packages/components/src/DataList/components/DataListAction/DataListAction.css
  packages/components/src/DataList/components/DataListAction/DataListAction.css.d.ts
  packages/components/src/DataList/components/DataListAction/DataListAction.tsx
  packages/components/src/DataList/components/DataListAction/index.ts
  packages/components/src/DataList/components/DataListActionsMenu/DataListActionsMenu.css
  packages/components/src/DataList/components/DataListActionsMenu/DataListActionsMenu.css.d.ts
  packages/components/src/DataList/components/DataListActionsMenu/DataListActionsMenu.tsx
  packages/components/src/DataList/components/DataListActionsMenu/index.ts
  packages/components/src/DataList/components/DataListItemActions/DataListItemActions.css
  packages/components/src/DataList/components/DataListItemActions/DataListItemActions.css.d.ts
  packages/components/src/DataList/components/DataListItemActions/DataListItemActions.tsx
  packages/components/src/DataList/components/DataListItemActions/DataListItemActionsOverflow.tsx
  packages/components/src/DataList/components/DataListItemActions/index.ts
  packages/components/src/DataList/components/DataListLayoutInternal/DataListItems.tsx
Labels: approved, design approved, Team Atlantis

#1533 feat(components): Add sorting to DataList
  docs/components/DataList/Web.stories.tsx
  packages/components/src/DataList/DataList.css
  packages/components/src/DataList/DataList.css.d.ts
  packages/components/src/DataList/DataList.test.tsx
  packages/components/src/DataList/DataList.tsx
  packages/components/src/DataList/DataList.types.ts
  packages/components/src/DataList/DataList.utils.tsx
  packages/components/src/DataList/__tests__/DataList.utils.test.tsx
  packages/components/src/DataList/components/DataListHeaderTile/DataListHeaderTile.css
  packages/components/src/DataList/components/DataListHeaderTile/DataListHeaderTile.css.d.ts
  packages/components/src/DataList/components/DataListHeaderTile/DataListHeaderTile.tsx
  packages/components/src/DataList/components/DataListHeaderTile/SortingArrows.css
  packages/components/src/DataList/components/DataListHeaderTile/SortingArrows.css.d.ts
  packages/components/src/DataList/components/DataListHeaderTile/SortingArrows.tsx
  packages/components/src/DataList/components/DataListHeaderTile/index.ts
  packages/components/src/DataList/index.ts
  packages/design/src/icons/Colors.css
  packages/design/src/icons/Colors.css.d.ts
Labels: approved, design review requested, design in review, Team Atlantis

#1537 refactor(components): Add ComboboxContent Tests
  packages/components/src/Combobox/Combobox.test.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.test.tsx
Labels: approved, Team Atlantis

#1536 feat(components): Add optional role to Button
  packages/components/src/Button/Button.test.tsx
  packages/components/src/Button/Button.tsx
Labels: approved, Team Atlantis

#1540 feat(components): Refactor options as li elements
  packages/components/src/Combobox/Combobox.test.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.css
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.css.d.ts
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.tsx
Labels: approved, Team Atlantis

#1541 feat(components): move sorting to a button when the header disappears
  jest.web.config.js
  packages/components/src/DataList/DataList.test.tsx
  packages/components/src/DataList/DataList.types.ts
  packages/components/src/DataList/components/DataListFilters/DataListFilters.test.tsx
  packages/components/src/DataList/components/DataListFilters/DataListFilters.tsx
  packages/components/src/DataList/components/DataListFilters/components/DataListSort/DataListSort.test.tsx
  packages/components/src/DataList/components/DataListFilters/components/DataListSort/DataListSort.tsx
  packages/components/src/DataList/components/DataListFilters/components/DataListSort/index.ts
  packages/components/src/DataList/components/DataListHeaderTile/DataListHeaderTile.tsx
  packages/components/src/DataList/components/DataListLayoutInternal/DataListHeader.tsx
  packages/components/src/DataList/components/DataListSearch/DataListSearch.css
  packages/components/src/DataList/components/DataListSearch/DataListSearch.tsx
  packages/components/src/DataList/hooks/useMediaQuery.ts
  packages/components/src/DataList/hooks/useResponsiveSizing.ts
  packages/components/src/DataList/hooks/useShowHeader.ts
  packages/components/tsconfig.json
Labels: approved, Team Atlantis

#1542 feat(components): add context menu on data list
  packages/components/src/DataList/DataList.css
  packages/components/src/DataList/DataList.css.d.ts
  packages/components/src/DataList/components/DataListActionsMenu/DataListActionsMenu.tsx
  packages/components/src/DataList/components/DataListItemActions/DataListItemActions.tsx
  packages/components/src/DataList/components/DataListLayoutInternal/DataListItems.tsx
  packages/components/src/DataList/components/DataListLayoutInternal/__tests__/DataListItems.test.tsx
  packages/components/src/DataList/components/DataListTags/DataListTags.css
Labels: approved, design approved, Team Atlantis

#1543 feat(components): Ability to externally clear combobox selection
  docs/components/Combobox/Web.stories.tsx
  packages/components/src/Combobox/Combobox.test.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.test.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.tsx
  packages/components/src/Combobox/index.ts
Labels: approved, Team Atlantis

#1544 feat(components): DataList Layout pluggable actions
  docs/components/DataList/Web.stories.tsx
  packages/components/src/DataList/DataList.tsx
  packages/components/src/DataList/DataList.types.ts
  packages/components/src/DataList/components/DataListAction/DataListAction.css
  packages/components/src/DataList/components/DataListActionsMenu/DataListActionsMenu.tsx
  packages/components/src/DataList/components/DataListItemActions/DataListItemActionsOverflow.tsx
  packages/components/src/DataList/components/DataListLayoutActions/DataListLayoutActions.css
  packages/components/src/DataList/components/DataListLayoutActions/DataListLayoutActions.css.d.ts
  packages/components/src/DataList/components/DataListLayoutActions/DataListLayoutActions.test.tsx
  packages/components/src/DataList/components/DataListLayoutActions/DataListLayoutActions.tsx
  packages/components/src/DataList/components/DataListLayoutActions/index.ts
  packages/components/src/DataList/components/DataListLayoutInternal/DataListItems.tsx
  packages/components/src/DataList/context/DataListContext/DataListContext.tsx
  packages/components/src/DataList/context/DataListLayoutContext/DataListLayoutContext.tsx
  packages/components/src/DataList/context/DataListLayoutContext/index.ts
Labels: design approved, Team Atlantis

#1532 feat(components): Combobox Accessibility
  packages/components/src/Combobox/Combobox.test.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.css
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.test.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.tsx
  packages/components/src/Combobox/components/ComboboxTrigger/ComboboxTriggerButton/ComboboxTriggerButton.test.tsx
  packages/components/src/Combobox/components/ComboboxTrigger/ComboboxTriggerButton/ComboboxTriggerButton.tsx
  packages/components/src/Combobox/components/ComboboxTrigger/ComboboxTriggerChip/ComboboxTriggerChip.test.tsx
  packages/components/src/Combobox/components/ComboboxTrigger/ComboboxTriggerChip/ComboboxTriggerChip.tsx
Labels: approved, accessibility, design approved, Team Atlantis

#1547 fix(components): Improve performance on the list item creation
  packages/components/src/DataList/DataList.types.ts
  packages/components/src/DataList/DataList.utils.tsx
  packages/components/src/DataList/__tests__/DataList.utils.test.tsx
  packages/components/src/DataList/components/DataListItem/DataListItem.tsx
  packages/components/src/DataList/components/DataListItem/DataListItemInternal.tsx
  packages/components/src/DataList/components/DataListItem/index.ts
  packages/components/src/DataList/components/DataListItemActions/index.ts
  packages/components/src/DataList/components/DataListLayoutActions/DataListLayoutActions.tsx
  packages/components/src/DataList/components/DataListLayoutActions/DataListLayoutContext/DataListLayoutContext.tsx
  packages/components/src/DataList/components/DataListLayoutActions/DataListLayoutContext/index.ts
  packages/components/src/DataList/components/DataListLayoutInternal/DataListItems.tsx
  packages/components/src/DataList/context/DataListLayoutContext/DataListLayoutContext.tsx
Labels: approved, Team Atlantis

#1534 docs(components): Add Combobox docs - Alpha
  .storybook/components/SidebarLabel/alphaComponents.ts
  docs/components/Combobox/Combobox.stories.mdx
  docs/components/Combobox/Web.stories.tsx
Labels: approved, Team Atlantis

#1548 feat(components): DataList row click and tabbing a11y
  docs/components/DataList/Web.stories.tsx
  packages/components/src/DataList/DataList.css
  packages/components/src/DataList/DataList.css.d.ts
  packages/components/src/DataList/DataList.types.ts
  packages/components/src/DataList/components/DataListActionsMenu/DataListActionsMenu.css
  packages/components/src/DataList/components/DataListActionsMenu/DataListActionsMenu.tsx
  packages/components/src/DataList/components/DataListItem/DataListItem.tsx
  packages/components/src/DataList/components/DataListItem/DataListItemInternal.tsx
  packages/components/src/DataList/components/DataListItem/components/DataListItemClickable/DataListItemClickable.test.tsx
  packages/components/src/DataList/components/DataListItem/components/DataListItemClickable/DataListItemClickable.tsx
  packages/components/src/DataList/components/DataListItem/components/DataListItemClickable/DataListItemClickableInternal.tsx
  packages/components/src/DataList/components/DataListItem/components/DataListItemClickable/index.ts
  packages/components/src/DataList/components/DataListLayoutActions/DataListLayoutContext/DataListLayoutContext.tsx
  packages/hooks/src/useFocusTrap/useFocusTrap.ts
Labels: approved, design approved, Team Atlantis

#1551 fix(components): Expose Link component props
  packages/components/src/Link/Link.tsx
  packages/components/src/Link/index.ts
Labels: approved, Team Atlantis

#1530 feat(components): Refine styling on Combobox
  packages/components/src/Combobox/components/ComboboxAction/ComboboxAction.css
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.css
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.css.d.ts
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.test.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.tsx
  packages/components/src/Combobox/components/ComboboxTrigger/ComboboxTriggerChip/ComboboxTriggerChip.css
Labels: approved, design approved, Team Atlantis

#1550 feat(components): Refactor/Clean Up Combobox Content
  packages/components/src/Combobox/Combobox.test.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.css
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.css.d.ts
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxList.css
  packages/components/src/Combobox/components/ComboboxContent/ComboboxList.css.d.ts
  packages/components/src/Combobox/components/ComboboxContent/ComboboxList.test.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxList.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxSearch.css
  packages/components/src/Combobox/components/ComboboxContent/ComboboxSearch.css.d.ts
  packages/components/src/Combobox/components/ComboboxContent/ComboboxSearch.test.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxSearch.tsx
  packages/components/src/Combobox/hooks/useComboboxAccessibility.ts
  packages/components/src/Combobox/hooks/useComboboxContent.ts
Labels: approved, Team Atlantis

#1553 docs(components): global banner layout position update on mobile [JOB-79966]
  docs/components/Banner/Banner.stories.mdx
Labels: approved, Team Atlantis
