Repository GetJobber/atlantis, pull requests merged in 2023-04, with the labels that each got.

#1172 chore: Allow optional deps in CircleCI build
  .circleci/config.yml
  package.json
Labels: approved, Team Atlantis

#1167 docs: Update package installation information in README
  docs/README.md
Labels: approved, Team Atlantis

#1175 fix: Use chip label instead of value on aria-label [JOB-66426]
  packages/components/src/Chips/InternalChipDismissible/InternalChipDismissible.tsx
Labels: approved, Team Atlantis

#1173 build(design): Bump postcss in design package
  package-lock.json
  packages/design/buildColors.js
  packages/design/buildFoundation.js
  packages/design/buildIconStyles.js
  packages/design/jobberStyle.js
  packages/design/package.json
Labels: approved, Team Atlantis

#1179 feat(components): Skeleton loader for image thumbnails
  packages/components/src/FormatFile/FormatFile.test.tsx
  packages/components/src/FormatFile/InternalThumbnail.css
  packages/components/src/FormatFile/InternalThumbnail.css.d.ts
  packages/components/src/FormatFile/InternalThumbnail.tsx
  packages/components/src/FormatFile/InternalThumbnailImage.css
  packages/components/src/FormatFile/InternalThumbnailImage.css.d.ts
  packages/components/src/FormatFile/InternalThumbnailImage.tsx
Labels: approved, Team Atlantis

#1176 fix(components): fix datepicker validations
  packages/components/src/FormField/FormField.tsx
  packages/components/src/InputDate/InputDate.stories.mdx
  packages/components/src/InputDate/InputDate.tsx
Labels: approved, Team Atlantis

#1185 feat(components): Add Drag Icon
  packages/components/src/Icon/Icon.stories.mdx
  packages/design/src/icons/iconMap.ts
Labels: approved, Team Atlantis, Team Workday

#1184 build: Update scripts to support uploading a new icon
  package-lock.json
  package.json
Labels: review requested, Team Atlantis

#1183 feat: Make a generic glimmer component
  packages/components/src/FormatFile/FormatFile.test.tsx
  packages/components/src/FormatFile/InternalThumbnailImage.css
  packages/components/src/FormatFile/InternalThumbnailImage.css.d.ts
  packages/components/src/FormatFile/InternalThumbnailImage.tsx
  packages/components/src/Glimmer/Glimmer.css
  packages/components/src/Glimmer/Glimmer.css.d.ts
  packages/components/src/Glimmer/Glimmer.stories.mdx
  packages/components/src/Glimmer/Glimmer.test.tsx
  packages/components/src/Glimmer/Glimmer.tsx
  packages/components/src/Glimmer/index.ts
  packages/components/src/Glimmer/style/Shape.css
  packages/components/src/Glimmer/style/Shape.css.d.ts
  packages/components/src/Glimmer/style/Sizes.css
  packages/components/src/Glimmer/style/Sizes.css.d.ts
  packages/components/src/Glimmer/style/Timing.css
  packages/components/src/Glimmer/style/Timing.css.d.ts
Labels: approved, Team Atlantis

#1189 docs: Fix CircleCi badge
  docs/README.md
Labels: approved, Team Atlantis

#1180 feat: Added Pre Release Action
  .github/workflows/trigger-qa-build.yml
  docs/README.md
  package.json
  scripts/commentOnPrAfterPreRelease.js
Labels: approved, Team Atlantis

#1195 feat(design): Add opacity tokens to Atlantis web
  packages/design/jobberStyle.js
  packages/design/src/foundation.css
  packages/design/src/opacity.css
Labels: approved, Team Atlantis

#1199 feat(components): Add the column button icon to atlantis [JOB-63504]
  packages/components/src/Icon/Icon.stories.mdx
  packages/design/src/icons/iconMap.ts
Labels: approved, Team Finsights

#1193 build(hooks): @jobber/hooks export entry files
  .eslintrc.js
  .storybook/main.js
  jest.config.js
  package-lock.json
  packages/components/package.json
  packages/components/rollup.config.js
  packages/components/src/Banner/Banner.tsx
  packages/components/src/Chips/Chip.tsx
  packages/components/src/Chips/InternalChipAffix.tsx
  packages/components/src/Chips/InternalChipDismissible/hooks/useInternalChipDismissible.ts
  packages/components/src/Chips/InternalChipDismissible/hooks/useInternalChipDismissibleInput.tsx
  packages/components/src/ConfirmationModal/ConfirmationModal.tsx
  packages/components/src/DataTable/DataTable.test.tsx
  packages/components/src/DataTable/DataTable.tsx
  packages/components/src/DataTable/test-utilities/helpers.ts
  packages/components/src/DatePicker/DatePicker.tsx
  packages/components/src/Disclosure/Disclosure.tsx
  packages/components/src/Form/Form.stories.mdx
  packages/components/src/Form/Form.test.tsx
  packages/components/src/LightBox/LightBox.tsx
  packages/components/src/Menu/Menu.tsx
  packages/components/src/Modal/Modal.tsx
  packages/components/src/MultiSelect/DropDownMenu.tsx
  packages/components/src/MultiSelect/MultiSelect.tsx
  packages/components/src/Page/Page.tsx
  packages/components/src/Popover/Popover.tsx
  packages/components/tsconfig.json
  packages/hooks/package.json
  packages/hooks/src/useAssert/useAssert.stories.mdx
  packages/hooks/src/useCollectionQuery/useCollectionQuery.stories.mdx
  packages/hooks/src/useFocusTrap/useFocusTrap.stories.mdx
  packages/hooks/src/useFormState/useFormState.stories.mdx
  packages/hooks/src/useIsMounted/useIsMounted.stories.mdx
  packages/hooks/src/useLiveAnnounce/useLiveAnnounce.stories.mdx
  packages/hooks/src/useOnKeyDown/useOnKeyDown.stories.mdx
  packages/hooks/src/usePasswordStrength/usePasswordStrength.stories.mdx
  packages/hooks/src/useRefocusOnActivator/useRefocusOnActivator.stories.mdx
  packages/hooks/src/useResizeObserver/useResizeObserver.stories.mdx
  scripts/entryPoints.ts
Labels: approved, Team Atlantis

#1203 fix(components): Autocomplete Menu Test Bug
  packages/components/src/Autocomplete/Menu.tsx
Labels: approved, Team Atlantis

#1202 chore: Remove upload_to_cloudfare step
  .circleci/config.yml
Labels: approved, Team Atlantis

#1208 feat(components): Add the Online Booking icon to Atlantis [JOB-59894]
  packages/components/src/Icon/Icon.stories.mdx
  packages/design/src/icons/iconMap.ts
Labels: approved, design review requested, Team Atlantis, Team Quotemeal

#1212 chore: Update VSCode settings to use node_modules TS version
  .vscode/settings.json
Labels: approved, Team Atlantis

#1214 feat(design): Move mobile fontSizes into design
  packages/design/jobberStyle.js
  packages/design/src/getMobileFontSizes.js
Labels: approved, Team Atlantis

#1215 fix(components): calculate Z index for autocomplete
  packages/components/src/Autocomplete/Autocomplete.css
Labels: approved, Team Atlantis

#1206 feat(design): Export mobile foundations files
  packages/design/README.mdx
  packages/design/jobberStyle.js
  packages/design/package.json
  packages/design/scripts/addFoundationExceptions.sh
  packages/design/scripts/removeFoundationTempFiles.sh
  packages/design/src/getMobileShadows.js
Labels: approved, Team Atlantis

#1219 refactor(design): Change archive icon to standard greyBlue
  packages/design/src/icons/Icon.css
  packages/design/src/icons/Icon.css.d.ts
  packages/design/src/icons/getIcon.ts
Labels: approved, Team Atlantis
