Repository GetJobber/atlantis, pull requests merged in 2023-03, with the labels that each got.

#1087 feat(components): update validation + description patterns for text inputs
  packages/components/src/FormField/FormFieldDescription.tsx
  packages/components/src/InputText/InputText.stories.mdx
  packages/components/src/InputValidation/InputValidation.test.tsx
  packages/components/src/InputValidation/InputValidation.tsx
Labels: approved, accessibility, design approved, Team Atlantis

#1096 docs: Update prerelease instructions
  docs/README.md
  package.json
Labels: approved, Team Atlantis

#1089 chore(components): Upgrade react router dom
  package-lock.json
  package.json
  packages/components/package-lock.json
  packages/components/package.json
Labels: dependencies, approved, Team Atlantis, Team Frontend Foundations

#1093 chore: properly write waitFor tests
  packages/components/src/Countdown/Countdown.test.tsx
  packages/components/src/Toast/Toast.test.tsx
Labels: approved, Team Atlantis

#1101 chore(components): Revert - Upgrade react router dom
  package-lock.json
  package.json
  packages/components/package-lock.json
  packages/components/package.json
Labels: approved, Team Atlantis, Team Frontend Foundations

#1100 feat(hooks): Add useFocusTrap hook
  packages/components/src/Modal/Modal.tsx
  packages/hooks/package-lock.json
  packages/hooks/package.json
  packages/hooks/src/index.ts
  packages/hooks/src/useFocusTrap/index.ts
  packages/hooks/src/useFocusTrap/useFocusTrap.stories.mdx
  packages/hooks/src/useFocusTrap/useFocusTrap.test.tsx
  packages/hooks/src/useFocusTrap/useFocusTrap.ts
Labels: approved, Team Atlantis

#1102 refactor: Fix typing issue on card header
  packages/components/src/Card/CardHeader.tsx
Labels: approved, Team Atlantis

#1070 fix(components): Allow "input" Chips to have hover states
  packages/components/src/Chips/InternalChip.css
Labels: approved, Team Atlantis

#1104 build(deps): Uninstall unused packages
  package-lock.json
  package.json
  packages/components/package-lock.json
Labels: approved, Team Atlantis

#1090 chore: cleanup contribution-related urls and PR title generator content
  .storybook/components/PullRequestGenerator/PullRequestGenerator.tsx
  docs/CONTRIBUTING.md
  docs/README.md
Labels: approved, Team Atlantis

#1092 chore(components): Upgrade react-hook-form to 6.15.8
  packages/components/package-lock.json
  packages/components/package.json
  packages/components/src/FormField/FormFieldTypes.ts
Labels: approved, Team Atlantis

#1025 refactor(components): replace base colors with semantic colors
  packages/components/src/DescriptionList/DescriptionList.tsx
  packages/components/src/DescriptionList/__snapshots__/DescriptionList.test.tsx.snap
  packages/components/src/InputFile/InputFile.tsx
  packages/components/src/InputFile/__snapshots__/InputFile.test.tsx.snap
  packages/components/src/Menu/Menu.tsx
Labels: approved, Team Atlantis

#1071 docs: add timesheets to product vocabulary stories.mdx
  docs/content/product-vocabulary.stories.mdx
Labels: approved, Team Atlantis

#1095 refactor(components): remove react-image-lightbox
  docs/README.md
  package-lock.json
  packages/components/package-lock.json
  packages/components/package.json
  packages/components/rollup.config.js
  packages/components/src/Gallery/Gallery.test.tsx
  packages/components/src/LightBox/LightBox.css
  packages/components/src/LightBox/LightBox.css.d.ts
  packages/components/src/LightBox/LightBox.stories.mdx
  packages/components/src/LightBox/LightBox.test.tsx
  packages/components/src/LightBox/LightBox.tsx
  packages/components/src/LightBox/__snapshots__/LightBoxSnapshots.test.tsx.snap
Labels: approved, design approved, Team Atlantis

#1106 refactor(components): Simplify Banner styling [JOB-46520]
  packages/components/src/Banner/Banner.css
  packages/components/src/Banner/Banner.css.d.ts
  packages/components/src/Banner/Banner.tsx
  packages/components/src/Banner/__snapshots__/Banner.test.tsx.snap
Labels: approved, Team Atlantis

#1107 docs: add rule about targeting html elements [JOB-61707]
  docs/guides/frontend-style.stories.mdx
Labels: approved

#1110 fix(components): Fix progress bar alignment on FormatFile [JOB-63249]
  packages/components/src/FormatFile/FormatFile.css
Labels: approved, Team Atlantis

#1103 chore(components): Reupdate react-router-dom and types
  package-lock.json
  package.json
  packages/components/package-lock.json
  packages/components/package.json
Labels: approved, Team Atlantis, Team Frontend Foundations

#1112 feat(components): only show the navigation buttons on Lightbox when there is more than 1 image
  packages/components/src/LightBox/LightBox.stories.mdx
  packages/components/src/LightBox/LightBox.tsx
  packages/components/src/LightBox/__snapshots__/LightBoxSnapshots.test.tsx.snap
Labels: approved, design approved, Team Atlantis

#1105 chore(hooks): Upgrade graphql and @apollo/query
  package-lock.json
  package.json
  packages/hooks/package-lock.json
  packages/hooks/package.json
  packages/hooks/src/useCollectionQuery/useCollectionQuery.test.tsx
Labels: approved, Team Atlantis

#1115 fix: use update instead of forceUpdate on popper
  packages/components/src/Chips/InternalChipDismissible/InternalChipDismissibleInput.tsx
Labels: approved, Team Atlantis

#1114 refactor(components): replace render with create root
  packages/components/src/Toast/Toast.test.tsx
  packages/components/src/Toast/showToast.tsx
Labels: approved, Team Atlantis

#1053 docs(components): bring back Card header with action example
  packages/components/src/Card/Card.stories.mdx
Labels: approved

#1075 docs: Copy changelog to storybook
  .storybook/main.ts
  .storybook/preview.tsx
  docs/changelog/components.stories.mdx
  docs/changelog/design.stories.mdx
  docs/changelog/docx.stories.mdx
  docs/changelog/eslint-config.stories.mdx
  docs/changelog/formatters.stories.mdx
  docs/changelog/generators.stories.mdx
  docs/changelog/hooks.stories.mdx
  docs/changelog/stylelint-config.stories.mdx
  packages/components/CHANGELOG.md
  packages/design/CHANGELOG.md
  packages/docx/CHANGELOG.md
  packages/eslint-config/CHANGELOG.md
  packages/formatters/CHANGELOG.md
  packages/generators/CHANGELOG.md
  packages/hooks/CHANGELOG.md
  packages/stylelint-config/CHANGELOG.md
Labels: approved, Team Atlantis

#1121 refactor(components): use Atlantis timing in Spinner
  packages/components/src/Spinner/Spinner.css
Labels: approved, Team Atlantis

#1126 fix(design): preserve responsive behaviour in larger fontSizes [JOB-64729]
  packages/design/src/typography.css
Labels: approved, Team Atlantis

#1116 build(deps): Upgrade Lerna to v6
  package-lock.json
  package.json
  packages/components/package-lock.json
Labels: approved, Team Atlantis

#1130 refactor: prepare for ESlint upgrade
  .eslintignore
  packages/components/src/Autocomplete/Menu.tsx
  packages/components/src/Banner/Banner.test.tsx
  packages/components/src/Chips/InternalChipDismissible/hooks/__tests__/useInternalChipDismissibleInput.test.tsx
  packages/components/src/DatePicker/DatePicker.test.tsx
  packages/components/src/Drawer/Drawer.tsx
  packages/components/src/FormField/FormFieldWrapper.tsx
  packages/components/src/FormatFile/FormatFile.test.tsx
  packages/components/src/Gallery/GalleryTypes.ts
  packages/components/src/InputAvatar/InputAvatar.tsx
  packages/components/src/LightBox/LightBox.test.tsx
  packages/components/src/MultiSelect/MultiSelect.test.tsx
  packages/components/src/Page/Page.test.tsx
  packages/components/src/RecurringSelect/RecurringSelect.test.tsx
  packages/components/src/Toast/Toast.test.tsx
  packages/formatters/src/global.ts
  packages/hooks/src/useCollectionQuery/mdxUtils.ts
  packages/hooks/src/useCollectionQuery/useCollectionQuery.test.tsx
Labels: approved, Team Atlantis

#1131 refactor: Cleanup before ESLint upgrade
  packages/components/src/Avatar/Avatar.test.tsx
  packages/components/src/Avatar/__snapshots__/Avatar.test.tsx.snap
  packages/components/src/Banner/Banner.test.tsx
  packages/components/src/DataTable/index.ts
  packages/components/src/RecurringSelect/RecurringSelect.test.tsx
  packages/components/src/Table/index.ts
  packages/design/src/index.ts
Labels: approved, Team Atlantis

#1118 build(deps): Bump eslint and related packages BREAKING CHANGE
  .eslintrc.js
  .storybook/components/TableOfContents/TableOfContents.tsx
  docs/guides/frontend-style.stories.mdx
  lint-staged.config.js
  package-lock.json
  package.json
  packages/eslint-config/.eslintrc.js
  packages/eslint-config/package-lock.json
  packages/eslint-config/package.json
Labels: approved, Team Atlantis

#1135 build(eslint): Revert ESLint bump
  .eslintrc.js
  .storybook/components/TableOfContents/TableOfContents.tsx
  docs/guides/frontend-style.stories.mdx
  lint-staged.config.js
  package-lock.json
  package.json
  packages/eslint-config/.eslintrc.js
  packages/eslint-config/package-lock.json
  packages/eslint-config/package.json
Labels: approved, Team Atlantis

#1136 feat(eslint)!: Bump ESLint and related packages to latest
  .eslintrc.js
  .storybook/components/TableOfContents/TableOfContents.tsx
  docs/guides/frontend-style.stories.mdx
  lint-staged.config.js
  package-lock.json
  package.json
  packages/eslint-config/.eslintrc.js
  packages/eslint-config/package-lock.json
  packages/eslint-config/package.json
Labels: approved, Team Atlantis

#1134 refactor(components): Cleanup after ESLint bump
  packages/components/src/Avatar/Avatar.test.tsx
  packages/components/src/Avatar/__snapshots__/Avatar.test.tsx.snap
  packages/components/src/RecurringSelect/RecurringSelect.test.tsx
Labels: approved, Team Atlantis

#1111 feat!: Make React 18 as the only Peer Deps [JOB-63252] BREAKING CHANGE
  package-lock.json
  package.json
  packages/components/package-lock.json
  packages/components/package.json
  packages/components/src/Toast/Toast.test.tsx
  packages/components/src/Toast/showToast.tsx
  packages/hooks/package-lock.json
  packages/hooks/package.json
  packages/hooks/src/useCollectionQuery/useCollectionQuery.test.tsx
Labels: approved, Team Atlantis

#1138 docs(components): update casing of sample buttons to follow guidelines
  packages/components/src/Button/Button.stories.mdx
Labels: approved, Team Atlantis

#1139 fix(components): define and standardize lineheight in FormField
  packages/components/src/FormField/FormField.css
Labels: approved, 90%, Team Atlantis

#1137 build: Upgrade Typescript to 4.9 [JOB-65415]
  package-lock.json
  package.json
  packages/components/package-lock.json
  packages/components/package.json
  packages/components/src/DataTable/DataTable.test.tsx
  packages/design/package-lock.json
  packages/design/package.json
  packages/formatters/package-lock.json
  packages/formatters/package.json
  packages/hooks/package-lock.json
  packages/hooks/package.json
  tsconfig.base.json
Labels: approved, Team Atlantis

#1140 build(deps): Update react-hook-form to v7.43.7 [JOB-65458]
  packages/components/package-lock.json
  packages/components/package.json
  packages/components/src/Form/Form.test.tsx
  packages/components/src/Form/Form.tsx
  packages/components/src/FormField/FormField.test.tsx
  packages/components/src/FormField/FormField.tsx
  packages/components/src/InputNumber/InputNumber.test.tsx
  packages/hooks/src/useFormState/useFormState.ts
Labels: approved, Team Atlantis

#1142 build: Use NPM Workspace instead of Lerna to bootstrap
  .circleci/config.yml
  .storybook/main.js
  jest.config.js
  lerna.json
  package-lock.json
  package.json
  packages/components/package-lock.json
  packages/components/package.json
  packages/components/src/DatePicker/DatePicker.css
  packages/components/src/FormatRelativeDateTime/FormatRelativeDateTime.test.tsx
  packages/components/src/InputAvatar/__snapshots__/InputAvatar.test.tsx.snap
  packages/components/src/InputFile/__snapshots__/InputFile.test.tsx.snap
  packages/design/package-lock.json
  packages/design/package.json
  packages/docx/package-lock.json
  packages/eslint-config/package-lock.json
  packages/formatters/package-lock.json
  packages/formatters/package.json
  packages/generators/package-lock.json
  packages/hooks/package-lock.json
  packages/hooks/package.json
  packages/stylelint-config/package-lock.json
  scripts/bootstrap.sh
  scripts/preventManualRelease.js
Labels: approved, Team Atlantis

#1146 build(deps): Upgrade jest to v29.5.0
  jest.config.js
  package-lock.json
  package.json
  packages/components/src/Checkbox/__snapshots__/Checkbox.test.tsx.snap
  packages/components/src/DatePicker/DatePicker.test.tsx
  packages/components/src/FormatRelativeDateTime/FormatRelativeDateTime.test.tsx
  packages/components/src/Toast/Toast.test.tsx
  packages/design/package-lock.json
  packages/design/package.json
Labels: approved, Team Atlantis

#1141 feat: Upgrade to Node 18 [Feature Branch][JOB-62820]
  .circleci/config.yml
  .npmrc.pages
  .nvmrc
  .storybook/main.js
  docs/README.md
  lerna.json
  package-lock.json
  package.json
  packages/components/package-lock.json
  packages/components/package.json
  packages/components/src/DatePicker/DatePicker.css
  packages/components/src/FormatRelativeDateTime/FormatRelativeDateTime.test.tsx
  packages/components/src/InputAvatar/__snapshots__/InputAvatar.test.tsx.snap
  packages/components/src/InputFile/__snapshots__/InputFile.test.tsx.snap
  packages/design/package-lock.json
  packages/design/package.json
  packages/docx/package-lock.json
  packages/eslint-config/package-lock.json
  packages/formatters/package-lock.json
  packages/formatters/package.json
  packages/generators/package-lock.json
  packages/hooks/package-lock.json
  packages/hooks/package.json
  packages/stylelint-config/package-lock.json
  scripts/bootstrap.sh
  scripts/preventManualRelease.js
Labels: approved, Team Atlantis

#1152 build: Update Github rsa fingerprint
  .circleci/config.yml
Labels: approved, Team Atlantis

#1155 fix(components): Fix Typescript warnings on components
  lint-staged.config.js
  packages/components/rollup.config.js
  packages/components/src/DatePicker/DatePickerActivator.tsx
  packages/components/src/List/ListItem.tsx
Labels: approved, Team Atlantis

#1156 fix(components): update Disclosure component to use useResizeObserver on title
  packages/components/src/Disclosure/Disclosure.tsx
Labels: approved

#1159 feat: Add uploadUrl to FileUpload
  packages/components/src/InputFile/InputFile.test.tsx
  packages/components/src/InputFile/InputFile.tsx
Labels: approved, Team Atlantis

#1161 feat(components): Add new “money” icons
  packages/components/src/Icon/Icon.stories.mdx
  packages/design/src/icons/iconMap.ts
Labels: approved, Team Atlantis

#1163 chore: Change trim version to fix security vulnerability
  package-lock.json
  package.json
Labels: approved, Team Atlantis

#1164 refactor(components): Remove redundant button prop types
  packages/components/src/Button/Button.tsx
Labels: approved, Team Atlantis

#1162 build(deps): Remove postcss-svg
  package-lock.json
  packages/components/package.json
  packages/components/rollup.config.js
  packages/components/src/Typography/css/Emphasis.css
Labels: approved, Team Atlantis

#1169 fix: Gallery and InputFile uploadurl required
  packages/components/src/InputFile/InputFile.tsx
Labels: changes requested, in review

#1171 fix: Enable noEmitOnError on component bootstrap
  packages/components/rollup.config.js
Labels: review requested, Team Atlantis

#1166 chore: Add vscode settings and extensions for linting
  .vscode/extensions.json
  .vscode/settings.json
  docs/README.md
Labels: approved, Team Atlantis
