Repository GetJobber/atlantis, pull requests merged in 2023-10, with the labels that each got.

#1549 feat(components): Allow Bulk actions on DataList
  docs/components/DataList/Web.stories.tsx
  packages/components/src/DataList/DataList.css
  packages/components/src/DataList/DataList.css.d.ts
  packages/components/src/DataList/DataList.tsx
  packages/components/src/DataList/DataList.types.ts
  packages/components/src/DataList/DataList.utils.tsx
  packages/components/src/DataList/components/DataListAction/DataListAction.tsx
  packages/components/src/DataList/components/DataListBulkActions/DataListBulkActions.const.ts
  packages/components/src/DataList/components/DataListBulkActions/DataListBulkActions.css.d.ts
  packages/components/src/DataList/components/DataListBulkActions/DataListBulkActions.tsx
  packages/components/src/DataList/components/DataListBulkActions/index.ts
  packages/components/src/DataList/components/DataListFilters/DataListFilters.test.tsx
  packages/components/src/DataList/components/DataListFilters/DataListFilters.tsx
  packages/components/src/DataList/components/DataListItemActions/DataListItemActions.tsx
  packages/components/src/DataList/components/DataListItemActions/DataListItemActionsOverflow.tsx
  packages/components/src/DataList/components/DataListLayoutInternal/DataListHeader.tsx
  packages/components/src/DataList/components/DataListLayoutInternal/DataListHeaderCheckbox.tsx
  packages/components/src/DataList/components/DataListLayoutInternal/__tests__/DataListHeaderCheckbox.test.tsx
  packages/components/src/DataList/components/DataListOverflowFade/DataListOverflowFade.const.ts
  packages/components/src/DataList/components/DataListOverflowFade/DataListOverflowFade.css
  packages/components/src/DataList/components/DataListOverflowFade/DataListOverflowFade.css.d.ts
  packages/components/src/DataList/components/DataListOverflowFade/DataListOverflowFade.tsx
  packages/components/src/DataList/components/DataListOverflowFade/index.ts
Labels: approved, Team Atlantis

#1552 chore(components): add more tests for DataList actions
  packages/components/src/DataList/DataList.types.ts
  packages/components/src/DataList/components/DataListAction/DataListAction.test.tsx
  packages/components/src/DataList/components/DataListAction/DataListAction.tsx
  packages/components/src/DataList/components/DataListActionsMenu/DataListActionsMenu.test.tsx
  packages/components/src/DataList/components/DataListActionsMenu/DataListActionsMenu.tsx
  packages/components/src/DataList/components/DataListItem/DataListItem.test.tsx
  packages/components/src/DataList/components/DataListItem/DataListItem.tsx
  packages/components/src/DataList/components/DataListItemActions/DataListItemActions.test.tsx
  packages/components/src/DataList/components/DataListItemActions/DataListItemActions.tsx
  packages/components/src/DataList/components/DataListItemActions/DataListItemActionsOverflow.tsx
  packages/components/src/DataList/components/DataListLayoutActions/DataListLayoutActions.tsx
Labels: approved, Team Atlantis

#1558 refactor(components): Style adjustments and refactor in DataList
  packages/components/src/DataList/DataList.css
  packages/components/src/DataList/DataList.css.d.ts
  packages/components/src/DataList/DataList.types.ts
  packages/components/src/DataList/components/DataListActions/DataListActions.tsx
  packages/components/src/DataList/components/DataListActions/index.ts
  packages/components/src/DataList/components/DataListBulkActions/DataListBulkActions.tsx
  packages/components/src/DataList/components/DataListItem/DataListItem.tsx
  packages/components/src/DataList/components/DataListItemActions/DataListItemActions.test.tsx
  packages/components/src/DataList/components/DataListItemActions/DataListItemActions.tsx
  packages/components/src/DataList/components/DataListItemActions/index.ts
  packages/components/src/DataList/components/DataListItemActionsOverflow/DataListItemActionsOverflow.tsx
  packages/components/src/DataList/components/DataListItemActionsOverflow/index.ts
  packages/components/src/DataList/components/DataListLayoutActions/DataListLayoutActions.tsx
  packages/components/src/DataList/components/DataListLayoutInternal/DataListHeaderCheckbox.tsx
Labels: approved, design approved, Team Atlantis

#1559 fix(components): Fix importing of datalist css issue
  packages/components/src/DataList/components/DataListItem/DataListItem.tsx
  packages/components/src/DataList/components/DataListItem/DataListItemInternal.tsx
  packages/components/src/DataList/components/DataListItem/components/DataListItemClickable/DataListItemClickableInternal.tsx
Labels: approved, hacktoberfest, hacktoberfest-accepted, Team Atlantis

#1560 refactor(components): reduce the amount of reduce we do in DataList
  packages/components/src/DataList/DataList.tsx
  packages/components/src/DataList/DataList.types.ts
  packages/components/src/DataList/DataList.utils.tsx
  packages/components/src/DataList/__tests__/DataList.utils.test.tsx
  packages/components/src/DataList/components/DataListActionsMenu/DataListActionsMenu.test.tsx
  packages/components/src/DataList/components/DataListHeader/DataListHeader.tsx
  packages/components/src/DataList/components/DataListHeader/DataListHeaderCheckbox.test.tsx
  packages/components/src/DataList/components/DataListHeader/DataListHeaderCheckbox.tsx
  packages/components/src/DataList/components/DataListHeader/index.ts
  packages/components/src/DataList/components/DataListItem/DataListItem.test.tsx
  packages/components/src/DataList/components/DataListItem/DataListItem.tsx
  packages/components/src/DataList/components/DataListItems/DataListItems.test.tsx
  packages/components/src/DataList/components/DataListItems/DataListItems.tsx
  packages/components/src/DataList/components/DataListItems/index.ts
  packages/components/src/DataList/components/DataListLayout/DataListLayout.tsx
  packages/components/src/DataList/components/DataListLayoutActions/DataListLayoutActions.tsx
  packages/components/src/DataList/components/DataListLayoutInternal/DataListHeader.tsx
  packages/components/src/DataList/components/DataListLayoutInternal/DataListItems.tsx
  packages/components/src/DataList/components/DataListLayoutInternal/DataListLayoutInternal.tsx
  packages/components/src/DataList/components/DataListLayoutInternal/__tests__/DataListItems.test.tsx
  packages/components/src/DataList/components/DataListLayoutInternal/index.ts
  packages/components/src/DataList/components/DataListLoadingState/DataListLoadingState.css
  packages/components/src/DataList/components/DataListLoadingState/DataListLoadingState.css.d.ts
  packages/components/src/DataList/components/DataListLoadingState/DataListLoadingState.tsx
  packages/components/src/DataList/context/DataListContext/DataListContext.tsx
  packages/components/src/DataList/hooks/useActiveLayout.ts
  packages/components/src/DataList/hooks/useLayoutMediaQueries.ts
Labels: approved, Team Atlantis

#1563 build: Fix warning from the rollup step
  packages/components/rollup.config.js
Labels: approved, Team Atlantis

#1564 fix(components): nested button issue on DataList
  packages/components/src/DataList/components/DataListActionsMenu/DataListActionsMenu.tsx
  packages/components/src/DataList/components/DataListItem/DataListItem.test.tsx
  packages/components/src/DataList/components/DataListItem/components/DataListItemClickable/DataListItemClickable.test.tsx
  packages/components/src/DataList/components/DataListItem/components/DataListItemClickable/DataListItemClickableInternal.tsx
  packages/components/src/DataList/components/DataListItemActionsOverflow/DataListItemActionsOverflow.tsx
Labels: approved, Team Atlantis

#1567 fix(components): Fixed using DataList in jest tests failing
  packages/components/src/DataList/components/DataListActionsMenu/DataListActionsMenu.tsx
Labels: approved, Team Atlantis

#1557 feat(components): Add multiselect prop to combobox
  docs/components/Combobox/Web.stories.tsx
  packages/components/src/Combobox/Combobox.tsx
  packages/components/src/Combobox/ComboboxProvider.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.test.tsx
Labels: approved, Team Atlantis

#1568 chore: Add tests for DataListActions and DataListBulkActions
  packages/components/src/DataList/components/DataListActions/DataListActions.test.tsx
  packages/components/src/DataList/components/DataListBulkActions/DataListBulkActions.test.tsx
  packages/components/src/DataList/components/DataListItemActions/DataListItemActions.test.tsx
Labels: approved, Team Atlantis

#1565 feat(hooks): create breakpoints hook
  packages/design/src/ResponsiveBreakpoint.stories.mdx
  packages/hooks/src/useBreakpoints/index.ts
  packages/hooks/src/useBreakpoints/mockViewportWidth/index.ts
  packages/hooks/src/useBreakpoints/mockViewportWidth/mockViewportWidth.test.ts
  packages/hooks/src/useBreakpoints/mockViewportWidth/mockViewportWidth.ts
  packages/hooks/src/useBreakpoints/useBreakpoints.stories.mdx
  packages/hooks/src/useBreakpoints/useBreakpoints.test.ts
  packages/hooks/src/useBreakpoints/useBreakpoints.ts
  packages/hooks/src/useBreakpoints/useMediaQuery.ts
Labels: approved, Team Atlantis

#1554 fix(components): Always Allow Combobox Gradient to Show
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.css
  packages/components/src/Combobox/components/ComboboxContent/ComboboxList.css
  packages/components/src/Combobox/components/ComboboxContent/ComboboxSearch.css
Labels: approved, Team Atlantis

#1576 fix(components): Use button type in Dismissable Chip menu items
  packages/components/src/Chips/InternalChipDismissible/InternalChipDismissibleInput.tsx
Labels: approved, Team Atlantis

#1575 chore: enforce a better relative import
  .eslintrc.js
  package-lock.json
  package.json
Labels: approved, Team Atlantis

#1574 fix(components): DataList search initial value
  packages/components/src/DataList/DataList.tsx
  packages/components/src/DataList/DataList.types.ts
  packages/components/src/DataList/components/DataListSearch/DataListSearch.tsx
Labels: approved, Team Atlantis

#1577 chore: automate code quality and nitpicks
  .eslintrc.js
  package-lock.json
  package.json
  packages/eslint-config/package.json
Labels: approved, Team Atlantis

#1569 feat(components): MultiSelect Combobox
  docs/components/Combobox/Combobox.stories.mdx
  docs/components/Combobox/Web.stories.tsx
  packages/components/src/Combobox/Combobox.test.tsx
  packages/components/src/Combobox/components/ComboboxAction/ComboboxAction.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.test.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxList.test.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxList.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxSearch.tsx
  packages/components/src/Combobox/components/ComboboxTrigger/ComboboxTriggerChip/ComboboxTriggerChip.tsx
  packages/components/src/Combobox/hooks/useComboboxContent.ts
Labels: approved, Team Atlantis

#1579 docs: add local cross-package link steps to readme
  docs/README.md
Labels: approved, Team Atlantis

#1581 feat(components): Adjust Combobox Selected Style
  packages/components/src/Combobox/Combobox.test.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxList.css
  packages/components/src/Combobox/components/ComboboxContent/ComboboxList.css.d.ts
  packages/components/src/Combobox/components/ComboboxContent/ComboboxList.test.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxList.tsx
Labels: approved, design approved, Team Atlantis

#1584 chore: reduce the amount of mocking a consumer would have to do when using DataList
  packages/components/src/DataList/hooks/useMediaQuery.ts
Labels: approved, Team Atlantis

#1585 fix(components): Avoid rendering DataListItemActions when there's no children
  packages/components/src/DataList/components/DataListItemActions/DataListItemActions.test.tsx
  packages/components/src/DataList/components/DataListItemActions/DataListItemActions.tsx
Labels: approved, Team Atlantis

#1571 feat(components): Chip
  docs/components/Chip/Comparison.stories.tsx
  docs/components/Chip/Web.stories.tsx
  packages/components/src/Chip/Chip.css
  packages/components/src/Chip/Chip.css.d.ts
  packages/components/src/Chip/Chip.test.tsx
  packages/components/src/Chip/Chip.tsx
  packages/components/src/Chip/Chip.types.d.ts
  packages/components/src/Chip/components/ChipDismissible/ChipDismissible.test.tsx
  packages/components/src/Chip/components/ChipDismissible/ChipDismissible.tsx
  packages/components/src/Chip/components/ChipPrefix/Chip.Prefix.test.tsx
  packages/components/src/Chip/components/ChipPrefix/Chip.Prefix.tsx
  packages/components/src/Chip/components/ChipSelectable/ChipSelectable.test.tsx
  packages/components/src/Chip/components/ChipSelectable/ChipSelectable.tsx
  packages/components/src/Chip/components/ChipSuffix/Chip.Suffix.test.tsx
  packages/components/src/Chip/components/ChipSuffix/Chip.Suffix.tsx
  packages/components/src/Chip/hooks/index.ts
  packages/components/src/Chip/hooks/useChildComponent.ts
  packages/components/src/Chip/index.ts
  packages/components/src/Typography/css/FontWeights.css
  packages/components/src/Typography/css/FontWeights.css.d.ts
  packages/hooks/src/index.ts
  packages/hooks/tsconfig.json
Labels: approved, design approved, Team Atlantis

#1587 docs(hooks): Example for using breakpoints in tests
  packages/hooks/src/useBreakpoints/useBreakpoints.stories.mdx
Labels: approved, Team Atlantis

#1555 refactor(components): update tooltip styling and reduce bounce [JOB-75936]
  packages/components/src/Tooltip/Tooltip.css
  packages/components/src/Tooltip/Tooltip.css.d.ts
  packages/components/src/Tooltip/Tooltip.tsx
Labels: approved, Team Atlantis

#1556 feat(components): add Flex component for web
  docs/components/Flex/Flex.stories.mdx
  docs/components/Flex/Web.stories.tsx
  packages/components/src/Content/Content.tsx
  packages/components/src/Flex/Flex.css
  packages/components/src/Flex/Flex.css.d.ts
  packages/components/src/Flex/Flex.test.tsx
  packages/components/src/Flex/Flex.tsx
  packages/components/src/Flex/Flex.types.ts
  packages/components/src/Flex/index.ts
Labels: approved, design approved, Team Atlantis

#1583 chore(components): Combobox Cleanup
  packages/components/src/Combobox/Combobox.test.tsx
  packages/components/src/Combobox/Combobox.tsx
  packages/components/src/Combobox/Combobox.types.ts
  packages/components/src/Combobox/components/ComboboxAction/ComboboxAction.tsx
  packages/components/src/Combobox/components/ComboboxAction/index.ts
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContentList/ComboboxContentList.css
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContentList/ComboboxContentList.css.d.ts
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContentList/ComboboxContentList.test.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContentList/ComboboxContentList.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContentList/index.ts
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContentSearch/ComboboxContentSearch.css
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContentSearch/ComboboxContentSearch.css.d.ts
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContentSearch/ComboboxContentSearch.test.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContentSearch/ComboboxContentSearch.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContentSearch/index.ts
  packages/components/src/Combobox/components/ComboboxTrigger/ComboboxTriggerButton/ComboboxTriggerButton.tsx
  packages/components/src/Combobox/components/ComboboxTrigger/ComboboxTriggerChip/ComboboxTriggerChip.tsx
  packages/components/src/Combobox/hooks/useComboboxAccessibility.ts
  packages/components/src/Combobox/hooks/useComboboxContent.ts
  packages/components/src/Combobox/hooks/useComboboxValidation.ts
  packages/components/src/Combobox/index.ts
Labels: approved, Team Atlantis

#1580 docs(components): Update Docs for Combobox MultiSelect Variation
  docs/components/Combobox/Combobox.stories.mdx
  docs/components/Combobox/Web.stories.tsx
Labels: approved, design approved, Team Atlantis

#1572 docs(components): improve data list docs
  docs/components/DataList/DataList.stories.mdx
Labels: approved, Team Atlantis

#1597 docs(components): Add related component guidance to common layout tools
  docs/components/Content/Content.stories.mdx
  docs/components/Flex/Flex.stories.mdx
  docs/components/Grid/Grid.stories.mdx
Labels: approved, Team Atlantis

#1578 chore: ensure paths are aliased on test as well in components
  .gitignore
  packages/components/package.json
  packages/components/rollup.config.js
  packages/components/tsconfig.json
  packages/components/tsconfig.rollup.json
Labels: approved, Team Atlantis

#1586 docs(components): update usage examples in InlineLabel docs
  docs/components/InlineLabel/InlineLabel.stories.mdx
Labels: approved, Team Atlantis

#1570 feat(components): Combobox Header
  docs/components/Combobox/Web.stories.tsx
  packages/components/src/Combobox/Combobox.test.tsx
  packages/components/src/Combobox/Combobox.types.ts
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.test.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContentHeader/ComboboxContentHeader.css
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContentHeader/ComboboxContentHeader.css.d.ts
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContentHeader/ComboboxContentHeader.test.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContentHeader/ComboboxContentHeader.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContentHeader/index.ts
  packages/components/src/Combobox/hooks/useComboboxContent.ts
Labels: approved, design approved, Team Atlantis

#1591 feat(components): Tabs supports caching active tab between page loads
  docs/components/Tabs/Web.stories.tsx
  packages/components/src/Tabs/Tabs.test.tsx
  packages/components/src/Tabs/Tabs.tsx
  packages/components/src/Tabs/__snapshots__/Tabs.test.tsx.snap
Labels: approved, Team Atlantis

#1590 feat(components-native): add testID property to Button and default testID values to ButtonGroup
  packages/components-native/src/Button/Button.tsx
  packages/components-native/src/ButtonGroup/ButtonGroup.tsx
  packages/components-native/src/Form/components/FormSaveButton/FormSaveButton.tsx
Labels: approved, Team Atlantis

#1601 test(components): Additional keyboard tests for Calendar Date Picker
  packages/components/src/CalendarDatePicker/CalendarDatePicker.test.tsx
Labels: review requested, Team Atlantis

#1595 feat(components): JOB-80773 Datatable scroll to top pagination loading
  docs/components/DataTable/Web.stories.tsx
  packages/components/src/DataTable/DataTable.test.tsx
  packages/components/src/DataTable/DataTable.tsx
  packages/components/src/DataTable/Pagination.tsx
Labels: approved, Team Atlantis, Team Quotemeal

#1607 fix(components-native): remove doubled testID prefix for GroupButton
  packages/components-native/src/ButtonGroup/ButtonGroup.tsx
Labels: approved, Team Atlantis

#1606 fix(components): Fix Combobox Types Exports
  jobber-components-4.53.0.tgz
  packages/components/src/Combobox/Combobox.tsx
  packages/components/src/Combobox/components/ComboboxAction/ComboboxAction.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContentHeader/ComboboxContentHeader.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContentList/ComboboxContentList.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContentSearch/ComboboxContentSearch.tsx
  packages/components/src/Combobox/components/ComboboxTrigger/ComboboxTriggerButton/ComboboxTriggerButton.tsx
  packages/components/src/Combobox/components/ComboboxTrigger/ComboboxTriggerChip/ComboboxTriggerChip.tsx
  packages/components/src/Combobox/hooks/useComboboxAccessibility.ts
  packages/components/src/Combobox/hooks/useComboboxContent.ts
  packages/components/src/Combobox/index.ts
Labels: approved, Team Atlantis

#1596 feat(components): Add DataList.StatusBar
  docs/components/DataList/DataList.stories.mdx
  docs/components/DataList/Web.stories.tsx
  packages/components/src/Banner/Banner.tsx
  packages/components/src/DataList/DataList.test.tsx
  packages/components/src/DataList/DataList.tsx
  packages/components/src/DataList/components/DataListStatusBar/DataListStatusBar.tsx
  packages/components/src/DataList/components/DataListStatusBar/index.ts
Labels: approved, design approved, Team Atlantis

#1593 feat(components): Truncate Long Chip Content with Gradient
  docs/components/Chip/Web.stories.tsx
  packages/components/src/Chip/Chip.css
  packages/components/src/Chip/Chip.css.d.ts
  packages/components/src/Chip/Chip.test.tsx
  packages/components/src/Chip/Chip.tsx
  packages/components/src/Tooltip/Tooltip.test.tsx
  packages/components/src/Tooltip/Tooltip.tsx
Labels: approved, design approved, Team Atlantis

#1608 fix(hooks): Fix useCollectionQuery error state when fetching more
  packages/hooks/src/useCollectionQuery/useCollectionQuery.test.tsx
  packages/hooks/src/useCollectionQuery/useCollectionQuery.ts
Labels: approved, Team Atlantis

#1611 chore: Remove .tgz file
  jobber-components-4.53.0.tgz
Labels: approved, Team Atlantis

#1609 fix(components): eliminate Tooltip/activator flicker
  packages/components/src/Tooltip/Tooltip.css
Labels: approved, Team Atlantis

#1613 feat(components-native): add custom testID to Select component
  packages/components-native/src/Select/Select.test.tsx
  packages/components-native/src/Select/Select.tsx
Labels: approved, Team Atlantis

#1612 fix(components): DataList UI updates
  packages/components/src/DataList/DataList.css
  packages/components/src/DataList/DataList.css.d.ts
  packages/components/src/DataList/components/DataListBulkActions/DataListBulkActions.css
  packages/components/src/DataList/components/DataListBulkActions/DataListBulkActions.css.d.ts
  packages/components/src/DataList/components/DataListBulkActions/DataListBulkActions.tsx
  packages/components/src/DataList/components/DataListLoadingState/DataListLoadingState.css
  packages/components/src/DataList/components/DataListLoadingState/DataListLoadingState.tsx
  packages/components/src/DataList/components/DataListOverflowFade/DataListOverflowFade.css
  packages/components/src/DataList/components/DataListOverflowFade/DataListOverflowFade.tsx
  packages/components/src/DataList/components/DataListTags/DataListTags.css
Labels: approved, Team Atlantis

#1610 feat(components): Implement Custom Activator to Combobox
  docs/components/Combobox/Web.stories.tsx
  packages/components/src/Chip/Chip.tsx
  packages/components/src/Combobox/Combobox.test.tsx
  packages/components/src/Combobox/Combobox.tsx
  packages/components/src/Combobox/Combobox.types.ts
  packages/components/src/Combobox/ComboboxProvider.tsx
  packages/components/src/Combobox/components/ComboboxActivator/ComboboxActivator.test.tsx
  packages/components/src/Combobox/components/ComboboxActivator/ComboboxActivator.tsx
  packages/components/src/Combobox/components/ComboboxActivator/index.ts
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.test.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.tsx
  packages/components/src/Combobox/components/ComboboxTrigger/ComboboxTrigger.test.tsx
  packages/components/src/Combobox/components/ComboboxTrigger/ComboboxTrigger.tsx
  packages/components/src/Combobox/components/ComboboxTrigger/index.ts
  packages/components/src/Combobox/hooks/useComboboxValidation.ts
Labels: approved, Team Atlantis

#1616 feat(components): Implement option and deprecate content
  docs/components/Combobox/Web.stories.tsx
  packages/components/src/Combobox/Combobox.test.tsx
  packages/components/src/Combobox/Combobox.tsx
  packages/components/src/Combobox/Combobox.types.ts
  packages/components/src/Combobox/ComboboxProvider.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.tsx
  packages/components/src/Combobox/components/ComboboxOption/ComboboxOption.tsx
  packages/components/src/Combobox/components/ComboboxOption/index.ts
  packages/components/src/Combobox/components/ComboboxTrigger/ComboboxTrigger.test.tsx
  packages/components/src/Combobox/components/ComboboxTrigger/ComboboxTrigger.tsx
  packages/components/src/Combobox/hooks/useComboboxValidation.ts
Labels: approved, Team Atlantis

#1618 feat(components): Make Combobox heading prop optional
  docs/components/Combobox/Web.stories.tsx
  packages/components/src/Combobox/Combobox.tsx
  packages/components/src/Combobox/Combobox.types.ts
  packages/components/src/Combobox/components/ComboboxActivator/ComboboxActivator.test.tsx
  packages/components/src/Combobox/components/ComboboxTrigger/ComboboxTrigger.test.tsx
  packages/components/src/Combobox/components/ComboboxTrigger/ComboboxTrigger.tsx
Labels: approved, Team Atlantis

#1617 chore(components): Update the Combobox test to follow the new API
  packages/components/src/Combobox/Combobox.test.tsx
Labels: approved, Team Atlantis
