Repository GetJobber/atlantis, pull requests merged in 2023-02, with the labels that each got.

#1017 docs: update casing of all custom section titles [JOB-61191]
  packages/components/src/Autocomplete/Autocomplete.mdx
  packages/components/src/Button/Button.mdx
  packages/components/src/Countdown/Countdown.mdx
  packages/components/src/DataTable/DataTable.mdx
  packages/components/src/DatePicker/DatePicker.mdx
  packages/components/src/DescriptionList/DescriptionList.mdx
  packages/components/src/Divider/Divider.mdx
  packages/components/src/Drawer/Drawer.mdx
  packages/components/src/Form/Form.mdx
  packages/components/src/FormField/FormField.mdx
  packages/components/src/FormatDate/FormatDate.mdx
  packages/components/src/FormatRelativeDateTime/FormatRelativeDateTime.mdx
  packages/components/src/FormatTime/FormatTime.mdx
  packages/components/src/InputFile/InputFile.mdx
  packages/components/src/InputGroup/InputGroup.mdx
  packages/components/src/InputNumber/InputNumber.mdx
  packages/components/src/InputPassword/InputPassword.mdx
  packages/components/src/InputText/InputText.mdx
  packages/components/src/InputTime/InputTime.mdx
  packages/components/src/List/List.mdx
  packages/components/src/Page/Page.mdx
  packages/components/src/ProgressBar/ProgressBar.mdx
  packages/components/src/RadioGroup/RadioGroup.mdx
  packages/components/src/Select/Select.mdx
  packages/components/src/Table/Table.mdx
Labels: approved

#1018 refactor(design): Cleanup function to export SCSS tokens
  packages/design/jobberStyle.js
Labels: approved, Team Atlantis

#1020 fix(deps): Update react date picker and adjust usage
  packages/components/package-lock.json
  packages/components/package.json
  packages/components/src/DatePicker/DatePicker.tsx
Labels: approved, design approved, Team Atlantis

#1024 fix(components): Make CSS selector more specific on SortIcon to not affect other icons [JOB-61694]
  packages/components/src/DataTable/SortIcon.css
Labels: approved, Team Atlantis

#1027 cleanup(design): Remove unwanted console log
  packages/design/jobberStyle.js
Labels: approved, Team Atlantis

#1030 chore(components): Update package-lock.json and npm-shrinkwrap.json
  packages/components/package-lock.json
  packages/design/npm-shrinkwrap.json
Labels: approved, Team Atlantis

#1022 fix(components): Remove default value for prop size in ConfirmationModal
  packages/components/src/ConfirmationModal/ConfirmationModal.tsx
  packages/components/src/ConfirmationModal/tests/__snapshots__/snapshot-ConfirmationModal.test.tsx.snap
Labels: approved, Team Atlantis

#1023 fix(components): JOB-61635 InputNumber on iOS not allowing decimals
  packages/components/src/FormField/FormFieldTypes.ts
  packages/components/src/InputNumber/InputNumber.test.tsx
  packages/components/src/InputNumber/InputNumber.tsx
Labels: approved, Team Atlantis

#1031 build: Update how we handle jobber fonts
  gatsby-browser.js
  package-lock.json
  package.json
  packages/design/foundation_config/postcss-filter-rules/index.js
  packages/design/foundation_config/postcss.config.js
  packages/design/package-lock.json
  packages/design/package.json
  packages/design/rollup.config.js
  packages/design/src/foundation.css
  packages/design/tsconfig.json
  packages/docz-tools/package-lock.json
  scripts/pre-prerelease.sh
Labels: approved, Team Atlantis

#1033 JOB-62075: Fix package lock out of sync take 4
  gatsby-browser.js
  package-lock.json
  package.json
  packages/components/package.json
  packages/docz-tools/package-lock.json
  packages/docz-tools/package.json
  packages/eslint-config/package-lock.json
Labels: approved, Team Atlantis

#1035 chore: Enforce semantic pull request titles
  .github/semantic.yml
  .github/workflows/pr-title-checker.yml
Labels: approved

#1037 docs: Storybook in atlantis
  .eslintrc.js
  .storybook/assets/favicon.svg
  .storybook/main.ts
  .storybook/manager.js
  .storybook/preview.js
  .storybook/theme.ts
  doczrc.js
  package-lock.json
  package.json
  packages/components/src/Button/Button.stories.mdx
Labels: approved, Team Atlantis

#1040 docs: Ignore stories.mdx on docz
  doczrc.js
  package-lock.json
  packages/docz-tools/src/gatsby-theme-docz/components/Navigation/useJobberMenu.tsx
Labels: approved, Team Atlantis

#1026 feat(components): Add Customizable Header Prop to Atlantis Web Card Component
  packages/components/src/Card/Card.css
  packages/components/src/Card/Card.mdx
  packages/components/src/Card/Card.tsx
  packages/components/src/Card/CardHeader.tsx
  packages/components/src/Card/tests/Card.test.tsx
  packages/components/src/Card/types.ts
  packages/components/src/Menu/Menu.tsx
  packages/components/src/Menu/index.ts
Labels: approved, Team Atlantis, Team Quotemeal

#1042 build: Temporarily skip InputAvatar flaky spec
  packages/components/src/InputAvatar/InputAvatar.test.tsx
Labels: approved, Team Atlantis

#1039 docs(components): Convert Typography component to Storybook
  packages/components/src/Typography/Typography.stories.mdx
Labels: approved, Team Atlantis

#1041 docs(design): Move first bundle of the design package to storybook
  packages/design/README.stories.mdx
  packages/design/src/Animation.stories.mdx
  packages/design/src/Radii.stories.mdx
  packages/design/src/Spacing.stories.mdx
Labels: approved, Team Atlantis

#1048 refactor(components): Minor Cleanup in Card component post Customizable Header Change
  packages/components/src/Card/Card.mdx
  packages/components/src/Card/Card.tsx
  packages/components/src/Card/CardHeader.tsx
Labels: approved, Team Atlantis, Team Quotemeal

#1052 docs: Add ExampleWithHooks component
  .storybook/components/ExampleWithHooks/ExampleWithHooks.tsx
  .storybook/components/ExampleWithHooks/index.ts
  .storybook/main.ts
Labels: approved, Team Atlantis

#1046 docs(components): Docs migration bundle 3
  .storybook/preview.js
  packages/components/src/Chips/Chips.stories.mdx
  packages/components/src/Countdown/Countdown.stories.mdx
  packages/components/src/FormatFile/FormatFile.stories.mdx
  packages/components/src/FormatRelativeDateTime/FormatRelativeDateTime.stories.mdx
  packages/components/src/FormatTime/FormatTime.stories.mdx
  packages/components/src/InputAvatar/InputAvatar.stories.mdx
  packages/components/src/InputEmail/InputEmail.stories.mdx
  packages/components/src/Table/Table.stories.mdx
Labels: approved, Team Atlantis

#1056 docs: Make docz gatsby work with stories again
  doczrc.js
  gatsby-config.js
  gatsby-node.js
Labels: approved, Team Atlantis

#1049 docs(design): Docs Migration Bundle 1
  .storybook/main.ts
  packages/design/src/Borders.stories.mdx
  packages/design/src/Colors.stories.mdx
  packages/design/src/Elevations.stories.mdx
  packages/design/src/ResponsiveBreakpoint.stories.mdx
  packages/docz-tools/src/components/index.ts
Labels: approved, Team Atlantis

#1050 docs(components): Convert component package bundle two
  packages/components/src/Card/Card.stories.mdx
  packages/components/src/Divider/Divider.stories.mdx
  packages/components/src/Form/Form.stories.mdx
  packages/components/src/InputFile/InputFile.stories.mdx
  packages/components/src/InputTime/InputTime.stories.mdx
  packages/components/src/List/List.stories.mdx
  packages/components/src/List/List.stories.tsx
  packages/components/src/Page/Page.stories.mdx
  packages/components/src/Tooltip/Tooltip.stories.mdx
Labels: approved, Team Atlantis

#1059 docs(components): Add Storybook stories bundle 7
  packages/components/src/Banner/Banner.stories.mdx
  packages/components/src/ButtonDismiss/ButtonDismiss.stories.mdx
  packages/components/src/ConfirmationModal/ConfirmationModal.stories.mdx
  packages/components/src/DataDump/DataDump.stories.mdx
  packages/components/src/DataTable/DataTable.stories.mdx
  packages/components/src/FeatureSwitch/FeatureSwitch.stories.mdx
  packages/components/src/FormatDate/FormatDate.stories.mdx
  packages/components/src/FormatEmail/FormatEmail.stories.mdx
  packages/components/src/InputGroup/InputGroup.stories.mdx
  packages/components/src/MultiSelect/MultiSelect.stories.mdx
  packages/components/src/RecurringSelect/RecurringSelect.stories.mdx
Labels: approved, Team Atlantis

#1058 fix: Override iOS default styling for disabled input
  packages/components/src/FormField/FormField.css
Labels: approved, Team Atlantis

#1055 docs(components): Convert docs files
  .storybook/components/PullRequestGenerator/PullRequestGenerator.tsx
  .storybook/components/PullRequestGenerator/index.ts
  .storybook/main.ts
  docs/content/assets/addvscreate.png
  docs/content/formatting.stories.mdx
  docs/content/product-vocabulary.stories.mdx
  docs/content/voice-and-tone.stories.mdx
  docs/getting-started-with-react/getting-started-with-react.stories.mdx
  docs/guides/assets/AmountCounter.gif
  docs/guides/assets/AmountPicker-annotated.png
  docs/guides/assets/AmountPicker-gridified.png
  docs/guides/assets/AmountPicker.png
  docs/guides/assets/component-grouped.png
  docs/guides/assets/component-jsx.png
  docs/guides/assets/component-props.png
  docs/guides/assets/component-using-icons.png
  docs/guides/assets/first-preview.png
  docs/guides/assets/imported-existing-components.png
  docs/guides/assets/making-the-button-work-increment-handler.png
  docs/guides/assets/making-the-button-work-increment-onclick.png
  docs/guides/assets/props.png
  docs/guides/assets/second-preview.png
  docs/guides/create-basic-component.stories.mdx
  docs/guides/frontend-style.stories.mdx
  docs/guides/pull-request-title-generator.stories.mdx
  docs/introduction/readme.stories.mdx
Labels: approved, Team Atlantis

#1061 docs(components): Update Patterns section and add Typography for Design (JOB-62647)
  packages/components/src/InputDate/InputDate.stories.mdx
  packages/components/src/Page/Page.stories.mdx
  packages/design/src/Typography.stories.mdx
Labels: approved, Team Atlantis

#1062 feat(components): Add new "range slider" icons
  packages/components/src/Icon/Icon.mdx
  packages/components/src/Icon/Icon.stories.mdx
  packages/design/src/icons/iconMap.ts
Labels: approved, design approved, Team Atlantis

#1057 docs: Implement example with hooks
  packages/components/src/Chips/Chips.stories.mdx
  packages/components/src/Countdown/Countdown.stories.mdx
Labels: approved, Team Atlantis

#1064 docs: add storybook content links and GitHub button
  .storybook/components/DocsWithSidebar/DocsWithSidebar.css
  .storybook/components/DocsWithSidebar/DocsWithSidebar.css.d.ts
  .storybook/components/DocsWithSidebar/DocsWithSidebar.tsx
  .storybook/components/DocsWithSidebar/index.ts
  .storybook/components/TableOfContents/TableOfContents.tsx
  .storybook/components/TableOfContents/index.ts
  .storybook/preview.ts
  .storybook/tsconfig.json
Labels: approved, Team Atlantis

#1065 docs: Allow md files to be imported to stories so readme isn't duplicated
  .storybook/main.ts
  .storybook/preview.ts
  docs/introduction/readme.stories.mdx
Labels: approved, Team Atlantis

#1054 docs: add timesheets to product vocabulary
  docs/content/product-vocabulary.mdx
Labels: approved

#1073 docs: Update spelling of Timesheets
  docs/content/product-vocabulary.mdx
Labels: approved

#1069 fix: JOB-62724 Update RadioGroup alignment
  packages/components/src/RadioGroup/RadioGroup.css
Labels: approved, Team Atlantis, Team Work Setup

#1074 docs: separate css loader for Atlantis and lib
  .storybook/main.ts
Labels: approved, Team Atlantis

#1072 docs(components): Update links to work when opening on a new tab
  docs/getting-started-with-react/getting-started-with-react.stories.mdx
  docs/guides/create-basic-component.stories.mdx
  docs/guides/frontend-style.stories.mdx
  packages/components/src/Autocomplete/Autocomplete.stories.mdx
  packages/components/src/Banner/Banner.stories.mdx
  packages/components/src/Button/Button.stories.mdx
  packages/components/src/Checkbox/Checkbox.stories.mdx
  packages/components/src/Chips/Chips.stories.mdx
  packages/components/src/ConfirmationModal/ConfirmationModal.stories.mdx
  packages/components/src/Countdown/Countdown.stories.mdx
  packages/components/src/DataTable/DataTable.stories.mdx
  packages/components/src/DatePicker/DatePicker.stories.mdx
  packages/components/src/DescriptionList/DescriptionList.stories.mdx
  packages/components/src/Divider/Divider.stories.mdx
  packages/components/src/Drawer/Drawer.stories.mdx
  packages/components/src/FeatureSwitch/FeatureSwitch.stories.mdx
  packages/components/src/Form/Form.stories.mdx
  packages/components/src/FormatDate/FormatDate.stories.mdx
  packages/components/src/FormatFile/FormatFile.stories.mdx
  packages/components/src/Heading/Heading.stories.mdx
  packages/components/src/Icon/Icon.stories.mdx
  packages/components/src/InlineLabel/InlineLabel.stories.mdx
  packages/components/src/InputAvatar/InputAvatar.stories.mdx
  packages/components/src/InputDate/InputDate.stories.mdx
  packages/components/src/InputGroup/InputGroup.stories.mdx
  packages/components/src/InputNumber/InputNumber.stories.mdx
  packages/components/src/InputPassword/InputPassword.stories.mdx
  packages/components/src/InputText/InputText.stories.mdx
  packages/components/src/InputValidation/InputValidation.stories.mdx
  packages/components/src/Menu/Menu.stories.mdx
  packages/components/src/Popover/Popover.stories.mdx
  packages/components/src/RecurringSelect/RecurringSelect.stories.mdx
  packages/components/src/Spinner/Spinner.stories.mdx
  packages/components/src/StatusLabel/StatusLabel.stories.mdx
  packages/components/src/Table/Table.stories.mdx
  packages/components/src/Tabs/Tabs.stories.mdx
  packages/components/src/Toast/Toast.stories.mdx
  packages/components/src/Tooltip/Tooltip.stories.mdx
  packages/design/src/Borders.stories.mdx
  packages/design/src/Colors.stories.mdx
  packages/design/src/Elevations.stories.mdx
  packages/design/src/Radii.stories.mdx
  packages/design/src/ResponsiveBreakpoint.stories.mdx
  packages/design/src/Spacing.stories.mdx
  packages/design/src/Typography.stories.mdx
  packages/hooks/src/useFormState/useFormState.stories.mdx
Labels: approved, Team Atlantis

#1060 docs(components): Improve Atlantis branding on Storybook
  .gitignore
  .storybook/assets/css/preview.css
  .storybook/components/DocsWithSidebar/DocsWithSidebar.css
  .storybook/components/Header/Header.tsx
  .storybook/components/Header/index.ts
  .storybook/components/InlineCode/InlineCode.tsx
  .storybook/components/InlineCode/index.ts
  .storybook/components/TableOfContents/TableOfContents.tsx
  .storybook/main.ts
  .storybook/preview.ts
  .storybook/preview.tsx
  docs/introduction/readme.stories.mdx
Labels: approved, design approved, Team Atlantis

#1077 docs(components): Add LightBox storybook page
  packages/components/src/LightBox/LightBox.stories.mdx
Labels: approved, Team Atlantis

#1084 docs: add table styling + bring back content guides for button
  .storybook/assets/css/preview.css
  packages/components/src/Button/Button.stories.mdx
Labels: approved, Team Atlantis
