Repository GetJobber/atlantis, pull requests merged in 2023-05, with the labels that each got.

#1217 chore(hooks): Check if dropping hooks dev dependency version works [JOB-67899]
  package-lock.json
  packages/hooks/package.json
Labels: approved, Team Atlantis

#1201 build: Enable the use of npm pack
  docs/README.md
  package.json
  packages/components/package.json
  packages/hooks/package.json
Labels: approved, Team Atlantis

#1218 feat: Create package for mobile components
  .eslintrc.js
  package-lock.json
  package.json
  packages/components-native/LICENSE
  packages/components-native/README.md
  packages/components-native/babel.config.js
  packages/components-native/package.json
  packages/components-native/src/Divider/Divider.style.ts
  packages/components-native/src/Divider/Divider.tsx
  packages/components-native/src/Divider/index.ts
  packages/components-native/src/Icon/Icon.tsx
  packages/components-native/src/Icon/index.ts
  packages/components-native/src/index.ts
  packages/components-native/tsconfig.json
Labels: approved, Team Atlantis

#1223 fix: Ensure form fields positioned children are contained
  packages/components/src/FormField/FormField.css
  packages/design/src/elevations.css
Labels: approved, Team Atlantis, Team Quotemeal

#1224 feat(components): Add validations to InputPhoneNumber
  packages/components/src/InputPhoneNumber/InputPhoneNumber.test.tsx
  packages/components/src/InputPhoneNumber/InputPhoneNumber.tsx
Labels: review requested, Team Atlantis

#1225 fix(components): fix the styling of DescriptionList component
  packages/components/src/DescriptionList/DescriptionList.css
Labels: Team Atlantis

#1226 feat(components): Expose pattern prop in InputPhoneNumber
  packages/components/src/InputPhoneNumber/InputPhoneNumber.stories.mdx
  packages/components/src/InputPhoneNumber/InputPhoneNumber.test.tsx
  packages/components/src/InputPhoneNumber/InputPhoneNumber.tsx
Labels: approved

#1227 build: Clear rollup cache when running lerna:clean
  package.json
Labels: approved, Team Atlantis

#1232 chore: Tag atlantis team on any PR
  .github/CODEOWNERS
Labels: approved, Team Atlantis

#1220 fix(components): fix autocomplete menu positioning when used in modal
  packages/components/src/Autocomplete/Autocomplete.test.tsx
  packages/components/src/Autocomplete/Autocomplete.tsx
  packages/components/src/Autocomplete/Menu.tsx
Labels: review requested, approved, Team Atlantis

#1230 docs: Update design tokens in Storybook to highlight mobile uses
  packages/components/src/Button/Button.css
  packages/components/src/Content/Content.stories.mdx
  packages/design/src/Animation.stories.mdx
  packages/design/src/Elevations.stories.mdx
  packages/design/src/Opacity.stories.mdx
  packages/design/src/Typography.stories.mdx
Labels: approved, Team Atlantis

#1237 chore: Add components-native to the allow PR titles
  .github/pull_request_template.md
  .github/workflows/pr-title-checker.yml
Labels: approved, Team Atlantis

#1239 docs: Allow react-native components to run in Storybook Web
  .storybook/main.js
  package-lock.json
  package.json
  packages/components/src/Divider/Divider.stories.mdx
Labels: approved, Team Atlantis

#1229 feat: Grid component
  packages/components/rollup.config.js
  packages/components/src/Grid/Grid.css
  packages/components/src/Grid/Grid.css.d.ts
  packages/components/src/Grid/Grid.stories.mdx
  packages/components/src/Grid/Grid.test.tsx
  packages/components/src/Grid/Grid.tsx
  packages/components/src/Grid/GridAlign.css
  packages/components/src/Grid/GridAlign.css.d.ts
  packages/components/src/Grid/GridCell/GridCell.css
  packages/components/src/Grid/GridCell/GridCell.css.d.ts
  packages/components/src/Grid/GridCell/GridCell.test.tsx
  packages/components/src/Grid/GridCell/GridCell.tsx
  packages/components/src/Grid/GridCell/index.ts
  packages/components/src/Grid/index.ts
  packages/design/src/ResponsiveBreakpoint.stories.mdx
  packages/design/src/responsiveBreakpoints.css
Labels: approved, Team Atlantis

#1245 fix(components): fix phone number validation for when it's not required
  packages/components/src/InputPhoneNumber/InputPhoneNumber.tsx
Labels: approved, Team Atlantis

#1242 docs: Remove the need for example with hooks
  .storybook/components/CustomCanvas/CustomCanvas.tsx
  .storybook/components/CustomCanvas/index.ts
  .storybook/components/ExampleWithHooks/ExampleWithHooks.tsx
  .storybook/components/ExampleWithHooks/index.ts
  .storybook/preview.tsx
  docs/getting-started-with-react/getting-started-with-react.stories.mdx
  packages/components/src/Autocomplete/Autocomplete.stories.mdx
  packages/components/src/Avatar/Avatar.stories.mdx
  packages/components/src/Checkbox/Checkbox.stories.mdx
  packages/components/src/Chips/Chips.stories.mdx
  packages/components/src/ConfirmationModal/ConfirmationModal.stories.mdx
  packages/components/src/Countdown/Countdown.stories.mdx
  packages/components/src/DataTable/DataTable.stories.mdx
  packages/components/src/DatePicker/DatePicker.stories.mdx
  packages/components/src/Form/Form.stories.mdx
  packages/components/src/FormatDate/FormatDate.stories.mdx
  packages/components/src/InputDate/InputDate.stories.mdx
  packages/components/src/InputGroup/InputGroup.stories.mdx
  packages/components/src/InputNumber/InputNumber.stories.mdx
  packages/components/src/InputPassword/InputPassword.stories.mdx
  packages/components/src/InputPhoneNumber/InputPhoneNumber.stories.mdx
  packages/components/src/InputText/InputText.stories.mdx
  packages/components/src/InputTime/InputTime.stories.mdx
  packages/components/src/LightBox/LightBox.stories.mdx
  packages/components/src/Modal/Modal.stories.mdx
  packages/components/src/MultiSelect/MultiSelect.stories.mdx
  packages/components/src/Popover/Popover.stories.mdx
  packages/components/src/ProgressBar/ProgressBar.stories.mdx
  packages/components/src/RadioGroup/RadioGroup.stories.mdx
  packages/components/src/RecurringSelect/RecurringSelect.stories.mdx
  packages/components/src/Switch/Switch.stories.mdx
  packages/hooks/src/useResizeObserver/useResizeObserver.stories.mdx
Labels: approved, Team Atlantis

#1241 fix(components): Fix Select component hit area
  packages/components/src/FormField/FormField.css
  packages/components/src/FormField/FormField.css.d.ts
  packages/components/src/FormField/FormFieldWrapper.tsx
  packages/components/src/Select/__snapshots__/Select.test.tsx.snap
Labels: approved, Team Atlantis

#1231 build: Support jest tests for components native
  .circleci/config.yml
  jest.config.js
  jest.web.config.js
  jestWebSetupConfig.js
  package-lock.json
  package.json
  packages/components-native/jest.config.js
  packages/components-native/jestMobileSetupConfig.js
  packages/components-native/package.json
  packages/components-native/src/Divider/Divider.test.tsx
  packages/components-native/src/Icon/Icon.test.tsx
  packages/components-native/src/Icon/__snapshots__/Icon.test.tsx.snap
Labels: approved, Team Atlantis

#1246 docs: update banner from updated design guidelines
  packages/components/src/Banner/Banner.stories.mdx
Labels: review requested, Team Atlantis

#1235 feat(components-native): Import Typography to components-native
  .eslintrc.js
  package-lock.json
  packages/components-native/package.json
  packages/components-native/src/Divider/Divider.style.ts
  packages/components-native/src/Typography/Typography.style.ts
  packages/components-native/src/Typography/Typography.tsx
  packages/components-native/src/Typography/TypographyGestureDetector.tsx
  packages/components-native/src/Typography/index.ts
  packages/components-native/src/index.ts
  packages/components-native/src/utils/design/index.ts
  packages/components-native/src/utils/intl/capitalize.ts
  packages/components-native/src/utils/intl/index.ts
Labels: approved, Team Atlantis

#1247 refactor(components-native): Add tests to components-native's Typography
  package-lock.json
  packages/components-native/jest.config.js
  packages/components-native/package.json
  packages/components-native/src/Typography/Typography.test.tsx
  packages/components-native/src/Typography/__snapshots__/Typography.test.tsx.snap
Labels: approved, Team Atlantis

#1248 feat(components-native): Import Text to components-native
  packages/components-native/src/Text/Text.test.tsx
  packages/components-native/src/Text/Text.tsx
  packages/components-native/src/Text/__snapshots__/Text.test.tsx.snap
  packages/components-native/src/Text/index.ts
  packages/components-native/src/index.ts
Labels: approved, Team Atlantis

#1243 docs: add updated language guidance from PMM updates
  docs/content/product-vocabulary.stories.mdx
Labels: approved, Team Atlantis

#1253 feat(components-native): Import ActivityIndicator to components-native
  packages/components-native/src/ActivityIndicator/ActivityIndicator.test.tsx
  packages/components-native/src/ActivityIndicator/ActivityIndicator.tsx
  packages/components-native/src/ActivityIndicator/index.ts
  packages/components-native/src/index.ts
Labels: approved, Team Atlantis

#1252 feat(components-native): Import Content to components-native
  package-lock.json
  packages/components-native/package.json
  packages/components-native/src/Content/Content.test.tsx
  packages/components-native/src/Content/Content.tsx
  packages/components-native/src/Content/ContentHorizontal.style.ts
  packages/components-native/src/Content/ContentSpaceAround.style.ts
  packages/components-native/src/Content/ContentVertical.style.ts
  packages/components-native/src/Content/index.ts
  packages/components-native/src/index.ts
Labels: approved, Team Atlantis

#1250 feat(components-native): Import ActionLabel to components-native
  packages/components-native/src/ActionLabel/ActionLabel.test.tsx
  packages/components-native/src/ActionLabel/ActionLabel.tsx
  packages/components-native/src/ActionLabel/index.ts
  packages/components-native/src/index.ts
Labels: approved, Team Atlantis

#1251 feat(components-native): Import ErrorMessageWrapper to components-native
  package-lock.json
  packages/components-native/package.json
  packages/components-native/src/ErrorMessageWrapper/ErrorMessageWrapper.style.ts
  packages/components-native/src/ErrorMessageWrapper/ErrorMessageWrapper.test.tsx
  packages/components-native/src/ErrorMessageWrapper/ErrorMessageWrapper.tsx
  packages/components-native/src/ErrorMessageWrapper/context/ErrorMessageContext.tsx
  packages/components-native/src/ErrorMessageWrapper/context/ErrorMessageProvider.tsx
  packages/components-native/src/ErrorMessageWrapper/context/index.ts
  packages/components-native/src/ErrorMessageWrapper/context/types.ts
  packages/components-native/src/ErrorMessageWrapper/index.ts
  packages/components-native/src/index.ts
  tsconfig.base.json
Labels: approved, Team Atlantis

#1258 feat(components-native): Import AtlantisContext
  package-lock.json
  packages/components-native/jest.config.js
  packages/components-native/jestNativeSetup.ts
  packages/components-native/package.json
  packages/components-native/src/AtlantisContext/AtlantisContext.test.tsx
  packages/components-native/src/AtlantisContext/AtlantisContext.tsx
  packages/components-native/src/AtlantisContext/index.ts
  packages/components-native/src/__mocks__/__mocks.ts
  packages/components-native/src/index.ts
Labels: approved, Team Atlantis

#1257 feat(components-native): Import StatusLabel to components-native
  packages/components-native/src/StatusLabel/StatusLabel.style.ts
  packages/components-native/src/StatusLabel/StatusLabel.test.tsx
  packages/components-native/src/StatusLabel/StatusLabel.tsx
  packages/components-native/src/StatusLabel/__snapshots__/StatusLabel.test.tsx.snap
  packages/components-native/src/StatusLabel/index.ts
  packages/components-native/src/index.ts
Labels: approved, Team Atlantis

#1255 feat(components-native): Make react native components fonts render on Storybook
  packages/components-native/src/Typography/Typography.style.ts
  packages/components-native/src/Typography/webFonts.ts
Labels: approved, Team Atlantis

#1256 feat(components-native): Import Card to components-native
  packages/components-native/src/Card/Card.style.ts
  packages/components-native/src/Card/Card.test.tsx
  packages/components-native/src/Card/Card.tsx
  packages/components-native/src/Card/components/InternalCardHeader.style.ts
  packages/components-native/src/Card/components/InternalCardHeader.test.tsx
  packages/components-native/src/Card/components/InternalCardHeader.tsx
  packages/components-native/src/Card/components/index.ts
  packages/components-native/src/Card/index.ts
  packages/components-native/src/index.ts
Labels: approved, Team Atlantis

#1254 feat(components): Allow GridCell' s to only be usable in Grids
  packages/components/src/Grid/Grid.tsx
  packages/components/src/Grid/GridCell.test.tsx
  packages/components/src/Grid/GridCell.tsx
  packages/components/src/Grid/GridCell/index.ts
  packages/components/src/Grid/InternalGridCell/InternalGridCell.css
  packages/components/src/Grid/InternalGridCell/InternalGridCell.css.d.ts
  packages/components/src/Grid/InternalGridCell/InternalGridCell.test.tsx
  packages/components/src/Grid/InternalGridCell/InternalGridCell.tsx
  packages/components/src/Grid/InternalGridCell/index.ts
Labels: approved, Team Atlantis

#1263 feat(components-native): Import Button
  package-lock.json
  packages/components-native/package.json
  packages/components-native/src/Button/Button.style.ts
  packages/components-native/src/Button/Button.test.tsx
  packages/components-native/src/Button/Button.tsx
  packages/components-native/src/Button/components/InternalButtonLoading/InternalButtonLoading.style.ts
  packages/components-native/src/Button/components/InternalButtonLoading/InternalButtonLoading.test.tsx
  packages/components-native/src/Button/components/InternalButtonLoading/InternalButtonLoading.tsx
  packages/components-native/src/Button/components/InternalButtonLoading/index.ts
  packages/components-native/src/Button/index.ts
  packages/components-native/src/Button/types.ts
  packages/components-native/src/__mocks__/__mocks.ts
  packages/components-native/src/index.ts
Labels: approved, Team Atlantis

#1264 feat(components-native): Import Heading to components-native
  packages/components-native/src/Heading/Heading.test.tsx
  packages/components-native/src/Heading/Heading.tsx
  packages/components-native/src/Heading/__snapshots__/Heading.test.tsx.snap
  packages/components-native/src/Heading/index.ts
  packages/components-native/src/index.ts
Labels: approved, Team Atlantis

#1265 feat(components-native): Import Chip to components-native
  packages/components-native/src/Chip/Chip.style.ts
  packages/components-native/src/Chip/Chip.test.tsx
  packages/components-native/src/Chip/Chip.tsx
  packages/components-native/src/Chip/index.ts
  packages/components-native/src/index.ts
Labels: approved, Team Atlantis

#1267 fix(components-native): Fix Gesture handler storybook mock
  .storybook/__mocks__/react-native-gesture-handler.tsx
Labels: approved, Team Atlantis

#1266 feat(components-native): Import ProgressBar
  .storybook/components/SBProvider/SBProvider.tsx
  .storybook/components/SBProvider/index.ts
  .storybook/preview.tsx
  docs/components/Content/Mobile.stories.mdx
  docs/components/Content/Web.stories.mdx
  docs/components/Icon/Mobile.stories.mdx
  docs/components/ProgressBar/Mobile.stories.mdx
  docs/components/ProgressBar/ProgressBar.stories.mdx
  docs/components/ProgressBar/Web.stories.mdx
  packages/components-native/src/ProgressBar/ProgressBar.style.ts
  packages/components-native/src/ProgressBar/ProgressBar.test.tsx
  packages/components-native/src/ProgressBar/ProgressBar.tsx
  packages/components-native/src/ProgressBar/ProgressBarInner.tsx
  packages/components-native/src/ProgressBar/__snapshots__/ProgressBar.test.tsx.snap
  packages/components-native/src/ProgressBar/index.tsx
  packages/components-native/src/ProgressBar/messages.ts
  packages/components-native/src/ProgressBar/types.ts
  packages/components-native/src/index.ts
Labels: approved, Team Atlantis

#1268 docs(components-native): Add Text storybook documentation
  docs/components/Text/Mobile.stories.mdx
  docs/components/Text/Text.stories.mdx
  docs/components/Text/Web.stories.mdx
Labels: approved, Team Atlantis

#1272 docs(components): Cleanup unused vars in stories
  docs/components/Content/Content.stories.mdx
  docs/components/Content/Mobile.stories.mdx
Labels: approved, Team Atlantis

#1271 docs(components-native): Add ActivityIndicator storybook
  docs/components/ActivityIndicator/ActivityIndicator.stories.mdx
  docs/components/ActivityIndicator/Mobile.stories.mdx
Labels: approved, Team Atlantis

#1262 feat(components-native): Import ActionItem
  packages/components-native/jestMobileSetupConfig.js
  packages/components-native/src/ActionItem/ActionItem.style.ts
  packages/components-native/src/ActionItem/ActionItem.test.tsx
  packages/components-native/src/ActionItem/ActionItem.tsx
  packages/components-native/src/ActionItem/ActionItemGroup.test.tsx
  packages/components-native/src/ActionItem/ActionItemGroup.tsx
  packages/components-native/src/ActionItem/components/ActionItemContainer.style.ts
  packages/components-native/src/ActionItem/components/ActionItemContainer.test.tsx
  packages/components-native/src/ActionItem/components/ActionItemContainer.tsx
  packages/components-native/src/ActionItem/index.ts
  packages/components-native/src/Button/Button.tsx
  packages/components-native/src/Card/Card.tsx
  packages/components-native/src/Card/index.ts
  packages/components-native/src/index.ts
Labels: approved, Team Atlantis

#1259 refactor: Replace deprecated breakpoint usage with new breakpoints
  .storybook/components/DocsWithSidebar/DocsWithSidebar.css
  packages/components/src/DataTable/Pagination.css
  packages/components/src/Drawer/Drawer.css
  packages/components/src/Drawer/Drawer.tsx
  packages/components/src/Grid/InternalGridCell/InternalGridCell.css
  packages/components/src/Menu/Menu.css
  packages/components/src/Modal/Modal.css
  packages/design/src/responsiveBreakpoints.css
Labels: approved, Team Atlantis

#1275 chore: Skip flaky Date test
  packages/components/src/FormatRelativeDateTime/FormatRelativeDateTime.test.tsx
Labels: approved, Team Atlantis

#1270 docs(components-native): Add Mobile ActionLabel docs
  .storybook/components/SBProvider/SBProvider.tsx
  docs/components/ActionLabel/ActionLabel.stories.mdx
  docs/components/ActionLabel/Mobile.stories.mdx
  package-lock.json
  package.json
Labels: approved, Team Atlantis

#1278 feat(components-native): Import IconButton to components-native
  packages/components-native/src/IconButton/IconButton.style.ts
  packages/components-native/src/IconButton/IconButton.test.tsx
  packages/components-native/src/IconButton/IconButton.tsx
  packages/components-native/src/IconButton/index.ts
  packages/components-native/src/index.ts
Labels: approved, Team Atlantis

#1277 feat(components-native): Import Flex (before it was Grid) to components-native
  package-lock.json
  packages/components-native/package.json
  packages/components-native/src/Flex/Flex.styles.tsx
  packages/components-native/src/Flex/Flex.test.tsx
  packages/components-native/src/Flex/Flex.tsx
  packages/components-native/src/Flex/index.ts
  packages/components-native/src/Flex/types.ts
  packages/components-native/src/index.ts
Labels: approved, Team Atlantis

#1280 feat(design): change colour code for brand--highlight
  packages/components-native/src/Heading/__snapshots__/Heading.test.tsx.snap
  packages/components-native/src/StatusLabel/__snapshots__/StatusLabel.test.tsx.snap
  packages/components-native/src/Text/__snapshots__/Text.test.tsx.snap
  packages/components-native/src/Typography/__snapshots__/Typography.test.tsx.snap
  packages/design/src/colors.css
Labels: approved, Team Atlantis

#1276 build: Upgrade react-hook-form to v7.43.7 [JOB-65817]
  package-lock.json
  packages/components/package.json
  packages/components/src/Form/Form.test.tsx
  packages/components/src/Form/Form.tsx
  packages/components/src/FormField/FormField.test.tsx
  packages/components/src/FormField/FormField.tsx
  packages/components/src/InputNumber/InputNumber.test.tsx
  packages/components/src/InputPhoneNumber/InputPhoneNumber.tsx
  packages/hooks/src/useFormState/useFormState.ts
Labels: approved, Team Atlantis

#1281 feat(components-native): Import InputPressable to components-native
  packages/components-native/src/InputPressable/InputPressable.style.ts
  packages/components-native/src/InputPressable/InputPressable.test.tsx
  packages/components-native/src/InputPressable/InputPressable.tsx
  packages/components-native/src/InputPressable/index.ts
  packages/components-native/src/index.ts
Labels: approved, Team Atlantis

#1283 feat(design)!: rename `JobberStyle` to `tokens` BREAKING CHANGE
  .storybook/theme.ts
  packages/components-native/src/Flex/Flex.test.tsx
  packages/components-native/src/utils/design/index.ts
  packages/design/README.mdx
  packages/design/package.json
  packages/design/resolveFoundationTokens.js
  packages/design/src/Typography.stories.mdx
  packages/design/src/getMobileShadows.js
Labels: approved, Team Atlantis

#1288 fix: use tokens instead of JobberStyle on InputPressable
  packages/components-native/src/InputPressable/InputPressable.style.ts
Labels: approved, Team Atlantis

#1289 fix: enable prefix and suffix on InputNumber
  packages/components/src/InputNumber/InputNumber.tsx
Labels: approved, Team Atlantis

#1286 feat(components-native): Import EmptyState to components-native
  packages/components-native/src/EmptyState/EmptyState.style.ts
  packages/components-native/src/EmptyState/EmptyState.test.tsx
  packages/components-native/src/EmptyState/EmptyState.tsx
  packages/components-native/src/EmptyState/index.ts
  packages/components-native/src/index.ts
Labels: approved, Team Atlantis

#1285 fix(design)!: Adjust breakpoints BREAKING CHANGE
  packages/design/src/ResponsiveBreakpoint.stories.mdx
  packages/design/src/responsiveBreakpoints.css
Labels: approved, Team Atlantis

#1287 fix(components): adjust grid and page spacing
  packages/components/src/Grid/Grid.css
  packages/components/src/Page/Page.css
Labels: approved, Team Atlantis

#1279 feat(components-native): Import InputText to components-native
  package-lock.json
  package.json
  packages/components-native/package.json
  packages/components-native/src/InputText/InputText.style.ts
  packages/components-native/src/InputText/InputText.test.tsx
  packages/components-native/src/InputText/InputText.tsx
  packages/components-native/src/InputText/context/InputAccessoriesContext.ts
  packages/components-native/src/InputText/context/InputAccessoriesProvider.style.tsx
  packages/components-native/src/InputText/context/InputAccessoriesProvider.test.tsx
  packages/components-native/src/InputText/context/InputAccessoriesProvider.tsx
  packages/components-native/src/InputText/context/InputAccessory.style.ts
  packages/components-native/src/InputText/context/index.ts
  packages/components-native/src/InputText/context/types.ts
  packages/components-native/src/InputText/index.ts
  packages/components-native/src/hooks/index.ts
  packages/components-native/src/hooks/useFormController.ts
  packages/components-native/src/index.ts
Labels: approved, Team Atlantis

#1295 feat(components-native): Import Switch to components-native
  packages/components-native/src/Switch/Switch.styles.ts
  packages/components-native/src/Switch/Switch.test.tsx
  packages/components-native/src/Switch/Switch.tsx
  packages/components-native/src/Switch/components/BaseSwitch/BaseSwitch.test.tsx
  packages/components-native/src/Switch/components/BaseSwitch/BaseSwitch.tsx
  packages/components-native/src/Switch/components/BaseSwitch/__snapshots__/BaseSwitch.test.tsx.snap
  packages/components-native/src/Switch/components/BaseSwitch/index.ts
  packages/components-native/src/Switch/index.ts
  packages/components-native/src/index.ts
Labels: approved, Team Atlantis

#1296 feat(components): Add Controller to Checkbox
  packages/components/src/Checkbox/Checkbox.tsx
  packages/components/src/Checkbox/__snapshots__/Checkbox.test.tsx.snap
Labels: approved, Team Atlantis
