Repository GetJobber/atlantis, pull requests merged in 2023-08, with the labels that each got.

#1461 docs(components): Update ButtonDismiss docs
  docs/components/ButtonDismiss/ButtonDismiss.stories.mdx
  docs/components/ButtonDismiss/Web.stories.tsx
  packages/components/src/ButtonDismiss/ButtonDismiss.stories.mdx
Labels: approved, Team Atlantis

#1456 docs(components): Update Countdown docs
  docs/components/Countdown/Countdown.stories.mdx
  docs/components/Countdown/Web.stories.tsx
  packages/components/src/Countdown/Countdown.stories.mdx
Labels: approved, Team Atlantis

#1452 docs: Update Link docs
  docs/components/Link/Link.stories.mdx
  docs/components/Link/Web.stories.tsx
  packages/components/src/Link/Link.stories.mdx
Labels: approved, Team Atlantis

#1453 docs(components): Update Heading docs
  docs/components/Heading/Heading.stories.mdx
  docs/components/Heading/Mobile.stories.tsx
  docs/components/Heading/Web.stories.tsx
  docs/components/Typography/Typography.stories.mdx
  docs/guides/create-basic-component.stories.mdx
  packages/components/src/FormatDate/FormatDate.stories.mdx
  packages/components/src/Heading/Heading.stories.mdx
  packages/design/src/Typography.stories.mdx
Labels: approved, Team Atlantis

#1442 fix: update FormatTime logic for 12 or 24 hours
  packages/components/src/FormatTime/FormatTime.stories.mdx
  packages/components/src/FormatTime/FormatTime.test.tsx
  packages/components/src/FormatTime/FormatTime.tsx
  packages/components/src/FormatTime/__snapshots__/FormatTime.test.tsx.snap
Labels: approved, Team Atlantis

#1462 docs(components): Update FormatRelativeDateTime docs
  docs/components/Datepicker/Datepicker.stories.mdx
  docs/components/FormatRelativeDateTime/FormatRelativeDateTime.stories.mdx
  docs/components/FormatRelativeDateTime/Web.stories.tsx
  packages/components/src/FormatRelativeDateTime/FormatRelativeDateTime.stories.mdx
Labels: approved, Team Atlantis

#1463 docs: Update InputFieldWrapper docs
  docs/components/InputFieldWrapper/InputFieldWrapper.stories.mdx
  docs/components/InputFieldWrapper/Mobile.stories.tsx
Labels: approved, Team Atlantis

#1457 docs(components): Update DataDump docs
  docs/components/DataDump/DataDump.stories.mdx
  docs/components/DataDump/Web.stories.tsx
  packages/components/src/DataDump/DataDump.stories.mdx
Labels: approved, Team Atlantis

#1458 docs(components): Update FormatDate docs
  docs/components/Datepicker/Datepicker.stories.mdx
  docs/components/FormatDate/FormatDate.stories.mdx
  docs/components/FormatDate/Web.stories.tsx
Labels: approved, Team Atlantis

#1464 docs(components): Update FormField docs
  docs/components/FormField/FormField.stories.mdx
  docs/components/FormField/Mobile.stories.tsx
  docs/components/FormField/Web.stories.tsx
  packages/components/src/FormField/FormField.stories.mdx
Labels: approved, Team Atlantis

#1465 feat(components): InputText Props for Autocomplete
  packages/components/src/Autocomplete/Autocomplete.tsx
Labels: approved, Team Atlantis

#1468 fix: chips code sandbox
  .storybook/components/Playground/Playground.tsx
  docs/components/Chips/Web.stories.tsx
  docs/components/Chips/utils/storyUtils.ts
Labels: approved, Team Atlantis

#1400 docs(components): Move InputEmail folder to docs/components
  docs/components/InputEmail/InputEmail.stories.mdx
  docs/components/InputEmail/Web.stories.tsx
Labels: approved, Team Atlantis

#1470 docs: code sandbox not rendering on browser refresh
  .storybook/manager.js
Labels: approved, Team Atlantis

#1469 fix(components): add ref to Autocomplete component
  packages/components/src/Autocomplete/Autocomplete.test.tsx
  packages/components/src/Autocomplete/Autocomplete.tsx
  packages/components/src/InputText/InputText.test.tsx
  packages/components/src/InputText/InputText.tsx
Labels: approved, Team Atlantis

#1475 fix(components): Only render the label element if a placeholder value has been provided
  packages/components/src/FormField/FormFieldWrapper.tsx
  packages/components/src/FormField/__snapshots__/FormField.test.tsx.snap
  packages/components/src/InputNumber/InputNumber.test.tsx
  packages/components/src/InputPassword/__snapshots__/InputPassword.test.tsx.snap
  packages/components/src/InputTime/InputTime.test.tsx
  packages/components/src/Select/__snapshots__/Select.test.tsx.snap
Labels: approved, Team Atlantis

#1467 fix(components): Fix input group spacing issues
  packages/components/src/Autocomplete/__snapshots__/Autocomplete.test.tsx.snap
  packages/components/src/FormField/FormField.css
  packages/components/src/FormField/FormField.css.d.ts
  packages/components/src/FormField/FormFieldWrapper.tsx
  packages/components/src/FormField/__snapshots__/FormField.test.tsx.snap
  packages/components/src/InputGroup/InputGroup.css
  packages/components/src/InputNumber/InputNumber.test.tsx
  packages/components/src/InputPassword/__snapshots__/InputPassword.test.tsx.snap
  packages/components/src/InputText/InputText.test.tsx
  packages/components/src/InputTime/InputTime.test.tsx
  packages/components/src/Select/__snapshots__/Select.test.tsx.snap
Labels: approved, Team Atlantis

#1474 build(components-native): JOB-75931 - Update Components Native instructions to fix tests
  package-lock.json
  package.json
  packages/components-native/README.md
  packages/components-native/jestSetup.js
  packages/components-native/package.json
  packages/components-native/src/Form/components/FormActionBar/FormActionBar.tsx
  packages/components-native/src/Form/hooks/useScrollToError/useScrollToError.ts
Labels: approved, Team Atlantis

#1479 docs: Added upcoming breaking changes to changelogs
  docs/changelog/breaking-changes.stories.mdx
Labels: approved, Team Atlantis

#1480 fix(components): Fix snapshot tests that weren't updated.
  packages/components/src/FormField/__snapshots__/FormField.test.tsx.snap
  packages/components/src/InputNumber/InputNumber.test.tsx
  packages/components/src/InputPassword/__snapshots__/InputPassword.test.tsx.snap
  packages/components/src/InputTime/InputTime.test.tsx
  packages/components/src/Select/__snapshots__/Select.test.tsx.snap
Labels: approved, Team Atlantis

#1477 fix(components): Prevent Open on DatePicker Focus
  packages/components/src/DatePicker/DatePicker.tsx
  packages/components/src/InputDate/InputDate.test.tsx
  packages/components/src/InputDate/InputDate.tsx
Labels: approved, Team Atlantis

#1471 feat(components): Permit using children on RadioOption with label
  docs/components/RadioGroup/RadioGroup.stories.mdx
  docs/components/RadioGroup/Web.stories.tsx
  packages/components/src/RadioGroup/RadioGroup.css
  packages/components/src/RadioGroup/RadioGroup.css.d.ts
  packages/components/src/RadioGroup/RadioGroup.test.tsx
  packages/components/src/RadioGroup/RadioOption.tsx
Labels: approved, Team Atlantis, Team SC First Touch

#1478 build(components-native): Forbid html elements in components-native
  .eslintrc.js
  docs/components/Divider/Mobile.stories.tsx
  docs/components/FormatFile/Mobile.stories.tsx
  docs/components/Toast/Mobile.stories.tsx
Labels: approved, Team Atlantis

#1482 docs: fix custom radio option code tab
  docs/components/RadioGroup/Web.stories.tsx
Labels: approved, Team Atlantis

#1481 fix(components): Prevent Closing Parent on DatePicker ESC
  packages/components/src/DatePicker/DatePicker.test.tsx
  packages/components/src/DatePicker/DatePicker.tsx
  packages/components/src/InputDate/InputDate.test.tsx
Labels: approved, Team Atlantis

#1473 feat(components-native): Add Icon prop to Banner
  docs/changelog/breaking-changes.stories.mdx
  docs/components/Banner/Banner.stories.mdx
  docs/components/Banner/Mobile.stories.tsx
  docs/components/Banner/Web.stories.tsx
  packages/components-native/src/Banner/Banner.style.ts
  packages/components-native/src/Banner/Banner.tsx
  packages/components-native/src/Banner/components/BannerIcon/BannerIcon.tsx
  packages/components-native/src/Banner/types.ts
  packages/components/.eslintrc.js
  packages/components/src/Banner/Banner.css
  packages/components/src/Banner/Banner.tsx
  packages/components/src/Banner/components/BannerIcon/BannerIcon.tsx
  packages/components/src/Banner/components/BannerIcon/index.ts
Labels: approved, Team Atlantis

#1483 docs(generators): Update docs for generators usage
  docs/CONTRIBUTING.md
  docs/README.md
  docs/guides/create-basic-component.stories.mdx
Labels: approved, Team Atlantis

#1485 fix(components): Fix broken links for popover docs
  docs/components/Popover/Popover.stories.mdx
Labels: approved, Team Atlantis

#1487 chore: create DataList shell component
  packages/components/src/DataList/DataList.css
  packages/components/src/DataList/DataList.css.d.ts
  packages/components/src/DataList/DataList.stories.tsx
  packages/components/src/DataList/DataList.tsx
Labels: approved, Team Atlantis

#1490 chore(components): JOB-75738 Added Empty State for DataList
  packages/components/src/DataList/DataList.stories.tsx
  packages/components/src/DataList/DataList.test.tsx
  packages/components/src/DataList/DataList.tsx
  packages/components/src/DataList/components/EmptyState/EmptyState.css
  packages/components/src/DataList/components/EmptyState/EmptyState.css.d.ts
  packages/components/src/DataList/components/EmptyState/EmptyState.test.tsx
  packages/components/src/DataList/components/EmptyState/EmptyState.tsx
  packages/components/src/DataList/components/EmptyState/index.ts
Labels: approved, Team Atlantis

#1491 chore(components-native): Remove datalist story
  packages/components/src/DataList/DataList.stories.tsx
Labels: approved, Team Atlantis

#1492 chore(components): make the data list list part happen
  packages/components/src/DataList/DataList.const.ts
  packages/components/src/DataList/DataList.css
  packages/components/src/DataList/DataList.css.d.ts
  packages/components/src/DataList/DataList.stories.tsx
  packages/components/src/DataList/DataList.test.tsx
  packages/components/src/DataList/DataList.tsx
  packages/components/src/DataList/DataList.types.ts
  packages/components/src/DataList/DataList.utils.tsx
  packages/components/src/DataList/components/DataListLayout/DataListLayout.tsx
  packages/components/src/DataList/components/DataListLayout/index.ts
  packages/components/src/DataList/storyUtils.ts
Labels: approved, Team Atlantis

#1493 chore(components): add some data list test
  packages/components/src/DataList/DataList.css
  packages/components/src/DataList/DataList.test.tsx
  packages/components/src/DataList/DataList.utils.tsx
  packages/components/src/DataList/__tests__/DataList.utils.test.tsx
Labels: approved, Team Atlantis

#1488 chore(components): Add counter and title to DataList
  packages/components/src/DataList/DataList.css
  packages/components/src/DataList/DataList.css.d.ts
  packages/components/src/DataList/DataList.stories.tsx
  packages/components/src/DataList/DataList.test.tsx
  packages/components/src/DataList/DataList.tsx
  packages/components/src/DataList/DataList.types.ts
  packages/components/src/DataList/components/DataListTotalCount/DataListTotalCount.css
  packages/components/src/DataList/components/DataListTotalCount/DataListTotalCount.css.d.ts
  packages/components/src/DataList/components/DataListTotalCount/DataListTotalCount.test.tsx
  packages/components/src/DataList/components/DataListTotalCount/DataListTotalCount.tsx
  packages/components/src/DataList/components/DataListTotalCount/index.ts
  packages/components/src/DataList/storyUtils.ts
Labels: approved, Team Atlantis

#1489 chore(components-native): Bring latest changes of Atlantis components from jobber-mobile
  packages/components-native/src/ContentOverlay/ContentOverlay.style.ts
Labels: review requested, Team Atlantis

#1495 chore(components): add data list tags pattern
  package-lock.json
  packages/components/package.json
  packages/components/src/DataList/DataList.css
  packages/components/src/DataList/DataList.stories.tsx
  packages/components/src/DataList/DataList.utils.tsx
  packages/components/src/DataList/__tests__/DataList.utils.test.tsx
  packages/components/src/DataList/components/DataListTags/DataListTags.css
  packages/components/src/DataList/components/DataListTags/DataListTags.css.d.ts
  packages/components/src/DataList/components/DataListTags/DataListTags.test.tsx
  packages/components/src/DataList/components/DataListTags/DataListTags.tsx
  packages/components/src/DataList/components/DataListTags/index.ts
Labels: approved, Team Atlantis

#1496 chore(components): better keys for data list items
  packages/components/src/DataList/DataList.stories.tsx
  packages/components/src/DataList/DataList.test.tsx
  packages/components/src/DataList/DataList.tsx
  packages/components/src/DataList/DataList.types.ts
  packages/components/src/DataList/DataList.utils.tsx
  packages/components/src/DataList/__tests__/DataList.utils.test.tsx
Labels: approved, Team Atlantis

#1497 chore(components): JOB-75752 DataList responsivenes
  packages/components/src/DataList/DataList.const.ts
  packages/components/src/DataList/DataList.stories.tsx
  packages/components/src/DataList/DataList.test.tsx
  packages/components/src/DataList/DataList.tsx
  packages/components/src/DataList/DataList.types.ts
  packages/components/src/DataList/DataList.utils.tsx
  packages/components/src/DataList/__tests__/DataList.utils.test.tsx
  packages/components/src/DataList/components/DataListLayout/DataListLayout.tsx
  packages/components/src/DataList/components/DataListLayoutInternal/DataListHeader.tsx
  packages/components/src/DataList/components/DataListLayoutInternal/DataListItems.tsx
  packages/components/src/DataList/components/DataListLayoutInternal/DataListLayoutInternal.tsx
  packages/components/src/DataList/components/DataListLayoutInternal/index.ts
  packages/components/src/DataList/hooks/useLayoutMediaQueries.ts
Labels: approved, Team Atlantis

#1501 docs(components-native): Add ActionItem & ActionItemGroup documentation
  docs/components/ActionItem/ActionItem.stories.mdx
  docs/components/ActionItem/Mobile.stories.tsx
  docs/components/ActionItemGroup/ActionItemGroup.stories.mdx
  docs/components/ActionItemGroup/Mobile.stories.tsx
Labels: approved, Team Atlantis

#1498 chore(components): Add loading state to DataList
  packages/components/src/DataList/DataList.stories.tsx
  packages/components/src/DataList/DataList.test.tsx
  packages/components/src/DataList/DataList.tsx
  packages/components/src/DataList/components/DataListLayoutInternal/DataListLayoutInternal.tsx
  packages/components/src/DataList/components/DataListLayoutInternal/index.ts
  packages/components/src/DataList/components/DataListLoadingState/DataListLoadingState.css
  packages/components/src/DataList/components/DataListLoadingState/DataListLoadingState.css.d.ts
  packages/components/src/DataList/components/DataListLoadingState/DataListLoadingState.tsx
  packages/components/src/DataList/components/DataListLoadingState/index.ts
Labels: approved, Team Atlantis

#1508 refactor(components-native): Add setHeaderHeight to AtlantisContext
  packages/components-native/src/AtlantisContext/AtlantisContext.test.tsx
  packages/components-native/src/AtlantisContext/AtlantisContext.tsx
Labels: review requested, Team Atlantis

#1507 feat(components): expose data list to the masses
  .storybook/components/DocsWithSidebar/DocsWithSidebar.tsx
  .storybook/components/SidebarLabel/SidebarLabel.tsx
  .storybook/components/SidebarLabel/alphaComponents.ts
  docs/components/DataList/DataList.stories.mdx
  docs/components/DataList/Web.stories.tsx
  docs/components/DataList/storyUtils.ts
  packages/components/src/DataList/DataList.stories.tsx
  packages/components/src/DataList/DataList.utils.tsx
  packages/components/src/DataList/__tests__/DataList.utils.test.tsx
  packages/components/src/DataList/components/DataListLoadingState/DataListLoadingState.css
  packages/components/src/DataList/components/DataListLoadingState/DataListLoadingState.css.d.ts
  packages/components/src/DataList/components/DataListLoadingState/DataListLoadingState.tsx
  packages/components/src/DataList/components/EmptyState/EmptyState.css
  packages/components/src/DataList/components/EmptyState/EmptyState.tsx
  packages/components/src/DataList/index.ts
Labels: approved, Team Atlantis

#1505 fix: update autolink built in messages to be translateable
  packages/components-native/src/AutoLink/AutoLink.test.tsx
  packages/components-native/src/AutoLink/components/ComposeTextWithLinks/ComposeTextWithLinks.tsx
  packages/components-native/src/AutoLink/messages.ts
  packages/components-native/src/AutoLink/utils.ts
  packages/components-native/src/hooks/useAtlantisI18n/locales/en.json
  packages/components-native/src/hooks/useAtlantisI18n/locales/es.json
  packages/components-native/src/hooks/useAtlantisI18n/useAtlantisI18n.ts
Labels: approved, Team Atlantis

#1504 feat(components): localized date formatter
  packages/components-native/src/InputDate/InputDate.tsx
  packages/components-native/src/InputTime/InputTime.tsx
  packages/components-native/src/hooks/useAtlantisI18n/useAtlantisI18n.test.ts
  packages/components-native/src/hooks/useAtlantisI18n/useAtlantisI18n.ts
  packages/components-native/src/hooks/useAtlantisI18n/utils/dateFormatter.ts
Labels: approved, Team Atlantis

#1511 refactor(components-native): Refactor default values in to match the related context
  packages/components-native/src/AtlantisContext/AtlantisContext.test.tsx
  packages/components-native/src/AtlantisContext/AtlantisContext.tsx
  packages/components-native/src/ButtonGroup/ButtonGroup.test.tsx
  packages/components-native/src/Form/Form.test.tsx
  packages/components-native/src/Form/components/FormErrorBanner/FormErrorBanner.test.tsx
  packages/components-native/src/Form/context/AtlantisFormContext.test.tsx
  packages/components-native/src/Form/context/AtlantisFormContext.tsx
  packages/components-native/src/InputCurrency/InputCurrency.test.tsx
  packages/components-native/src/InputDate/InputDate.test.tsx
  packages/components-native/src/InputText/context/InputAccessoriesContext.ts
  packages/components-native/src/InputTime/InputTime.test.tsx
  packages/components-native/src/hooks/useAtlantisI18n/useAtlantisI18n.test.ts
Labels: approved, Team Atlantis
