Repository GetJobber/atlantis, pull requests merged in 2023-11, with the labels that each got.

#1622 chore(components): replace heading with label in comboobx test
  packages/components/src/Combobox/Combobox.test.tsx
Labels: approved, Team Atlantis

#1522 feat(design): Add Marketing Icon
  docs/components/Icon/Icon.stories.mdx
  packages/design/assets/icons/marketing.svg
Labels: approved, Team Atlantis

#1598 feat(hooks): Hook for managing boolean values
  packages/hooks/README.mdx
  packages/hooks/src/index.ts
  packages/hooks/src/useBool/index.ts
  packages/hooks/src/useBool/useBool.stories.mdx
  packages/hooks/src/useBool/useBool.test.ts
  packages/hooks/src/useBool/useBool.ts
Labels: approved, Team Atlantis

#1627 fix(components): Fix Chip gradient on Safari
  packages/components/src/Chip/Chip.css
  packages/components/src/Chip/Chip.css.d.ts
  packages/components/src/Chip/Chip.tsx
Labels: approved, Team Atlantis

#1625 fix(components): remove useragent styling from Combobox search [JOB-82086]
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContentSearch/ComboboxContentSearch.css
Labels: approved, Team Atlantis

#1614 feat(components): Refactor ComboboxContent to ComboboxOption
  docs/components/Combobox/Web.stories.tsx
  packages/components/src/Combobox/Combobox.css
  packages/components/src/Combobox/Combobox.css.d.ts
  packages/components/src/Combobox/Combobox.test.tsx
  packages/components/src/Combobox/Combobox.tsx
  packages/components/src/Combobox/Combobox.types.ts
  packages/components/src/Combobox/ComboboxProvider.tsx
  packages/components/src/Combobox/components/ComboboxActivator/ComboboxActivator.test.tsx
  packages/components/src/Combobox/components/ComboboxActivator/ComboboxActivator.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.test.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContentList/ComboboxContentList.css
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContentList/ComboboxContentList.css.d.ts
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContentList/ComboboxContentList.test.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContentList/ComboboxContentList.tsx
  packages/components/src/Combobox/components/ComboboxOption/ComboboxOption.css
  packages/components/src/Combobox/components/ComboboxOption/ComboboxOption.css.d.ts
  packages/components/src/Combobox/components/ComboboxOption/ComboboxOption.test.tsx
  packages/components/src/Combobox/components/ComboboxOption/ComboboxOption.tsx
  packages/components/src/Combobox/components/ComboboxTrigger/ComboboxTrigger.test.tsx
  packages/components/src/Combobox/components/ComboboxTrigger/ComboboxTrigger.tsx
  packages/components/src/Combobox/components/ComboboxTrigger/ComboboxTriggerButton/ComboboxTriggerButton.test.tsx
  packages/components/src/Combobox/components/ComboboxTrigger/ComboboxTriggerButton/ComboboxTriggerButton.tsx
  packages/components/src/Combobox/components/ComboboxTrigger/ComboboxTriggerChip/ComboboxTriggerChip.css
  packages/components/src/Combobox/components/ComboboxTrigger/ComboboxTriggerChip/ComboboxTriggerChip.css.d.ts
  packages/components/src/Combobox/components/ComboboxTrigger/ComboboxTriggerChip/ComboboxTriggerChip.test.tsx
  packages/components/src/Combobox/components/ComboboxTrigger/ComboboxTriggerChip/ComboboxTriggerChip.tsx
  packages/components/src/Combobox/components/ComboboxTrigger/index.ts
  packages/components/src/Combobox/hooks/useCombobox.ts
  packages/components/src/Combobox/hooks/useComboboxAccessibility.ts
  packages/components/src/Combobox/hooks/useComboboxContent.ts
  packages/components/src/Combobox/hooks/useComboboxValidation.ts
  packages/components/src/Combobox/hooks/useMakeComboboxHandlers.ts
Labels: approved, Team Atlantis

#1626 feat(components): Optional DataList action
  docs/components/DataList/DataList.stories.mdx
  docs/components/DataList/Web.stories.tsx
  packages/components/src/DataList/DataList.types.ts
  packages/components/src/DataList/components/DataListAction/DataListAction.test.tsx
  packages/components/src/DataList/components/DataListAction/DataListAction.tsx
  packages/components/src/DataList/components/DataListActions/DataListActions.test.tsx
  packages/components/src/DataList/components/DataListActions/DataListActions.tsx
  packages/components/src/DataList/components/DataListActionsMenu/DataListActionsMenu.tsx
  packages/components/src/DataList/components/DataListItem/DataListItem.test.tsx
  packages/components/src/DataList/components/DataListItem/DataListItem.tsx
  packages/components/src/DataList/components/DataListItemActions/DataListItemActions.test.tsx
  packages/components/src/DataList/components/DataListItemActions/DataListItemActions.tsx
  packages/components/src/DataList/hooks/useGetItemActions.ts
Labels: approved, Team Atlantis

#1632 fix(components): Make pseudo-elements avoid pointer events on Combobox
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContentList/ComboboxContentList.css
Labels: approved, Team Atlantis

#1635 fix(components): Ensure DataList sorting gets cleared in a predictable manner
  packages/components/src/DataList/components/DataListHeaderTile/DataListHeaderTile.tsx
  packages/components/src/DataList/components/DataListHeaderTile/DataListSortingArrows.css
Labels: approved, design approved, Team Atlantis

#1639 fix(components): Ensure DataList renders the list item on safari
  packages/components/src/DataList/hooks/useResponsiveSizing.ts
Labels: approved, Team Atlantis

#1638 fix(components): Refactor DataListSort to use Combobox
  docs/components/DataList/Web.stories.tsx
  packages/components/src/Chip/components/ChipSuffix/Chip.Suffix.tsx
  packages/components/src/Combobox/hooks/useComboboxAccessibility.ts
  packages/components/src/DataList/components/DataListFilters/DataListFilters.test.tsx
  packages/components/src/DataList/components/DataListFilters/components/DataListSort/DataListSort.test.tsx
  packages/components/src/DataList/components/DataListFilters/components/DataListSort/DataListSort.tsx
Labels: approved, design approved, Team Atlantis

#1637 fix(components): resolve transition flicker on DataList "tag count" element
  packages/components/src/DataList/components/DataListTags/DataListTags.css
  packages/components/src/DataList/components/DataListTags/DataListTags.css.d.ts
  packages/components/src/DataList/components/DataListTags/DataListTags.tsx
Labels: approved, Team Atlantis

#1630 fix: remove @use-it/event-listener dependency and use regular event handler attachment api.
  package-lock.json
  packages/components/package.json
  packages/components/rollup.config.js
  packages/components/src/Autocomplete/Menu.tsx
  packages/hooks/package.json
  packages/hooks/src/useOnKeyDown/useOnKeyDown.ts
Labels: approved, Team Atlantis

#1641 refactor(components): Cleanup on DataListSort
  packages/components/src/DataList/components/DataListFilters/components/DataListSort/DataListSort.tsx
Labels: approved, Team Atlantis

#1642 fix: breakpoints and viewport mock
  packages/design/src/responsiveBreakpoints.css
  packages/hooks/src/useBreakpoints/mockViewportWidth/mockViewportWidth.test.ts
  packages/hooks/src/useBreakpoints/mockViewportWidth/mockViewportWidth.ts
  packages/hooks/src/useBreakpoints/useBreakpoints.ts
Labels: approved, Team Atlantis

#1643 docs: remove warning Banner from Glimmer
  docs/components/Glimmer/Glimmer.stories.mdx
Labels: approved, Team Atlantis

#1636 fix(components): fix Chip, Combobox, and DataList focus states [JOB-82715]
  packages/components/src/Chip/Chip.css
  packages/components/src/Combobox/components/ComboboxAction/ComboboxAction.css
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.css
  packages/components/src/Combobox/components/ComboboxOption/ComboboxOption.css
  packages/components/src/DataList/components/DataListAction/DataListAction.css
  packages/components/src/DataList/components/DataListHeaderTile/DataListHeaderTile.css
Labels: approved, Team Atlantis

#1646 fix(components): DataList filters gap
  packages/components/src/DataList/components/DataListOverflowFade/DataListOverflowFade.css
  packages/components/src/DataList/components/DataListOverflowFade/DataListOverflowFade.css.d.ts
  packages/components/src/DataList/components/DataListOverflowFade/DataListOverflowFade.tsx
  packages/components/src/DataList/components/DataListSearch/DataListSearch.css
  packages/components/src/DataList/components/DataListSearch/DataListSearch.css.d.ts
  packages/components/src/DataList/components/DataListSearch/DataListSearch.tsx
Labels: approved, Team Atlantis

#1647 chore(components): remove unnecessary comment
  packages/components/src/DataList/components/DataListSearch/DataListSearch.css
Labels: approved, Team Atlantis

#1634 build(eslint): Upgrade eslint and tslint related packages [JOB-81741]
  docs/components/Checkbox/Mobile.stories.tsx
  docs/components/InputAvatar/Web.stories.tsx
  docs/components/InputDate/Mobile.stories.tsx
  docs/components/InputTime/Mobile.stories.tsx
  package-lock.json
  packages/components-native/src/Form/Form.tsx
  packages/components-native/src/InputText/InputText.tsx
  packages/components/src/DatePicker/DatePicker.test.tsx
  packages/components/src/Form/Form.tsx
  packages/components/src/InputFile/InputFile.tsx
  packages/eslint-config/.eslintrc.js
  packages/eslint-config/package.json
Labels: approved, Team Atlantis, Team Frontend Foundations

#1648 fix(components): fix Chip transition state
  packages/components/src/Chip/Chip.css
  packages/design/src/Animation.stories.mdx
Labels: approved, Team Atlantis

#1621 docs: Update Combobox documentation for Activator and new API
  docs/components/Combobox/Combobox.stories.mdx
  docs/components/Combobox/Web.stories.tsx
  packages/components/src/Combobox/Combobox.tsx
  packages/components/src/Combobox/Combobox.types.ts
  packages/components/src/DataList/components/DataListTags/DataListTags.tsx
Labels: approved, Team Atlantis

#1644 feat(components): Adding onBlur and onFocus support to Web <Select />
  docs/components/Select/Web.stories.tsx
  packages/components/src/FormField/FormField.tsx
Labels: approved, Team Atlantis

#1619 feat(components): add missing role to modal component
  packages/components/src/ConfirmationModal/tests/__snapshots__/snapshot-ConfirmationModal.test.tsx.snap
  packages/components/src/Modal/Modal.test.tsx
  packages/components/src/Modal/Modal.tsx
  packages/components/src/Modal/__snapshots__/ModalSnapshots.test.tsx.snap
Labels: approved, Team Atlantis

#1652 fix(components-native): avoid InputText re-renders
  packages/components-native/src/InputCurrency/InputCurrency.test.tsx
  packages/components-native/src/InputText/InputText.test.tsx
  packages/components-native/src/InputText/InputText.tsx
Labels: approved, Team Atlantis

#1650 feat: DataList batch selection for select all with unknown IDs
  docs/components/DataList/DataList.stories.mdx
  docs/components/DataList/Web.stories.tsx
  docs/components/DataList/storyUtils.ts
  packages/components/src/DataList/DataList.tsx
  packages/components/src/DataList/DataList.types.ts
  packages/components/src/DataList/__POM__/DataList.selectable.pom.tsx
  packages/components/src/DataList/__tests__/DataList.selectable.test.tsx
  packages/components/src/DataList/components/DataListHeader/DataListHeader.tsx
  packages/components/src/DataList/components/DataListHeader/DataListHeaderCheckbox.tsx
  packages/components/src/DataList/components/DataListItem/DataListItemInternal.tsx
  packages/components/src/DataList/components/DataListItems/DataListItems.test.tsx
  packages/components/src/DataList/hooks/useBatchSelect.ts
  packages/components/src/DataList/index.ts
  packages/components/tsconfig.rollup.json
Labels: approved, Team Atlantis

#1654 feat(components): Add css changes to show the placeholder label to the form field [JOB-83555]
  docs/components/InputTime/Web.stories.tsx
  packages/components/src/Autocomplete/__snapshots__/Autocomplete.test.tsx.snap
  packages/components/src/FormField/FormField.css
  packages/components/src/FormField/FormField.css.d.ts
  packages/components/src/FormField/FormField.test.tsx
  packages/components/src/FormField/FormFieldWrapper.tsx
  packages/components/src/FormField/__snapshots__/FormField.test.tsx.snap
  packages/components/src/InputNumber/InputNumber.test.tsx
  packages/components/src/InputPassword/__snapshots__/InputPassword.test.tsx.snap
  packages/components/src/InputText/InputText.test.tsx
  packages/components/src/InputTime/InputTime.test.tsx
  packages/components/src/Select/__snapshots__/Select.test.tsx.snap
Labels: approved, design approved, Team Atlantis, Team Work Setup

#1657 fix(components): Prevent data list from navigating within the link when opening the menu
  packages/components/src/DataList/components/DataListItemActionsOverflow/DataListItemActionsOverflow.tsx
Labels: approved, Team Atlantis

#1649 fix(components-native): add padding horizontal on content overlay title
  packages/components-native/src/ContentOverlay/ContentOverlay.style.ts
  packages/components-native/src/ContentOverlay/ContentOverlay.tsx
Labels: approved, Team Atlantis

#1660 feat(components): add 'starHalf' icon — (Minor) Feature Release
  docs/components/Icon/Icon.stories.mdx
  packages/design/assets/icons/starHalf.svg
Labels: approved, Team Atlantis, Team Workflow

#1659 feat(design): add tag icon
  docs/components/Icon/Icon.stories.mdx
  packages/design/assets/icons/tag.svg
Labels: approved, Team Atlantis

#1545 feat(design): update hover colors for common surfaces [JOB-82570]
  .storybook/components/ColorSwatches/ColorSwatches.module.css
  packages/components-native/src/Heading/__snapshots__/Heading.test.tsx.snap
  packages/components-native/src/ProgressBar/__snapshots__/ProgressBar.test.tsx.snap
  packages/components-native/src/StatusLabel/__snapshots__/StatusLabel.test.tsx.snap
  packages/components-native/src/Switch/components/BaseSwitch/__snapshots__/BaseSwitch.test.tsx.snap
  packages/components-native/src/Text/__snapshots__/Text.test.tsx.snap
  packages/components-native/src/ThumbnailList/__snapshots__/ThumbnailList.test.tsx.snap
  packages/components/src/DataList/DataList.css
  packages/components/src/DatePicker/DatePicker.css
  packages/components/src/List/ListItem.css
  packages/design/src/Colors.stories.mdx
  packages/design/src/colors.css
  packages/design/src/shadows.css
Labels: approved, accessibility, Team Atlantis

#1662 refactor(components): swap icon and label placement in DataList context menu
  packages/components/src/DataList/components/DataListAction/DataListAction.css
  packages/components/src/DataList/components/DataListAction/DataListAction.tsx
Labels: approved, Team Atlantis

#1663 fix(components): Fix stepped variation of progress bar
  packages/components/src/ProgressBar/ProgressBar.css
Labels: approved, Team Atlantis

#1668 chore(components): remove flakey test
  packages/components/src/DataList/__tests__/DataList.selectable.test.tsx
Labels: approved, Team Atlantis

#1666 refactor(components): Update Chip and DataList with semantic colors
  packages/components/src/Chip/Chip.css
  packages/components/src/DataList/components/DataListHeaderTile/DataListSortingArrows.css
Labels: approved, Team Atlantis

#1665 fix(components): multiselect preventing space bar from being recognized
  packages/components/src/MultiSelect/DropDownMenu.tsx
  packages/components/src/MultiSelect/MultiSelect.test.tsx
  packages/components/src/MultiSelect/MultiSelect.tsx
  packages/components/src/MultiSelect/utils.ts
Labels: approved, Team Atlantis
