Repository GetJobber/atlantis, pull requests merged in 2024-01, with the labels that each got.

#1705 refactor(components): update lightbox toolbar for retheme
  packages/components/src/LightBox/LightBox.css
Labels: approved, Team Atlantis

#1715 feat(components): Add better typescript types for to prop on Button
  packages/components/src/Button/Button.test.tsx
  packages/components/src/Button/Button.tsx
Labels: approved, Team Atlantis

#1709 fix(components): InputFile update the useCallback dependency array [85395]
  packages/components/src/InputFile/InputFile.tsx
Labels: approved, Team Atlantis, Team SC First Touch

#1708 feat: Add support for providing your own of acceptable file types to upload for InputFile
  packages/components/src/InputFile/InputFile.test.tsx
  packages/components/src/InputFile/InputFile.tsx
  packages/components/src/InputFile/__snapshots__/InputFile.test.tsx.snap
Labels: approved, Team Atlantis

#1717 chore: Updated testing for custom file types
  packages/components/src/InputFile/InputFile.test.tsx
  packages/components/src/InputFile/__snapshots__/InputFile.test.tsx.snap
Labels: approved, Team Atlantis, Team SC First Touch

#1719 fix(components): Bring back card border and padding for retheme
  packages/components/src/Card/Card.css
Labels: approved, Team Atlantis

#1718 fix: align center banner icon on retheme
  packages/components/src/Banner/Banner.css
  packages/components/src/Banner/Banner.css.d.ts
  packages/components/src/Banner/Banner.tsx
  packages/components/src/Banner/__snapshots__/Banner.test.tsx.snap
  packages/components/src/Banner/components/BannerIcon/BannerIcon.css
  packages/components/src/Banner/components/BannerIcon/BannerIcon.css.d.ts
  packages/components/src/Banner/components/BannerIcon/BannerIcon.tsx
Labels: approved, Team Atlantis

#1722 fix(components): Hide anything overflowing the dataTable
  packages/components/src/DataTable/DataTable.css
Labels: approved, Team Atlantis

#1720 fix(components): Fix DataList Small Breakpoint DataListHeader Visibility
  packages/components/src/DataList/components/DataListHeader/DataListHeader.tsx
Labels: approved, Team Atlantis

#1712 fix(components): static thumbnails for HEIC in all browsers but safari (fixes forever loading thumbnail for HEIC) [84773]
  packages/components/src/FormatFile/InternalThumbnail.test.tsx
  packages/components/src/FormatFile/InternalThumbnail.tsx
  packages/components/src/utils/getClientBrowser.ts
Labels: approved, design approved, Team Atlantis, Team SC First Touch

#1716 fix(components): DataTable empty state should span full width with pinFirstColumn enabled [85639]
  packages/components/src/DataTable/Body.tsx
  packages/components/src/DataTable/DataTable.css
  packages/components/src/DataTable/DataTable.css.d.ts
Labels: approved, Team Atlantis

#1724 fix(components): Adapt toast and menu for retheme [JOB-86410]
  packages/components/src/Menu/Menu.css
  packages/components/src/Toast/Toast.css
Labels: approved, Team Atlantis

#1710 feat: Added Error State and onErrorCallback for InputFile
  docs/components/InputFile/InputFile.stories.mdx
  packages/components/src/InputFile/InputFile.css
  packages/components/src/InputFile/InputFile.css.d.ts
  packages/components/src/InputFile/InputFile.test.tsx
  packages/components/src/InputFile/InputFile.tsx
Labels: approved, design approved, Team Atlantis, Team SC First Touch

#1700 feat: Input time auto fill
  docs/components/InputTime/InputTime.stories.mdx
  docs/components/InputTime/Web.stories.tsx
  packages/components/src/FormField/FormField.tsx
  packages/components/src/FormField/FormFieldTypes.ts
  packages/components/src/InputTime/InputTime.test.tsx
  packages/components/src/InputTime/InputTime.tsx
  packages/components/src/InputTime/hooks/__test__/useTimePredict.test.ts
  packages/components/src/InputTime/hooks/useTimePredict.ts
Labels: approved, Team Atlantis

#1729 docs(design): add use case for 'appointment' language in vocabulary guidelines
  docs/content/product-vocabulary.stories.mdx
Labels: approved, Team Atlantis

#1730 feat(components): Expose all sizing tokens in web Content
  packages/components/src/Content/Paddings.css
  packages/components/src/Content/Paddings.css.d.ts
  packages/components/src/Content/Spacing.css
  packages/components/src/Content/Spacing.css.d.ts
  packages/design/src/Spacing.stories.mdx
Labels: approved, Team Atlantis

#1725 fix(hooks): Guard useAssert to work with SSR
  packages/hooks/src/useAssert/useAssert.tsx
Labels: approved, Team Atlantis

#1706 fix(components): Attemping to fix typing issues for Vue-based Atlantis consumption
  package-lock.json
  packages/components/package.json
  packages/components/rollup.config.js
Labels: approved, Team Atlantis

#1727 feat(components): onSearch Callback Prop for Combobox
  docs/components/Combobox/Combobox.stories.mdx
  docs/components/Combobox/Web.stories.tsx
  packages/components/src/Combobox/Combobox.test.tsx
  packages/components/src/Combobox/Combobox.tsx
  packages/components/src/Combobox/Combobox.types.ts
  packages/components/src/Combobox/components/ComboboxActivator/ComboboxActivator.test.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.test.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContentList/ComboboxContentList.css
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContentList/ComboboxContentList.css.d.ts
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContentList/ComboboxContentList.test.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContentList/ComboboxContentList.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContentSearch/ComboboxContentSearch.test.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContentSearch/ComboboxContentSearch.tsx
  packages/components/src/Combobox/components/ComboboxOption/ComboboxOption.test.tsx
  packages/components/src/Combobox/components/ComboboxTrigger/ComboboxTrigger.test.tsx
  packages/components/src/Combobox/hooks/useCombobox.ts
  packages/components/src/Combobox/hooks/useComboboxContent.ts
Labels: approved, design review requested, Team Atlantis

#1723 feat(components): Add ability to have multiple sort options on DataList
  docs/components/DataList/Web.stories.tsx
  packages/components/src/DataList/DataList.test.tsx
  packages/components/src/DataList/DataList.types.ts
  packages/components/src/DataList/DataList.utils.tsx
  packages/components/src/DataList/components/DataListFilters/components/DataListSort/DataListSort.test.tsx
  packages/components/src/DataList/components/DataListFilters/components/DataListSort/DataListSort.tsx
  packages/components/src/DataList/components/DataListHeaderTile/DataListHeaderTile.css
  packages/components/src/DataList/components/DataListHeaderTile/DataListHeaderTile.tsx
  packages/components/src/DataList/components/DataListHeaderTile/components/DataListSortingOptions.css
  packages/components/src/DataList/components/DataListHeaderTile/components/DataListSortingOptions.css.d.ts
  packages/components/src/DataList/components/DataListHeaderTile/components/DataListSortingOptions.tsx
  packages/components/src/DataList/components/DataListHeaderTile/components/index.ts
Labels: approved, design approved, Team Atlantis

#1732 docs(components): Improve Combobox Custom Search Example
  docs/components/Combobox/Web.stories.tsx
  docs/components/Combobox/storyUtils.ts
Labels: approved, Team Atlantis

#1736 fix(components): Updating InputTime to remove InputTimeSafari for SSR compatibility (and because we didn't need it anymore)
  packages/components/src/InputTime/InputTime.tsx
  packages/components/src/InputTime/InputTimeSafari.tsx
  packages/components/src/InputTime/civilTimeConversions.tsx
Labels: approved, Team Atlantis

#1734 feat(components): Add data-value to sortable options
  docs/components/DataList/Web.stories.tsx
  packages/components/src/DataList/DataList.types.ts
  packages/components/src/DataList/components/DataListFilters/components/DataListSort/DataListSort.test.tsx
  packages/components/src/DataList/components/DataListFilters/components/DataListSort/DataListSort.tsx
  packages/components/src/DataList/components/DataListHeaderTile/DataListHeaderTile.tsx
  packages/components/src/DataList/components/DataListHeaderTile/components/DataListSortingOptions.tsx
Labels: approved, Team Atlantis

#1740 fix(components): Add SortableOptions Partial to DataListSorting
  packages/components/src/DataList/DataList.types.ts
  packages/components/src/DataList/components/DataListHeaderTile/DataListHeaderTile.tsx
  packages/components/src/DataList/components/DataListHeaderTile/components/DataListSortingOptions.tsx
Labels: approved, Team Atlantis

#1743 fix(components): Update handling of sorting state
  packages/components/src/DataList/components/DataListHeaderTile/DataListHeaderTile.tsx
Labels: approved, Team Atlantis

#1744 fix(components): Ensure Combobox Updates on New Options
  packages/components/src/Combobox/Combobox.test.tsx
  packages/components/src/Combobox/hooks/useCombobox.ts
Labels: approved, Team Atlantis

#1741 chore: upgrade framer motion to 11.0.3
  package-lock.json
  packages/components/package.json
  packages/components/src/AnimatedSwitcher/AnimatedSwitcher.tsx
  packages/components/src/InputValidation/InputValidation.tsx
Labels: approved, Team Atlantis
