Repository GetJobber/atlantis, pull requests merged in 2024-09, with the labels that each got.

#1999 docs(design): update swatches and fix broken base colors
  .storybook/assets/css/preview.css
  .storybook/components/ColorSwatches/ColorSwatches.module.css
  .storybook/components/ColorSwatches/ColorSwatches.module.css.d.ts
  .storybook/components/ColorSwatches/ColorSwatches.tsx
  docs/design/Colors.stories.mdx
Labels: approved, Team Atlantis

#2008 docs: Move base swatches into a Disclosure
  docs/components/Chips/Chips.stories.mdx
  docs/design/Colors.stories.mdx
Labels: approved, Team Atlantis

#2010 fix(components): Add ref prop to primary and secondary actions on Page component
  docs/components/Page/Web.stories.tsx
  packages/components/src/Page/Page.css
  packages/components/src/Page/Page.test.tsx
  packages/components/src/Page/Page.tsx
Labels: approved, Team Atlantis

#2004 fix(components): match Glimmer mobile styles to web
  packages/components-native/src/Glimmer/Glimmer.style.ts
  packages/components-native/src/Glimmer/Glimmer.tsx
Labels: approved, Team Atlantis

#2022 feat(components-native): Add underline support to Text/Typography components for mobile (JOB-104505)
  packages/components-native/src/Text/Text.test.tsx
  packages/components-native/src/Text/Text.tsx
  packages/components-native/src/Text/__snapshots__/Text.test.tsx.snap
  packages/components-native/src/Typography/Typography.style.ts
  packages/components-native/src/Typography/Typography.test.tsx
  packages/components-native/src/Typography/Typography.tsx
  packages/components-native/src/Typography/__snapshots__/Typography.test.tsx.snap
Labels: approved, Team Atlantis, Team Jobber Copilot

#2028 revert: "feat(components): Separate Chip from Chips Again"
  docs/components/Chips/Chips.stories.mdx
  docs/components/Chips/Web.stories.tsx
  packages/components/src/Chip/Chip.css
  packages/components/src/Chip/Chip.test.tsx
  packages/components/src/Chip/Chip.tsx
  packages/components/src/Chip/Chip.types.d.ts
  packages/components/src/Chip/components/ChipSuffix/Chip.Suffix.tsx
  packages/components/src/Chips/ChipsTypes.tsx
  packages/components/src/Chips/InternalChip.css
  packages/components/src/Chips/InternalChip.tsx
  packages/components/src/Chips/InternalChipButton.tsx
  packages/components/src/Chips/InternalChipDismissible/__tests__/InternalChipDismissible.test.tsx
  packages/components/src/Chips/InternalChipMultiSelect.tsx
  packages/components/src/Chips/InternalChipSingleSelect.tsx
  packages/components/src/Chips/tests/InternalChip.test.tsx
  packages/components/src/Tooltip/Tooltip.tsx
Labels: approved, Team Atlantis

#2029 refactor(components): Tooltip refinements [JOB-99926]
  packages/components/src/Tooltip/Tooltip.css
  packages/components/src/Tooltip/Tooltip.tsx
Labels: approved, Team Atlantis

#2019 feat(components): Add description prop to InputFile
  docs/components/InputFile/InputFile.stories.mdx
  docs/components/InputFile/Web.stories.tsx
  packages/components/src/InputFile/InputFile.tsx
  packages/components/src/InputFile/__snapshots__/InputFile.test.tsx.snap
Labels: approved, Team Atlantis

#2013 fix(components): Display Datalist checkbox based on device type instead of breakpoint
  packages/components/src/DataList/DataList.css
Labels: approved, design approved, Team Atlantis

#2016 docs(design): add subtle background usage to color docs
  docs/design/Colors.stories.mdx
Labels: approved, Team Atlantis

#2021 feat(components): Add underline support to Typography component for web (JOB-104497)
  packages/components/src/Typography/Typography.test.tsx
  packages/components/src/Typography/Typography.tsx
  packages/components/src/Typography/css/Underline.css
  packages/components/src/Typography/css/Underline.css.d.ts
  packages/components/src/Typography/types.ts
Labels: approved, Team Atlantis, Team Jobber Copilot

#2000 feat(components): add elevation to DataList item actions
  packages/components/src/DataList/components/DataListItemActions/DataListItemActions.tsx
Labels: approved, Team Atlantis

#2014 feat(components): small improvement to focus state of DataList headers
  packages/components/src/DataList/components/DataListHeaderTile/DataListHeaderTile.css
  packages/components/src/DataList/components/DataListHeaderTile/DataListSortingArrows.css
Labels: approved, Team Atlantis

#2034 docs: Dark Mode applied in Storybook controls
  .storybook/theme.ts
Labels: approved, Team Atlantis

#2020 feat(components): update Chip.Prefix to accept more than Icon and Avatar
  docs/components/Chip/Chip.stories.mdx
  packages/components/src/Chip/components/ChipPrefix/Chip.Prefix.test.tsx
  packages/components/src/Chip/components/ChipPrefix/Chip.Prefix.tsx
Labels: approved, Team Atlantis

#2007 feat(components): Add maxFiles prop to InputFile
  docs/components/InputFile/InputFile.stories.mdx
  docs/components/InputFile/Web.stories.tsx
  packages/components/src/InputFile/InputFile.test.tsx
  packages/components/src/InputFile/InputFile.tsx
Labels: approved, Team Atlantis

#1915 feat(components): improve positioning of DataList actions [JOB-99926]
  packages/components/src/DataList/components/DataListActions/DataListActions.tsx
  packages/components/src/DataList/components/DataListBulkActions/DataListBulkActions.test.tsx
  packages/components/src/DataList/components/DataListBulkActions/DataListBulkActions.tsx
  packages/components/src/DataList/components/DataListItemActions/DataListItemActions.css
  packages/components/src/DataList/components/DataListItemActions/DataListItemActions.tsx
  packages/components/src/DataList/components/DataListItemActionsOverflow/DataListItemActionsOverflow.tsx
  packages/components/src/DataList/components/DataListOverflowFade/DataListOverflowFade.css
Labels: approved, Team Atlantis

#2038 fix(components): Fix DataListOverflowFade spacing
  packages/components/src/DataList/components/DataListOverflowFade/DataListOverflowFade.css
Labels: approved, Team Atlantis

#2030 refactor(components): Add semantic colors to typography on web [97200]
  packages/components/src/Typography/Typography.test.tsx
  packages/components/src/Typography/css/TextColors.css
  packages/components/src/Typography/css/TextColors.css.d.ts
Labels: approved, design approved, Team Atlantis

#2011 fix(components): Keep dismiss on drawers aligned to top when titles wrap
  packages/components/src/Drawer/Drawer.css
  packages/components/src/Drawer/Drawer.css.d.ts
  packages/components/src/Drawer/Drawer.tsx
  packages/components/src/SideDrawer/SideDrawer.css
  packages/components/src/SideDrawer/SideDrawer.css.d.ts
  packages/components/src/SideDrawer/SideDrawer.tsx
Labels: approved, Team Atlantis

#2041 fix: Revert "Adding trouebleshooting link to the failure comment"
  scripts/commentOnPrAfterPreRelease.js
Labels: approved, Team Atlantis

#2042 docs: Adding trouebleshooting link to the failure comment
  scripts/commentOnPrAfterPreRelease.js
Labels: approved, Team Atlantis

#2033 refactor(components): Add semantic colors to typography on mobile [97200]
  packages/components-native/src/Typography/Typography.style.ts
  packages/components-native/src/Typography/Typography.test.tsx
  packages/components-native/src/Typography/Typography.tsx
  packages/components-native/src/Typography/__snapshots__/Typography.test.tsx.snap
Labels: approved, design review requested, Team Atlantis

#2043 docs: Add an example how to clear all filters in DataList (JOB-103665)
  .storybook/components/Playground/Playground.tsx
  .storybook/components/Playground/constants.ts
  docs/components/DataList/DataList.stories.mdx
  docs/components/DataList/Web.stories.tsx
Labels: approved, design approved, Team Atlantis

#2046 feat(components): Create FileTypes enum for InputFile and use in validation error
  docs/components/InputFile/InputFile.stories.mdx
  docs/components/InputFile/Web.stories.tsx
  packages/components/src/InputFile/FileTypes.ts
  packages/components/src/InputFile/InputFile.test.tsx
  packages/components/src/InputFile/InputFile.tsx
Labels: approved, design approved, Team Atlantis

#2048 fix(docx): Fix regex in Playground for the code tab to work correctly
  .storybook/components/Playground/Playground.tsx
Labels: approved, Team Atlantis

#2050 feat(components): Clearable Autocomplete
  packages/components/src/Autocomplete/Autocomplete.tsx
Labels: approved, Team Atlantis
