Repository GetJobber/atlantis, pull requests merged in 2024-04, with the labels that each got.

#1820 fix(components): Fixing issue with InputDate causing an additional render
  packages/components/src/InputDate/InputDate.tsx
Labels: approved, Team Atlantis

#1838 fix(components): Fix when InputDate's emptyValueLabel is updated
  packages/components/src/InputDate/InputDate.tsx
Labels: approved, Team Atlantis

#1841 chore: Update gitignore to ignore local runs of npm run pack
  .gitignore
Labels: approved, Team Atlantis

#1846 Revert "build(components)!: Adding ESM Build + Changing CSS Export Pattern BREAKING CHANGE"
  .gitignore
  .prettierignore
  .stylelintignore
  package-lock.json
  packages/components/.eslintrc.js
  packages/components/package.json
  packages/components/rollup.config.js
  packages/components/src/index.tsx
  packages/components/tsconfig.json
  packages/design/package.json
  packages/design/rollup.config.js
Labels: review requested, Team Atlantis

#1848 Revert "feat!: BREAKING CHANGE Adding ESM Build + Changing CSS Export Pattern"
  .gitignore
  .prettierignore
  .stylelintignore
  package-lock.json
  packages/components/.eslintrc.js
  packages/components/package.json
  packages/components/rollup.config.js
  packages/components/src/index.tsx
  packages/components/tsconfig.json
  packages/design/package.json
  packages/design/rollup.config.js
Labels: review requested, Team Atlantis

#1842 feat(components-native): implement glimmer and add loading state to native inputs
  docs/components/Glimmer/Mobile.stories.tsx
  packages/components-native/src/Glimmer/Glimmer.shape.style.ts
  packages/components-native/src/Glimmer/Glimmer.size.style.ts
  packages/components-native/src/Glimmer/Glimmer.style.ts
  packages/components-native/src/Glimmer/Glimmer.test.tsx
  packages/components-native/src/Glimmer/Glimmer.tsx
  packages/components-native/src/Glimmer/index.ts
  packages/components-native/src/InputFieldWrapper/InputFieldWrapper.style.ts
  packages/components-native/src/InputFieldWrapper/InputFieldWrapper.test.tsx
  packages/components-native/src/InputFieldWrapper/InputFieldWrapper.tsx
  packages/components-native/src/InputText/InputText.tsx
  packages/components-native/src/index.ts
Labels: in review, approved, Team Atlantis

#1849 feat(components): BREAKING CHANGE: Updating Atlantis to support ESM + Injected CSS
  .gitignore
  .prettierignore
  .stylelintignore
  package-lock.json
  packages/components/.eslintrc.cjs
  packages/components/package.json
  packages/components/rollup.config.mjs
  packages/components/src/MultiSelect/MultiSelect.tsx
  packages/components/src/index.tsx
  packages/components/tsconfig.json
  packages/design/package.json
  packages/design/rollup.config.cjs
Labels: approved, Team Atlantis

#1852 feat(components): BREAKING CHANGE: Revert - Updating Atlantis to support ESM + Injected CSS
  .gitignore
  .prettierignore
  .stylelintignore
  package-lock.json
  packages/components/.eslintrc.js
  packages/components/package.json
  packages/components/rollup.config.js
  packages/components/src/MultiSelect/MultiSelect.tsx
  packages/components/src/index.tsx
  packages/components/tsconfig.json
  packages/design/package.json
  packages/design/rollup.config.js
Labels: approved, Team Atlantis

#1843 fix(components): Update modal close button to stay fixed
  packages/components/src/Modal/Modal.css
  packages/components/src/Modal/Modal.test.tsx
  packages/components/src/Modal/Modal.tsx
  packages/components/src/Modal/ModalSnapshots.test.tsx
  packages/components/src/Modal/__snapshots__/ModalSnapshots.test.tsx.snap
Labels: approved, design review requested, Team Atlantis

#1837 feat(design): Create longArrowRight and rename backArrow
  docs/components/AnimatedSwitcher/Web.stories.tsx
  docs/components/Icon/Icon.stories.mdx
  packages/components-native/src/ActionItem/ActionItem.test.tsx
  packages/components-native/src/ActionItem/ActionItem.tsx
  packages/design/src/icons/Icon.css
  packages/design/src/icons/Icon.css.d.ts
  packages/design/src/icons/getIcon.ts
Labels: approved, Team Atlantis

#1855 docs(components-native): Mark mobile Menu component as alpha
  .storybook/components/SidebarLabel/SidebarLabel.tsx
  .storybook/components/SidebarLabel/alphaComponents.ts
Labels: in review, approved, Team Atlantis

#1857 feat(components): Update Headings to match retheme design
  packages/components/src/ConfirmationModal/tests/__snapshots__/snapshot-ConfirmationModal.test.tsx.snap
  packages/components/src/Heading/Heading.tsx
  packages/components/src/Modal/Modal.css
  packages/components/src/Modal/Modal.tsx
  packages/components/src/Typography/css/FontWeights.css
Labels: approved, Team Atlantis

#1839 feat(design): new design tokens for retheme [JOB-87500]
  packages/components-native/src/Heading/__snapshots__/Heading.test.tsx.snap
  packages/components-native/src/Icon/__snapshots__/Icon.test.tsx.snap
  packages/components-native/src/ProgressBar/__snapshots__/ProgressBar.test.tsx.snap
  packages/components-native/src/StatusLabel/__snapshots__/StatusLabel.test.tsx.snap
  packages/components-native/src/Switch/components/BaseSwitch/__snapshots__/BaseSwitch.test.tsx.snap
  packages/components-native/src/Text/__snapshots__/Text.test.tsx.snap
  packages/components-native/src/ThumbnailList/__snapshots__/ThumbnailList.test.tsx.snap
  packages/components-native/src/Typography/__snapshots__/Typography.test.tsx.snap
  packages/design/src/Colors.stories.mdx
  packages/design/src/Radii.stories.mdx
  packages/design/src/colors.css
  packages/design/src/radii.css
Labels: approved, Team Atlantis

#1851 build(components): ESM + CSS + Peer Dep Update
  .gitignore
  .prettierignore
  .stylelintignore
  package-lock.json
  packages/components/.eslintrc.cjs
  packages/components/package.json
  packages/components/rollup.config.mjs
  packages/components/src/index.tsx
  packages/design/package.json
  packages/design/rollup.config.cjs
Labels: approved, Team Atlantis

#1860 build: removing manual release for now.
  .circleci/config.yml
Labels: approved, Team Atlantis

#1861 build: Moving Manual Release Check back
  .circleci/config.yml
Labels: approved, Team Atlantis

#1840 refactor(components): apply new theme to all components by default [JOB-87500]
  docs/components/Heading/Heading.stories.mdx
  packages/components-native/src/Icon/__snapshots__/Icon.test.tsx.snap
  packages/components/src/Banner/Banner.css
  packages/components/src/Banner/Banner.test.tsx
  packages/components/src/Banner/Banner.tsx
  packages/components/src/Banner/__snapshots__/Banner.test.tsx.snap
  packages/components/src/Banner/components/BannerIcon/BannerIcon.tsx
  packages/components/src/Banner/notificationTypes.css
  packages/components/src/Banner/notificationTypes.css.d.ts
  packages/components/src/Button/Button.css
  packages/components/src/Button/Button.css.d.ts
  packages/components/src/Button/Button.tsx
  packages/components/src/Button/__snapshots__/Button.test.tsx.snap
  packages/components/src/ButtonDismiss/__snapshots__/ButtonDismiss.test.tsx.snap
  packages/components/src/Card/Card.css
  packages/components/src/Card/Card.css.d.ts
  packages/components/src/Card/CardHeader.tsx
  packages/components/src/Card/tests/Card.test.tsx
  packages/components/src/Checkbox/Checkbox.css
  packages/components/src/Checkbox/Checkbox.css.d.ts
  packages/components/src/Checkbox/Checkbox.tsx
  packages/components/src/Checkbox/__snapshots__/Checkbox.test.tsx.snap
  packages/components/src/Combobox/components/ComboboxAction/ComboboxAction.css
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.css
  packages/components/src/Combobox/components/ComboboxOption/ComboboxOption.css
  packages/components/src/ConfirmationModal/tests/__snapshots__/snapshot-ConfirmationModal.test.tsx.snap
  packages/components/src/DataList/components/DataListActionsMenu/DataListActionsMenu.css
  packages/components/src/DataList/components/DataListHeaderTile/components/DataListSortingOptions.css
  packages/components/src/DataList/components/DataListItemActions/DataListItemActions.css
  packages/components/src/Drawer/Drawer.css
  packages/components/src/Drawer/Drawer.tsx
  packages/components/src/FeatureSwitch/__snapshots__/FeatureSwitch.test.tsx.snap
  packages/components/src/Heading/Heading.test.tsx
  packages/components/src/Heading/Heading.tsx
  packages/components/src/InputAvatar/__snapshots__/InputAvatar.test.tsx.snap
  packages/components/src/InputFile/__snapshots__/InputFile.test.tsx.snap
  packages/components/src/LightBox/LightBox.css
  packages/components/src/LightBox/__snapshots__/LightBoxSnapshots.test.tsx.snap
  packages/components/src/Markdown/__snapshots__/Markdown.test.tsx.snap
  packages/components/src/Menu/Menu.css
  packages/components/src/Menu/Menu.css.d.ts
  packages/components/src/Menu/Menu.tsx
  packages/components/src/Menu/__snapshots__/Menu.test.tsx.snap
  packages/components/src/Modal/Modal.css
  packages/components/src/Modal/Sizes.css
  packages/components/src/Page/__snapshots__/Page.test.tsx.snap
  packages/components/src/RadioGroup/RadioGroup.css
  packages/components/src/Switch/Switch.css
  packages/components/src/Toast/Toast.css
  packages/components/src/Toast/Toast.css.d.ts
  packages/components/src/Toast/Toast.tsx
  packages/components/src/Tooltip/Tooltip.css
  packages/components/src/Typography/css/TextColors.css
  packages/components/src/Typography/css/TextColors.css.d.ts
  packages/design/src/Typography.stories.mdx
  packages/design/src/colors.css
  packages/design/src/icons/Icon.css
Labels: approved, Team Atlantis

#1864 build(formatters): Fixing a build issue with formatters in a Cloudflare environment
  packages/formatters/src/global.ts
Labels: approved, Team Atlantis

#1844 feat(components): adds ability to provide "preferredPlacement" for Tooltip
  docs/components/Tooltip/Web.stories.tsx
  packages/components/src/Popover/Popover.css
  packages/components/src/Tooltip/Tooltip.css
  packages/components/src/Tooltip/Tooltip.css.d.ts
  packages/components/src/Tooltip/Tooltip.test.tsx
  packages/components/src/Tooltip/Tooltip.tsx
  packages/components/src/Tooltip/Tooltip.types.ts
  packages/components/src/Tooltip/useTooltipPositioning.ts
Labels: approved, Team Atlantis

#1783 fix(components): Leave space for down arrow in Select inline variant
  docs/components/Select/Web.stories.tsx
  packages/components/src/FormField/FormField.css
  packages/components/src/FormField/FormField.css.d.ts
Labels: approved, design approved, Team Atlantis

#1867 fix(components): Select improvements
  packages/components/src/FormField/FormField.css
  packages/components/src/FormField/FormField.css.d.ts
Labels: approved, Team Atlantis

#1868 fix(components): remove Chip prefix background [JOB-92493]
  docs/components/Chip/Web.stories.tsx
  packages/components/src/Chip/Chip.css
Labels: approved, Team Atlantis

#1866 fix(components): SSR Fixes
  packages/components/src/Tooltip/Tooltip.tsx
  packages/components/src/index.tsx
Labels: approved, Team Atlantis

#1856 feat(components): Add Toolbar to InputText
  docs/components/InputText/Web.stories.tsx
  packages/components/src/Autocomplete/__snapshots__/Autocomplete.test.tsx.snap
  packages/components/src/FormField/FormField.css
  packages/components/src/FormField/FormField.css.d.ts
  packages/components/src/FormField/FormFieldTypes.ts
  packages/components/src/FormField/FormFieldWrapper.tsx
  packages/components/src/FormField/__snapshots__/FormField.test.tsx.snap
  packages/components/src/FormField/components/ClearAction.css
  packages/components/src/FormField/components/ClearAction.css.d.ts
  packages/components/src/FormField/components/ClearAction.tsx
  packages/components/src/FormField/hooks/useFormFieldFocus.ts
  packages/components/src/FormField/hooks/useToolbar.ts
  packages/components/src/InputNumber/InputNumber.test.tsx
  packages/components/src/InputPassword/__snapshots__/InputPassword.test.tsx.snap
  packages/components/src/InputText/InputText.test.tsx
  packages/components/src/InputText/InputText.tsx
  packages/components/src/Select/__snapshots__/Select.test.tsx.snap
Labels: design approved, Team Atlantis

#1869 feat(components): Add autofocus support for InputText (JOB-94181)
  packages/components/src/FormField/FormField.tsx
  packages/components/src/FormField/FormFieldTypes.ts
  packages/components/src/InputText/InputText.test.tsx
  packages/components/src/InputText/InputText.tsx
Labels: approved, Team Atlantis, Team Jobber Assistant

#1871 fix(components): update small button sizing
  packages/components/src/Button/Button.css
Labels: in review, approved, Team Atlantis

#1872 refactor(design): update value of taupe--light
  packages/design/src/colors.css
Labels: approved, Team Atlantis

#1874 feat(design): add semantic value for subtle backgrounds
  packages/design/src/colors.css
Labels: review requested, approved, Team Atlantis

#1875 fix(components): Allow InputText Default Value to be Clearable
  packages/components/src/FormField/FormField.tsx
  packages/components/src/FormField/FormFieldTypes.ts
  packages/components/src/FormField/FormFieldWrapper.tsx
Labels: approved, Team Atlantis

#1876 fix(components): Input Text Safari Resize Handle
  packages/components/src/FormField/FormField.css
  packages/components/src/FormField/FormField.css.d.ts
Labels: approved, Team Atlantis
