Repository GetJobber/atlantis, pull requests merged in 2024-11, with the labels that each got.

#2099 docs: Fix disclosure code tab
  docs/components/Disclosure/Web.stories.tsx
Labels: approved, Team Atlantis

#2098 docs: Update links in README.md
  docs/README.md
Labels: approved, Team Atlantis

#2097 fix(design): Updating the task icon to use task-color [JOB-98804]
  packages/design/src/iconStyles/iconColors.ts
  packages/design/src/iconStyles/iconStyles.web.ts
Labels: approved, Team Atlantis

#2078 feat(components): Improve list composability [JOB-107035]
  docs/components/List/List.stories.mdx
  docs/components/List/Web.stories.tsx
  packages/components/src/List/List.test.tsx
  packages/components/src/List/List.tsx
  packages/components/src/List/ListItem.module.css
  packages/components/src/List/ListItem.module.css.d.ts
  packages/components/src/List/ListItem.tsx
  packages/components/src/List/__snapshots__/List.test.tsx.snap
  packages/components/src/List/index.ts
Labels: approved, design review requested, Team Atlantis

#2100 feat(docx): Improve search experience in new docs site
  packages/site/src/layout/NavMenu.tsx
  packages/site/src/layout/SearchBox.module.css
  packages/site/src/layout/SearchBox.tsx
Labels: approved, Team Atlantis

#2096 feat(components-native): Add size variation for progress bar
  packages/components-native/src/ProgressBar/ProgressBar.size.style.ts
  packages/components-native/src/ProgressBar/ProgressBar.style.ts
  packages/components-native/src/ProgressBar/ProgressBar.tsx
  packages/components-native/src/ProgressBar/__snapshots__/ProgressBar.test.tsx.snap
  packages/components-native/src/ProgressBar/types.ts
Labels: approved, design approved, Team Atlantis

#2101 feat(docx): Update code sandbox styling
  packages/site/src/components/CodeViewer.tsx
  packages/site/src/layout/code-theme.css
  packages/site/src/main.css
Labels: approved, Team Atlantis

#2106 fix(design): Updated CSS selectors for dark scrollbar colour [JOB-108461]
  packages/design/src/styles/dark.mode.suffixStyles.css
Labels: approved, Team Atlantis

#2107 chore(design): Added descriptions to semantic tokens JSON files
  packages/design/src/tokens/dark.tokens.json
  packages/design/src/tokens/darkElevated.tokens.json
  packages/design/src/tokens/semanticColor.tokens.json
  packages/design/src/tokens/workflow.tokens.json
Labels: approved, Team Atlantis

#2111 fix(components): Remove unnecessary useRefocusOnActivator from DataListHeaderTile
  packages/components/src/DataList/DataList.utils.tsx
  packages/components/src/DataList/components/DataListHeaderTile/DataListHeaderTile.tsx
Labels: approved, Team Atlantis

#2113 refactor(design): Decouple border width tokens from spacing
  packages/design/src/tokens/border.tokens.json
Labels: approved, Team Atlantis

#2114 docs(design): Adding values for the border
  docs/design/Borders.stories.mdx
Labels: approved, Team Atlantis

#2109 feat(docx): add disambiguation to a few components' Search
  packages/site/src/componentList.ts
  packages/site/src/layout/SearchBox.tsx
  packages/site/src/pages/HomePage.tsx
Labels: approved, Team Atlantis

#2116 chore(deps-dev): upgrade node to 22
  .circleci/config.yml
  .github/workflows/trigger-qa-build.yml
  .nvmrc
  package-lock.json
  package.json
Labels: approved, Team Atlantis

#1966 feat(components): SegmentedControl
  docs/components/SegmentedControl/SegmentedControl.stories.mdx
  docs/components/SegmentedControl/Web.stories.tsx
  packages/components/src/SegmentedControl/SegmentedControl.module.css
  packages/components/src/SegmentedControl/SegmentedControl.module.css.d.ts
  packages/components/src/SegmentedControl/SegmentedControl.test.tsx
  packages/components/src/SegmentedControl/SegmentedControl.tsx
  packages/components/src/SegmentedControl/SegmentedControlBase.tsx
  packages/components/src/SegmentedControl/SegmentedControlOption.tsx
  packages/components/src/SegmentedControl/SegmentedControlProvider.test.tsx
  packages/components/src/SegmentedControl/SegmentedControlProvider.tsx
  packages/components/src/SegmentedControl/index.ts
  packages/components/src/index.tsx
  packages/components/src/utils/meta/meta.json
Labels: Team Atlantis

#2091 feat(components): BREAKING CHANGE: remove Civil Date and Time libraries
  .storybook/components/Playground/constants.ts
  docs/components/DescriptionList/Web.stories.tsx
  docs/components/FormatDate/Web.stories.tsx
  docs/components/FormatTime/FormatTime.stories.mdx
  docs/components/FormatTime/Web.stories.tsx
  docs/components/InputGroup/Web.stories.tsx
  docs/components/InputTime/Web.stories.tsx
  package-lock.json
  package.json
  packages/components/package.json
  packages/components/rollup.config.mjs
  packages/components/src/Countdown/Countdown.tsx
  packages/components/src/FormatDate/FormatDate.test.tsx
  packages/components/src/FormatDate/FormatDate.tsx
  packages/components/src/FormatRelativeDateTime/FormatRelativeDateTime.test.tsx
  packages/components/src/FormatRelativeDateTime/FormatRelativeDateTime.tsx
  packages/components/src/FormatTime/FormatTime.test.tsx
  packages/components/src/FormatTime/FormatTime.tsx
  packages/components/src/InputTime/InputTime.test.tsx
  packages/components/src/InputTime/InputTime.tsx
  packages/components/src/InputTime/InputTimeProps.tsx
  packages/components/src/InputTime/civilTimeConversions.tsx
  packages/components/src/InputTime/hooks/__test__/useTimePredict.test.ts
  packages/components/src/InputTime/time-input-polyfill.d.ts
Labels: approved, Team Atlantis

#2110 feat(components-native): Updated Divider component - added 'vertical' mode and 'testID' prop [JOB-97734]
  docs/components/Divider/Mobile.stories.tsx
  packages/components-native/src/Divider/Divider.test.tsx
  packages/components-native/src/Divider/Divider.tsx
  packages/components-native/src/Divider/DividerHorizontal.style.ts
  packages/components-native/src/Divider/DividerVertical.style.ts
Labels: approved, Team Atlantis

#2112 feat(docx): Refine sidenav and docs
  packages/site/src/assets/JobberLogo.svg.tsx
  packages/site/src/layout/ComponentView.tsx
  packages/site/src/layout/NavMenu.tsx
Labels: review requested, approved, Team Atlantis

#2120 feat(components): Add size prop to SegmentedControl
  docs/components/SegmentedControl/Web.stories.tsx
  packages/components/src/SegmentedControl/SegmentedControl.module.css
  packages/components/src/SegmentedControl/SegmentedControl.module.css.d.ts
  packages/components/src/SegmentedControl/SegmentedControl.tsx
  packages/components/src/SegmentedControl/SegmentedControlBase.tsx
Labels: approved, design approved, Team Atlantis

#2129 docs(docx): Introduce documentation guidelines
  docs/guides/assets/Atlantis_Docs_Show_Do.png
  docs/guides/assets/Atlantis_Docs_Show_Dont.png
  docs/guides/documentation-style.stories.mdx
Labels: review requested, approved, Team Atlantis

#2125 docs(components): Add thumbnail imagery for new component
  packages/site/public/SegmentedControl.png
  packages/site/public/SegmentedControl.svg
Labels: approved, Team Atlantis

#2130 fix(components): Fix DataList Sticky Header Scrolling [JOB-96126]
  packages/components/src/DataList/components/DataListSearch/DataListSearch.module.css
Labels: approved, Team Atlantis

#2136 docs(components): Document composability best practices [107012]
  docs/getting-started-with-react/getting-started-with-react.stories.mdx
  docs/guides/customizing-components.stories.mdx
Labels: approved, Team Atlantis

#2137 feat(components): Add testID to Divider and dynamically reference size and direction props
  packages/components/src/Divider/Divider.module.css
  packages/components/src/Divider/Divider.module.css.d.ts
  packages/components/src/Divider/Divider.test.tsx
  packages/components/src/Divider/Divider.tsx
  packages/components/src/Divider/DividerDirections.module.css
  packages/components/src/Divider/DividerDirections.module.css.d.ts
  packages/components/src/Divider/DividerSizes.module.css
  packages/components/src/Divider/DividerSizes.module.css.d.ts
  packages/components/src/Divider/__snapshots__/Divider.test.tsx.snap
Labels: approved, Team Atlantis

#2134 refactor(components): update Tab focus styles - related to: [JOB-84017]
  packages/components/src/Tabs/Tabs.module.css
Labels: approved, Team Atlantis

#2135 docs(components): Update success Banner example
  docs/components/Banner/Banner.stories.mdx
Labels: approved, Team Atlantis

#2143 docs(components): Adding Countdown to Docs
  packages/site/generateDocs.mjs
  packages/site/src/componentList.ts
  packages/site/src/content/Countdown/Countdown.props.json
  packages/site/src/content/Countdown/index.tsx
  packages/site/src/content/index.ts
Labels: approved, Team Atlantis, docs site

#2141 docs(components): Adding ButtonDismiss to Docs
  packages/site/generateDocs.mjs
  packages/site/public/ButtonDismiss.png
  packages/site/public/ButtonDismiss.svg
  packages/site/src/componentList.ts
  packages/site/src/content/ButtonDismiss/ButtonDismiss.props.json
  packages/site/src/content/ButtonDismiss/index.tsx
  packages/site/src/content/index.ts
Labels: approved, Team Atlantis, docs site

#2139 docs(components): Adding Banner to New Docs Site [JOB-109864]
  packages/site/generateDocs.mjs
  packages/site/src/componentList.ts
  packages/site/src/content/Banner/Banner.props.json
  packages/site/src/content/Banner/index.tsx
  packages/site/src/content/index.ts
  packages/site/src/types/banner.ts
  packages/site/src/types/content.ts
Labels: approved, Team Atlantis, docs site

#2145 docs(components): Adding Heading to Docs
  packages/site/generateDocs.mjs
  packages/site/src/componentList.ts
  packages/site/src/content/Heading/Heading.props.json
  packages/site/src/content/Heading/index.tsx
  packages/site/src/content/index.ts
Labels: approved, Team Atlantis, docs site

#2147 docs(components): Adding Link to Docs
  packages/site/generateDocs.mjs
  packages/site/public/Link.png
  packages/site/public/Link.svg
  packages/site/src/componentList.ts
  packages/site/src/content/Link/Link.props.json
  packages/site/src/content/Link/index.tsx
  packages/site/src/content/index.ts
  packages/site/src/main.css
Labels: approved, Team Atlantis, docs site

#2148 docs(components): Adding Chips to New Docs Site [JOB-109867]
  packages/site/generateDocs.mjs
  packages/site/public/Chips.png
  packages/site/public/Chips.svg
  packages/site/src/componentList.ts
  packages/site/src/content/Chips/Chips.props.json
  packages/site/src/content/Chips/index.tsx
  packages/site/src/content/index.ts
Labels: approved, Team Atlantis, docs site

#2144 docs(components): Adding Emphasis to Docs
  packages/site/generateDocs.mjs
  packages/site/src/componentList.ts
  packages/site/src/content/Emphasis/Emphasis.props.json
  packages/site/src/content/Emphasis/index.tsx
  packages/site/src/content/index.ts
  packages/site/src/types/content.ts
Labels: approved, Team Atlantis, docs site

#2150 docs(components): Adding Icon to New Docs Site [JOB-110366]
  packages/site/generateDocs.mjs
  packages/site/public/Icon.png
  packages/site/public/Icon.svg
  packages/site/src/componentList.ts
  packages/site/src/content/Icon/Icon.props.json
  packages/site/src/content/Icon/index.tsx
  packages/site/src/content/index.ts
Labels: approved, Team Atlantis, docs site

#2152 docs: Remove description from component indexes and page [JOB-110417]
  packages/site/src/content/AnimatedPresence/index.tsx
  packages/site/src/content/AnimatedSwitcher/index.tsx
  packages/site/src/content/Autocomplete/index.tsx
  packages/site/src/content/Button/index.tsx
  packages/site/src/content/ButtonDismiss/index.tsx
  packages/site/src/content/Checkbox/index.tsx
  packages/site/src/content/Chip/index.tsx
  packages/site/src/content/Countdown/index.tsx
  packages/site/src/content/Disclosure/index.tsx
  packages/site/src/content/StatusLabel/index.tsx
  packages/site/src/content/Switch/index.tsx
  packages/site/src/layout/ComponentView.tsx
Labels: approved, Team Atlantis

#2138 feat(components): Add customRender to DataList EmptyState
  docs/components/DataList/DataList.stories.mdx
  docs/components/DataList/Web.stories.tsx
  packages/components/src/DataList/DataList.types.ts
  packages/components/src/DataList/components/DataListEmptyState/DataListEmptyState.test.tsx
  packages/components/src/DataList/components/DataListEmptyState/DataListEmptyState.tsx
  packages/components/src/DataList/index.ts
Labels: approved, Team Atlantis

#2142 docs(components): Adding Card to New Docs Site [JOB-109866]
  packages/site/generateDocs.mjs
  packages/site/src/componentList.ts
  packages/site/src/content/Card/Card.props.json
  packages/site/src/content/Card/index.tsx
  packages/site/src/content/index.ts
Labels: approved, Team Atlantis, docs site

#2090 fix(components): Fix SectionHeader Overlap
  packages/components/src/List/SectionHeader.module.css
  packages/components/src/List/SectionHeader.module.css.d.ts
Labels: approved, design approved, Team Atlantis

#2151 docs(components): Adding InlineLabel to New Docs Site [JOB-110397]
  packages/site/generateDocs.mjs
  packages/site/src/componentList.ts
  packages/site/src/content/InlineLabel/InlineLabel.props.json
  packages/site/src/content/InlineLabel/index.tsx
  packages/site/src/content/index.ts
Labels: approved, Team Atlantis, docs site

#2127 docs(components): Adding Avatar to Docs
  packages/site/generateDocs.mjs
  packages/site/src/componentList.ts
  packages/site/src/content/Avatar/Avatar.props.json
  packages/site/src/content/Avatar/index.tsx
  packages/site/src/content/index.ts
Labels: approved, Team Atlantis, docs site

#2153 docs(components): Adding ProgressBar to New Docs Site [JOB-110399]
  packages/site/generateDocs.mjs
  packages/site/src/componentList.ts
  packages/site/src/content/ProgressBar/ProgressBar.props.json
  packages/site/src/content/ProgressBar/index.tsx
  packages/site/src/content/index.ts
  packages/site/src/types/content.ts
Labels: approved, Team Atlantis

#2156 feat(components): DataList to Docs
  packages/site/generateDocs.mjs
  packages/site/src/componentList.ts
  packages/site/src/content/Autocomplete/Autocomplete.props.json
  packages/site/src/content/DataList/DataList.props.json
  packages/site/src/content/DataList/index.tsx
  packages/site/src/content/index.ts
Labels: approved, Team Atlantis

#2164 docs: add remaining util thumbnails
  packages/site/public/DataDump.png
  packages/site/public/DataDump.svg
  packages/site/public/FormatDate.png
  packages/site/public/FormatDate.svg
  packages/site/public/FormatEmail.png
  packages/site/public/FormatEmail.svg
  packages/site/public/FormatTime-1.png
  packages/site/public/FormatTime-1.svg
  packages/site/public/FormatTime.png
  packages/site/public/FormatTime.svg
Labels: approved, Team Atlantis, docs site

#2161 docs: replace datalist thumbnails with correct size
  packages/site/public/DataList.png
  packages/site/public/DataList.svg
Labels: approved, Team Atlantis, docs site

#2162 docs(components): Adding FormateDate to New Docs Site [JOB-110497]
  packages/site/generateDocs.mjs
  packages/site/src/componentList.ts
  packages/site/src/content/FormatDate/FormatDate.props.json
  packages/site/src/content/FormatDate/index.tsx
  packages/site/src/content/index.ts
Labels: approved, Team Atlantis

#2163 docs: add placeholder thumbnail image
  packages/site/public/Placeholder.png
  packages/site/public/Placeholder.svg
Labels: approved, Team Atlantis, docs site

#2159 docs(components): Adding DataDump to New Docs Site [JOB-109864]
  packages/site/generateDocs.mjs
  packages/site/src/componentList.ts
  packages/site/src/content/DataDump/DataDump.props.json
  packages/site/src/content/DataDump/index.tsx
  packages/site/src/content/index.ts
Labels: approved, Team Atlantis

#2157 docs(components): Adding StatusIndicator to New Docs Site [JOB-110402]
  packages/site/generateDocs.mjs
  packages/site/src/componentList.ts
  packages/site/src/content/StatusIndicator/StatusIndicator.props.json
  packages/site/src/content/StatusIndicator/index.tsx
  packages/site/src/content/index.ts
Labels: approved, Team Atlantis

#2165 docs(components): Adding FormatEmail to New Docs Site [JOB-110499]
  packages/site/generateDocs.mjs
  packages/site/src/componentList.ts
  packages/site/src/content/Autocomplete/Autocomplete.props.json
  packages/site/src/content/FormatEmail/FormatEmail.props.json
  packages/site/src/content/FormatEmail/index.tsx
  packages/site/src/content/index.ts
Labels: approved, Team Atlantis, docs site

#2158 docs(components): Adding Glimmer to New Docs Site [JOB-110396]
  packages/components/src/Glimmer/Glimmer.tsx
  packages/site/generateDocs.mjs
  packages/site/src/componentList.ts
  packages/site/src/components/StorybookOverrides.tsx
  packages/site/src/content/Glimmer/Glimmer.props.json
  packages/site/src/content/Glimmer/index.tsx
  packages/site/src/content/index.ts
Labels: approved, Team Atlantis, docs site

#2169 docs(components): Adding FormatRelativeDateTime to New Docs Site [JOB-110500]
  packages/site/generateDocs.mjs
  packages/site/src/componentList.ts
  packages/site/src/content/FormatRelativeDateTime/FormatRelativeDateTime.props.json
  packages/site/src/content/FormatRelativeDateTime/index.tsx
  packages/site/src/content/index.ts
Labels: approved, Team Atlantis

#2171 docs(components): Adding InputDate to New Docs Site [JOB-110588]
  packages/site/generateDocs.mjs
  packages/site/src/componentList.ts
  packages/site/src/content/InputDate/InputDate.props.json
  packages/site/src/content/InputDate/index.tsx
  packages/site/src/content/index.ts
Labels: approved, Team Atlantis, docs site

#2155 feat(components): Adding DatePicker to Docs
  packages/site/generateDocs.mjs
  packages/site/src/componentList.ts
  packages/site/src/content/Autocomplete/Autocomplete.props.json
  packages/site/src/content/DatePicker/DatePicker.props.json
  packages/site/src/content/DatePicker/index.tsx
  packages/site/src/content/index.ts
Labels: approved, Team Atlantis, docs site

#2154 feat(components): Adding Spinner to Docs Site
  .vscode/docs.code-snippets
  packages/site/generateDocs.mjs
  packages/site/src/componentList.ts
  packages/site/src/content/Spinner/Spinner.props.json
  packages/site/src/content/Spinner/index.tsx
  packages/site/src/content/index.ts
Labels: approved, Team Atlantis, docs site

#2172 docs(components): Adding InputEmail to New Docs Site [JOB-110589]
  packages/site/generateDocs.mjs
  packages/site/public/InputEmail.png
  packages/site/public/InputEmail.svg
  packages/site/src/componentList.ts
  packages/site/src/content/InputEmail/InputEmail.props.json
  packages/site/src/content/InputEmail/index.tsx
  packages/site/src/content/index.ts
Labels: approved, Team Atlantis, docs site

#2173 docs(components): Adding InputPassword to New Docs Site [JOB-110593]
  packages/site/generateDocs.mjs
  packages/site/src/componentList.ts
  packages/site/src/content/InputPassword/InputPassword.props.json
  packages/site/src/content/InputPassword/index.tsx
  packages/site/src/content/index.ts
Labels: approved, Team Atlantis, docs site

#2177 docs(components): add more detail to buttondismiss
  docs/components/ButtonDismiss/ButtonDismiss.stories.mdx
Labels: approved, Team Atlantis

#2178 docs(components): add outstanding input thumbnails
  packages/site/public/InputNumber.png
  packages/site/public/InputNumber.svg
  packages/site/public/InputTime.png
  packages/site/public/InputTime.svg
Labels: approved, Team Atlantis
