Repository GetJobber/atlantis, pull requests merged in 2024-10, with the labels that each got.

#2037 refactor(hooks): Add useOnMount and useCallbackRef [96563]
  docs/hooks/useCallbackRef.stories.mdx
  docs/hooks/useIsMounted.stories.mdx
  docs/hooks/useOnMount.stories.mdx
  packages/hooks/README.md
  packages/hooks/src/index.ts
  packages/hooks/src/useCallbackRef/index.ts
  packages/hooks/src/useCallbackRef/useCallbackRef.test.tsx
  packages/hooks/src/useCallbackRef/useCallbackRef.ts
  packages/hooks/src/useIsMounted/useIsMounted.ts
  packages/hooks/src/useOnMount/index.ts
  packages/hooks/src/useOnMount/useOnMount.test.tsx
  packages/hooks/src/useOnMount/useOnMount.ts
Labels: approved, Team Atlantis

#2049 feat(deps): Update storybook to the latest patch version (7.6.20)
  package-lock.json
  package.json
  packages/components/src/Disclosure/Disclosure.tsx
Labels: approved, Team Atlantis

#2035 feat(components): Re-separate Chip from Chips w/Background Color Fixes
  docs/components/Chip/Chip.stories.mdx
  docs/components/Chips/Chips.stories.mdx
  docs/components/Chips/Web.stories.tsx
  packages/components/src/Chip/Chip.css
  packages/components/src/Chip/Chip.test.tsx
  packages/components/src/Chip/Chip.tsx
  packages/components/src/Chip/Chip.types.d.ts
  packages/components/src/Chip/components/ChipSuffix/Chip.Suffix.tsx
  packages/components/src/Chips/ChipsTypes.tsx
  packages/components/src/Chips/InternalChip.css
  packages/components/src/Chips/InternalChip.css.d.ts
  packages/components/src/Chips/InternalChip.tsx
  packages/components/src/Chips/InternalChipButton.tsx
  packages/components/src/Chips/InternalChipDismissible/__tests__/InternalChipDismissible.test.tsx
  packages/components/src/Chips/InternalChipMultiSelect.tsx
  packages/components/src/Chips/InternalChipSingleSelect.tsx
  packages/components/src/Chips/tests/InternalChip.test.tsx
  packages/components/src/Tooltip/Tooltip.tsx
Labels: approved, design review requested, Team Atlantis

#2051 docs(components): use semantic colors in `SelectableChip` story
  packages/components/src/Chip/components/ChipSelectable/ChipSelectable.tsx
Labels: approved, Team Atlantis

#2047 feat(components): Make Suffix Optional on Single and Multi Select Chips
  docs/hooks/useOnMount.stories.mdx
  packages/components/src/Chips/ChipsTypes.tsx
  packages/components/src/Chips/InternalChipMultiSelect.tsx
  packages/components/src/Chips/InternalChipSingleSelect.tsx
  packages/components/src/Chips/hooks/useInternalChip.tsx
  packages/components/src/Chips/tests/InternalChipMultiSelect.test.tsx
  packages/components/src/Chips/tests/InternalChipSingleSelect.test.tsx
Labels: approved, design approved, Team Atlantis

#2044 feat(design): Add new colors into base palette [JOB-105102]
  docs/design/Colors.stories.mdx
  packages/design/src/tokens/baseColor.tokens.json
  packages/design/src/tokens/dark.tokens.json
Labels: approved, Team Atlantis

#2054 feat(components): Decouple shadow from clickability [JOB-105101]
  docs/components/Card/Web.stories.tsx
  packages/components/src/Card/Card.module.css
  packages/components/src/Card/Card.tsx
  packages/components/src/Card/CardElevations.module.css
  packages/components/src/Card/CardElevations.module.css.d.ts
  packages/components/src/Card/tests/Card.test.tsx
  packages/components/src/Card/types.ts
Labels: approved, design approved, Team Atlantis

#2071 docs(components): Update `Card` docs
  docs/components/Card/Card.stories.mdx
Labels: approved, Team Atlantis

#2070 refactor(components): export `DataListObject` type
  packages/components/src/DataList/index.ts
Labels: approved, Team Atlantis

#2072 fix(docx): Fix bug in PR title generator
  .storybook/components/PullRequestGenerator/PullRequestGenerator.tsx
Labels: approved, Team Atlantis

#2073 feat(components): Update apple icon and Add bank icon [JOB-106774]
  docs/components/Icon/Icon.stories.mdx
  packages/components-native/src/Icon/__snapshots__/Icon.test.tsx.snap
  packages/components/src/Icon/__snapshots__/Icon.test.tsx.snap
  packages/design/src/icons/apple.svg
  packages/design/src/icons/bank.svg
Labels: approved, design approved, Team Atlantis

#2055 feat(components): Add keepOpenOnClick prop to Combobox.Action
  docs/components/Combobox/Combobox.stories.mdx
  docs/components/Combobox/Web.stories.tsx
  packages/components/src/Combobox/Combobox.test.tsx
  packages/components/src/Combobox/Combobox.types.ts
  packages/components/src/Combobox/components/ComboboxAction/ComboboxAction.pom.tsx
  packages/components/src/Combobox/components/ComboboxAction/ComboboxAction.test.tsx
  packages/components/src/Combobox/components/ComboboxAction/ComboboxAction.tsx
Labels: approved, Team Atlantis

#2058 chore: Clean up deps and npm audit issues
  package-lock.json
  package.json
  packages/components-native/package.json
  packages/components-native/src/InputText/InputText.tsx
  packages/components/package.json
  packages/design/package.json
  packages/design/src/index.ts
  packages/docx/package.json
  packages/formatters/package.json
  packages/generators/index.mjs
  packages/hooks/package.json
  plopfile.js
  plopfile.mjs
Labels: approved, Team Atlantis

#2074 refactor(components): move Grid to leverage compositional patterns
  packages/components/src/Grid/Grid.tsx
  packages/components/src/Grid/GridCell.test.tsx
  packages/components/src/Grid/GridCell.tsx
  packages/components/src/Grid/GridCell/GridCell.module.css
  packages/components/src/Grid/GridCell/GridCell.module.css.d.ts
  packages/components/src/Grid/GridCell/GridCell.test.tsx
  packages/components/src/Grid/GridCell/GridCell.tsx
  packages/components/src/Grid/GridCell/index.ts
  packages/components/src/Grid/InternalGridCell/index.ts
Labels: approved, Team Atlantis

#2076 fix(components-native): ContentOverlay Heading alignment should not change with presence of dismiss button
  packages/components-native/src/ContentOverlay/ContentOverlay.style.ts
  packages/components-native/src/ContentOverlay/ContentOverlay.tsx
Labels: approved, design approved, Team Atlantis

#2077 fix(components): Fixed issue where GridCell could no longer have no children
  packages/components/src/Grid/GridCell/GridCell.tsx
Labels: approved, Team Atlantis

#2069 fix(components): DataList toggle sorting header doesn't transpose id and key
  packages/components/src/DataList/DataList.test.tsx
  packages/components/src/DataList/components/DataListHeaderTile/DataListHeaderTile.tsx
Labels: approved, Team Atlantis

#2075 feat(components): Allow Fully Custom Combobox Activator
  docs/components/Combobox/Combobox.stories.mdx
  docs/components/Combobox/Web.stories.tsx
  packages/components/src/Combobox/Combobox.tsx
  packages/components/src/Combobox/Combobox.types.ts
  packages/components/src/Combobox/ComboboxProvider.tsx
  packages/components/src/Combobox/components/ComboboxActivator/ComboboxActivator.test.tsx
  packages/components/src/Combobox/components/ComboboxActivator/ComboboxActivator.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.tsx
  packages/components/src/Combobox/components/ComboboxTrigger/ComboboxTrigger.test.tsx
  packages/components/src/Combobox/components/ComboboxTrigger/ComboboxTrigger.tsx
  packages/components/src/Combobox/constants.ts
  packages/components/src/Combobox/hooks/useCombobox.ts
  packages/components/src/Combobox/hooks/useComboboxActivatorAccessibility.ts
  packages/components/src/Combobox/hooks/useMakeComboboxHandlers.ts
  packages/components/src/Combobox/index.ts
Labels: approved, Team Atlantis

#2080 fix(components): JOB-104988 Add accessibility attributes (also helps with testing)
  packages/components/src/DataList/components/DataListHeaderTile/DataListHeaderTile.tsx
  packages/components/src/DataList/components/DataListHeaderTile/DataListSortingArrows.tsx
Labels: approved, Team Atlantis

#2082 fix(components): Fix Combobox Dependencies and Test Mocks
  packages/components/src/Combobox/components/ComboboxAction/ComboboxAction.pom.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.test.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContentList/ComboboxContentList.test.tsx
  packages/components/src/Combobox/components/ComboboxOption/ComboboxOption.pom.tsx
  packages/components/src/Combobox/hooks/useMakeComboboxHandlers.ts
Labels: approved, Team Atlantis

#2062 docs(components): Use color tokens for base colors in Storybook
  docs/design/Colors.stories.mdx
Labels: approved, Team Atlantis

#2083 refactor(components): Replace ToggleOpen with HandleOpen
  docs/components/Combobox/Combobox.stories.mdx
  docs/components/Combobox/Web.stories.tsx
  packages/components/src/Combobox/Combobox.test.tsx
  packages/components/src/Combobox/Combobox.tsx
  packages/components/src/Combobox/Combobox.types.ts
  packages/components/src/Combobox/ComboboxProvider.tsx
  packages/components/src/Combobox/components/ComboboxAction/ComboboxAction.pom.tsx
  packages/components/src/Combobox/components/ComboboxActivator/ComboboxActivator.test.tsx
  packages/components/src/Combobox/components/ComboboxActivator/ComboboxActivator.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.test.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContentList/ComboboxContentList.test.tsx
  packages/components/src/Combobox/components/ComboboxTrigger/ComboboxTrigger.test.tsx
  packages/components/src/Combobox/components/ComboboxTrigger/ComboboxTrigger.tsx
  packages/components/src/Combobox/hooks/useCombobox.ts
  packages/components/src/Combobox/hooks/useMakeComboboxHandlers.ts
  packages/components/src/DataList/components/DataListFilters/components/DataListSort/DataListSort.test.tsx
Labels: approved, Team Atlantis

#2088 feat(components): Add support for controlled disclosures
  docs/components/Disclosure/Web.stories.tsx
  packages/components/src/Disclosure/Disclosure.test.tsx
  packages/components/src/Disclosure/Disclosure.tsx
  packages/components/src/Disclosure/__snapshots__/Disclosure.test.tsx.snap
Labels: approved, Team Atlantis

#2092 docs(components): better disambiguate InlineLabel and StatusLabel [JOB-108048]
  docs/components/InlineLabel/InlineLabel.stories.mdx
  docs/components/StatusLabel/StatusLabel.stories.mdx
Labels: approved, Team Atlantis
