Repository GetJobber/atlantis, pull requests merged in 2024-05, with the labels that each got.

#1880 fix(components): use semantic values in combobox
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContentList/ComboboxContentList.css
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContentSearch/ComboboxContentSearch.css
Labels: approved, Team Atlantis

#1879 chore(components): Delete useAtlantisConfig
  packages/components/src/utils/useAtlantisConfig.ts
Labels: approved, Team Atlantis

#1877 fix(components): Reduce Scope of Safari Scrollbar Issue
  packages/components/src/FormField/FormField.css
  packages/components/src/FormField/FormField.css.d.ts
  packages/components/src/FormField/FormFieldWrapper.tsx
  packages/components/src/FormField/hooks/useIsSafari.ts
Labels: approved, design review requested, Team Atlantis

#1884 feat(components): add textCase=none to Typography
  packages/components/src/Menu/Menu.tsx
  packages/components/src/Typography/Typography.test.tsx
  packages/components/src/Typography/css/TextCases.css
  packages/components/src/Typography/css/TextCases.css.d.ts
Labels: approved, Team Atlantis

#1873 feat(design): overhaul the base color palette
  packages/components-native/src/Disclosure/__snapshots__/Disclosure.test.tsx.snap
  packages/components-native/src/Heading/__snapshots__/Heading.test.tsx.snap
  packages/components-native/src/Icon/__snapshots__/Icon.test.tsx.snap
  packages/components-native/src/InputFieldWrapper/InputFieldWrapper.test.tsx
  packages/components-native/src/ProgressBar/__snapshots__/ProgressBar.test.tsx.snap
  packages/components-native/src/StatusLabel/__snapshots__/StatusLabel.test.tsx.snap
  packages/components-native/src/Switch/components/BaseSwitch/__snapshots__/BaseSwitch.test.tsx.snap
  packages/components-native/src/Text/__snapshots__/Text.test.tsx.snap
  packages/components-native/src/TextList/__snapshots__/TextList.test.tsx.snap
  packages/components-native/src/ThumbnailList/__snapshots__/ThumbnailList.test.tsx.snap
  packages/components-native/src/Typography/__snapshots__/Typography.test.tsx.snap
  packages/components/src/Checkbox/Checkbox.tsx
  packages/components/src/Checkbox/__snapshots__/Checkbox.test.tsx.snap
  packages/components/src/FormField/FormField.css
  packages/components/src/InlineLabel/InlineLabel.css
  packages/components/src/InlineLabel/InlineLabel.css.d.ts
  packages/components/src/Spinner/Spinner.css
  packages/design/src/colors.css
Labels: approved, Team Atlantis

#1881 fix(components): Portal Menu Content
  packages/components/src/FormField/hooks/useActiveElement.ts
  packages/components/src/FormField/hooks/useFormFieldFocus.ts
  packages/components/src/Menu/Menu.css
  packages/components/src/Menu/Menu.css.d.ts
  packages/components/src/Menu/Menu.test.tsx
  packages/components/src/Menu/Menu.tsx
  packages/components/src/Menu/__snapshots__/Menu.test.tsx.snap
  packages/components/src/Page/__snapshots__/Page.test.tsx.snap
  packages/hooks/README.mdx
  packages/hooks/src/index.ts
  packages/hooks/src/useWindowDimensions/index.ts
  packages/hooks/src/useWindowDimensions/useWIndowDimensions.test.tsx
  packages/hooks/src/useWindowDimensions/useWindowDimensions.stories.mdx
  packages/hooks/src/useWindowDimensions/useWindowDimensions.ts
Labels: approved, design approved, Team Atlantis

#1887 fix(components): Code Tab CSS Issue
  .storybook/components/Playground/Playground.tsx
Labels: approved, Team Atlantis

#1889 fix(components): Allow type on submit action button
  packages/components/src/Button/Button.tsx
Labels: approved, Team Atlantis

#1891 revert: Revert "fix(components): Portal Menu Content"
  packages/components/src/FormField/hooks/useActiveElement.ts
  packages/components/src/FormField/hooks/useFormFieldFocus.ts
  packages/components/src/Menu/Menu.css
  packages/components/src/Menu/Menu.css.d.ts
  packages/components/src/Menu/Menu.test.tsx
  packages/components/src/Menu/Menu.tsx
  packages/components/src/Menu/__snapshots__/Menu.test.tsx.snap
  packages/components/src/Page/__snapshots__/Page.test.tsx.snap
  packages/hooks/README.mdx
  packages/hooks/src/index.ts
  packages/hooks/src/useWindowDimensions/index.ts
  packages/hooks/src/useWindowDimensions/useWIndowDimensions.test.tsx
  packages/hooks/src/useWindowDimensions/useWindowDimensions.stories.mdx
  packages/hooks/src/useWindowDimensions/useWindowDimensions.ts
Labels: in review, approved, Team Atlantis

#1888 feat(components): Add support for link click listener for Markdown component (JOB-96041)
  packages/components/src/FeatureSwitch/__snapshots__/FeatureSwitch.test.tsx.snap
  packages/components/src/Markdown/Markdown.test.tsx
  packages/components/src/Markdown/Markdown.tsx
  packages/components/src/Markdown/__snapshots__/Markdown.test.tsx.snap
  packages/components/src/Page/__snapshots__/Page.test.tsx.snap
Labels: approved, Team Atlantis, Team Jobber Assistant

#1892 docs: Fix Tabs story code tab
  docs/components/Tabs/Web.stories.tsx
Labels: approved, Team Atlantis

#1893 docs: Documentation updates
  docs/README.md
  docs/changelog/breaking-changes.stories.mdx
Labels: approved, Team Atlantis

#1895 feat(components-native): Export typography max font scaling in components-native
  packages/components-native/src/Heading/Heading.tsx
  packages/components-native/src/Heading/index.ts
  packages/components-native/src/Text/Text.tsx
  packages/components-native/src/Text/index.ts
Labels: approved, Team Atlantis

#1900 fix(design): Reduce Shadow Radius for MobileShadows
  packages/design/src/getMobileShadows.js
Labels: in review, approved, design review requested, Team Atlantis

#1899 refactor(components): Update Styling of Tabs
  packages/components/src/Tabs/Tabs.css
  packages/components/src/Tabs/Tabs.tsx
  packages/components/src/Tabs/__snapshots__/Tabs.test.tsx.snap
Labels: approved, Team Atlantis

#1898 fix(components): Portalled Menu Take 2
  packages/components/src/FormField/hooks/useActiveElement.ts
  packages/components/src/FormField/hooks/useFormFieldFocus.ts
  packages/components/src/Menu/Menu.css
  packages/components/src/Menu/Menu.css.d.ts
  packages/components/src/Menu/Menu.test.tsx
  packages/components/src/Menu/Menu.tsx
  packages/components/src/Menu/__snapshots__/Menu.test.tsx.snap
  packages/components/src/Page/__snapshots__/Page.test.tsx.snap
  packages/hooks/README.mdx
  packages/hooks/src/index.ts
  packages/hooks/src/useWindowDimensions/index.ts
  packages/hooks/src/useWindowDimensions/useWIndowDimensions.test.tsx
  packages/hooks/src/useWindowDimensions/useWindowDimensions.stories.mdx
  packages/hooks/src/useWindowDimensions/useWindowDimensions.ts
Labels: approved, Team Atlantis

#1906 fix(components): Increase zIndex for Menu
  packages/components/src/Menu/Menu.css
Labels: approved, Team Atlantis

#1903 chore: Update Testing Instructions in PR descriptions
  .github/pull_request_template.md
Labels: approved, Team Atlantis

#1902 fix(components-native): Dismiss keyboard on Date and Time Picker being opened
  docs/components/InputPressable/InputPressable.stories.mdx
  packages/components-native/src/InputDate/InputDate.test.tsx
  packages/components-native/src/InputDate/InputDate.tsx
  packages/components-native/src/InputTime/InputTime.test.tsx
  packages/components-native/src/InputTime/InputTime.tsx
Labels: approved, Team Atlantis

#1907 fix(components): Menu Small Screen zIndex Layering
  packages/components/src/Menu/Menu.css
Labels: approved, Team Atlantis

#1901 fix(components): fixes a bug where we call setState inside of the react render cycle
  packages/components/src/ConfirmationModal/ConfirmationModal.tsx
  packages/components/src/ConfirmationModal/tests/interaction-ConfirmationModal.test.tsx
Labels: approved, Team Atlantis

#1905 fix(components): Animated switcher
  packages/components/src/AnimatedSwitcher/AnimatedSwitcher.tsx
Labels: approved, Team Atlantis
