Repository GetJobber/atlantis, pull requests merged in 2024-02, with the labels that each got.

#1733 feat(components): Animated presence
  docs/components/AnimatedPresence/AnimatedPresence.stories.mdx
  docs/components/AnimatedPresence/Web.stories.tsx
  packages/components/src/AnimatedPresence/AnimatedPresence.pom.tsx
  packages/components/src/AnimatedPresence/AnimatedPresence.test.tsx
  packages/components/src/AnimatedPresence/AnimatedPresence.transitions.tsx
  packages/components/src/AnimatedPresence/AnimatedPresence.tsx
  packages/components/src/AnimatedPresence/hooks/usePreviousValue.ts
  packages/components/src/AnimatedPresence/index.ts
Labels: approved, Team Atlantis

#1748 fix(components): Extract and Export Sortable Type
  packages/components/src/DataList/DataList.types.ts
  packages/components/src/DataList/index.ts
Labels: approved, Team Atlantis

#1750 fix(hooks): support add and remove listener on mockViewportWidth
  packages/hooks/src/useBreakpoints/mockViewportWidth/mockViewportWidth.ts
Labels: approved, Team Atlantis

#1751 feat(generators): Modifying css naming pattern in component generator to follow css modules convention [JOB-87530]
  packages/generators/templates/component/{{name}}.module.css
  packages/generators/templates/component/{{name}}.module.css.d.ts
  packages/generators/templates/component/{{name}}.tsx
Labels: approved, Team Atlantis, Team Frontend Foundations

#1746 feat(components): Add support for load more trigger to combobox
  docs/components/Combobox/Web.stories.tsx
  packages/components/src/Combobox/Combobox.test.tsx
  packages/components/src/Combobox/Combobox.tsx
  packages/components/src/Combobox/Combobox.types.ts
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContentList/ComboboxContentList.css
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContentList/ComboboxContentList.css.d.ts
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContentList/ComboboxContentList.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxLoadMore/ComboboxLoadMore.css
  packages/components/src/Combobox/components/ComboboxContent/ComboboxLoadMore/ComboboxLoadMore.css.d.ts
  packages/components/src/Combobox/components/ComboboxContent/ComboboxLoadMore/ComboboxLoadMore.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxLoadMore/index.ts
Labels: Team Atlantis

#1754 fix: ensure loading spinner shows up on combobox when actions are there
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContentList/ComboboxContentList.css
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContentList/ComboboxContentList.tsx
Labels: approved, Team Atlantis

#1756 fix(components): clearing search term in Combobox after clicking on clear button
  packages/components/src/Combobox/Combobox.test.tsx
  packages/components/src/Combobox/hooks/useCombobox.ts
  packages/components/src/Combobox/hooks/useMakeComboboxHandlers.ts
Labels: approved, Team Atlantis

#1755 feat(components): Conditionally render DataListStickyHeader based on presence of children
  packages/components/src/DataList/DataList.const.ts
  packages/components/src/DataList/DataList.test.tsx
  packages/components/src/DataList/DataList.tsx
  packages/components/src/DataList/__POM__/DataList.selectable.pom.tsx
  packages/components/src/DataList/components/DataListStickyHeader/DataListStickyHeader.tsx
Labels: approved, Team Atlantis

#1753 feat(components-native): JOB-88274 Prep inputs for retheme
  packages/components-native/src/InputDate/InputDate.tsx
  packages/components-native/src/InputFieldWrapper/CommonInputStyles.style.ts
  packages/components-native/src/InputFieldWrapper/InputFieldWrapper.style.ts
  packages/components-native/src/InputFieldWrapper/InputFieldWrapper.test.tsx
  packages/components-native/src/InputFieldWrapper/InputFieldWrapper.tsx
  packages/components-native/src/InputPressable/InputPressable.style.ts
  packages/components-native/src/InputPressable/InputPressable.tsx
  packages/components-native/src/InputSearch/InputSearch.style.ts
  packages/components-native/src/InputText/InputText.style.ts
  packages/components-native/src/InputText/InputText.tsx
  packages/components-native/src/InputTime/InputTime.tsx
  packages/components-native/src/Select/Select.style.ts
  packages/components-native/src/Select/Select.tsx
Labels: approved, Team Atlantis

#1758 feat(components): Render DataListStickyHeader when headers are present
  packages/components/src/DataList/DataList.css
  packages/components/src/DataList/DataList.test.tsx
  packages/components/src/DataList/DataList.tsx
Labels: approved, Team Atlantis

#1760 fix(components-native): remove action label letter spacing
  packages/components-native/src/ActionLabel/ActionLabel.test.tsx
  packages/components-native/src/ActionLabel/ActionLabel.tsx
Labels: approved, Team Atlantis

#1763 docs: use jobber fonts on manager js
  .storybook/manager.js
Labels: approved, Team Atlantis

#1761 fix(components-native): hard code status label radius
  packages/components-native/src/StatusLabel/StatusLabel.style.ts
  packages/components-native/src/StatusLabel/__snapshots__/StatusLabel.test.tsx.snap
Labels: approved, Team Atlantis

#1765 feat(components-native): Update Heading styles
  packages/components-native/src/Heading/Heading.tsx
  packages/components-native/src/Heading/__snapshots__/Heading.test.tsx.snap
Labels: approved, Team Atlantis

#1766 refactor(components): Increase coverage of DataListHeaderTile
  packages/components/src/DataList/DataList.test.tsx
Labels: approved, Team Atlantis

#1764 fix(components-native): Apply input transform in InputText before trim [OPS-20241]
  packages/components-native/src/InputText/InputText.test.tsx
  packages/components-native/src/InputText/InputText.tsx
Labels: approved, Team Atlantis

#1772 docs(components-native): Add components-native changelog page
  docs/changelog/components-native.stories.mdx
Labels: approved, Team Atlantis

#1768 fix(components): Always show clear when there are selected options in ComboBox
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.tsx
Labels: approved, Team Atlantis

#1776 refactor(components): Move useSafeLayoutEffect to @jobber/hooks and update its usages
  packages/components/src/Autocomplete/Menu.tsx
  packages/components/src/InputText/InputText.tsx
  packages/components/src/Menu/Menu.tsx
  packages/components/src/Tooltip/Tooltip.tsx
  packages/hooks/src/index.ts
  packages/hooks/src/useIsMounted/useIsMounted.ts
  packages/hooks/src/useSafeLayoutEffect/index.ts
  packages/hooks/src/useSafeLayoutEffect/useSafeLayoutEffect.ts
Labels: approved, Team Atlantis

#1770 feat: Add unscheduled icon
  packages/design/assets/icons/unscheduled.svg
Labels: approved

#1782 fix(components): keep ComboboxContentHeader label and action aligned across themes
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContentHeader/ComboboxContentHeader.css
Labels: approved, Team Atlantis

#1781 feat(components): Adds a role of status to the Glimmer component
  packages/components/src/Glimmer/Glimmer.tsx
Labels: approved, Team Atlantis

#1784 feat(components): Bring back card accent in retheme
  packages/components/src/Card/Card.css
Labels: approved, Team Atlantis

#1737 fix(components): Removing uuid in web and replacing with useId
  package-lock.json
  packages/components/__mocks__/uuid.ts
  packages/components/package.json
  packages/components/rollup.config.js
  packages/components/src/Autocomplete/__snapshots__/Autocomplete.test.tsx.snap
  packages/components/src/Checkbox/Checkbox.tsx
  packages/components/src/Checkbox/__snapshots__/Checkbox.test.tsx.snap
  packages/components/src/Chips/InternalChipDismissible/hooks/useInternalChipDismissibleInput.tsx
  packages/components/src/Chips/InternalChipSingleSelect.tsx
  packages/components/src/FormField/FormField.tsx
  packages/components/src/FormField/__snapshots__/FormField.test.tsx.snap
  packages/components/src/InputFile/InputFile.tsx
  packages/components/src/InputNumber/InputNumber.test.tsx
  packages/components/src/InputPassword/__snapshots__/InputPassword.test.tsx.snap
  packages/components/src/InputText/InputText.test.tsx
  packages/components/src/Menu/Menu.test.tsx
  packages/components/src/Menu/Menu.tsx
  packages/components/src/Menu/__snapshots__/Menu.test.tsx.snap
  packages/components/src/Page/__snapshots__/Page.test.tsx.snap
  packages/components/src/RadioGroup/RadioGroup.test.tsx
  packages/components/src/RadioGroup/RadioGroup.tsx
  packages/components/src/RadioGroup/RadioOption.tsx
  packages/components/src/RadioGroup/__snapshots__/RadioGroup.test.tsx.snap
  packages/components/src/RecurringSelect/components/DayOfMonthSelect.tsx
  packages/components/src/RecurringSelect/components/WeeklySelect.tsx
  packages/components/src/Select/__snapshots__/Select.test.tsx.snap
Labels: approved, Team Atlantis
