Repository GetJobber/atlantis, pull requests merged in 2024-03, with the labels that each got.

#1786 feat(components): Added accessible name for combobox trigger
  packages/components/src/Combobox/Combobox.test.tsx
  packages/components/src/Combobox/components/ComboboxTrigger/ComboboxTrigger.test.tsx
  packages/components/src/Combobox/components/ComboboxTrigger/ComboboxTrigger.tsx
  packages/hooks/src/index.ts
Labels: approved, Team Atlantis

#1704 fix(components): prevent multiple breakpoints being registered within DataList
  packages/components/src/DataList/DataList.tsx
  packages/components/src/DataList/DataList.types.ts
  packages/components/src/DataList/components/DataListLayout/DataListLayout.tsx
  packages/components/src/DataList/context/DataListContext/DataListContext.tsx
  packages/components/src/DataList/hooks/useActiveLayout.ts
Labels: approved, Team Atlantis

#1785 feat(components-native): Update Banner styling for retheme
  docs/components/Banner/Mobile.stories.tsx
  packages/components-native/src/Banner/Banner.style.ts
  packages/components-native/src/Banner/Banner.test.tsx
  packages/components-native/src/Banner/Banner.tsx
  packages/components-native/src/Banner/components/BannerIcon/BannerIcon.style.ts
  packages/components-native/src/Banner/components/BannerIcon/BannerIcon.tsx
  packages/components-native/src/Banner/constants.ts
  packages/components-native/src/Banner/types.ts
  packages/components-native/src/TextList/TextList.style.ts
  packages/components-native/src/TextList/__snapshots__/TextList.test.tsx.snap
Labels: review requested, approved, design approved, Team Atlantis

#1789 fix(components): Fix button label and icon alignment when inside a modal
  packages/components/src/Modal/Modal.css
Labels: approved, Team Atlantis

#1774 feat(components): Swap twitter bird with X icon
  packages/design/assets/icons/twitter.svg
Labels: approved

#1790 fix(components): Fix DataListLayout not rerendering
  packages/components/src/DataList/components/DataListLayout/DataListLayout.tsx
Labels: approved, Team Atlantis

#1798 feat(components-native): Update Button learning variation style
  packages/components-native/src/Button/Button.style.ts
  packages/components-native/src/Button/Button.test.tsx
  packages/components-native/src/Button/Button.tsx
Labels: approved, Team Atlantis

#1792 fix(components): Fix an improper console mock in a test
  packages/components/src/Combobox/Combobox.test.tsx
Labels: approved, Team Atlantis

#1803 feat(design): JOB-91365 Update client icons using color-teal to use the client semantic color
  packages/design/src/icons/Icon.css
Labels: approved, design approved, Team Atlantis

#1804 fix(components): Removing Broken CI Badge
  docs/README.md
Labels: approved, Team Atlantis

#1771 fix(components): Allow duplicated terms on DescriptionList data tuple [1767]
  packages/components/src/DescriptionList/DescriptionList.test.tsx
  packages/components/src/DescriptionList/DescriptionList.tsx
Labels: approved, Team Atlantis

#1802 feat(components): Restyle web statusLabel
  packages/components/src/StatusIndicator/StatusIndicator.css
  packages/components/src/StatusLabel/StatusLabel.css
  packages/components/src/StatusLabel/StatusLabel.css.d.ts
  packages/components/src/StatusLabel/StatusLabel.tsx
  packages/components/src/StatusLabel/__snapshots__/StatusLabel.test.tsx.snap
  packages/components/src/Typography/css/TextColors.css
  packages/components/src/Typography/css/TextColors.css.d.ts
Labels: approved, Team Atlantis

#1808 fix(components): Remove subdued text from DataList
  packages/components/src/DataList/DataList.utils.tsx
  packages/components/src/DataList/__tests__/DataList.utils.test.tsx
Labels: approved, Team Atlantis

#1787 feat(components-native): Bump peerDependency for react-native-reanimated to also accept v3
  package-lock.json
  package.json
  packages/components-native/package.json
  packages/components-native/src/Button/components/InternalButtonLoading/InternalButtonLoading.tsx
  packages/components-native/src/Disclosure/Disclosure.tsx
  packages/components-native/src/Disclosure/__snapshots__/Disclosure.test.tsx.snap
Labels: approved, Team Atlantis

#1807 fix(components): Use unique item key in DataListSortingOptions
  packages/components/src/DataList/components/DataListHeaderTile/components/DataListSortingOptions.tsx
Labels: approved, Team Atlantis

#1801 feat(components): Guard Portal Usages for Remix
  packages/components/src/Autocomplete/Menu.tsx
  packages/components/src/Banner/Banner.tsx
  packages/components/src/Banner/components/BannerIcon/BannerIcon.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.tsx
  packages/components/src/DataList/components/DataListActionsMenu/DataListActionsMenu.tsx
  packages/components/src/Heading/Heading.tsx
  packages/components/src/LightBox/LightBox.tsx
  packages/components/src/Modal/Modal.tsx
  packages/components/src/Popover/Popover.tsx
  packages/components/src/Tooltip/Tooltip.tsx
  packages/components/src/utils/getAtlantisConfig.ts
  packages/components/src/utils/useAtlantisConfig.ts
Labels: approved, Team Atlantis

#1800 refactor(components): Deprecate to prop for Button
  packages/components/src/Button/Button.tsx
Labels: approved, Team Atlantis

#1797 fix(components): Make useMediaQuery SSR Friendly
  packages/components/src/DataList/hooks/useMediaQuery.ts
  packages/hooks/src/useBreakpoints/useMediaQuery.ts
Labels: approved, Team Atlantis

#1813 fix(components): Revert Make useMediaQuery SSR Friendly
  packages/components/src/DataList/hooks/useMediaQuery.ts
  packages/hooks/src/useBreakpoints/useMediaQuery.ts
Labels: approved, Team Atlantis

#1816 refactor(components): Export ListItemProps from List
  packages/components/src/List/index.ts
Labels: approved, Team Atlantis

#1810 fix(components): InternalThumbnailImage to support SSR
  packages/components/src/FormatFile/InternalThumbnailImage.tsx
Labels: approved, Team Atlantis

#1814 fix(components): Make useMediaQuery SSR Friendly
  packages/components/src/DataList/hooks/useMediaQuery.ts
  packages/hooks/src/useBreakpoints/useMediaQuery.ts
Labels: approved, Team Atlantis

#1815 refactor(components): Guard InputTime's useTimePredict for SSR
  packages/components/src/InputTime/hooks/useTimePredict.ts
Labels: approved, Team Atlantis

#1821 feat: Add stylelint-config to pre-release options
  .github/workflows/trigger-qa-build.yml
Labels: approved, Team Atlantis

#1819 build(stylelint): Upgrade stylelint from v14.2.0 to v16.2.1
  .circleci/config.yml
  package-lock.json
  package.json
  packages/components/src/DatePicker/DatePicker.css
  packages/components/src/FormField/FormField.css
  packages/stylelint-config/package.json
  packages/stylelint-config/stylelint.config.js
Labels: approved, Team Atlantis

#1824 fix(components): Make FormatTime work on SSR environments
  packages/components/src/FormatTime/FormatTime.tsx
Labels: approved, Team Atlantis

#1826 feat(components-native): add input toolbar
  docs/components/InputText/Mobile.stories.tsx
  packages/components-native/src/InputFieldWrapper/InputFieldWrapper.style.ts
  packages/components-native/src/InputFieldWrapper/InputFieldWrapper.test.tsx
  packages/components-native/src/InputFieldWrapper/InputFieldWrapper.tsx
  packages/components-native/src/InputText/InputText.tsx
Labels: approved, Team Atlantis

#1828 fix(components): stop InputPhoneNumber crashing page when it's translated with a Google Translate browser extension — Patch Release
  packages/components/src/InputPhoneNumber/InputMask.tsx
Labels: approved, Team Atlantis

#1831 feat(components-native): implement toolbar visibility
  packages/components-native/src/InputFieldWrapper/InputFieldWrapper.test.tsx
  packages/components-native/src/InputFieldWrapper/InputFieldWrapper.tsx
  packages/components-native/src/InputText/InputText.tsx
Labels: approved, Team Atlantis

#1823 feat(components): Make inlineLabel sizing match statusLabel
  packages/components/src/InlineLabel/InlineLabel.css
Labels: approved, Team Atlantis

#1817 feat(components): Update InputDate to customize date format, calendar icon and displayed value
  package-lock.json
  packages/components/package.json
  packages/components/src/AtlantisContext/AtlantisContext.test.tsx
  packages/components/src/AtlantisContext/AtlantisContext.tsx
  packages/components/src/AtlantisContext/index.ts
  packages/components/src/DatePicker/DatePicker.tsx
  packages/components/src/InputDate/InputDate.test.tsx
  packages/components/src/InputDate/InputDate.tsx
Labels: approved, Team Atlantis

#1832 fix: allow readonly prop on input text native
  packages/components-native/src/InputText/InputText.test.tsx
  packages/components-native/src/InputText/InputText.tsx
Labels: approved, Team Atlantis

#1834 feat(components): Heading can accept an element prop to override the numbered heading element
  packages/components/src/Heading/Heading.test.tsx
  packages/components/src/Heading/Heading.tsx
Labels: approved, Team Atlantis

#1836 fix(components-native): ensure prefix is beside the input
  packages/components-native/src/InputFieldWrapper/InputFieldWrapper.style.ts
  packages/components-native/src/InputFieldWrapper/InputFieldWrapper.tsx
Labels: approved, Team Atlantis

#1830 feat(components-native): BREAKING CHANGE: Move react-native-svg to peerDependencies
  package-lock.json
  package.json
  packages/components-native/package.json
  packages/components-native/src/Icon/__snapshots__/Icon.test.tsx.snap
Labels: approved, Team Atlantis
