Repository GetJobber/atlantis, pull requests merged in 2024-06, with the labels that each got.

#1911 docs(components): Added more description about how Form onSubmit works with throwing errors.
  docs/components/Form/Form.stories.mdx
  packages/components-native/src/Form/types.ts
Labels: approved, Team Atlantis

#1912 fix(components): Fix Menu Focus Logic
  packages/components/src/FormField/hooks/useActiveElement.ts
  packages/components/src/FormField/hooks/useFormFieldFocus.ts
Labels: approved, Team Atlantis

#1667 fix(components): hide hover menu when context menu shows up
  packages/components/src/DataList/components/DataListItem/DataListItem.test.tsx
  packages/components/src/DataList/components/DataListItem/DataListItem.tsx
Labels: changes requested, Team Atlantis

#1890 feat(components): Box Component
  .storybook/components/SidebarLabel/alphaComponents.ts
  docs/components/Box/Box.stories.mdx
  docs/components/Box/Web.stories.tsx
  packages/components/package.json
  packages/components/src/Box/Box.tsx
  packages/components/src/Box/Box.types.ts
  packages/components/src/Box/index.ts
  packages/components/src/Box/styles/Box.css
  packages/components/src/Box/styles/Box.css.d.ts
  packages/components/src/Box/styles/BoxBorder.css
  packages/components/src/Box/styles/BoxBorder.css.d.ts
  packages/components/src/Box/styles/BoxDimension.css
  packages/components/src/Box/styles/BoxDimension.css.d.ts
  packages/components/src/Box/styles/BoxGap.css
  packages/components/src/Box/styles/BoxGap.css.d.ts
  packages/components/src/Box/styles/BoxMargin.css
  packages/components/src/Box/styles/BoxMargin.css.d.ts
  packages/components/src/Box/styles/BoxPadding.css
  packages/components/src/Box/styles/BoxPadding.css.d.ts
  packages/components/src/Box/styles/BoxRadius.css
  packages/components/src/Box/styles/BoxRadius.css.d.ts
  packages/components/src/Box/utils/getBoxConfig.ts
  packages/components/src/Box/utils/getBoxDimension.ts
  packages/components/src/Box/utils/getBoxSpaces.ts
  packages/components/src/index.tsx
Labels: approved, Team Atlantis

#1909 feat(components): add side drawer
  .storybook/components/SidebarLabel/alphaComponents.ts
  docs/components/SideDrawer/SideDrawer.stories.mdx
  docs/components/SideDrawer/Web.stories.tsx
  packages/components/src/SideDrawer/SideDrawer.css
  packages/components/src/SideDrawer/SideDrawer.css.d.ts
  packages/components/src/SideDrawer/SideDrawer.test.tsx
  packages/components/src/SideDrawer/SideDrawer.tsx
  packages/components/src/SideDrawer/SideDrawerActions.tsx
  packages/components/src/SideDrawer/SideDrawerBackButton.tsx
  packages/components/src/SideDrawer/SideDrawerContext.tsx
  packages/components/src/SideDrawer/SideDrawerFooter.tsx
  packages/components/src/SideDrawer/SideDrawerTitle.tsx
  packages/components/src/SideDrawer/SideDrawerToolbar.tsx
  packages/components/src/SideDrawer/index.ts
  packages/components/src/index.tsx
Labels: approved, Team Atlantis

#1910 feat(components): Add url to DataList.ItemAction
  docs/components/DataList/DataList.stories.mdx
  docs/components/DataList/Web.stories.tsx
  packages/components/src/DataList/DataList.types.ts
  packages/components/src/DataList/components/DataListAction/DataListAction.css
  packages/components/src/DataList/components/DataListAction/DataListAction.css.d.ts
  packages/components/src/DataList/components/DataListAction/DataListAction.test.tsx
  packages/components/src/DataList/components/DataListAction/DataListAction.tsx
Labels: approved, Team Atlantis

#1914 feat(components): add elevation attribute to elevated UI elements [JOB-97584]
  packages/components/src/Autocomplete/Menu.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.tsx
  packages/components/src/DataList/components/DataListActionsMenu/DataListActionsMenu.tsx
  packages/components/src/DatePicker/DatePicker.css
  packages/components/src/DatePicker/DatePicker.tsx
  packages/components/src/Menu/Menu.tsx
  packages/components/src/MultiSelect/DropDownMenu.tsx
  packages/components/src/Popover/Popover.tsx
  packages/components/src/SideDrawer/SideDrawer.tsx
Labels: approved, Team Atlantis

#1926 feat: side drawer improvements
  packages/components/src/SideDrawer/SideDrawer.css
  packages/components/src/SideDrawer/SideDrawer.css.d.ts
  packages/components/src/SideDrawer/SideDrawer.tsx
  packages/components/src/SideDrawer/SideDrawerBackButton.tsx
  packages/components/src/SideDrawer/SideDrawerContext.tsx
Labels: approved, Team Atlantis

#1924 feat(components): update interactive borders and avatar [JOB-97530]
  packages/components/src/Avatar/Avatar.css
  packages/components/src/Button/Button.css
  packages/components/src/Checkbox/Checkbox.css
  packages/components/src/Chip/Chip.css
  packages/components/src/Chips/InternalChip.css
  packages/components/src/FormField/FormField.css
  packages/components/src/InputFile/InputFile.css
  packages/components/src/RadioGroup/RadioGroup.css
  packages/components/src/Select/Select.css
  packages/components/src/Switch/Switch.css
  packages/design/src/colors.css
Labels: approved, Team Atlantis

#1917 fix(components): Handle dynamic number of Tab children
  packages/components/src/Tabs/Tabs.test.tsx
  packages/components/src/Tabs/Tabs.tsx
  packages/components/src/Tabs/hooks/useTabsOverflow.ts
Labels: approved, Team Atlantis

#1928 fix: side drawer scroll overflow to auto
  packages/components/src/SideDrawer/SideDrawer.css
Labels: approved, Team Atlantis

#1930 fix(components): allow Select background to work in dark modes
  packages/components/src/Select/Select.css
Labels: approved, Team Atlantis

#1931 fix: Add css to style href in link component
  packages/components/src/Link/Link.css
  packages/components/src/Link/Link.css.d.ts
  packages/components/src/Link/Link.tsx
Labels: approved, Team Atlantis

#1933 feat: allow thumbnails on gallery
  docs/components/Gallery/Web.stories.tsx
  packages/components/src/Gallery/Gallery.test.tsx
  packages/components/src/Gallery/Gallery.tsx
  packages/components/src/Gallery/GalleryTypes.ts
Labels: approved, Team Atlantis

#1934 feat: on error callback on image files in format file
  packages/components/src/FormatFile/FormatFile.test.tsx
  packages/components/src/FormatFile/InternalThumbnailImage.tsx
  packages/components/src/InputFile/InputFile.tsx
Labels: approved, Team Atlantis

#1858 docs: use jobber font from CDN instead of package
  .gitignore
  .npmrc.pages
  .storybook/manager-head.html
  .storybook/manager.js
  .storybook/preview-head.html
  .storybook/preview.tsx
  docs/README.md
  package-lock.json
  package.json
  scripts/pre-install.sh
Labels: approved, Team Atlantis

#1935 fix(components): make `Select` options readable in dark mode
  packages/components/src/Select/Select.css
Labels: approved, Team Atlantis

#1936 feat(components): Allow Banner dismiss to be controlled
  docs/components/Banner/Web.stories.tsx
  packages/components/src/Banner/Banner.test.tsx
  packages/components/src/Banner/Banner.tsx
Labels: approved, Team Atlantis

#1929 fix(components): Adjust style of section headings in autocomplete
  packages/components/src/Autocomplete/Autocomplete.css
Labels: approved, Team Atlantis

#1939 refactor(components): delete unused CSS files for Select
  packages/components/src/Select/Select.css
  packages/components/src/Select/Select.css.d.ts
Labels: in review, approved, Team Atlantis

#1932 feat: Add button variation option to actions buttons in the Menu component (JOB-98306)
  docs/components/Menu/Web.stories.tsx
  packages/components/src/Menu/Menu.css
  packages/components/src/Menu/Menu.css.d.ts
  packages/components/src/Menu/Menu.tsx
Labels: approved, Team Atlantis

#1941 feat(components): Update Page component to accept a titleMetaData component [JOB-97759]
  docs/components/Page/Web.stories.tsx
  packages/components/src/Page/Page.css
  packages/components/src/Page/Page.css.d.ts
  packages/components/src/Page/Page.test.tsx
  packages/components/src/Page/Page.tsx
Labels: approved, design approved, Team Atlantis, Team Campaigns

#1927 feat(components): Add testID prop to components Icon
  packages/components/src/Icon/Icon.test.tsx
  packages/components/src/Icon/Icon.tsx
Labels: approved, Team Atlantis

#1943 feat(components-native): Add testID prop to components-native Icon
  packages/components-native/src/Icon/Icon.test.tsx
  packages/components-native/src/Icon/Icon.tsx
Labels: approved, Team Atlantis
