Repository GetJobber/atlantis, pull requests merged in 2025-03, with the labels that each got.

#2400 docs: AutoComplete customRenderMenu sticky footer implementation
  docs/components/Autocomplete/Web.stories.tsx
  packages/site/src/content/Autocomplete/AutocompleteExamples.tsx
  packages/site/src/content/Autocomplete/AutocompleteNotes.mdx
Labels: approved, Team UX Foundations

#2409 docs: use h3 instead of h2 for Triton welcome message
  packages/site/src/components/TritonConversation.tsx
Labels: approved, Team UX Foundations

#2411 fix(components): Export form field internal components.
  packages/components/src/FormField/FormFieldAffix.tsx
  packages/components/src/FormField/FormFieldWrapper.tsx
  packages/components/src/FormField/index.ts
  packages/components/src/utils/meta/meta.json
Labels: approved, Team UX Foundations

#2412 feat(components): Add support for composable buttons
  docs/components/Button/Web.stories.tsx
  packages/components/src/Banner/__snapshots__/Banner.test.tsx.snap
  packages/components/src/Button/Button.module.css
  packages/components/src/Button/Button.module.css.d.ts
  packages/components/src/Button/Button.test.tsx
  packages/components/src/Button/Button.tsx
  packages/components/src/Button/Button.types.ts
  packages/components/src/Button/ButtonInternals.tsx
  packages/components/src/Button/ButtonProvider.tsx
  packages/components/src/Button/__snapshots__/Button.test.tsx.snap
  packages/components/src/Button/index.ts
  packages/components/src/Button/useButtonStyles.ts
  packages/components/src/ButtonDismiss/__snapshots__/ButtonDismiss.test.tsx.snap
  packages/components/src/ConfirmationModal/tests/__snapshots__/snapshot-ConfirmationModal.test.tsx.snap
  packages/components/src/FeatureSwitch/__snapshots__/FeatureSwitch.test.tsx.snap
  packages/components/src/InputAvatar/__snapshots__/InputAvatar.test.tsx.snap
  packages/components/src/InputFile/__snapshots__/InputFile.test.tsx.snap
  packages/components/src/LightBox/__snapshots__/LightBoxSnapshots.test.tsx.snap
  packages/components/src/Menu/__snapshots__/Menu.test.tsx.snap
  packages/components/src/Page/__snapshots__/Page.test.tsx.snap
  packages/components/src/Typography/Typography.tsx
  packages/components/src/utils/meta/meta.json
  packages/hooks/src/index.ts
  packages/site/src/content/Banner/Banner.props.json
  packages/site/src/content/Button/Button.props.json
  packages/site/src/content/Button/ButtonNotes.mdx
  packages/site/src/content/DataList/DataList.props.json
  packages/site/src/content/Modal/Modal.props.json
  packages/site/src/content/SideDrawer/SideDrawer.props.json
Labels: approved, Team UX Foundations

#2417 feat(components): Make InputFile composable [JOB-110281]
  docs/components/InputFile/Web.stories.tsx
  packages/components/src/Button/Button.types.ts
  packages/components/src/InputAvatar/__snapshots__/InputAvatar.test.tsx.snap
  packages/components/src/InputFile/InputFile.test.tsx
  packages/components/src/InputFile/InputFile.tsx
  packages/components/src/InputFile/InputFileButton.test.tsx
  packages/components/src/InputFile/InputFileButton.tsx
  packages/components/src/InputFile/InputFileContentContext.test.tsx
  packages/components/src/InputFile/InputFileContentContext.tsx
  packages/components/src/InputFile/InputFileDescription.test.tsx
  packages/components/src/InputFile/InputFileDescription.tsx
  packages/components/src/InputFile/InputFileDropzoneWrapper.tsx
  packages/components/src/InputFile/InputFileHintText.test.tsx
  packages/components/src/InputFile/InputFileHintText.tsx
  packages/components/src/InputFile/InputFileValidationErrors.tsx
  packages/components/src/InputFile/__snapshots__/InputFile.test.tsx.snap
  packages/components/src/InputFile/index.ts
  packages/components/src/InputFile/types.ts
  packages/components/src/Text/Text.tsx
  packages/components/src/Text/index.ts
  packages/components/src/utils/meta/meta.json
  packages/site/src/content/Button/Button.props.json
  packages/site/src/content/InputFile/InputFile.props.json
  packages/site/src/content/InputFile/InputFileNotes.mdx
Labels: approved, Team UX Foundations

#2418 fix(design): move warning icon up by 1px
  packages/design/src/icons/warning.svg
Labels: approved, Team UX Foundations

#2423 docs: Add personality SegmentedControl to Triton SideDrawer
  packages/site/src/components/TritonSideDrawer.tsx
  packages/site/src/providers/TritonProvider.tsx
  packages/site/src/utils/useTritonApi.ts
Labels: approved, docs site, Team UX Foundations

#2434 docs: Add FormFieldLabel to extraImports in InputText example
  docs/components/InputText/Web.stories.tsx
Labels: approved, Team UX Foundations

#2429 feat(components): Add UNSAFE_ props to Icon
  packages/components/src/Icon/Icon.test.tsx
  packages/components/src/Icon/Icon.tsx
  packages/site/src/content/Icon/Icon.props.json
  packages/site/src/content/Icon/IconNotes.mdx
  packages/site/src/content/Icon/index.tsx
Labels: approved, Team UX Foundations

#2428 fix(components): fix controlled SegmentedControl render state update
  packages/components/src/SegmentedControl/SegmentedControlProvider.test.tsx
  packages/components/src/SegmentedControl/SegmentedControlProvider.tsx
Labels: approved, Team UX Foundations

#2437 fix(components): remove unnecessary useEffect in SegmentedControlProvider
  packages/components/src/SegmentedControl/SegmentedControlProvider.test.tsx
  packages/components/src/SegmentedControl/SegmentedControlProvider.tsx
Labels: approved, Team UX Foundations

#2403 feat(components): Add anchored positioning support for SideDrawer
  docs/components/SideDrawer/Web.stories.tsx
  packages/components/src/SideDrawer/SideDrawer.module.css
  packages/components/src/SideDrawer/SideDrawer.module.css.d.ts
  packages/components/src/SideDrawer/SideDrawer.test.tsx
  packages/components/src/SideDrawer/SideDrawer.tsx
  packages/site/src/content/SideDrawer/SideDrawer.props.json
  packages/site/src/content/SideDrawer/SideDrawerNotes.mdx
Labels: approved, Team UX Foundations

#2430 feat(components): Add UNSAFE_ props to Typography
  packages/components/src/Typography/Typography.test.tsx
  packages/components/src/Typography/Typography.tsx
  packages/site/src/content/Typography/Typography.props.json
  packages/site/src/content/Typography/TypographyNotes.mdx
Labels: approved, Team UX Foundations

#2427 docs: make docs tables more predictable
  packages/site/src/main.css
Labels: approved, docs site, Team UX Foundations

#2426 docs: adjust layout of doc site chrome
  packages/site/src/layout/NavMenu.module.css
  packages/site/src/layout/TopNav.tsx
  packages/site/src/main.css
Labels: approved, docs site, Team UX Foundations

#2431 feat(components): Add UNSAFE_ props to Disclosure
  packages/components/src/Disclosure/Disclosure.test.tsx
  packages/components/src/Disclosure/Disclosure.tsx
  packages/site/src/content/Disclosure/Disclosure.props.json
  packages/site/src/content/Disclosure/DisclosureNotes.mdx
  packages/site/src/content/Disclosure/index.tsx
Labels: approved, Team UX Foundations

#2435 refactor(components): Replace popperjs with floating-ui in combobox
  package-lock.json
  packages/components/package.json
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.module.css
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.tsx
  packages/components/src/Combobox/hooks/useComboboxAccessibility.ts
Labels: approved, Team UX Foundations

#2425 fix(components): Move Phone Input Cursor Inside Parentheses
  packages/components/src/FormField/FormField.module.css
  packages/components/src/FormField/FormField.module.css.d.ts
  packages/components/src/FormField/FormField.tsx
  packages/components/src/FormField/FormFieldTypes.ts
  packages/components/src/FormField/hooks/useAtlantisFormField.ts
  packages/components/src/InputPhoneNumber/InputPhoneNumber.test.tsx
  packages/components/src/InputPhoneNumber/InputPhoneNumber.tsx
  packages/components/src/Select/Select.tsx
  packages/site/src/content/FormField/FormField.props.json
Labels: approved, design review requested, Team UX Foundations

#2444 feat(components): Add New Schedule Day View Icons
  docs/components/Icon/Icon.stories.mdx
  packages/design/src/icons/orientationHorizontal.svg
  packages/design/src/icons/orientationVertical.svg
Labels: approved, Team Scheduing, Team UX Foundations, Team Scheduling

#2439 refactor(components): Make Card component composable
  docs/components/Card/Web.stories.tsx
  packages/components/src/Card/Card.tsx
  packages/components/src/Card/tests/Card.test.tsx
  packages/components/src/Card/types.ts
  packages/components/src/utils/meta/meta.json
  packages/site/src/content/Card/Card.props.json
  packages/site/src/content/Card/CardNotes.mdx
  packages/site/src/content/Card/index.tsx
Labels: approved, Team UX Foundations

#2419 feat(components): Use new status icons in Banner
  docs/components/Banner/Web.stories.tsx
  packages/components/src/Banner/Banner.tsx
  packages/components/src/Banner/__snapshots__/Banner.test.tsx.snap
Labels: approved, Team UX Foundations

#2446 feat(components): Add secondary action support to Page component even without primary action
  docs/components/Page/Web.stories.tsx
  packages/components/src/Page/Page.test.tsx
  packages/components/src/Page/Page.tsx
  packages/site/src/content/Page/Page.props.json
Labels: approved, Team UX Foundations
