Repository GetJobber/atlantis, pull requests merged in 2025-05, with the labels that each got.

#2533 refactor(components): Export layout components props
  packages/components/src/Cluster/index.ts
  packages/components/src/ContentBlock/index.ts
  packages/components/src/Cover/index.ts
  packages/components/src/ResponsiveSwitcher/index.ts
  packages/components/src/SideKick/index.ts
  packages/components/src/Stack/index.ts
  packages/components/src/Tiles/index.ts
Labels: approved, Team UX Foundations

#2532 fix(components): Fix modal size not being respected in all cases
  packages/components/src/Modal/ModalSizes.module.css
Labels: approved, Team UX Foundations

#2537 feat(components): Add clientColor to Card accent
  packages/components/src/Card/cardcolors.module.css
  packages/components/src/Card/cardcolors.module.css.d.ts
Labels: approved, Team UX Foundations

#2534 feat(components): InputPhoneNumber v2
  docs/components/InputPhoneNumber/Web.stories.tsx
  packages/components/src/InputPhoneNumber/InputMask.module.css
  packages/components/src/InputPhoneNumber/InputMask.module.css.d.ts
  packages/components/src/InputPhoneNumber/InputMask.tsx
  packages/components/src/InputPhoneNumber/InputPhoneNumber.rebuilt.test.tsx
  packages/components/src/InputPhoneNumber/InputPhoneNumber.rebuilt.tsx
  packages/components/src/InputPhoneNumber/InputPhoneNumber.test.tsx
  packages/components/src/InputPhoneNumber/InputPhoneNumber.tsx
  packages/components/src/InputPhoneNumber/InputPhoneNumber.types.ts
  packages/components/src/InputPhoneNumber/hooks/useInputPhoneActions.ts
  packages/components/src/InputPhoneNumber/hooks/useInputPhoneFormField.ts
  packages/components/src/InputPhoneNumber/index.ts
  packages/components/src/InputPhoneNumber/index.tsx
  packages/components/src/InputPhoneNumber/useInputMask.ts
  packages/site/src/content/InputPhoneNumber/InputPhoneNumber.props.json
Labels: approved, Team UX Foundations

#2539 feat(design): Add surface and onSurface colors for color-client
  packages/design/src/tokens/dark.tokens.json
  packages/design/src/tokens/workflow.tokens.json
  packages/site/src/content/Box/Box.props.json
  packages/site/src/content/Typography/Typography.props.json
Labels: approved, design review requested, Team UX Foundations

#2536 refactor(components-native): use interactive--background token in mobile components
  packages/components-native/src/Chip/Chip.test.tsx
  packages/components-native/src/Chip/Chip.tsx
  packages/components-native/src/FormatFile/components/ProgressBar/ProgressBar.style.tsx
  packages/components-native/src/ProgressBar/ProgressBar.tsx
  packages/components-native/src/ProgressBar/__snapshots__/ProgressBar.test.tsx.snap
  packages/components-native/src/Switch/components/BaseSwitch/BaseSwitch.tsx
  packages/components-native/src/Switch/components/BaseSwitch/__snapshots__/BaseSwitch.test.tsx.snap
Labels: approved, Team UX Foundations

#2544 feat(components): Update tiles to support alignment prop.
  docs/components/Tiles/Web.stories.tsx
  packages/components/src/Tiles/Tiles.module.css
  packages/components/src/Tiles/Tiles.tsx
  packages/components/src/Tiles/types.ts
  packages/site/src/content/Tiles/Tiles.mdx
  packages/site/src/content/Tiles/Tiles.props.json
Labels: approved, Team UX Foundations

#2546 feat(design): JOB-122715 Add editDisabled icon
  docs/components/Icon/Icon.stories.mdx
  packages/design/src/icons/editDisabled.svg
Labels: approved, Team Quotemeal, Team UX Foundations

#2540 feat(components-native): BREAKING CHANGE: Upgrade to React Native 0.77
  package-lock.json
  package.json
  packages/components-native/package.json
  packages/components-native/src/Disclosure/Disclosure.test.tsx
  packages/components-native/src/Disclosure/__snapshots__/Disclosure.test.tsx.snap
  packages/components-native/src/Glimmer/Glimmer.test.tsx
  packages/components-native/src/Switch/components/BaseSwitch/BaseSwitch.test.tsx
  packages/components-native/src/Switch/components/BaseSwitch/__snapshots__/BaseSwitch.test.tsx.snap
  packages/site/src/content/ActivityIndicator/ActivityIndicator.props-mobile.json
  packages/site/src/content/InputEmail/InputEmail.props-mobile.json
  packages/site/src/content/InputNumber/InputNumber.props-mobile.json
  packages/site/src/content/InputText/InputText.props-mobile.json
Labels: review requested, in review, Team UX Foundations

#2528 feat(components-native): BREAKING CHANGE: Upgrade React Native Version
  package-lock.json
  package.json
  packages/components-native/babel.config.js
  packages/components-native/jestSetup.js
  packages/components-native/package.json
  packages/components-native/src/Disclosure/Disclosure.test.tsx
  packages/components-native/src/Disclosure/__snapshots__/Disclosure.test.tsx.snap
  packages/components-native/src/Form/Form.test.tsx
  packages/components-native/src/Glimmer/Glimmer.test.tsx
  packages/components-native/src/Switch/components/BaseSwitch/BaseSwitch.test.tsx
  packages/components-native/src/Switch/components/BaseSwitch/__snapshots__/BaseSwitch.test.tsx.snap
  packages/components-native/src/__mocks__/__mocks.ts
  packages/components/src/ConfirmationModal/ConfirmationModal.tsx
  packages/site/package.json
  packages/site/src/content/ActivityIndicator/ActivityIndicator.props-mobile.json
  packages/site/src/content/Autocomplete/Autocomplete.props.json
  packages/site/src/content/BottomSheet/BottomSheet.props-mobile.json
  packages/site/src/content/Chip/Chip.props.json
  packages/site/src/content/ConfirmationModal/ConfirmationModal.props.json
  packages/site/src/content/ContentOverlay/ContentOverlay.props-mobile.json
  packages/site/src/content/Form/Form.props.json
  packages/site/src/content/InputEmail/InputEmail.props-mobile.json
  packages/site/src/content/InputNumber/InputNumber.props-mobile.json
  packages/site/src/content/InputNumber/InputNumber.props.json
  packages/site/src/content/InputPassword/InputPassword.props-mobile.json
  packages/site/src/content/InputPressable/InputPressable.props-mobile.json
  packages/site/src/content/InputSearch/InputSearch.props-mobile.json
  packages/site/src/content/InputText/InputText.props-mobile.json
  packages/site/src/content/InputText/InputText.props.json
Labels: approved, Team UX Foundations

#2549 refactor(components): replace calcs to 12 with slim in web
  packages/components/src/Banner/Banner.module.css
  packages/components/src/Button/Button.module.css
  packages/components/src/FormField/FormField.module.css
  packages/components/src/InlineLabel/InlineLabel.module.css
  packages/components/src/MultiSelect/MultiSelect.module.css
  packages/components/src/SegmentedControl/SegmentedControl.module.css
Labels: approved, Team UX Foundations

#2558 fix(components): stop showing focus ring on disabled and invalid components
  packages/components/src/FormField/FormField.module.css
  packages/components/src/FormField/FormField.module.css.d.ts
  packages/components/src/InputDate/InputDate.rebuilt.tsx
  packages/components/src/InputDate/InputDate.tsx
Labels: approved, Team UX Foundations

#2563 fix(components): Allowing error passthrough on <Select version={2} />
  docs/components/Select/Web.stories.tsx
  packages/components/src/Select/Select.rebuilt.tsx
  packages/components/src/Select/Select.types.ts
Labels: approved, Team UX Foundations

#2564 fix(components): stop minilabel from responding on empty disabled InputTime
  packages/components/src/FormField/FormField.module.css
Labels: approved, Team UX Foundations

#2562 fix(components): Remove z-index from affix icons with actions [JOB-119173 ]
  packages/components/src/FormField/FormField.module.css
  packages/components/src/FormField/FormField.module.css.d.ts
  packages/components/src/FormField/FormFieldAffix.tsx
Labels: approved, Team UX Foundations

#2551 feat(components): Add InputNumber v2
  docs/components/InputNumber/Web.stories.tsx
  docs/components/InputText/Web.stories.tsx
  package-lock.json
  packages/components/package.json
  packages/components/src/InputNumber/InputNumber.rebuilt.module.css
  packages/components/src/InputNumber/InputNumber.rebuilt.module.css.d.ts
  packages/components/src/InputNumber/InputNumber.rebuilt.test.tsx
  packages/components/src/InputNumber/InputNumber.rebuilt.tsx
  packages/components/src/InputNumber/InputNumber.rebuilt.types.tsx
  packages/components/src/InputNumber/InputNumber.tsx
  packages/components/src/InputNumber/index.ts
  packages/components/src/InputNumber/index.tsx
  packages/components/src/InputText/InputText.rebuilt.tsx
  packages/components/src/LightBox/LightBox.module.css
  packages/components/src/utils/meta/meta.json
  packages/site/src/content/InputNumber/InputNumber.props.json
Labels: approved, Team UX Foundations

#2571 chore: Update Angies List Icon
  packages/design/src/icons/angieslist.svg
Labels: approved, design approved, Team UX Foundations

#2572 docs: Add pattern for "settings"
  packages/site/public/Settings.png
  packages/site/public/Settings.svg
  packages/site/src/content/Patterns/settings.mdx
  packages/site/src/maps/patternsContent.tsx
  packages/site/src/patternsList.ts
  packages/site/src/routes.tsx
Labels: approved, Team UX Foundations

#2574 docs: Add missing layout thumbnails
  packages/site/public/Cluster.png
  packages/site/public/Cluster.svg
  packages/site/public/Container.png
  packages/site/public/Container.svg
  packages/site/public/Content.png
  packages/site/public/Content.svg
  packages/site/public/ContentBlock.png
  packages/site/public/ContentBlock.svg
  packages/site/public/Cover.png
  packages/site/public/Cover.svg
  packages/site/public/Frame.png
  packages/site/public/Frame.svg
  packages/site/public/ResponsiveSwitcher.png
  packages/site/public/ResponsiveSwitcher.svg
  packages/site/public/Sidekick.png
  packages/site/public/Sidekick.svg
  packages/site/public/Stack.png
  packages/site/public/Stack.svg
  packages/site/public/Tiles.png
  packages/site/public/Tiles.svg
  packages/site/src/componentList.ts
Labels: approved, Team UX Foundations
