Repository GetJobber/atlantis, pull requests merged in 2025-02, with the labels that each got.

#2346 docs: Add AtlantisThemeContext to new docs
  packages/site/baseComponentLists.mjs
  packages/site/src/componentList.ts
  packages/site/src/componentSections.ts
  packages/site/src/components/ComponentNotFound.tsx
  packages/site/src/content/AtlantisThemeContext/AtlantisThemeContext.props.json
  packages/site/src/content/AtlantisThemeContext/index.tsx
  packages/site/src/content/index.ts
  packages/site/src/editorBundle.js
Labels: approved, Team Atlantis, docs site

#2333 feat(components): Allow for external label [JOB-113378]
  docs/components/InputNumber/InputNumber.stories.mdx
  docs/components/InputText/InputText.stories.mdx
  docs/components/InputText/Web.stories.tsx
  packages/components/src/FormField/FormField.module.css
  packages/components/src/FormField/FormField.module.css.d.ts
  packages/components/src/FormField/FormField.test.tsx
  packages/components/src/FormField/FormField.tsx
  packages/components/src/FormField/FormFieldTypes.ts
  packages/components/src/FormField/FormFieldWrapper.tsx
  packages/components/src/FormField/__snapshots__/FormField.test.tsx.snap
  packages/components/src/FormField/hooks/useFormFieldWrapperStyles.ts
  packages/components/src/FormField/index.ts
  packages/components/src/InputText/InputText.rebuilt.tsx
  packages/components/src/InputTime/InputTimeProps.tsx
  packages/components/src/utils/meta/meta.json
Labels: approved, Team Atlantis

#2353 refactor(components): update menu hover state animation curve and transition state guidance
  docs/patterns/interaction.stories.mdx
  packages/components/src/Menu/Menu.module.css
Labels: approved, Team Atlantis

#2355 feat(design): Add new airspace logo
  docs/components/Icon/Icon.stories.mdx
  packages/design/src/icons/airSpace.svg
Labels: approved, Team Atlantis

#2356 refactor(components): Rename airSpace icon to headset
  docs/components/Icon/Icon.stories.mdx
  packages/design/src/icons/headset.svg
Labels: review requested, approved, Team Atlantis

#2349 fix(components-native): Add missing onPress prop type to InputPressable suffix (it's already accepted)
  docs/components/InputPressable/Mobile.stories.tsx
  packages/components-native/src/InputPressable/InputPressable.tsx
Labels: approved, Team Atlantis

#2358 build: Make Design peer depencency of components
  package-lock.json
  packages/components-native/package.json
  packages/components/package.json
  packages/formatters/package.json
  packages/hooks/package.json
Labels: approved, Team Atlantis

#2351 feat(components): Allow Gallery to take a promise source [JOB-113953]
  docs/components/Gallery/Web.stories.tsx
  packages/components/src/Gallery/Gallery.test.tsx
  packages/components/src/Gallery/Gallery.tsx
  packages/components/src/Gallery/GalleryTypes.ts
  packages/components/src/Gallery/index.ts
Labels: approved, Team Atlantis

#2229 feat(components): Autocomplete Custom Menu Rendering
  docs/components/Autocomplete/Autocomplete.stories.mdx
  docs/components/Autocomplete/Web.stories.tsx
  packages/components/src/Autocomplete/Autocomplete.module.css
  packages/components/src/Autocomplete/Autocomplete.module.css.d.ts
  packages/components/src/Autocomplete/Autocomplete.test.tsx
  packages/components/src/Autocomplete/Autocomplete.tsx
  packages/components/src/Autocomplete/Autocomplete.types.ts
  packages/components/src/Autocomplete/Autocomplete.utils.ts
  packages/components/src/Autocomplete/Menu.tsx
  packages/components/src/Autocomplete/Menu/DefaultMenu.tsx
  packages/components/src/Autocomplete/Menu/Menu.tsx
  packages/components/src/Autocomplete/Menu/MenuWrapper.tsx
  packages/components/src/Autocomplete/Option.ts
  packages/components/src/Autocomplete/Option.tsx
  packages/components/src/Autocomplete/__snapshots__/Autocomplete.test.tsx.snap
  packages/components/src/Autocomplete/index.ts
  packages/components/src/Autocomplete/useKeyboardNavigation.ts
  packages/components/src/Autocomplete/useRepositionMenu.ts
  packages/site/src/content/Autocomplete/Autocomplete.props.json
  packages/site/src/content/Autocomplete/AutocompleteExamples.tsx
  packages/site/src/content/Autocomplete/AutocompleteNotes.mdx
  packages/site/src/content/Autocomplete/index.tsx
Labels: approved, Team Atlantis

#2337 feat(components): Enhance image lightbox layout and background
  packages/components/src/Gallery/Gallery.test.tsx
  packages/components/src/LightBox/LightBox.module.css
  packages/components/src/LightBox/LightBox.module.css.d.ts
  packages/components/src/LightBox/LightBox.test.tsx
  packages/components/src/LightBox/LightBox.tsx
  packages/components/src/LightBox/LightBoxSnapshots.test.tsx
  packages/components/src/LightBox/__snapshots__/LightBoxSnapshots.test.tsx.snap
Labels: blocked, Team Atlantis

#2338 feat(components): bring back status-driven surface color in Banner
  packages/components/src/Banner/Banner.module.css
  packages/components/src/Banner/Banner.module.css.d.ts
  packages/components/src/Banner/Banner.tsx
  packages/components/src/Banner/__snapshots__/Banner.test.tsx.snap
Labels: approved, Team Atlantis

#2360 fix(components): Put Popover inside a portal
  packages/components/src/Popover/Popover.tsx
Labels: approved, Team Atlantis

#2363 fix(components): Prevent Stretching Small Images in Lightbox
  packages/components/src/LightBox/LightBox.module.css
Labels: approved, Team Atlantis

#2352 docs: Add error state patterns
  docs/patterns/empty-states.stories.mdx
  docs/patterns/errors.stories.mdx
  packages/site/public/Errors.png
  packages/site/public/Errors.svg
  packages/site/src/maps/patternsContent.tsx
  packages/site/src/patternsList.ts
  packages/site/src/routes.tsx
Labels: approved, Team Atlantis, docs site

#2367 chore: Update generate command when creating a new component
  packages/generators/index.mjs
  packages/generators/templates/docs/{{name}}.stories.{{mdx}}
  packages/generators/templates/site/index.ts
  packages/generators/templates/site/index.tsx
  packages/generators/templates/site/{{name}}Notes.mdx
  packages/site/src/components/ComponentNotFound.tsx
Labels: approved, Team Atlantis

#2308 docs: Remove duplicated documentation from Docs Pages
  docs/components/AnimatedPresence/AnimatedPresence.stories.mdx
  docs/components/AnimatedSwitcher/AnimatedSwitcher.stories.mdx
  docs/components/AutoLink/AutoLink.stories.mdx
  docs/components/Banner/Banner.stories.mdx
  docs/components/BottomSheet/BottomSheet.stories.mdx
  docs/components/Box/Box.stories.mdx
  docs/components/Button/Button.stories.mdx
  docs/components/Checkbox/Checkbox.stories.mdx
  docs/components/Chip/Chip.stories.mdx
  docs/components/Chips/Chips.stories.mdx
  docs/components/Combobox/Combobox.stories.mdx
  docs/components/ContentOverlay/ContentOverlay.stories.mdx
  docs/components/DataList/DataList.stories.mdx
  docs/components/Datepicker/Datepicker.stories.mdx
  docs/components/Form/Form.stories.mdx
  docs/components/FormField/FormField.stories.mdx
  docs/components/InputDate/InputDate.stories.mdx
  docs/components/InputFieldWrapper/InputFieldWrapper.stories.mdx
  docs/components/InputFile/InputFile.stories.mdx
  docs/components/InputNumber/InputNumber.stories.mdx
  docs/components/InputPressable/InputPressable.stories.mdx
  docs/components/InputText/InputText.stories.mdx
  docs/components/InputTime/InputTime.stories.mdx
  docs/components/LightBox/LightBox.stories.mdx
  docs/components/List/List.stories.mdx
  docs/components/Popover/Popover.stories.mdx
  docs/components/SegmentedControl/SegmentedControl.stories.mdx
  docs/components/SideDrawer/SideDrawer.stories.mdx
  docs/components/Switch/Switch.stories.mdx
  docs/components/Table/Table.stories.mdx
  docs/components/Tabs/Tabs.stories.mdx
  docs/components/Typography/Typography.stories.mdx
  docs/guides/documentation-style.stories.mdx
  packages/site/src/content/AutoLink/AutoLinkNotes.mdx
  packages/site/src/content/Box/BoxNotes.mdx
  packages/site/src/content/Button/ButtonNotes.mdx
  packages/site/src/content/Checkbox/CheckboxNotes.mdx
  packages/site/src/content/Checkbox/index.tsx
  packages/site/src/content/Chip/ChipNotes.mdx
  packages/site/src/content/Chips/ChipsNotes.mdx
  packages/site/src/content/Combobox/ComboboxNotes.mdx
  packages/site/src/content/ContentOverlay/ContentOverlayNotes.mdx
  packages/site/src/content/DatePicker/DatePickerNotes.mdx
  packages/site/src/content/InputDate/InputDateNotes.mdx
  packages/site/src/content/InputFile/InputFileNotes.mdx
  packages/site/src/content/InputText/InputTextNotes.mdx
  packages/site/src/content/InputText/index.tsx
  packages/site/src/content/LightBox/LightBoxNotes.mdx
  packages/site/src/content/List/ListNotes.mdx
  packages/site/src/content/SegmentedControl/SegmentedControlNotes.mdx
  packages/site/src/content/Tabs/TabsNotes.mdx
  packages/site/src/content/Typography/TypographyNotes.mdx
  packages/site/src/content/Typography/index.tsx
Labels: approved, Team Atlantis, docs site

#2365 docs: update banner thumbnail
  packages/site/public/Banner.png
  packages/site/public/Banner.svg
Labels: approved, Team Atlantis

#2366 docs: Add "Adding an icon" docs and update Icon docs
  docs/components/Icon/Icon.stories.mdx
  docs/guides/adding-an-icon.stories.mdx
  docs/guides/assets/add_icon_1.png
  docs/guides/assets/add_icon_2.png
  docs/guides/assets/add_icon_3.png
  docs/guides/assets/add_icon_4.png
  docs/guides/assets/add_icon_5.png
  docs/guides/assets/add_icon_6.png
  docs/guides/assets/add_icon_7.gif
  docs/guides/assets/add_icon_8.png
  docs/guides/assets/add_icon_9.png
  packages/site/src/guidesList.ts
  packages/site/src/maps/guidesContent.tsx
  packages/site/src/routes.tsx
  public/assets/images/adding-an-icon/add_icon_1.png
  public/assets/images/adding-an-icon/add_icon_2.png
  public/assets/images/adding-an-icon/add_icon_3.png
  public/assets/images/adding-an-icon/add_icon_4.png
  public/assets/images/adding-an-icon/add_icon_5.png
  public/assets/images/adding-an-icon/add_icon_6.png
  public/assets/images/adding-an-icon/add_icon_7.gif
  public/assets/images/adding-an-icon/add_icon_8.png
  public/assets/images/adding-an-icon/add_icon_9.png
Labels: approved, Team Atlantis

#2350 feat(components-native): Adding Unsafe style to mobile Text and Button [JOB-112128]
  .eslintignore
  packages/components-native/src/Button/Button.test.tsx
  packages/components-native/src/Button/Button.tsx
  packages/components-native/src/Text/Text.test.tsx
  packages/components-native/src/Text/Text.tsx
  packages/components-native/src/Typography/Typography.test.tsx
  packages/components-native/src/Typography/Typography.tsx
Labels: approved, Team Atlantis

#2362 feat(components): Add thumbnails and change animations in lightbox component
  docs/components/LightBox/Web.stories.tsx
  packages/components/src/LightBox/LightBox.module.css
  packages/components/src/LightBox/LightBox.module.css.d.ts
  packages/components/src/LightBox/LightBox.test.tsx
  packages/components/src/LightBox/LightBox.tsx
  packages/components/src/LightBox/__snapshots__/LightBoxSnapshots.test.tsx.snap
  packages/site/src/content/LightBox/LightBox.props.json
Labels: approved, Team Atlantis, Team Websites

#2369 feat(components): Checkbox v2
  docs/components/Checkbox/Web.stories.tsx
  packages/components/src/Checkbox/Checkbox.rebuilt.test.tsx
  packages/components/src/Checkbox/Checkbox.rebuilt.tsx
  packages/components/src/Checkbox/Checkbox.test.tsx
  packages/components/src/Checkbox/Checkbox.tsx
  packages/components/src/Checkbox/Checkbox.types.ts
  packages/components/src/Checkbox/index.ts
  packages/components/src/Checkbox/index.tsx
Labels: approved, Team Atlantis

#2376 fix(components): Fix scrollbar styling bug in Lightbox component for Safari
  packages/components/src/LightBox/LightBox.module.css
Labels: approved, Team Atlantis

#2370 feat: Allow DataList.ItemAction to avoid nesting
  packages/components/src/DataList/DataList.types.ts
  packages/components/src/DataList/DataList.utils.tsx
  packages/components/src/DataList/components/DataListActions/DataListActions.test.tsx
  packages/components/src/DataList/components/DataListActions/DataListActions.tsx
Labels: approved, Team Atlantis

#2385 docs: Added note about testing lightbox
  packages/site/src/content/LightBox/LightBoxNotes.mdx
Labels: approved, Team UX Foundations

#2375 fix(components): Allow Chip to be used as an activator in Menu
  packages/components/src/Menu/Menu.module.css
  packages/components/src/Menu/Menu.module.css.d.ts
  packages/components/src/Menu/Menu.tsx
  packages/components/src/Menu/__snapshots__/Menu.test.tsx.snap
  packages/components/src/Page/__snapshots__/Page.test.tsx.snap
Labels: approved, Team UX Foundations

#2380 docs: Add Triton to SideDrawer
  package-lock.json
  packages/site/package.json
  packages/site/src/components/TritonConversation.module.css
  packages/site/src/components/TritonConversation.tsx
  packages/site/src/components/TritonSideDrawer.tsx
  packages/site/src/providers/TritonProvider.tsx
  packages/site/src/utils/TritonLinks.ts
  packages/site/src/utils/useTritonApi.ts
Labels: approved, Team UX Foundations

#2394 feat(design): Add battery, speed, wheel icons, replace fuel Fleet management icons
  docs/components/Icon/Icon.stories.mdx
  packages/design/src/icons/battery.svg
  packages/design/src/icons/fuel.svg
  packages/design/src/icons/speed.svg
  packages/design/src/icons/wheel.svg
Labels: approved, Team UX Foundations

#2392 docs: Add UNSAFE documentation to mobile Button and Text
  docs/components/Text/Text.stories.mdx
  packages/components-native/src/Button/Button.tsx
  packages/components-native/src/Text/Text.tsx
  packages/components/src/Popover/Popover.tsx
  packages/site/src/content/Button/Button.props-mobile.json
  packages/site/src/content/Button/ButtonNotes.mdx
  packages/site/src/content/Popover/Popover.props.json
  packages/site/src/content/Popover/PopoverNotes.mdx
  packages/site/src/content/Text/Text.props-mobile.json
  packages/site/src/content/Text/TextNotes.mdx
  packages/site/src/content/Text/index.tsx
Labels: approved, Team UX Foundations

#2395 fix(components): There was a typo in the DataList.ItemAction logic
  packages/components/src/DataList/components/DataListActions/DataListActions.test.tsx
  packages/components/src/DataList/components/DataListActions/DataListActions.tsx
Labels: approved, Team SC Engagement, Team UX Foundations

#2396 fix(docx): Stop Triton Link from doing full page navigation
  packages/site/src/components/TritonConversation.tsx
Labels: approved, Team UX Foundations

#2386 docs: Hide nav and add hamburger to collapse side nav
  docs/components/AtlantisThemeContext/AtlantisThemeContext.stories.mdx
  packages/site/src/layout/AnimatedPresenceDisclosure.tsx
  packages/site/src/layout/LeftDrawer.module.css
  packages/site/src/layout/LeftDrawer.tsx
  packages/site/src/layout/NavMenu.module.css
  packages/site/src/layout/NavMenu.tsx
  packages/site/src/layout/SearchButton.module.css
  packages/site/src/layout/TopNav.tsx
  packages/site/src/preview/AtlantisPreviewProvider.tsx
  packages/site/src/providers/AtlantisSiteProvider.tsx
Labels: approved, Team UX Foundations

#2382 build(docx): Add Sitemap
  package.json
  sitemap-generator.js
  sitemap-generator.test.js
Labels: approved, Team Atlantis, Team UX Foundations

#2398 fix(docx): Hide menu button, logo, and search in minimal mode
  packages/site/src/layout/TopNav.tsx
Labels: approved, Team UX Foundations

#2401 build: Update circle to only report errors when linting javascript
  .circleci/config.yml
Labels: approved, Team UX Foundations

#2397 fix(components): Keep only one DatePicker open at a time
  docs/components/InputGroup/Web.stories.tsx
  packages/components/src/DatePicker/DatePicker.test.tsx
  packages/components/src/DatePicker/DatePicker.tsx
Labels: approved, Team UX Foundations

#2402 fix: update svg to fix fill rule issue
  packages/design/src/icons/headset.svg
Labels: approved, Team UX Foundations

#2399 fix(components): Fix Chip Truncation Gradient
  docs/components/Chip/Comparison.stories.tsx
  packages/components/src/Chip/Chip.module.css
  packages/components/src/Chip/Chip.tsx
Labels: approved, Team UX Foundations
