Repository GetJobber/atlantis, pull requests merged in 2025-01, with the labels that each got.

#2275 docs: Refactor SearchBox
  docs/hooks/UseBool.tsx
  packages/site/index.html
  packages/site/src/layout/SearchBox.tsx
Labels: approved, Team Atlantis, docs site

#2279 refactor(docx): Refactoring the Live Code Editor
  packages/site/src/components/CodeCopyButton.tsx
  packages/site/src/layout/ComponentView.tsx
  packages/site/src/main.tsx
  packages/site/src/preview/AtlantisPreviewEditor.tsx
  packages/site/src/preview/AtlantisPreviewProvider.tsx
  packages/site/src/preview/AtlantisPreviewViewer.tsx
  packages/site/src/preview/README.md
  packages/site/src/preview/useAtlantisPreviewCode.tsx
  packages/site/src/preview/useAtlantisPreviewCodeTheme.ts
  packages/site/src/preview/useAtlantisPreviewSkeleton.tsx
  packages/site/src/preview/useAtlantisPreviewViewer.tsx
  packages/site/src/providers/AtlantisPreviewEditorProvider.tsx
Labels: approved, Team Atlantis, docs site

#2282 feat(components): Add UNSAFE_className and UNSAFE_style to Popover
  docs/guides/customizing-components.stories.mdx
  packages/components/src/Popover/Popover.test.tsx
  packages/components/src/Popover/Popover.tsx
Labels: approved, Team Atlantis

#2283 docs: refine UI for search button
  packages/site/src/layout/NavMenu.module.css
  packages/site/src/layout/NavMenu.tsx
Labels: approved, Team Atlantis, docs site

#2278 docs(docx): Adding metatags [JOB-111822]
  packages/site/index.html
Labels: approved, Team Atlantis, docs site

#2280 docs(docx): Adding Design e2e tests [JOB-111581]
  packages/site/baseDesignList.mjs
  packages/site/tests/site.components.e2e.ts
Labels: approved, Team Atlantis

#2284 docs: give preview window contents more room to breathe [JOB-112177]
  packages/site/src/components/CodePreviewWindow.tsx
  packages/site/src/preview/useAtlantisPreviewSkeleton.tsx
Labels: approved, Team Atlantis, docs site

#2274 docs: Add Not Found Page [JOB-111818]
  packages/site/src/components/ContentLoader.tsx
  packages/site/src/layout/ComponentView.tsx
  packages/site/src/layout/Layout.tsx
  packages/site/src/pages/NotFoundPage.module.css
  packages/site/src/pages/NotFoundPage.tsx
  packages/site/src/routes.tsx
Labels: approved, Team Atlantis, docs site

#2287 fix(components): Garbled Component Names in Prod Site Build Canvas
  packages/site/vite.config.ts
Labels: approved, Team Atlantis

#2170 fix(components): Avoid rendering DataList title container when empty
  packages/components/src/DataList/DataList.const.ts
  packages/components/src/DataList/DataList.test.tsx
  packages/components/src/DataList/DataList.tsx
  packages/components/src/DataList/components/DataListTotalCount/DataListTotalCount.tsx
Labels: approved, Team Atlantis

#2291 docs: fix h1s across the docs site [JOB-113010]
  packages/site/index.html
  packages/site/src/components/HeaderBlock.tsx
  packages/site/src/main.css
Labels: approved, Team Atlantis

#2273 docs: Adjust margin on Disclosure Nav Item
  packages/site/src/layout/NavMenu.module.css
  packages/site/src/layout/NavMenu.tsx
Labels: approved, Team Atlantis, docs site

#2295 fix(docx): Jobber Pro not rendering properly within Heading + Typography coded examples.
  packages/site/src/preview/useAtlantisPreviewSkeleton.tsx
Labels: approved, Team Atlantis

#2292 docs: overhaul of collection page grid layouts
  packages/site/src/components/BodyBlock.tsx
  packages/site/src/components/CategoryCardSection.module.css
  packages/site/src/components/CategoryCardSection.tsx
  packages/site/src/components/ContentCardWrapper.tsx
  packages/site/src/components/PageBlock.tsx
  packages/site/src/main.css
Labels: approved, Team Atlantis

#2296 fix(docx): Fixing the double scroll bars on the Docs Site
  packages/site/src/components/VisibleWhenFocused.module.css
  packages/site/src/layout/NavMenu.module.css
Labels: approved, Team Atlantis

#2293 docs: add sticky sections
  packages/site/src/components/CategoryCardSection.tsx
  packages/site/src/layout/AnimatedPresenceDisclosure.tsx
  packages/site/src/layout/NavMenu.module.css
  packages/site/src/layout/NavMenu.tsx
  packages/site/src/main.css
Labels: review requested, approved, Team Atlantis

#2300 docs: improvements to the state of thumbnails [JOB-112069]
  packages/site/public/Formatting.png
  packages/site/public/Formatting.svg
  packages/site/public/Product Vocabulary.png
  packages/site/public/Product Vocabulary.svg
  packages/site/public/Voice & Tone.png
  packages/site/public/Voice & Tone.svg
  packages/site/src/changelogList.ts
  packages/site/src/components/ContentCard.tsx
  packages/site/src/contentList.ts
  packages/site/src/guidesList.ts
  packages/site/src/hooksList.ts
  packages/site/src/packagesList.ts
  packages/site/src/pages/HomePage.tsx
  packages/site/src/types/components.ts
Labels: approved, Team Atlantis

#2303 docs: Make the site work better at the sub-1024px range
  docs/guides/documentation-style.stories.mdx
  packages/site/src/components/PropsList.tsx
  packages/site/src/guidesList.ts
  packages/site/src/layout/BaseView.tsx
  packages/site/src/main.css
  packages/site/src/maps/guidesContent.tsx
  packages/site/src/routes.tsx
Labels: approved, Team Atlantis, docs site

#2307 docs: Update zIndex on ToggleThemeButton
  packages/site/src/components/ToggleThemeButton.tsx
Labels: approved, Team Atlantis, docs site

#2306 docs: Add a new route for Welcome Guide
  packages/site/src/maps/designContent.tsx
  packages/site/src/pages/HomePage.tsx
  packages/site/src/pages/WelcomeGuidePage.tsx
  packages/site/src/routes.tsx
Labels: approved, Team Atlantis, docs site

#2304 fix(docx): style sidenav correctly in Safari
  packages/site/src/layout/NavMenu.module.css
  packages/site/src/layout/NavMenu.tsx
Labels: approved, Team Atlantis, docs site

#2305 fix(docx): get component iframes rendering correctly
  packages/site/src/preview/AtlantisPreviewViewer.tsx
Labels: approved, Team Atlantis, docs site

#2301 fix(docx): Final Feedback before soft launch
  packages/site/editorMobileBundle.rollup.config.js
  packages/site/src/MobileOverrides.jsx
  packages/site/src/content/Form/index.tsx
  packages/site/src/content/FormField/index.tsx
  packages/site/src/hooksList.ts
  packages/site/src/layout/ComponentView.tsx
  packages/site/src/pages/HooksPage.tsx
Labels: approved, design approved, Team Atlantis

#2297 feat(docx): Soft Launch the Docs Site
  .storybook/components/DocsWithSidebar/DocsWithSidebar.tsx
  packages/site/src/components/FeedbackBanner.tsx
  packages/site/src/layout/Layout.tsx
  packages/site/src/layout/NavMenu.tsx
  packages/site/src/utils/storybook.ts
Labels: review requested, approved, Team Atlantis, docs site

#2213 feat(components): add input text rebuild EARLY Iterations
  docs/components/InputText/InputText.stories.mdx
  docs/components/InputText/Web.stories.tsx
  packages/components/src/FormField/FormFieldTypes.ts
  packages/components/src/FormField/hooks/useFormFieldWrapperStyles.ts
  packages/components/src/InputText/InputText.rebuilt.tsx
  packages/components/src/InputText/InputText.test.tsx
  packages/components/src/InputText/InputText.tsx
  packages/components/src/InputText/InputText.types.ts
  packages/components/src/InputText/__snapshots__/InputText.test.tsx.snap
  packages/components/src/InputText/index.ts
  packages/components/src/InputText/index.tsx
  packages/components/src/InputText/useInputTextActions.ts
  packages/components/src/InputText/useInputTextFormField.ts
  packages/components/src/InputText/useTextAreaResize.ts
Labels: approved, design review requested, Team Atlantis

#2289 docs: update layout component examples
  docs/components/Content/Content.stories.mdx
  packages/site/src/content/Box/index.tsx
  packages/site/src/content/Card/index.tsx
  packages/site/src/content/Content/index.tsx
  packages/site/src/content/DataList/index.tsx
  packages/site/src/content/Grid/index.tsx
Labels: approved, Team Atlantis, docs site

#2312 chore(design): change name in README
  packages/design/README.md
Labels: approved, Team Atlantis

#2315 revert: "feat(components): add input text rebuild EARLY Iterations"
  docs/components/InputText/InputText.stories.mdx
  docs/components/InputText/Web.stories.tsx
  packages/components/src/FormField/FormFieldTypes.ts
  packages/components/src/FormField/hooks/useFormFieldWrapperStyles.ts
  packages/components/src/InputText/InputText.rebuilt.tsx
  packages/components/src/InputText/InputText.test.tsx
  packages/components/src/InputText/InputText.tsx
  packages/components/src/InputText/InputText.types.ts
  packages/components/src/InputText/__snapshots__/InputText.test.tsx.snap
  packages/components/src/InputText/index.ts
  packages/components/src/InputText/index.tsx
  packages/components/src/InputText/useInputTextActions.ts
  packages/components/src/InputText/useInputTextFormField.ts
  packages/components/src/InputText/useTextAreaResize.ts
Labels: approved, Team Atlantis

#2314 fix(components): DataListTotalCount results pluralization
  packages/components/src/DataList/DataList.types.ts
  packages/components/src/DataList/components/DataListTotalCount/DataListTotalCount.test.tsx
  packages/components/src/DataList/components/DataListTotalCount/DataListTotalCount.tsx
Labels: approved, Team Atlantis

#2117 fix(components): Enabled Tree Shaking properly in Atlantis.
  packages/components/package.json
Labels: approved, Team Atlantis

#2318 fix(components): Add transparent outline for DataList sort options
  packages/components/src/DataList/components/DataListHeaderTile/components/DataListSortingOptions.module.css
Labels: approved, Team Atlantis

#2316 revert: "revert: "feat(components): add input text rebuild EARLY Iterations"
  docs/components/InputText/InputText.stories.mdx
  docs/components/InputText/Web.stories.tsx
  packages/components/src/FormField/FormFieldTypes.ts
  packages/components/src/FormField/hooks/useFormFieldWrapperStyles.ts
  packages/components/src/InputText/InputText.rebuilt.tsx
  packages/components/src/InputText/InputText.test.tsx
  packages/components/src/InputText/InputText.tsx
  packages/components/src/InputText/InputText.types.ts
  packages/components/src/InputText/__snapshots__/InputText.test.tsx.snap
  packages/components/src/InputText/index.ts
  packages/components/src/InputText/index.tsx
  packages/components/src/InputText/useInputTextActions.ts
  packages/components/src/InputText/useInputTextFormField.ts
  packages/components/src/InputText/useTextAreaResize.ts
Labels: approved, Team Atlantis

#2326 fix(docx): use a correct link for star wars graphQL API (useCollectionQuery hook)
  docs/components/DataList/Web.stories.tsx
  docs/components/DataList/storyUtils.ts
  packages/hooks/src/useCollectionQuery/mdxUtils.ts
Labels: approved, Team Atlantis

#2313 docs: component customization
  docs/guides/customizing-components.stories.mdx
Labels: approved, Team Atlantis

#2328 docs: Hide FeedbackBanner in minimal mode
  packages/site/src/components/FeedbackBanner.tsx
Labels: approved, Team Atlantis

#2327 refactor(components): menu item only changes color on `focus-visible`
  packages/components/src/Menu/Menu.module.css
Labels: approved, Team Atlantis

#2336 chore: Re-add check manual release
  .circleci/config.yml
  packages/generators/index.mjs
  packages/generators/package.json
Labels: review requested, approved, Team Atlantis

#2334 docs: add thumbnail for Content and Guides top-level sections
  packages/site/public/ContentGuidance.png
  packages/site/public/ContentGuidance.svg
  packages/site/public/Guides.png
  packages/site/public/Guides.svg
  packages/site/src/pages/HomePage.tsx
Labels: approved, Team Atlantis, docs site

#2332 docs: create a Patterns docs section and add 3 patterns
  docs/patterns/disabled-states.stories.mdx
  docs/patterns/empty-states.stories.mdx
  docs/patterns/interaction.stories.mdx
  packages/site/public/DisabledStates.png
  packages/site/public/DisabledStates.svg
  packages/site/public/EmptyStates.png
  packages/site/public/EmptyStates.svg
  packages/site/public/Interaction.png
  packages/site/public/Interaction.svg
  packages/site/public/Patterns.png
  packages/site/public/Patterns.svg
  packages/site/src/components/ContentLoader.tsx
  packages/site/src/layout/SearchBox.tsx
  packages/site/src/maps/index.ts
  packages/site/src/maps/patternsContent.tsx
  packages/site/src/pages/HomePage.tsx
  packages/site/src/pages/PatternsPage.tsx
  packages/site/src/patternsList.ts
  packages/site/src/routes.tsx
Labels: review requested, approved, Team Atlantis, docs site

#2344 docs: remove the feedback banner and its implementation
  packages/site/src/components/FeedbackBanner.tsx
  packages/site/src/layout/Layout.tsx
  packages/site/src/layout/NavMenu.module.css
  packages/site/src/layout/NavMenu.tsx
Labels: approved, Team Atlantis, docs site

#2348 feat(design): Add additional status icons for warning and info
  docs/components/Icon/Icon.stories.mdx
  packages/design/src/icons/info.svg
  packages/design/src/icons/warning.svg
Labels: approved, Team Atlantis
