Repository GetJobber/atlantis, pull requests merged in 2025-04, with the labels that each got.

#2448 feat(components): Add UNSAFE props to Button
  docs/guides/customizing-components.stories.mdx
  packages/components/src/Button/Button.test.tsx
  packages/components/src/Button/Button.tsx
  packages/components/src/Button/Button.types.ts
  packages/components/src/Button/ButtonInternals.tsx
  packages/site/src/content/Banner/Banner.props.json
  packages/site/src/content/Button/Button.props.json
  packages/site/src/content/Button/ButtonNotes.mdx
  packages/site/src/content/DataList/DataList.props.json
  packages/site/src/content/InputFile/InputFile.props.json
  packages/site/src/content/Modal/Modal.props.json
Labels: approved, Team UX Foundations

#2454 feat(components): Add UNSAFE props to Text
  packages/components/src/Text/Text.test.tsx
  packages/components/src/Text/Text.tsx
  packages/site/src/content/InputFile/InputFile.props.json
  packages/site/src/content/Text/Text.props.json
  packages/site/src/content/Text/TextNotes.mdx
  packages/site/src/content/Typography/TypographyNotes.mdx
Labels: approved, Team UX Foundations

#2447 fix(components): Dismissible Chip Focus Management
  packages/components/src/Chips/InternalChipButton.tsx
  packages/components/src/Chips/InternalChipDismissible/__tests__/InternalChipDismissible.test.tsx
  packages/components/src/Chips/InternalChipDismissible/hooks/useInternalChipDismissible.ts
Labels: approved, Team UX Foundations

#2459 feat(components): Add UNSAFE props to Heading
  packages/components/src/Heading/Heading.test.tsx
  packages/components/src/Heading/Heading.tsx
  packages/site/src/content/Heading/Heading.props.json
  packages/site/src/content/Heading/HeadingNotes.mdx
  packages/site/src/content/Heading/index.tsx
Labels: approved, Team UX Foundations

#2463 docs: clean up Banner prop docs
  packages/components/src/Banner/Banner.tsx
  packages/site/src/content/Banner/Banner.props.json
Labels: approved, Team UX Foundations

#2438 feat(design): Update lightness value of `base-blue--600` to improve accessibility
  packages/components-native/src/Heading/__snapshots__/Heading.test.tsx.snap
  packages/components-native/src/StatusLabel/__snapshots__/StatusLabel.test.tsx.snap
  packages/components-native/src/Text/__snapshots__/Text.test.tsx.snap
  packages/components-native/src/Typography/__snapshots__/Typography.test.tsx.snap
  packages/design/src/tokens/baseColor.tokens.json
Labels: approved, accessibility, Team UX Foundations

#2465 feat(design): add slim spacing token and add to docs
  docs/design/Spacing.stories.mdx
  packages/components/src/Box/styles/BoxGap.module.css
  packages/components/src/Box/styles/BoxGap.module.css.d.ts
  packages/design/src/tokens/space.tokens.json
  packages/site/src/content/Box/Box.props.json
Labels: approved, Team UX Foundations

#2485 feat(components): Feedback on Layout 2.0
  docs/components/Cluster/Web.stories.tsx
  docs/components/ContentBlock/Web.stories.tsx
  docs/components/ResponsiveSwitcher/Web.stories.tsx
  docs/components/SideKick/Web.stories.tsx
  docs/components/Stack/Web.stories.tsx
  docs/components/Tiles/Web.stories.tsx
  packages/components/src/Cluster/Cluster.module.css
  packages/components/src/Cluster/Cluster.module.css.d.ts
  packages/components/src/Cluster/Cluster.tsx
  packages/components/src/Cluster/types.ts
  packages/components/src/Container/Container.tsx
  packages/components/src/Container/types.ts
  packages/components/src/ContentBlock/ContentBlock.tsx
  packages/components/src/ContentBlock/types.ts
  packages/components/src/Cover/Cover.tsx
  packages/components/src/Cover/types.ts
  packages/components/src/Frame/Frame.tsx
  packages/components/src/Frame/types.ts
  packages/components/src/ResponsiveSwitcher/ResponsiveSwitcher.tsx
  packages/components/src/ResponsiveSwitcher/types.ts
  packages/components/src/SideKick/SideKick.module.css
  packages/components/src/SideKick/SideKick.module.css.d.ts
  packages/components/src/SideKick/SideKick.tsx
  packages/components/src/SideKick/types.ts
  packages/components/src/Stack/Stack.tsx
  packages/components/src/Stack/types.ts
  packages/components/src/Tiles/Tiles.tsx
  packages/components/src/Tiles/types.ts
  packages/components/src/sharedHelpers/getMappedAtlantisSpaceToken.ts
  packages/components/src/sharedHelpers/getMappedBreakpointWidth.ts
  packages/components/src/sharedHelpers/types.ts
  packages/hooks/src/useBreakpoints/index.ts
  packages/site/src/content/Cluster/Cluster.mdx
  packages/site/src/content/Cluster/Cluster.props.json
  packages/site/src/content/Container/Container.props.json
  packages/site/src/content/Container/Container.stories.mdx
  packages/site/src/content/ContentBlock/ContentBlock.props.json
  packages/site/src/content/Cover/Cover.props.json
  packages/site/src/content/Frame/Frame.props.json
  packages/site/src/content/ResponsiveSwitcher/ResponsiveSwitcher.mdx
  packages/site/src/content/ResponsiveSwitcher/ResponsiveSwitcher.props.json
  packages/site/src/content/SideKick/SideKick.props.json
  packages/site/src/content/Stack/Stack.mdx
  packages/site/src/content/Stack/Stack.props.json
  packages/site/src/content/Tiles/Tiles.mdx
  packages/site/src/content/Tiles/Tiles.props.json
  packages/site/src/guides/page-layouts.stories.mdx
  packages/site/src/guides/scaffolding.stories.mdx
  packages/site/src/pages/VisualTestComponentPage.tsx
  packages/site/src/pages/VisualTestLayoutPage.tsx
  packages/site/tests/visual/site.visual.ts-snapshots/visual-test-layout-page-chromium-darwin.png
Labels: approved, Team UX Foundations

#2487 fix(docx): Fix InputCurrency Storybook Link
  packages/site/src/content/InputCurrency/index.tsx
Labels: approved, Team UX Foundations

#2472 fix(components): make Glimmer respond to dark mode
  docs/components/Glimmer/Glimmer.stories.mdx
  docs/components/Glimmer/Web.stories.tsx
  packages/components/src/Glimmer/Glimmer.module.css
Labels: approved, Team UX Foundations

#2490 fix(components): Update text color on autofill in FormField
  packages/components/src/FormField/FormField.module.css
Labels: approved, Team UX Foundations

#2494 revert(components): Add ref to Button and Chip
  packages/components/src/Button/Button.tsx
  packages/components/src/Chip/Chip.tsx
  packages/components/src/Chip/Chip.types.d.ts
  packages/components/src/utils/meta/meta.test.tsx
  packages/site/src/content/Button/Button.props.json
  packages/site/src/content/Chip/Chip.props.json
Labels: approved, Team UX Foundations

#2491 fix(components): Assign type button to DataListHeaderTile when column is sortable
  packages/components/src/DataList/components/DataListHeaderTile/DataListHeaderTile.tsx
Labels: approved, Team UX Foundations

#2496 fix(components): Fix Chip Type Issue
  packages/components/src/Chip/Chip.tsx
  packages/components/src/Chip/Chip.types.ts
  packages/components/src/Chip/index.ts
  packages/site/src/content/Chip/Chip.props.json
Labels: approved, Team UX Foundations

#2477 feat(components): InputTime without RHF
  packages/components/src/FormField/FormFieldWrapper.tsx
  packages/components/src/FormField/components/ClearAction.tsx
  packages/components/src/InputTime/InputTime.rebuilt.test.tsx
  packages/components/src/InputTime/InputTime.rebuilt.tsx
  packages/components/src/InputTime/InputTime.tsx
  packages/components/src/InputTime/InputTime.types.ts
  packages/components/src/InputTime/hooks/useTimePredict.ts
  packages/components/src/InputTime/index.ts
  packages/components/src/InputTime/index.tsx
  packages/components/src/InputTime/utils/input-time-utils.ts
  packages/hooks/src/useShowClear/useShowClear.test.ts
  packages/hooks/src/useShowClear/useShowClear.ts
  packages/site/src/content/InputTime/InputTime.props.json
Labels: approved, Team UX Foundations

#2471 feat(components): Add ability to only open Chips menu on search [JOB-119726]
  cp
  packages/components/src/Chips/ChipsTypes.tsx
  packages/components/src/Chips/InternalChipDismissible/InternalChipDismissible.tsx
  packages/components/src/Chips/InternalChipDismissible/InternalChipDismissibleInput.tsx
  packages/components/src/Chips/InternalChipDismissible/InternalChipDismissibleTypes.ts
  packages/components/src/Chips/InternalChipDismissible/__tests__/InternalChipDismissibleInput.test.tsx
  packages/components/src/Chips/InternalChipDismissible/hooks/__tests__/useInternalChipDismissibleInput.test.tsx
  packages/components/src/Chips/InternalChipDismissible/hooks/useInternalChipDismissibleInput.tsx
  packages/site/src/content/Chips/Chips.props.json
Labels: approved, Team UX Foundations

#2495 feat(hooks): BREAKING CHANGE: Remove useAssert
  docs/hooks/useAssert.stories.mdx
  packages/components/src/Chips/Chip.tsx
  packages/components/src/Chips/InternalChipAffix.tsx
  packages/components/src/Chips/tests/Chip.test.tsx
  packages/components/src/Combobox/Combobox.test.tsx
  packages/components/src/Combobox/hooks/useComboboxValidation.ts
  packages/hooks/README.md
  packages/hooks/src/index.ts
  packages/hooks/src/useAssert/index.ts
  packages/hooks/src/useAssert/useAssert.tsx
  packages/site/src/hooksList.ts
  packages/site/src/maps/hooksContent.tsx
Labels: approved, Team UX Foundations

#2503 fix(components): Fix Type Definition Linking for Clearable
  packages/components/src/FormField/FormFieldTypes.ts
Labels: approved, Team UX Foundations

#2502 fix(components): Properly Exclude DefaultValue from InputTimev2 Props
  packages/components/src/InputTime/InputTime.types.ts
  packages/components/src/InputTime/index.tsx
  packages/site/src/content/InputTime/InputTime.props.json
Labels: approved, Team UX Foundations

#2484 feat(components): Select without RHF
  docs/components/Select/Web.stories.tsx
  packages/components/src/Select/Select.rebuilt.test.tsx
  packages/components/src/Select/Select.rebuilt.tsx
  packages/components/src/Select/Select.test.tsx
  packages/components/src/Select/Select.tsx
  packages/components/src/Select/Select.types.ts
  packages/components/src/Select/__snapshots__/Select.rebuilt.test.tsx.snap
  packages/components/src/Select/hooks/useSelectActions.ts
  packages/components/src/Select/hooks/useSelectFormField.ts
  packages/components/src/Select/index.ts
  packages/components/src/Select/index.tsx
  packages/site/src/content/Select/Select.props.json
Labels: approved, Team UX Foundations

#2475 feat(components): Add support for composable modals
  docs/components/Modal/Web.stories.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.tsx
  packages/components/src/Combobox/hooks/useComboboxAccessibility.ts
  packages/components/src/ConfirmationModal/tests/__snapshots__/snapshot-ConfirmationModal.test.tsx.snap
  packages/components/src/Heading/Heading.tsx
  packages/components/src/Heading/index.ts
  packages/components/src/Modal/Modal.rebuilt.module.css
  packages/components/src/Modal/Modal.rebuilt.module.css.d.ts
  packages/components/src/Modal/Modal.rebuilt.test.tsx
  packages/components/src/Modal/Modal.rebuilt.tsx
  packages/components/src/Modal/Modal.tsx
  packages/components/src/Modal/Modal.types.ts
  packages/components/src/Modal/ModalContext.rebuilt.tsx
  packages/components/src/Modal/index.ts
  packages/components/src/Modal/index.tsx
  packages/components/src/Modal/useModal.ts
  packages/components/src/Modal/useModalStyles.ts
  packages/components/src/utils/meta/meta.json
  packages/site/src/content/Modal/Modal.props.json
  packages/site/src/content/Modal/ModalNotes.mdx
  packages/site/src/content/Modal/index.tsx
Labels: approved, Team UX Foundations

#2508 revert(components): Add support for composable modals
  docs/components/Modal/Web.stories.tsx
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.tsx
  packages/components/src/Combobox/hooks/useComboboxAccessibility.ts
  packages/components/src/ConfirmationModal/tests/__snapshots__/snapshot-ConfirmationModal.test.tsx.snap
  packages/components/src/Heading/Heading.tsx
  packages/components/src/Heading/index.ts
  packages/components/src/Modal/Modal.rebuilt.module.css
  packages/components/src/Modal/Modal.rebuilt.module.css.d.ts
  packages/components/src/Modal/Modal.rebuilt.test.tsx
  packages/components/src/Modal/Modal.rebuilt.tsx
  packages/components/src/Modal/Modal.tsx
  packages/components/src/Modal/Modal.types.ts
  packages/components/src/Modal/ModalContext.rebuilt.tsx
  packages/components/src/Modal/index.ts
  packages/components/src/Modal/index.tsx
  packages/components/src/Modal/useModal.ts
  packages/components/src/Modal/useModalStyles.ts
  packages/components/src/utils/meta/meta.json
  packages/site/src/content/Modal/Modal.props.json
  packages/site/src/content/Modal/ModalNotes.mdx
  packages/site/src/content/Modal/index.tsx
Labels: approved, Team UX Foundations

#2510 feat(components): Add maxLength prop to both Select versions
  docs/components/Select/Web.stories.tsx
  packages/components/src/Select/Select.rebuilt.tsx
  packages/components/src/Select/Select.types.ts
  packages/site/src/content/Select/Select.props.json
Labels: approved, Team UX Foundations

#2511 feat(components): Add support for composable modals - Take 2
  docs/components/Modal/Web.stories.tsx
  package.json
  packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.tsx
  packages/components/src/Combobox/hooks/useComboboxAccessibility.ts
  packages/components/src/Heading/Heading.tsx
  packages/components/src/Heading/index.ts
  packages/components/src/Modal/Modal.rebuilt.module.css
  packages/components/src/Modal/Modal.rebuilt.module.css.d.ts
  packages/components/src/Modal/Modal.rebuilt.test.tsx
  packages/components/src/Modal/Modal.rebuilt.tsx
  packages/components/src/Modal/Modal.tsx
  packages/components/src/Modal/Modal.types.ts
  packages/components/src/Modal/ModalContext.rebuilt.tsx
  packages/components/src/Modal/index.ts
  packages/components/src/Modal/index.tsx
  packages/components/src/Modal/useModal.ts
  packages/components/src/Modal/useModalStyles.ts
  packages/components/src/utils/meta/meta.json
  packages/site/src/content/Modal/Modal.props.json
  packages/site/src/content/Modal/ModalNotes.mdx
  packages/site/src/content/Modal/index.tsx
Labels: approved, Team UX Foundations

#2507 feat(components): make onClear optional on FormFieldWrapper
  packages/components/src/FormField/FormFieldWrapper.tsx
  packages/components/src/FormField/components/ClearAction.tsx
  packages/components/src/Select/Select.rebuilt.tsx
  packages/components/src/Select/hooks/useSelectActions.ts
Labels: approved, Team UX Foundations

#2506 feat(components): Add Ref to Chip
  packages/components/src/Chip/Chip.tsx
  packages/components/src/utils/meta/meta.test.tsx
  packages/site/src/content/Chip/Chip.props.json
Labels: approved, Team UX Foundations

#2517 docs: fix link to layouts guide provided by the search
  packages/site/src/guidesList.ts
Labels: approved, Team UX Foundations

#2522 feat(design): Adding a new price tag icon
  docs/components/Icon/Icon.stories.mdx
  packages/design/src/icons/priceTag.svg
Labels: approved, Team UX Foundations, Team Retention

#2498 docs: add guide to Figma libraries
  docs/guides/figma-101.mdx
  packages/site/src/guidesList.ts
  packages/site/src/maps/guidesContent.tsx
  packages/site/src/routes.tsx
Labels: approved, Team UX Foundations

#2513 feat(components): Add Default Activator Ref to Combobox
  packages/components/src/Combobox/Combobox.tsx
  packages/components/src/Combobox/Combobox.types.ts
  packages/components/src/Combobox/components/ComboboxTrigger/ComboboxTrigger.tsx
  packages/site/src/content/Combobox/Combobox.props.json
Labels: approved, Team UX Foundations

#2499 feat(components): Add firstDayOfWeek to DatePicker and AtlantisContext
  docs/components/Datepicker/Web.stories.tsx
  packages/components/src/AtlantisContext/AtlantisContext.test.tsx
  packages/components/src/AtlantisContext/AtlantisContext.tsx
  packages/components/src/DatePicker/DatePicker.test.tsx
  packages/components/src/DatePicker/DatePicker.tsx
  packages/components/src/sharedHelpers/types.ts
  packages/site/src/content/DatePicker/DatePicker.props.json
  packages/site/src/content/DatePicker/DatePickerNotes.mdx
Labels: approved, Team UX Foundations

#2514 feat(components): Add noopener and noreferrer attributes to Link
  packages/components/src/Button/Button.tsx
  packages/components/src/Button/__snapshots__/Button.test.tsx.snap
  packages/components/src/Link/Link.tsx
Labels: approved, Team UX Foundations

#2515 feat(components): Add element prop to Text
  packages/components/src/Text/Text.tsx
  packages/site/src/content/InputFile/InputFile.props.json
  packages/site/src/content/Text/Text.props.json
Labels: approved, Team UX Foundations

#2520 feat(components-native): Add UNSAFE_style to Content
  packages/components-native/src/Content/Content.test.tsx
  packages/components-native/src/Content/Content.tsx
  packages/components-native/src/TextList/__snapshots__/TextList.test.tsx.snap
  packages/site/src/content/Content/Content.props-mobile.json
  packages/site/src/content/Content/ContentNotes.mdx
  packages/site/src/content/Content/index.tsx
Labels: approved, Team UX Foundations

#2526 fix(design): Updating priceTag icon to meet jobber design standards
  packages/design/src/icons/priceTag.svg
Labels: approved, Team UX Foundations

#2523 fix(components-native): Adjusting Type mismatch in ThumbnailList
  packages/components-native/src/ThumbnailList/types.ts
  packages/site/src/content/ThumbnailList/ThumbnailList.props-mobile.json
Labels: approved, Team UX Foundations

#2527 feat(components): InputEmail V2 without RHF
  docs/components/InputEmail/Web.stories.tsx
  packages/components/src/InputEmail/InputEmail.rebuilt.test.tsx
  packages/components/src/InputEmail/InputEmail.rebuilt.tsx
  packages/components/src/InputEmail/InputEmail.test.tsx
  packages/components/src/InputEmail/InputEmail.tsx
  packages/components/src/InputEmail/InputEmail.types.ts
  packages/components/src/InputEmail/__snapshots__/InputEmail.rebuilt.test.tsx.snap
  packages/components/src/InputEmail/hooks/useInputEmailActions.ts
  packages/components/src/InputEmail/hooks/useInputEmailFormField.ts
  packages/components/src/InputEmail/index.ts
  packages/components/src/InputEmail/index.tsx
Labels: approved, Team UX Foundations
